- features/collection/views/DefaultCollectionView/CollectionProducts.tsx
> fix: Fix collection list view layout bug

- features/collection/components/sections/FilterableProductsSection/FilterList/index.tsx
- features/collection/components/sections/FilterableProductsSection/FilterList/virtualAccordion.machine.ts
This PR closes #73 
2. Visit a collection page and verify that the bug described by #73 is fixed
> Fix filters rendering bug

- frontend/features/productList/components/sections/FilterableProductsSection/SearchInput.tsx
This PR closes #101 
- Prevents user from inserting long search queries into the search field
2. Visit parts product list page and verify that the product list search input is bounded
> Fix no safe guard against long search query

- frontend/lib/algolia-utils/index.ts
This PR closes #136 
- Parse range filters from url query
2. Visit parts product list page
3. Open the "Price range" filter and insert values into inputs
4. Verify that there are `price_min` and `price_max` params in the url that reflect the values of the input
5. Verify that when the page is reloaded the "Price range" inputs are prepopulated according to `price_min` and `price_max` url param
> Fix range filter parsing

- README.md
- package.json
This prevents it running on Rush installs, where it doesn't make any
sense anyhow.
I'm happy to help get Rush set up in this repo, if that would be desirable.
> Replace `postinstall` script

- frontend/components/common/AppProviders.tsx
- frontend/components/common/Layout/Footer.tsx
- frontend/components/common/Layout/Header.tsx
- frontend/components/common/Layout/Navigation.tsx
- frontend/components/common/Layout/SearchBar.tsx
- frontend/components/common/Layout/User.tsx
- frontend/package-lock.json
- frontend/package.json
closes #179 
- Update `@ifixit/react-components` to `v0.4.0`
- Fix styles accordingly
The product list behaviour is unchanged, only colors have been updated to match new core primitives tokens.
> refactor: Use react-components v0.4.0

- frontend/components/common/Layout/Header.tsx
- frontend/components/common/Layout/Navigation.tsx
- frontend/components/common/Layout/User.tsx
- frontend/components/product-list/ProductListBreadcrumb.tsx
fixes #206 
fixes #202 
As discussed on this Slack [thread](https://inkofpixel.slack.com/archives/C01K32B4FPX/p1647276389936719) we're also improving the navigation menu so that it gets easier to show content that goes over the header bar (e.g. user menu).
2. Visit parts product list page
3. Verify that all of the above bugs are fixed
> fix(user menu): Fix user menu bugs

- frontend/components/common/Layout/Footer.tsx
- frontend/components/common/Layout/Header.tsx
- frontend/components/common/Layout/Navigation.tsx
- frontend/components/common/Layout/User.tsx
- frontend/components/common/SecondaryNavbar.tsx
- frontend/components/product-list/sections/FilterableProductsSection/ProductListPagination.tsx
- frontend/components/product-list/sections/RelatedPostsSection/index.tsx
- frontend/lib/hooks/index.ts
- frontend/next.config.js
fixes #194 
1. Visit the Vercel PR preview (replace `vercel.app` with `govinor.com`)
2. Visit parts product list page
3. Use lighthouse to verify that accessibility is > 90
> Fix accessibility issues

- frontend/components/common/Layout/Header.tsx
- frontend/components/common/Layout/Navigation.tsx
fixes #216  
2. Visit parts product list page
3. Verify that the issues mentioned in #216 are fixed
> Fix navigation issues

- frontend/components/product-list/sections/FilterableProductsSection/ProductGrid.tsx
- frontend/components/product-list/sections/FilterableProductsSection/ProductList.tsx
fixes #215  
3. Verify that #215 logic is applied
> Fix product rating display logic

- frontend/components/product-list/sections/FilterableProductsSection/ProductList.tsx
fixes #221  
3. Verify that product list item shipping flair is not shown anymore
> Remove product list item shipping flair

- frontend/components/common/AppProviders.tsx
- frontend/components/common/ProductCard.tsx
- frontend/components/product-list/ProductListBreadcrumb.tsx
- frontend/components/product-list/sections/FilterableProductsSection/FiltersModal.tsx
- frontend/components/product-list/sections/FilterableProductsSection/ProductList.tsx
- frontend/components/product-list/sections/FilterableProductsSection/ProductListFilters/FilterRow.tsx
- frontend/components/product-list/sections/FilterableProductsSection/ProductListFilters/index.tsx
- frontend/components/product-list/sections/FilterableProductsSection/index.tsx
- frontend/components/product-list/sections/HeroSection.tsx
- frontend/components/product-list/sections/ProductListChildrenSection.tsx
- frontend/components/product-list/sections/RelatedPostsSection/PostCard.tsx
fixes #224
fixes #226 
fixes #228
fixes #188 
Mattia reviewed the product list page to fix stuff like paddings, color contrasts, fonts, etc. This PR applies the changes.
- Improve text contrast on breadcrumb
- Add lato font family
- Improved filters card ui
- Improved product list items and product grid cards
- Various adjustments to paddings, sizes, etc
2. Perform a smoke test to verify that main functionalities of the product list page still work
> Review product list UI

- backend/build-docker-and-push
This is meant to be run during a post-merge webhook or action.
> Docker: add script to build and push the image

- frontend/components/product-list/sections/FilterableProductsSection/Toolbar.tsx
fixes #240 
2. Visit the parts product list
3. Verify that #240 is fixed
> Fix product list switch view button

- frontend/components/common/Layout/index.tsx
- packages/ui/header/index.tsx
fixes #258 
1. Visit the Vercel PR preview (replace vercel.app with cominor.com) from a mobile device (or use the desktop browser device simulation)
2. Visit the parts product list
3. Open the drawer menu, click on `Store > Tools` and verify that the drawer closes
> Close navigation drawer on route change

- frontend/next.config.js
fixes #281 
- Add redirect rule
- Re export env variables to support AWS Amplify lambda poor env variables support
2. Navigate to `/Store/Guide/113862` and verify that you are redirected to a guide page
> Add guides redirects

- frontend/components/product-list/sections/FilterableProductsSection/ProductListPagination.tsx
fixes #293 
2. Verify that the problem described by #293 is fixed
> Fix product list pagination url issue

- frontend/components/product-list/sections/FilterableProductsSection/ProductList.tsx
fixes #241 
- Improve responsive styles for product list view
2. Navigate to `/Store/Parts`
3. Verify that the problem described by #241 is fixed
cc @erinemay
> Reduce mobile product list excessive whitespace

- frontend/package.json
- pnpm-lock.yaml
fixes #209 
2. Perform a smoke test to verify that the product list page is still working
> Upgrade Next.js and Immer.js to fix vulnerabilities

- backend/.env.example
- backend/config/middlewares.js
- backend/config/plugins.js
- backend/package.json
- backend/yarn.lock
Make the S3 bucket configurable via an env variable.
Closes #309
> Strapi Uploads: persist in s3

- backend/config/middlewares.js
- backend/config/plugins.js
- backend/package.json
- backend/yarn.lock
This PR pin the `@strapi/provider-upload-aws-s3` to version `4.1.8`, which is the current version being used by the project.
qa_req 0
> Pin aws provider upload plugin to specific version

- frontend/components/product-list/sections/FilterableProductsSection/SearchInput.tsx
~~🚨 Blocked by #332 deploy_block~~
This PR fixes the [search bug](https://github.com/iFixit/react-commerce/pull/326#issuecomment-1154252157) reported by @erinemay 
2. Verify that the search bug described in the above comment doesn't happen anymore
> Fix search debouncing

- frontend/components/product-list/sections/FilterableProductsSection/FacetsAccordion.tsx
- frontend/components/product-list/sections/FilterableProductsSection/FacetsDrawer.tsx
- frontend/components/product-list/sections/FilterableProductsSection/RefinementList.tsx
- frontend/test/cypress/integration/product-list/filters.spec.ts
~~🚨 Blocked by #332 deploy_block~~
This PR removes the buggy input price. Eventually we'll come up with something better and fix it.
2. Verify that we show the price range facet values without the the min and max price range input
> Remove buggy input price

- frontend/lib/cache.ts
- frontend/models/global-settings.ts
- frontend/models/store.ts
- frontend/package.json
- pnpm-lock.yaml
We were making these three strapi requests on every next request.
The data changes infrequently, so let's cache it for a bit and eliminate 3 requests for most page loads.
> Strapi: Cache some rarely-changing results

- frontend/next.config.js
- frontend/package.json
- pnpm-lock.yaml
This allows us to see what's making up our various bundles. We're hunting for what might be leading to slow boot times on our application.
> Add Webpack Bundle Analyzer to config

- frontend/next.config.js
- packages/cart-sdk/hooks/use-checkout.ts
fixes #346 
1. Visit the [Vercel PR preview](https://react-commerce-git-fix-sso-route-ifixit.cominor.com/Parts)
2. Verify that you can checkout as a normal customer (using the cart drawer checkout button)
3. Verify that you can checkout as a pro customer (using the cart drawer checkout button)
> Add shopify store from context to SSO route

- frontend/components/common/InstantSearchProvider.tsx
fixes #352 
1. Visit Vercel Preview
2. Verify that the bug described by #352 is fixed
> Fix Algolia popstate bug

- README.md
- frontend/components/product-list/sections/FeaturedProductListSection.tsx
- frontend/components/product-list/sections/FilterableProductsSection/ProductGrid.tsx
- frontend/components/product-list/sections/FilterableProductsSection/ProductList.tsx
- frontend/package.json
- package.json
- pnpm-lock.yaml
closes #313 
This PR switches the color of product card title to `brand` color while hovering onto product cards
1. Open [Vercel Preview](https://react-commerce-git-highlight-product-list-item-ti-5b3a1a-ifixit.cominor.com/Parts)
2. Verify than hovering on the cards of the product list the title color is correctly switched to `brand` color (both for list and grid view)
3. Verify that also the featured product tiles show the title highlight behaviour on hover (I've added a featured `MacBook parts` section on the bottom of the page
> Highlight product list item title on hover

- frontend/components/product-list/sections/FilterableProductsSection/useFacets.tsx
- frontend/components/product-list/sections/RelatedPostsSection/index.tsx
From #400 
> 1) Dates are incorrect. All items have today's date. 
> ![image](https://user-images.githubusercontent.com/7053450/177618847-faeae7a9-9141-46b7-b8c6-2720ec6ff5b4.png)
1. Open [Vercel Preview](https://react-commerce-git-fix-related-post-date-ifixit.vercel.app/Parts)
2. Visit `/Parts` and verify that posts have the correct date
> Fix related post date

- README.md
Took me a little while to get the dev environment set up, so I made a few updates to the README.
qa_req 0
> README: improve installation instructions

- README.md
Hopefully this speeds others up
qa_req 0
> Readme: Update it with my speed bumps

- .github/workflows/jest.yml
In https://github.com/iFixit/react-commerce/pull/438, we will add jest tests. This pull adds a new workflow to run jest tests using github actions.
Please re-run the jest action and make sure it passes.
Merge after https://github.com/iFixit/react-commerce/pull/438 is deployed.
> Add jest tests workflow to github actions 

- frontend/.env.development
- frontend/.env.production
- frontend/components/analytics/Matomo.tsx
- frontend/components/analytics/index.ts
- frontend/components/product-list/ProductListView.tsx
- frontend/config/env.ts
- frontend/next.config.js
Tracking code from: https://minerva.ifixit.com/index.php?module=CoreAdminHome&action=trackingCodeGenerator
Click around on dev and prod previews, and make sure the event show up in [matomo.ubreakit.com](http://matomo.ubreakit.com/) or [minerva.ifixit.com](https://minerva.ifixit.com). Thanks!
_Note:_ You should disable all ad blockers when testing this, as they might prevent the Matomo script from running.
CC @sterlinghirsh
Connects #300
> Analytics: Add Matomo script

- frontend/pages/Shop/[handle].tsx
Visit /Shops/anything. Make sure the page 404s for anything except marketing collections, and that the page works properly for marketing collections.
Closes #473
> Pages: Add `/Shop/[handle]` page

- frontend/components/product-list/sections/RelatedPostsSection/index.tsx
This PR introduces react query instead of a custom logic to retrieve related posts.
If no [additional clarification](https://github.com/iFixit/react-commerce/issues/426#issuecomment-1196868780) is required wrt that issue, this closes #426 
2. Verify that related news stories are rendered
3. Verify that related news stories are consistent with the collection
> Related posts fetched via react query

- frontend/legacyPartCollectionRoutes.js
Fixes https://github.com/iFixit/react-commerce/pull/524#issuecomment-1198632394
CC @erinemay
> iFixit Exclusives: add one more item type redirect

- frontend/components/product-list/MetaTags.tsx
- frontend/models/product-list/index.ts
- frontend/models/product-list/types.ts
- frontend/pages/Parts/[...deviceHandleItemType].tsx
> Add item type to canonical

- frontend/pages/Parts/[...deviceHandleItemType].tsx
- frontend/pages/Parts/index.tsx
- frontend/pages/Shop/[handle].tsx
- frontend/pages/Tools/[handle].tsx
- frontend/pages/Tools/index.tsx
> Bugfix: bad comment

- frontend/pages/Community/index.tsx
Here's a really basic "Community" page. This is just the first pull to give us a place to start building the page.
qa_req 0
This should be completely unused and inaccessible from prod for now.
> Add a Community page

- frontend/templates/product-list/index.tsx
This function takes no args and we don't need it till we return the
final result, so let's call it early and await on the result before
returning.
> Product List Template: DRY up layout props calls

- packages/ui/homepage-kpis/index.tsx
- Fix centering of stat numbers
- Increase font sizes
Minor changes to fix the KPI footer styling.
> KPIs: Styling fixes

- frontend/templates/product-list/sections/FilterableProductsSection/RefinementMultiSelect.tsx
Closes #636 
CC: @jordycosta @masonmcelvain
> Multi-Select Facet: Make the item count bold when refined

- frontend/models/product.ts
- frontend/package.json
- frontend/templates/product/index.tsx
- pnpm-lock.yaml
🛑 Blocked by #643 
Adds product model exporting a method to retrieve product data from Shopify
2. Visit [/Products/abcde](https://react-commerce-git-add-product-model-ifixit.vercel.app/Products/abcde) and verify that a 404 is returned
3. Visit [/Products/pro-tech-toolkit](https://react-commerce-git-add-product-model-ifixit.vercel.app/Products/pro-tech-toolkit) and verify that the pro tech toolkit title is displayed on the page
> Add product model

- frontend/templates/product-list/sections/ProductListChildrenSection.tsx
- frontend/templates/product-list/sections/ProductListSetSection.tsx
We didn't have the best screen reader experience for the product button images. This PR fixes this.
Closes #446 
CC: @erinemay
> Fix screen reader experience

- frontend/helpers/product-helpers.ts
- frontend/templates/product/sections/ProductSection/AddToCart/NotifyMeForm.tsx
- frontend/templates/product/sections/ProductSection/AddToCart/index.tsx
- frontend/templates/product/sections/ProductSection/index.tsx
- packages/ui/theme/components/alert.ts
- packages/ui/theme/index.ts
This is the first implementation of #688. When the new back in stock api is ready we'll make another PR to use that.
1. Open Vercel Preview
2. Visit a product without stock
3. Verify that you see the back in stock form 
4. Insert your email and verify that the request succeeds
5. Disable the network to simulate a network error, and verify that an error message is shown
> Add back in stock form

- frontend/package.json
- frontend/templates/product/hooks/useSwiper.ts
- frontend/templates/product/sections/ProductSection/ProductGallery.tsx
- frontend/templates/product/sections/ProductSection/index.tsx
- pnpm-lock.yaml
closes #674 
closes #669 
This PR introduces a new product gallery component to display product images.
The product page contains two product galleries: one for desktop, one for mobile.
The two galleries are kept in sync so that the same image is shown even if the screen dimensions changes (eg rotating a mobile device).
The whole productSection inside the product page (so gallery + product variant selectors) is now responsive
1. Visit the Vercel preview
2. Check that the gallery is working properly
3. Check that mobile and desktop galleries are kept in sync
4. Check that the product section is responsive
> Add carousel to product page

- frontend/templates/product/sections/ReviewsSection/index.tsx
closes #692 
2. Visit a product with reviews
3. Verify that now the product reviews section is responsive
> Make product page reviews responsive and apply design updates

- pnpm-lock.yaml
We think that we accidentally installed dependencies with pnpm 6 in #747.
> Hotfix: Install dependencies with pnpm 7

- frontend/templates/product/hooks/useSelectedVariant.ts
- frontend/templates/product/sections/FeaturedProductsSection/index.tsx
closes #767 
1. Visit a [product page](https://react-commerce-git-add-product-page-featured-prod-cbf560-ifixit.vercel.app/Products/pro-tech-toolkit) on the Vercel preview
2. Verify that the featured products at the bottom of the page link to product pages
> Add links to featured products section

- frontend/models/product.ts
- frontend/templates/product/sections/ReviewsSection/index.tsx
closes #801 
2. Visit a [product without reviews](https://react-commerce-git-add-product-page-reviews-empty-state-ifixit.vercel.app/Products/17-blade-5-pcs)
3. Verify that the empty state is implemented according to [mockup](https://www.figma.com/file/sfj6r7Bn6eREMvuqo0f7Du/iFixit---Components?node-id=979%3A30852)
> Add reviews section empty state

- frontend/templates/product/sections/ReplacementGuidesSection/index.tsx
- packages/ui/misc/IconBadge.tsx
closes #830 
1. Open [Vercel preview](https://react-commerce-git-fix-repair-guides-badge-overflow-ifixit.vercel.app/products/1-tb-5400-rpm-2-5-hard-drive)
2. Verify that issue described by #830 is fixed
> Fix repair guides badges overflow

- frontend/layouts/default/DefaultLayout/index.tsx
- frontend/pages/404.tsx
Connects with  https://github.com/iFixit/react-commerce/issues/506
Changes made
--
- Added new 404 Page
- Updated `DefaultLayout` to have a minimum height set to the user's viewport height
QA
--
- Do a smoke test to check that all pages have proper header, footer, and spacing consistent with master
- Ensure 404 page looks as expected
<details><summary>Docs used</summary>
https://nextjs.org/docs/advanced-features/custom-error-page#404-page
https://nextjs.org/docs/basic-features/data-fetching/get-static-props
https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props
</details>
cr_req 2
> Add Custom 404 Page

- frontend/templates/product/sections/ProductSection/AddToCart/index.tsx
- frontend/test/cypress/integration/product/add_to_cart.cy.ts
- frontend/test/cypress/support/commands.ts
- frontend/test/cypress/support/index.d.ts
- packages/ui/cart/drawer/CartDrawer.tsx
- packages/ui/cart/drawer/CartLineItem.tsx
We want to add some tests to the repo to cover cart functionality. This adds several tests that make sure that several actions go as expected.
Should be covered by tests qa_req 0;
Closes: #843
> Add Cypress Cart Test To Product Page

- frontend/public/robots.txt
This PR adds this file to the public folder and includes the 2 lines we want based on the issue.
Closes #743
> Add a robots.txt file

- frontend/templates/product/sections/ProductSection/index.tsx
closes #888 
1. Open [Vercel preview](https://react-commerce-git-improve-product-page-alerts-links-ifixit.vercel.app/products/google-pixel-3a-xl-replacement-battery-genuine)
2. Verify that links appearance is improved (the design has been reviewed with @mmarcon91 )
> Improve product page alerts links

- frontend/lib/shopify-storefront-sdk/generated/sdk.ts
- frontend/lib/shopify-storefront-sdk/operations/productVariantCard.fragment.graphql
- frontend/models/product.ts
- frontend/templates/product/sections/CrossSellSection/index.tsx
closes #895 
1. Visit [Vercel preview](http://localhost:3000/products/usb-power-adapter-for-iphone-and-ipod)
2. Verify the OOS cross sell variants are not shown
> Hide OOS cross sell variants

- frontend/templates/product/sections/ProductSection/index.tsx
- frontend/templates/product/sections/ServiceValuePropositionSection/index.tsx
Jeff has some new text to implement for the propositions [here](https://docs.google.com/spreadsheets/d/1ghuenb5j9kyDK3-RJtSLeBctrXxOseOHJr3gHk5G65k/edit#gid=0). Let's update our propositions to match these desired texts.
Is the text right now? Does everything else look the same?
Closes: #910
> Lets Fix the Hardcoded Proposition Text

- frontend/lib/shopify-storefront-sdk/generated/sdk.ts
- frontend/lib/shopify-storefront-sdk/operations/findProduct.graphql
- frontend/models/product.ts
closes #896 
1. Visit [Vercel preview](https://react-commerce-git-shuffle-product-page-featured-4d7020-ifixit.vercel.app/products/iphone-7-replacement-battery)
2. Verify that featured products are shuffled (this is done every time the page is requested, unless the page is cached)
> Shuffle product page featured products

- frontend/templates/product/sections/ProductSection/ProductGallery.tsx
closes #892 
The gallery component (and thumbnails) were updated to also support images with aspect ratio different from 1.
1. Visit [Vercel preview](https://react-commerce-git-fix-product-image-aspect-ratio-ifixit.vercel.app/products/p5-pentalobe-screwdriver-retina-macbook-pro-and-air)
2. Verify that images with aspect ratio different from 1 are now displayed correctly 
3. Verify that all the aspect of the gallery (zoom, zoomed area cursor etc) are still working as expected
> Handle different product image aspect ratios

- frontend/templates/product/index.tsx
Closes #912 
It's time.
qa_req 0
> Stop noindexing product page

- backend/src/components/store/social-media-accounts.json
After this PR is merged, we can add our TikTok social media page to the footer
> Strapi: add 'tiktok' attribute

- frontend/next.config.js
- frontend/test/cypress/integration/redirect.cy.ts
Max has requested a vanity redirect for the products.xml, so this implements a redirect to ifixit when you try to access it. 
Covered by test and also this is internal facing so im ok with qa_req 0;
Closes: #950
> Add sitemap redirect for products

- frontend/components/common/AppProviders.tsx
- frontend/helpers/next-helpers.ts
- frontend/layouts/default/getLayoutServerSideProps.ts
- frontend/models/product.ts
- frontend/templates/product/hooks/useProductReviews.ts
- frontend/templates/product/index.tsx
Add more logs and drop some verbose ones. Individual commits have more context.
Closes #944 
Connect #949 -- uses it in one more place
> PPv2: add logging

- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/operations/getProductList.graphql
- frontend/models/product-list/index.ts
- frontend/models/product-list/types.ts
- frontend/templates/product-list/sections/ProductListChildrenSection.tsx
Reverts iFixit/react-commerce#983
> Revert "Add a flag to control the show all default value of product list children on large screen (frontend changes)"

- backend/src/api/product-list/content-types/product-list/schema.json
- frontend/lib/strapi-sdk/generated/sdk.ts
Reverts iFixit/react-commerce#974
> Revert "Add a flag to control the show all default value of product list children on large screen (backend changes)"

- frontend/templates/product/hooks/useSelectedVariant.ts
- frontend/templates/product/index.tsx
- frontend/templates/product/sections/ProductSection/index.tsx
- frontend/templates/product/sections/ServiceValuePropositionSection/index.tsx
Hide the "shipping" parts of our value propositions for products that are not shipped by us.
Originally: #965 but simplified here
Closes https://github.com/iFixit/ifixit/issues/45298
CC @dhmacs
> Value propositions: hide parts for dropshipped products

- frontend/components/common/InstantSearchProvider.tsx
- frontend/helpers/algolia-helpers.ts
- frontend/models/product-list/index.ts
This is an attempt to increase Algolia timeouts to avoid unreachable hosts errors.
Make sure collection pages work normally.
CC @sterlinghirsh @danielbeardsley
Closes #1016
> Algolia: Bump connect timeout to 5 seconds

- frontend/test/cypress/integration/product/pro_user.cy.ts
- frontend/test/cypress/support/commands.ts
- frontend/test/cypress/support/index.d.ts
This verifies that pro users get a discount on products. We are using
the repair business toolkit and mocking the logged in user to verify
that they get the discount.
Because we are not mocking the product itself, I didn't want to get
too specific with prices. Instead, we just verify that the price
for a regular user is *higher* than it is for a pro user.
Connects: #1043 
cc @batbattur
> Pro users: Add a test

- README.md
- app_architecture_diagram.excalidraw
closes #1041 
qa_req 0
This PR updates the readme and adds an application architecture diagram
cc @ardelato
> Add application architecture diagram

- frontend/components/common/PageBreadcrumb.tsx
- frontend/components/product-list/ProductListCard.tsx
- frontend/package.json
- frontend/templates/product-list/ProductListBreadcrumb.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/ProductList.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/SearchInput.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/facets/accordion/index.tsx
- frontend/templates/product/sections/ProductSection/index.tsx
- packages/icons/misc/FaIcon.tsx
- packages/ui/header/NavigationMenu.tsx
- pnpm-lock.yaml
fixes #1074 
1. Open [Vercel preview](https://react-commerce-git-fix-fouc-ifixit.vercel.app/Parts)
2. Disable Javascript (you can do so using browser dev tools)
3. Verify that there's no unstyled content on product list and product pages (you can use #1074 screenshots as reference)
> Remove sources of FOUC

- backend/src/api/product-list/content-types/product-list/schema.json
- frontend/lib/strapi-sdk/generated/sdk.ts
Make sure the toggle shows up on this branches strapi https://strapi-noindex-productlist.govinor.com/admin
Connects #705
> Strapi: add `forceNoindex` toggle

- frontend/test/jest/__mocks__/products.ts
The Product type was recently updated so we started throwing a type error when running `pnpm type-check`. This commit updates the mocked product properties to match the new type definition.
qa_req 0 - CI is enough
> Hot Fix: Update mocked product properties to match new product type definition

- frontend/models/product.ts
Rating is an average of a bunch of ints and thus is a float!
Otherwise, 4.9 is rounded down to 4!
Closes iFixit/ifixit#45799
> Product Reviews: treat rating as float

- frontend/tests/jest/tests/ProductSection.test.tsx
This adds Jest tests to address #1132
I opted out of writing a `Jest` test to confirm the cart price matches the listed price when adding to the cart because it will be much simpler to test this through a `Cypress`, or `Playwright`, than through a `Jest` test. 
Connects: #1132
> Product Page: Add Discounted Product Tests

- .github/actions/pnpm-setup/action.yml
- .github/workflows/format.yml
- .github/workflows/jest.yml
- .github/workflows/main.yml
- .github/workflows/nextjs_bundle_analysis.yml
- .github/workflows/tsc.yml
- frontend/package.json
- package.json
Using this package: https://github.com/hashicorp/nextjs-bundle-analysis Add the github workflow to build our next bundle and compare the results to the bundle on the main branch.
The workflow may fail until it's run once on the main branch.
> GitHub workflow: add next bundle analysis

- frontend/components/admin/ProductEditMenu.tsx
- frontend/components/admin/index.ts
- frontend/helpers/path-helpers.ts
- frontend/helpers/product-helpers.ts
- frontend/lib/shopify-storefront-sdk/generated/sdk.ts
- frontend/lib/shopify-storefront-sdk/operations/findProduct.graphql
- frontend/templates/product/components/SecondaryNavigation.tsx
- frontend/templates/product/index.tsx
- frontend/tests/cypress/support/commands.ts
- frontend/tests/jest/__mocks__/products.ts
- frontend/tests/jest/tests/__snapshots__/ProductListItem.test.tsx.snap
- packages/auth-sdk/package.json
- packages/auth-sdk/user.tsx
- packages/icons/misc/FaIcon.tsx
- pnpm-lock.yaml
[Mockup link](https://www.figma.com/file/sfj6r7Bn6eREMvuqo0f7Du/iFixit---Components?node-id=127%3A14037&t=bQwXOMEnro4vO8D5-4)
- Log into cominor with your employee account.
- On the react-commerce product page, the edit dropdown should be visible on the product page.
- Make sure the links work and the UX seems ok on mobile and desktop.
- Log into cominor with a non-employee account
- The dropdown should be hidden. _The UI should be unchanged from `main` for non-admin users._
- Log out of cominor
- The dropdown should be hidden. _The UI should be unchanged from `main` for non-admin users._
Note: You should replace `.vercel.app` with `.cominor.com` in the preview url to make the user requests succeed.
Closes #941
> Add admin links to the product page

- frontend/templates/product/sections/ProductSection/AddToCart/index.tsx
- frontend/tests/jest/__mocks__/products.ts
- frontend/tests/jest/tests/ProductSection.test.tsx
This addresses #1141 
Closes: #1141
> Product Page: Test Low Stocked Product

- frontend/tests/jest/__mocks__/products.ts
- frontend/tests/jest/tests/ProductReviews.test.tsx
- frontend/tests/jest/utils.tsx
Added the following tests for checking the reviews:
- Checks if the review section renders when the product has reviews.
- Checks if the review section renders with `No reviews yet` text when the product has no reviews.
- Checks if the review count and average at the top of the page (from `ProductRating` component) match the review count and average at the bottom (from `ReviewSection` component).
Passing CI is enough. (qa_req 0)
closes #1146
> Product Page: Test Review Section

- packages/cart-sdk/hooks/use-cart.ts
- packages/cart-sdk/types.ts
- packages/helpers/commerce-helpers.ts
- packages/helpers/generic-helpers.ts
- packages/ui/cart/drawer/CartDrawer.tsx
- packages/ui/cart/drawer/CartDrawerTrigger.tsx
- packages/ui/cart/drawer/CartEmptyState.tsx
- packages/ui/cart/drawer/CartLineItem.tsx
- packages/ui/cart/drawer/CartLineItemImage.tsx
- packages/ui/cart/drawer/Upsell.tsx
closes #1095 
1. Verify that a product upsell is shown in the cart drawer
2. Verify that you can add the upsell to the cart
3. Check that the price are correctly displayed based on the logged in user
cc @sterlinghirsh
> Add minicart upsell

- frontend/templates/product/sections/FeaturedProductsSection/index.tsx
| Before | After |
| --------- | ------ |
| ![image](https://user-images.githubusercontent.com/806152/210278556-b4d33cb2-c1c5-4047-8b79-0c9dc503ed52.png) | ![image](https://user-images.githubusercontent.com/806152/210278558-c5dc5d61-12bb-4213-a8fb-4547ff77aeaf.png) |
CR
---
Ignore whitespace
Closes https://github.com/iFixit/react-commerce/issues/1206
> Featured Products: fix unbounded width

- frontend/templates/product/sections/CrossSellSection/index.tsx
- frontend/tests/playwright/product/cross_sell.spec.ts
This adds some basic tests for our cross sell component. We assert
that we can check and uncheck different products and they are
reflected in the price in the component as well as in the cart
drawer.
QA:
--
These should run in the playwright ci job.
Connects: https://github.com/ifixit/react-commerce/issues/1202
> Cross-sell: Add tests

- frontend/package.json
- frontend/tests/playwright/product/cross_sell.spec.ts
- pnpm-lock.yaml
1. Updated playwright to 1.29.1
2. Used `locator.all()` in `cross_sell` test to verify the feature from the new playwright version works properly. 
qa_req 0
cc: @mlahargou 
closes: #1226
> Tests: Update playwright version

- frontend/playwright.config.ts
- frontend/tests/playwright/fixtures/index.ts
- frontend/tests/playwright/fixtures/product-page.ts
- frontend/tests/playwright/product-list/collections_scroll.spec.ts
- frontend/tests/playwright/product-list/collections_view_button.spec.ts
- frontend/tests/playwright/product-list/filters.spec.ts
- frontend/tests/playwright/product-list/newsletter_subscribe.spec.ts
- frontend/tests/playwright/product-list/parts_page_devices.spec.ts
- frontend/tests/playwright/product-list/parts_page_search.spec.ts
- frontend/tests/playwright/product-list/parts_results_view.spec.ts
- frontend/tests/playwright/product/add_to_cart.spec.ts
- frontend/tests/playwright/product/cross_sell.spec.ts
- frontend/tests/playwright/product/disabled_product.spec.ts
- frontend/tests/playwright/product/fix_kit.spec.ts
- frontend/tests/playwright/product/pro_user.spec.ts
- frontend/tests/playwright/product/product_breadcrumb.spec.ts
- frontend/tests/playwright/product/product_image.spec.ts
- frontend/tests/playwright/product/product_option.spec.ts
- frontend/tests/playwright/product/product_page.spec.ts
- frontend/tests/playwright/product/product_reviews.spec.ts
- frontend/tests/playwright/redirect.spec.ts
- frontend/tests/playwright/test-fixtures.ts
- frontend/tests/playwright/troubleshooting/loading.spec.ts
By using Playwright custom fixtures[^1] we will be creating `iFixit/ifixit`'s extension-like classes to help with interacting with elements and making assertions.
We will be adding more methods and fixtures in the future to fully address #1217, but for now this is a good start.
Connects: https://github.com/ifixit/react-commerce/issues/1217
[^1]: https://playwright.dev/docs/test-fixtures#creating-a-fixture
qa_req 0
> Playwright: Create custom fixtures to help interact with elements

- README.md
- package.json
1. Added playwright commands in root `package.json`.
2. Updated the `Tests` section in read me.
Please make sure the Readme makes sense. 
closes: #1253
> Tests: Update Playwright scripts in root package.json

- frontend/templates/product/sections/ProductSection/ProductOptions.tsx
- frontend/templates/product/sections/ProductSection/index.tsx
- frontend/tests/jest/tests/ProductSection.test.tsx
- frontend/tests/jest/tests/__snapshots__/ProductListItem.test.tsx.snap
- frontend/tests/playwright/fixtures/product-page.ts
- frontend/tests/playwright/product-list/parts_results_view.spec.ts
- frontend/tests/playwright/product/add_to_cart.spec.ts
- frontend/tests/playwright/product/cross_sell.spec.ts
- frontend/tests/playwright/product/disabled_product.spec.ts
- frontend/tests/playwright/product/fix_kit.spec.ts
- frontend/tests/playwright/product/pro_user.spec.ts
- frontend/tests/playwright/product/product_option.spec.ts
- frontend/tests/playwright/product/product_page.spec.ts
- packages/ui/commerce/ProductPrice.tsx
This is a continuation of https://github.com/iFixit/react-commerce/pull/1258
- Adds utility functions to target the prices of the product page we are on
- Adds utility functions to help select the different variants
- Adds additional attributes to help locate and select price elements and the variant options
- Integrates the utility functions into our current tests
I did not extend the utility functions to interact with all types of variant selectors (i.e. the dropdown menu) as we primarily interact with the image type selector in our tests. If the need arises, we can extend the utility functions in the future.
Connects: #1217 
qa_req 0
> Playwright: Add more utility functions for the Product Page

- frontend/tests/playwright/fixtures/cart-drawer.ts
- frontend/tests/playwright/fixtures/index.ts
- frontend/tests/playwright/product/add_to_cart.spec.ts
- frontend/tests/playwright/product/product_option.spec.ts
- frontend/tests/playwright/test-fixtures.ts
- packages/ui/cart/drawer/CartDrawer.tsx
This is a continuation of https://github.com/iFixit/react-commerce/pull/1258 that builds on top of https://github.com/iFixit/react-commerce/pull/1261.
- Adds utility functions for opening and closing the cart drawer
- Adds utility functions for incrementing/decrementing the quantities of cart items
- Adds a utility function to remove specific cart items
- Adds utility functions for asserting quantities and the presence of cart items
qa_req 0
Connects: #1217
> Playwright: Add Cart Drawer Utility Functions

- frontend/templates/troubleshooting/prerendered.tsx
This makes them look much nicer and line up well with the rest of the text.
There's no mockup for lists, so please just confirm that this looks reasonable to you.
This may be a helpful link:
https://react-commerce-git-vulcan-add-list-styles-ifixit.vercel.app/Vulcan/troubleshooting-test
Closes https://github.com/iFixit/ifixit/issues/46306
> Vulcan: Add list styles

- frontend/templates/product/sections/ProductSection/AddToCart/NotifyMeForm.tsx
- frontend/templates/product/sections/ProductSection/AddToCart/index.tsx
- frontend/tests/jest/tests/ProductSection.test.tsx
- frontend/tests/playwright/product/add_to_cart.spec.ts
- packages/ui/commerce/ProductPrice.tsx
- packages/ui/theme/components/alert.ts
closes #951 
This PR adds an out of stock alert box as requested in #951 and contains also a couple of color corrections.
2. Verify that the new design for Out of Stock has been implemented
> Add Out of Stock alert

- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/operations/getProductList.graphql
- frontend/models/product-list/server.ts
- frontend/models/product-list/types.ts
- frontend/templates/product-list/sections/ProductListChildrenSection.tsx
Reverts iFixit/react-commerce#1309
We updated Strapi so this should be good to go.
> Revert "Revert "Display 4 rows devices on selected pages frontend""

- frontend/next.config.js
- frontend/package.json
- pnpm-lock.yaml
This is the other plugin we run on iFixit/ifixit; I wanted to see if it would provide better information for figuring out what's going on with a build. It wasn't able to answer the question I had, but I figure it seems worth keeping the set up work I did.
qa_req 0
This is dev-only, and we're not that concerned if it doesn't work.
> Add `bundle-stats` plugin

- frontend/templates/troubleshooting/prerendered.tsx
This makes them match the mockup better.
Please check that the paragraph spacing looks reasonable.
Link: https://react-commerce-git-troubleshooting-fix-paragraph-spacing-ifixit.vercel.app/Vulcan/troubleshooting-test
Mockup: https://www.figma.com/file/jRG4EyQXRDMGfyLqut08KP/iFixit---Working-files?node-id=9319%3A156393&t=JLFYzxqu8ZsEPfzI-0
Closes #46381
> Troubleshooting: Add padding on paragraphs

- frontend/templates/troubleshooting/prerendered.tsx
I don't think there's a demo of this on the mockup, so I've just imitated what the existing wikis do.
https://react-commerce-git-troubleshooting-add-quote-styling-ifixit.vercel.app/Vulcan/troubleshooting-test
Closes #46382
> Troubleshooting: Add styling for blockquote element

- frontend/helpers/cache-control-helpers.ts
- frontend/pages/Parts/[...deviceHandleItemType].tsx
- frontend/pages/Parts/index.tsx
- frontend/pages/Shop/[handle].tsx
- frontend/pages/Tools/[handle].tsx
- frontend/pages/Tools/index.tsx
- frontend/templates/product-list/server.tsx
closes #1367 
This also increases to 5 minutes the default `s-maxage` of product pages
qa_req 0
> Increase product list s-maxage and stale-while-revalidate duration

- packages/breadcrumbs/Breadcrumbs.tsx
- packages/breadcrumbs/package.json
- pnpm-lock.yaml
Seems I missed some dependencies when I set this up previously. I'm assuming this is because we don't have PNPM set to particularly strict settings in this repo, so I didn't notice that they were missing. It could also be because the code wasn't actually being used yet, so there wasn't any build to break.
qa_req 0
This is dependency-only, and this code is currently unused. We'll test it when we integrate it on the monorepo side.
> Breadcrumbs: Add missing dependencies

- frontend/templates/troubleshooting/hooks/useTroubleshootingProps.tsx
- frontend/templates/troubleshooting/index.tsx
This adds a nav bar and the `Edit` button/link on it. It's not adding anything else just yet, as this is about the easiest part of the bar to build first.
Link: https://react-commerce-git-vulcan-add-nav-bar-ifixit.vercel.app/Vulcan/troubleshooting-test
Please check that the nav bar looks decent and that the edit link works. You may have to click the link and then edit the URL to point at Cominor, because it only uses a relative URL. Deployed, that shouldn't be a problem, because we'll be on the `ifixit.com` domain.
Closes ifixit/ifixit#46529
> Troubleshooting: Add nav bar and edit link

- frontend/templates/troubleshooting/prerendered.tsx
I'm trying to do something like our existing design which also looks reasonable in react-commerce.
Please check that tables render reasonably in the new Vulcan pages.
Here's a page which includes a couple table examples:
https://react-commerce-git-vulcan-table-styling-ifixit.vercel.app/Vulcan/troubleshooting-test
> Troubleshooting: Add some basic styling on tables

- frontend/components/common/ProductCard.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/Pagination.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/ProductGrid.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/ProductList.tsx
- frontend/tests/jest/tests/__snapshots__/ProductListItem.test.tsx.snap
- packages/ui/commerce/ProductPrice.tsx
closes #1370 
This PR update the spacing and measures in the product list and grid items to adhere to https://github.com/iFixit/design/issues/510
1. Visit [Vercel preview](https://react-commerce-git-refactor-product-list-items-ifixit.vercel.app/Parts)
2. Verify that the page is correctly working and that grid and list items are aligned to the mockup
> Refactor product list items

- frontend/templates/troubleshooting/hooks/useTroubleshootingProps.tsx
- frontend/templates/troubleshooting/index.tsx
Both these URLs may be missing if there's not a sensible place to link to, so this will disable the tab if there's no URL for it.
Please confirm that the tabs look reasonable and link to the appropriate places.
Example URL which should have both a Parts and a Guide link:
https://react-commerce-git-vulcan-add-area-links-ifixit.vercel.app/Vulcan/iPhone_Won't_Turn_On
Example URL which should have a working Guide link and a disabled Parts link:
https://react-commerce-git-vulcan-add-area-links-ifixit.vercel.app/Vulcan/Washing_Machine_Not_Spinning
Example URL which should have both a disabled Guide link and a disabled Parts link:
https://react-commerce-git-vulcan-add-area-links-ifixit.vercel.app/Vulcan/troubleshooting-test
Closes iFixit/ifixit#46652
> Troubleshooting: Add nav tabs

- frontend/tests/playwright/troubleshooting/loading.spec.ts
I realized there were some new features which were easy enough to add tests for.
qa_req 0
This only adds tests.
Connects https://github.com/iFixit/ifixit/issues/46529
Connects https://github.com/iFixit/ifixit/issues/46560
> Troubleshooting: Add some frontend tests

- backend/src/api/product/content-types/product/schema.json
- backend/src/api/product/controllers/product.ts
- backend/src/api/product/routes/product.ts
- backend/src/api/product/services/product.ts
- backend/src/components/product/cross-sell.json
- backend/src/components/product/product-customer-reviews.json
- backend/src/components/product/product.json
- backend/src/components/product/replacement-guides.json
- backend/src/components/section/service-value-propositions.json
- backend/src/components/section/stories.json
- frontend/lib/strapi-sdk/generated/sdk.ts
closes #1450 
qa_req 0
This PR contains changes that only affect Strapi
> Add Strapi product collection type

- frontend/components/ui/Rating.tsx
- frontend/templates/product/sections/ProductSection/AddToCart/AddToCartBar.tsx
- frontend/templates/product/sections/ProductSection/AddToCart/InventoryMessage.tsx
- frontend/templates/product/sections/ProductSection/AddToCart/ShippingRestrictions.tsx
- frontend/templates/product/sections/ProductSection/AddToCart/index.tsx
- frontend/templates/product/sections/ProductSection/index.tsx
- frontend/tests/jest/tests/ProductSection.test.tsx
- frontend/tests/jest/utils.tsx
- packages/ui/hooks/index.ts
closes #1460 
- Implement add to cart bar
- Refactor of the add to cart component
1. Open a [product page preview](https://react-commerce-git-implement-product-page-add-to-ae2b72-ifixit.vercel.app/products/repair-business-toolkit)
2. Verify that the add to cart bar is implemented according to [mockup](https://www.figma.com/file/jRG4EyQXRDMGfyLqut08KP/iFixit---Working-files?node-id=4581%3A47483&t=etNQxH5K1Jws6dKx-4)
3. Verify that the add to cart bar is responsive
4. Verify that clicking "add to cart" on the bar takes you back to the add to cart section
The behaviour of the bar has been validated with @mmarcon91
> Implement add to cart bar

- frontend/components/common/ProductGrid.tsx
- frontend/components/ui/Rating.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/Pagination.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/index.tsx
closes #1472 
closes #1469 
This PR contains also some minor UI fixes
1. Open a product page preview with less than `6` featured products (e.g. [Arctic Silver Thermal Paste](https://react-commerce-git-fix-featured-products-section-d78d93-ifixit.vercel.app/products/arctic-silver-thermal-paste))
2. Verify that on desktop resolution you can still see featured products (5 columns for the Artic Silver Thermal Paste)
3. Open a product page preview with `6` or more featured products (e.g. [Repair Business Toolkit](https://react-commerce-git-fix-featured-products-section-d78d93-ifixit.vercel.app/products/repair-business-toolkit))
4. Verify that on desktop resolution up to `6` columns are shown
> Fix featured products section edge case

- backend/src/api/page/content-types/page/schema.json
- backend/src/api/social-post/content-types/social-post/schema.json
- backend/src/api/social-post/controllers/social-post.ts
- backend/src/api/social-post/routes/social-post.ts
- backend/src/api/social-post/services/social-post.ts
- backend/src/bootstrap/permissions/config.json
- backend/src/components/section/social-gallery.json
- frontend/components/sections/SocialGallerySection.tsx
- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/operations/findPage.graphql
- frontend/lib/strapi-sdk/operations/sections/SocialGallerySectionFields.fragment.graphql
- frontend/models/components/social-post.ts
- frontend/models/page/index.ts
- frontend/models/page/server.ts
- frontend/models/sections/social-gallery-section.ts
- frontend/templates/page/index.tsx
closes #1466 
cc @sterlinghirsh @danielbeardsley @masonmcelvain 
1. Open a [product page preview](https://react-commerce-git-add-social-gallery-section-ifixit.vercel.app/store)
2. Verify that the social gallery is implemented as specified in #1466 
3. Verify that the section is responsive
> 👁️ Data is editable from Strapi
> Add social gallery section

- frontend/templates/troubleshooting/hooks/useTroubleshootingProps.tsx
- frontend/templates/troubleshooting/index.tsx
These should match the `<meta>` tags on `/Wiki`.
Closes: https://github.com/ifixit/ifixit/issues/46901
> Troubleshooting: Add meta title, description, keywords

- frontend/layouts/default/Footer.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/facets/MenuFacet.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/facets/RefinementListFacet.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/facets/accordion/FacetMenuAccordionItem.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/facets/accordion/FacetRefinementListAccordionItem.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/facets/drawer/MenuFacetPanel.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/facets/drawer/RefinementListFacetPanel.tsx
- packages/ui/header/UserMenu.tsx
connects #447
Fixes to correct accessibility issues on product list page
2. Verify that no accessibility issue is present - excluding the one on color contrast
> Aria roles and labels fixes

- backend/src/api/banner/content-types/banner/schema.json
- backend/src/api/banner/controllers/banner.ts
- backend/src/api/banner/routes/banner.ts
- backend/src/api/banner/services/banner.ts
- backend/src/api/product/content-types/product/schema.json
- backend/src/components/section/banner.json
- backend/src/components/section/quote.json
closes #1526 
qa_req 0
This PR adds banners section and quote section to Strapi (frontend will be implemented in a separate PR)
> Add banners and quote sections content types

- backend/src/components/section/quote.json
qa_req 0
This is a quick PR to add a field in Strapi for the quote section background image
> Add image field to quote section

- frontend/components/sections/BannersSection/MultipleBanners.tsx
- frontend/components/sections/QuoteSection.tsx
- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/operations/findProduct.graphql
- frontend/lib/strapi-sdk/operations/sections/QuoteSectionFields.fragment.graphql
- frontend/models/product/sections/index.ts
- frontend/models/sections/banners-section.ts
- frontend/models/sections/quote-section.ts
- frontend/templates/product/index.tsx
closes #1535 
1. Open a [featured product page preview](https://react-commerce-git-add-product-page-quote-section-ifixit.vercel.app/products/repair-business-toolkit)
2. Verify that the quote section si implemented as specified in #1535 
3. Verify that the section is responsive
4. Verify that you can edit the section content from [Strapi](https://add-product-page-quote-section.govinor.com/admin/content-manager/collectionType/api::product.product/1)
> Add product page quote section

- frontend/components/sections/BannersSection/MultipleBanners.tsx
- frontend/components/sections/BannersSection/SingleBanner.tsx
- frontend/components/sections/BannersSection/index.tsx
- frontend/components/sections/FeaturedProductsSection.tsx
- frontend/components/sections/QuoteSection.tsx
- frontend/components/sections/ReplacementGuidesSection.tsx
- frontend/components/sections/ServiceValuePropositionSection.tsx
- frontend/components/sections/SplitWithImageSection.tsx
- frontend/helpers/strapi-helpers.ts
- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/operations/findProduct.graphql
- frontend/lib/strapi-sdk/operations/sections/DeviceCompatibilitySectionFields.fragment.graphql
- frontend/models/page/sections/browse-section.ts
- frontend/models/page/sections/hero-section.ts
- frontend/models/page/sections/press-quotes-section.ts
- frontend/models/page/server.ts
- frontend/models/product/sections/compatibility-section.ts
- frontend/models/product/sections/index.ts
- frontend/models/sections/ifixit-stats-section.ts
- frontend/models/sections/social-gallery-section.ts
- frontend/templates/page/index.tsx
- frontend/templates/product/index.tsx
- frontend/templates/product/sections/CompatibilitySection/index.tsx
- frontend/templates/product/sections/CrossSellSection/index.tsx
- frontend/templates/product/sections/LifetimeWarrantySection/index.tsx
- frontend/templates/product/sections/ProductOverviewSection/index.tsx
- frontend/templates/product/sections/ProductReviewsSection/index.tsx
- frontend/tests/jest/tests/ProductReplacementGuide.test.tsx
closes #1545 
This PR adds ids to sections, plus some minor UI fixes. A quick smoke test to see that product pages still work is sufficient
> Add product page section ids

- frontend/templates/troubleshooting/index.tsx
- frontend/templates/troubleshooting/prerendered.tsx
- frontend/templates/troubleshooting/solution.tsx
Adjust solution titles based on the updated mockup. This also includes some other text spacing changes, but we should do another pass after this pull for things like header sizes and spacing.
<details><summary>Image</summary>
</details> 
Closes: https://github.com/iFixit/ifixit/issues/47301
> Troubleshooting: Move solution title to same line as number

- frontend/lib/ifixit-api/devices.ts
- frontend/models/product/components/product-option.ts
- frontend/models/product/index.ts
- frontend/models/product/server.ts
- frontend/pages/api/nextjs/cache/product.ts
- frontend/templates/product/server.tsx
Reverts iFixit/react-commerce#1572
> Revert "Product Page: Use Sorted Variants"

- .github/actions/pnpm-setup/action.yml
- .github/workflows/format.yml
- .github/workflows/jest.yml
- .github/workflows/lint.yml
- .github/workflows/main.yml
- .github/workflows/nextjs_bundle_analysis.yml
- .github/workflows/stress_test.yml
- .github/workflows/tsc.yml
Resolves all github action deprecation warnings.
Check summaries for all CI workflows and make sure we don't get deprecation warnings anymore.
Also, make sure the bundle analysis comment shows up on the pull.
connects https://github.com/iFixit/ifixit/issues/47011
> GitHub Actions: Resolve deprecation warnings

- frontend/components/admin/PageEditMenu.tsx
- frontend/components/common/CompatibleDevice.tsx
- frontend/components/common/PageBreadcrumb.tsx
- frontend/components/sections/BannersSection/SingleBanner.tsx
- frontend/components/sections/SocialGallerySection.tsx
- frontend/components/sections/SplitWithImageSection.tsx
- frontend/components/ui/LinkButton.tsx
- frontend/components/ui/SmartLink.tsx
- frontend/helpers/path-helpers.ts
- frontend/layouts/default/Footer.tsx
- frontend/layouts/default/index.tsx
- frontend/templates/page/sections/HeroSection.tsx
- frontend/templates/page/sections/PressQuotesSection.tsx
- frontend/templates/product-list/ProductListBreadcrumb.tsx
- frontend/templates/product-list/ProductListDeviceNavigation.tsx
- frontend/templates/product-list/sections/BannerSection/index.tsx
- frontend/templates/product-list/sections/RelatedPostsSection/PostCard.tsx
closes #1600 
1. Open a [product list preview](https://react-commerce-git-add-smart-link-component-ifixit.vercel.app/Parts/Android_Phone) and verify these links are working:
1. Main navigation menu
2. Product list breadcrumb
3. Secondary nav links (guides and answers)
4. Page edit menu links (admin only)
5. Product list categories links 
6. Open a [product page preview](https://react-commerce-git-add-smart-link-component-ifixit.vercel.app/products/iphone-12-12-pro-replacement-battery) and verify these links are working:
1. Breadcrumbs
2. Device compatibility links
> Use smart link component to handle php pages links

- frontend/helpers/path-helpers.ts
- frontend/models/product-list/index.ts
- frontend/models/product-list/types.ts
Connects https://github.com/iFixit/react-commerce/issues/1612
CC @danielbeardsley @dhmacs 
qa_req 0 as long as CI passes
> Add zod schema for product list

- frontend/components/product-list/ProductListCard.tsx
- frontend/components/sections/SocialGallerySection.tsx
- frontend/templates/page/sections/PressQuotesSection.tsx
closes #1616 
qa_req 0
I went through the page template with @mmarcon91 and made a few adjustments/bug fixes
> Minor page template fixes and polishing

- frontend/layouts/default/index.tsx
- frontend/tests/playwright/utils.ts
- packages/auth-sdk/user.tsx
closes #152 
2. Verify that - according to the user's permissions - links to `/Manage` and `/Team` are shown
> Add manage links to user menu

- frontend/templates/product/sections/ProductOverviewSection/AddToCart/AddToCartBar.tsx
- frontend/templates/product/sections/ProductOverviewSection/AddToCart/index.tsx
- frontend/tests/jest/tests/ProductSection.test.tsx
- frontend/tests/jest/tests/__snapshots__/ProductListItem.test.tsx.snap
- frontend/tests/playwright/fixtures/product-page.ts
- frontend/tests/playwright/product-list/parts-page-product-listing.spec.ts
- frontend/tests/playwright/product/cross-sell.spec.ts
- frontend/tests/playwright/product/product-information.spec.ts
- packages/ui/commerce/ProductPrice.tsx
closes #1484 
1. Open [product page preview](https://react-commerce-git-update-add-to-cart-bar-behavior-ifixit.vercel.app/products/repair-business-toolkit)
2. Scroll to until you see the add to cart bar
3. Click the add to cart button on the bar
4. Verify the the selected product variant is added to the cart
> Update add to cart bar button behaviour

- packages/auth-sdk/user.tsx
> Hotfix: Handle undefined user teams from api

- frontend/components/common/CompatibleDevice.tsx
- frontend/components/common/TextWithHighlight.tsx
- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/generated/validation.ts
- frontend/templates/product/sections/CompatibilitySection/index.tsx
- frontend/tests/jest/tests/__snapshots__/CompatibleDevice.test.tsx.snap
closes #1437 
This PR also fixes some minor details on the functionality to show hidden variants.
The disclose button has been moved to the bottom of the list when the hidden variants are shown.
2. Verify that the implementation is coherent with the [mockup](https://www.figma.com/file/BolmFORO6ZfHXePOSyEGSS/iFixit---Page-sections?node-id=159-5560&t=3SorVnQp6rEmhV8U-0)
> Add search to compatibility section

- frontend/templates/product-list/sections/FilterableProductsSection/facets/drawer/index.tsx
> Correct filter drawer apply button size

- frontend/.eslintrc.json
- frontend/components/common/CompatibleDevice.tsx
- frontend/templates/product-list/SecondaryNavigation.tsx
- frontend/templates/product/components/PixelPing.tsx
The linter is commenting about these on every pull. Let's fix them so it's quiet.
Also, prevent inclusion of more undefined vars by making them errors.
qa_req 0
> Lint: fix outstanding linting issues

- frontend/templates/troubleshooting/server.tsx
Closes https://github.com/iFixit/ifixit/issues/48080
> Troubleshooting: Drop unneeded `credentials: include`

- frontend/components/common/InstantSearchProvider.tsx
- frontend/helpers/algolia-helpers.ts
- frontend/models/product-list/server.ts
- frontend/templates/product-list/server.tsx
- packages/breadcrumbs/FlexHiddenWrap.tsx
- packages/breadcrumbs/package.json
- pnpm-lock.yaml
Found a way to get it done!
First step is to measure, second will be to optimize.
Connect #1641
> Algolia: Log timing of all requests on the server

- frontend/templates/page/sections/PressQuotesSection.tsx
closes #1734 
Small style adjustments to better fit the new press logos
qa_req 0
> Adjust press quotes section style

- frontend/package.json
- packages/breadcrumbs/package.json
- packages/footer/package.json
- packages/icons/package.json
- packages/ui/package.json
- pnpm-lock.yaml
This gets us on the same version as iFixit/ifixit.
QA
---
This is mostly used via Chakra, but we do have a couple explicit usages in the Cart Drawer code. Let's double-check the cart drawer animations and make sure nothing's busted.
> framer-motion: upgrade to v10

- packages/cart-sdk/hooks/use-cart.ts
- packages/cart-sdk/types.ts
- packages/ui/cart/drawer/CrossSell.tsx
closes #1732 
2. Verify that the new cross sell is coherent with the mockup
> Cart drawer cross-sell layout updates

- frontend/templates/troubleshooting/server.tsx
I managed to completely bork https://github.com/iFixit/react-commerce/pull/1717/ when trying to resolve conflicts, so I'm porting over the original commit and starting fresh.
> Does what it says on the tin.
> 
> I looked at the page and it still shows up. I'll let the tests confirm everything else.
qa_req 0
Duplicate of https://github.com/iFixit/react-commerce/pull/1717/
Closes https://github.com/iFixit/ifixit/issues/48098
> Troubleshooting: Wrap page in standard middleware - Take 2

- frontend/templates/troubleshooting/Resource.tsx
- frontend/templates/troubleshooting/hooks/useTroubleshootingProps.tsx
- frontend/templates/troubleshooting/solution.tsx
We will change the API response so it is much smaller and only contains the required props
qa_req 0
Connects: https://github.com/iFixit/ifixit/issues/48100
> Vulcan Guides: Limit type to required props

- frontend/templates/troubleshooting/server.tsx
qa_req 0
Connects: https://github.com/iFixit/ifixit/pull/48641
Connects: https://github.com/iFixit/ifixit/issues/48101
> Vulcan Products: Update type to the result of the new api param

- frontend/layouts/default/index.tsx
- frontend/layouts/default/server.ts
- frontend/templates/troubleshooting/server.tsx
QA
---
* Ensure the tab title is `wiki title - iFixit Troubleshooting`
Closes: https://github.com/iFixit/ifixit/issues/48684
> Vulcan: Allow changing the page title

- backend/docker-compose.yaml
- backend/package.json
- backend/src/plugins/addons/package.json
- backend/src/plugins/addons/yarn.lock
- backend/yarn.lock
Closes #1818
1. Open [govinor preview](https://fix-strapi-dynamic-zone-bug.govinor.com/admin/content-manager/collectionType/api::page.page/1?plugins[i18n][locale]=en) for this branch
2. Check that the issue described by #1818 is no longer present
3. Since we're upgrading Strapi, let's also perform a quick smoke test of product, product list pages and store home. It should be sufficient to verify that they render correctly.
> Upgrade Strapi to fix dynamic zone bug

- frontend/layouts/default/Footer.tsx
> Remove footer top margin

- packages/ui/cart/drawer/CartDrawer.tsx
closes #1855 
Simply apply some handle based sorting to avoid cross sell elements to swap their position on refetch
qa_req 0
> Fix croll sell items moving on cart refetch

- frontend/tests/playwright/product/product-variant.spec.ts
- frontend/tests/playwright/troubleshooting/loading.spec.ts
> Failing tests: Fix or skip

- frontend/tests/playwright/product/product-page-and-cart.spec.ts
Background https://ifixit.slack.com/archives/C97UC89AR/p1691440323534229.
The products used in these tests are stocked using cron job on `iFixit/ifixit` side, background https://github.com/iFixit/ifixit/pull/48707.
However, due to Shopify / ifixit product mismatches, these tests have become flaky.
CI should pass. 
cc: @jarstelfox
> Tests: Skip flaky tests

- frontend/models/product-list/sections/filterable-products-section.ts
- frontend/models/product-list/sections/hero-section.ts
- frontend/models/product-list/sections/index.ts
- frontend/models/product-list/sections/product-list-children-section.ts
- frontend/models/product-list/server.ts
- frontend/templates/product-list/ProductListView.tsx
closes #1853 
Just a quick smoke test to check that [product list](https://react-commerce-git-make-product-list-sections-sortable-ifixit.vercel.app/Parts) sections are still shown
> Make product list sections sortable

- packages/ifixit-api-client/index.tsx
> Fix: Pass correct header name

- frontend/components/common/ViewStats.tsx
- frontend/templates/troubleshooting/hooks/useTroubleshootingProps.tsx
- frontend/templates/troubleshooting/index.tsx
QA
---
* Ensure the view stats show up on troubleshooting pages
* Ensure they look decent at all screen sizes
* Note: I made some minor improvements to the styling  when compared to view stats on the rest of the site
Connects: https://github.com/iFixit/ifixit/issues/49127
> View Stats: Add a base component to troubleshooting pages

- frontend/next-config/redirects/legacy-filter-slugs.json
We actually still want this page
Closes https://github.com/iFixit/ifixit/issues/49313
> Drop Organization redirect

- frontend/components/ui/IntlDate.tsx
- frontend/templates/troubleshooting/index.tsx
closes #1904 
1. Open a [troubleshooting preview page](https://react-commerce-git-fix-troubleshooting-date-ssr-bug-ifixit.vercel.app/Troubleshooting/Acer_Chromebook/Not+Charging/514224?revisionid=HEAD)
2. Verify that the last updated at date still renders
> Add IntlDate component

- backend/src/api/banner/content-types/banner/schema.json
- backend/src/api/reusable-section/content-types/reusable-section/schema.json
- backend/src/api/reusable-section/controllers/reusable-section.ts
- backend/src/api/reusable-section/routes/reusable-section.ts
- backend/src/api/reusable-section/services/reusable-section.ts
- backend/src/bootstrap/permissions/config.json
- backend/src/components/misc/placement.json
- backend/src/plugins/addons/yarn.lock
- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/generated/validation.ts
This PR ships the Strapi backend changes of #1908 so when we ship the frontend the Strapi API will be already available.
qa_req 0
> Add reusable sections to Strapi

- frontend/components/sections/FAQsSection.tsx
Addresses https://github.com/iFixit/react-commerce/pull/1920#discussion_r1296215973
Smoke test the FAQ section on a featured product page
CC @danielbeardsley @dhmacs
> FAQ fix: Use jsx instead of calling component as a function

- packages/ui/cart/drawer/AnimatedListItem.tsx
- packages/ui/cart/drawer/CartDrawer.tsx
- packages/ui/cart/drawer/CartLineItem.tsx
- packages/ui/cart/drawer/CrossSell.tsx
- packages/ui/cart/drawer/CrossSellItem.tsx
closes #1926 
This PR fixes the problem described by #1926. I've also review the UI of the cross sell with @mmarcon91 and we've made a few adjustments.
qa_req 0
> Fix cart drawer cross sell invalid dom

- frontend/templates/product/sections/ProductOverviewSection/CrossSell/index.tsx
> Hide cross sell when there are no available items

- README.md
> Read Me: Add note about deving on local network / mobile

- frontend/pages/Vulcan/[wikiname].tsx
- frontend/templates/troubleshooting/index.tsx
- frontend/templates/troubleshooting/server.tsx
- frontend/templates/troubleshooting/solution.tsx
- frontend/tests/playwright/troubleshooting/loading.spec.ts
> Troubleshooting: Clean up some dead code

- README.md
qa_req 0
This PR adds to the readme an explanation of how feature flags works in this project.
cc @jarstelfox
> Add feature flags instructions

- frontend/tests/playwright/product/product-page-and-cart.spec.ts
- frontend/tests/playwright/product/product-variant.spec.ts
These tests were previously skipped because some of the products were manually changed.
Now, in `iFixit/ifixit`, we are creating test products that will be used for these tests. These
products are less likely to change and created/stocked on a cron task. 
See https://github.com/iFixit/ifixit/pull/49748 for more context.
Make sure the CI checks pass. 
closes #1890
> Tests: Unskip skipped tests

- frontend/sentry.client.config.ts
- frontend/sentry.edge.config.ts
- frontend/sentry.server.config.ts
[Motivation in slack](https://ifixit.slack.com/archives/C04C05FA3EH/p1696266414063559)
[Docs](https://vercel.com/docs/projects/environment-variables/system-environment-variables#system-environment-variables) on system environment variables
Make sure errors are not reported to sentry by default in dev
CC @jarstelfox @sctice-ifixit
> Sentry: Sample Next.js client errors

- backend/.env.example
- backend/config/plugins.ts
- backend/package.json
- backend/yarn.lock
- pnpm-lock.yaml
qa_req 0 it requires testing after merge 😅 
Connects: https://github.com/iFixit/react-commerce/issues/1952
> Strapi: Allow sending emails

- frontend/next.config.js
Closes https://github.com/iFixit/react-commerce/issues/2065
We'll come up with a more general solution in https://github.com/iFixit/react-commerce/issues/2067
Make sure the base product lists redirect appropriately, and make sure the item type slugs also redirect appropriately.
> Add permanent product list redirects

- backend/src/api/page/content-types/page/schema.json
- frontend/lib/shopify-storefront-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/generated/validation.ts
Part of https://github.com/iFixit/ifixit/issues/50536
This PR adds a meta title field and a meta description field for the Strapi page collection type
qa_req 0
> Add page template metadata to Strapi

- frontend/lib/swr-cache/index.ts
- packages/helpers/logger.ts
qa_req 0
I could not figure out how to test this change locally. Any advice is appreciated
Closes https://github.com/iFixit/ifixit/issues/49898
> Revalidation reqs: Log info on success 

- backend/src/api/product/content-types/product/schema.json
- backend/src/api/screwdriver-bit-type/content-types/screwdriver-bit-type/schema.json
- backend/src/api/screwdriver-bit-type/controllers/screwdriver-bit-type.ts
- backend/src/api/screwdriver-bit-type/routes/screwdriver-bit-type.ts
- backend/src/api/screwdriver-bit-type/services/screwdriver-bit-type.ts
- backend/src/api/screwdriver-bit/content-types/screwdriver-bit/schema.json
- backend/src/api/screwdriver-bit/controllers/screwdriver-bit.ts
- backend/src/api/screwdriver-bit/routes/screwdriver-bit.ts
- backend/src/api/screwdriver-bit/services/screwdriver-bit.ts
- backend/src/bootstrap/permissions/config.json
- backend/src/components/product/bit-table.json
- frontend/components/sections/BitTableSection.tsx
- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/generated/validation.ts
- frontend/lib/strapi-sdk/operations/components/ScrewdriverBit.fragment.graphql
- frontend/lib/strapi-sdk/operations/components/ScrewdriverBitType.fragment.graphql
- frontend/lib/strapi-sdk/operations/findProduct.graphql
- frontend/lib/strapi-sdk/operations/sections/BitTableSectionFields.fragment.graphql
- frontend/models/components/screwdriver-bit-type.ts
- frontend/models/components/screwdriver-bit.ts
- frontend/models/product/sections/index.ts
- frontend/models/sections/bit-table-section.ts
- frontend/templates/product/index.tsx
Closes https://github.com/iFixit/ifixit/issues/49327
Figma: https://www.figma.com/file/BolmFORO6ZfHXePOSyEGSS/iFixit---Page-sections?type=design&node-id=1766-10708&mode=design&t=z7yor1h57OAQfLpy-0
This PR introduce the frontend components for the BitTable section.
1. Visit Vercel preview [here](https://react-commerce-git-bit-table-section-frontend-ifixit.vercel.app/products/repair-business-toolkit)
2. Verify that the frontend is aligned with the Figma mockup
> Bit table section frontend

- frontend/templates/product/sections/ProductOverviewSection/index.tsx
> Product Page: Add missing dependency

- backend/src/api/item-type/content-types/item-type/schema.json
- backend/src/api/item-type/controllers/item-type.ts
- backend/src/api/item-type/routes/item-type.ts
- backend/src/api/item-type/services/item-type.ts
- backend/src/bootstrap/permissions/config.json
- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/generated/validation.ts
Meant to store a picture associated with item types.
Connect iFixit/ifixit#49086
> Item Types: add new collection type

- frontend/templates/troubleshooting/hooks/useTroubleshootingProps.tsx
- frontend/templates/troubleshooting/index.tsx
This should be a pure refactor. The goal is to reduce the amount of code which is affected by implementing the frontend for https://github.com/iFixit/ifixit/issues/50604.
Turn on "ignore whitespace" on the diff; this is just extracting a couple functions and adding a new key to a type.
Please check that the `Related Problems` section of the page still looks reasonable.
Connects https://github.com/iFixit/ifixit/issues/50604
> Troubleshooting: Refactor related problems

- frontend/sentry.client.config.ts
- frontend/sentry.edge.config.ts
- frontend/sentry.server.config.ts
- frontend/tests/jest/tests/sentry.test.tsx
- packages/sentry/SentryErrorIntegration.tsx
- packages/sentry/index.tsx
qa_req 0 I added tests!
Closes: https://github.com/iFixit/ifixit/issues/50671
> Sentry: Receive details on the server

- frontend/templates/troubleshooting/index.tsx
6 was determined by counting a screenful on mobile. I'm mostly just picking a reasonable value to start with.
This is behind a feature flag.
qa_req 0
Connects https://github.com/iFixit/ifixit/issues/50604
> Troubleshooting: Include extra problems from device & ancestors

- frontend/layouts/default/index.tsx
- frontend/layouts/default/server.ts
- frontend/templates/product-list/server.tsx
Connects https://github.com/iFixit/ifixit/issues/50741
Make sure the bug described in the issue is no longer present on the react-commerce-prod deployment. We never saw the bug on the react-commerce deployment.
> Fix product list meta title

- backend/src/api/faq/content-types/faq/schema.json
- backend/src/api/product-list/content-types/product-list/schema.json
- backend/types/generated/contentTypes.d.ts
QA
---
Ensure the option now appears
Connects: https://github.com/iFixit/ifixit/issues/50437
> Strapi: Add setting for indexing a variant

- frontend/templates/troubleshooting/components/NavBar.tsx
- frontend/templates/troubleshooting/index.tsx
The index file for Vulcan/Troubleshooting is getting quite large. Let's break out the `navBar` function as its own component.
`/Troubleshooting/Mac_Laptop/MacBook+Will+Not+Turn+On/483799`
Should be zero changes in rendering and functionality.
> Vulcan: Segregate troubleshooting navBar component

- frontend/helpers/path-helpers.ts
- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/generated/validation.ts
- frontend/lib/strapi-sdk/operations/findProductList.graphql
- frontend/models/product-list/server.ts
- frontend/models/product-list/types.ts
- frontend/templates/product-list/MetaTags.tsx
Closes: https://github.com/iFixit/ifixit/issues/50437
> Index Variants Instead Of Device: Implement

- frontend/lib/redis/index.ts
- frontend/lib/swr-cache/adapters/index.ts
- frontend/lib/swr-cache/index.ts
- frontend/pages/api/nextjs/cache/product-list.ts
- frontend/pages/api/nextjs/cache/product.ts
qa_req 0
Fixes: https://ifixit.sentry.io/issues/4622102087/?project=6469069
Closes: https://github.com/iFixit/ifixit/issues/50778
> Redis: Double connection timeout

- frontend/next.config.js
Closes https://github.com/iFixit/ifixit/issues/50831
> Add steam deck fan redirect

- packages/cart-sdk/hooks/use-checkout.ts
Followup to https://github.com/iFixit/react-commerce/pull/2139, just fix some names and the like
Does checkout still work?
> Bad Shopify Checkout URL: Fix Names

- frontend/templates/product/sections/ProductOverviewSection/ProductOptions.tsx
We now will read out these are selected or not as well as state 'select <variant>'
Connects: https://github.com/iFixit/ifixit/issues/51161
> Part or Kit: make more accessible

- frontend/components/sections/ReplacementGuidesSection.tsx
- frontend/components/ui/Rating.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/ProductList.tsx
- frontend/templates/product/sections/ProductOverviewSection/ProductDescription.tsx
- frontend/templates/product/sections/ProductOverviewSection/ProductGallery.tsx
- frontend/templates/product/sections/ProductOverviewSection/ProductRating.tsx
- frontend/templates/product/sections/ProductReviewsSection/index.tsx
- frontend/tests/jest/tests/__snapshots__/ProductListItem.test.tsx.snap
- packages/ui/cart/drawer/CartDrawer.tsx
- packages/ui/slider/index.tsx
Connects: https://github.com/iFixit/ifixit/issues/51161
> Product Page: Add QoL for screenreaders

- frontend/templates/product/sections/ProductOverviewSection/ProductOptions.tsx
The selected state is being set in aria, but somehow not transfering.
This gets us the correct readout at least
Connects: https://github.com/iFixit/ifixit/issues/51161
> Product option: Manually handle output text

- frontend/templates/troubleshooting/components/Causes.tsx
- frontend/templates/troubleshooting/toc.tsx
This configures the table of contents per the description in https://github.com/iFixit/ifixit/issues/51115.
Please confirm that the table of contents matches the specified behaviors.
Closes https://github.com/iFixit/ifixit/issues/51115
> Troubleshooting ToC: Finalize headings

- frontend/lib/ifixit-api/productData.ts
Fixes a bug I introduced in https://github.com/iFixit/react-commerce/pull/2169
www.ifixit.com/products/asdf will 500. On this branch it should 404.
> Product: Don't 500 on ifixit product api 404s

- frontend/tests/playwright/troubleshooting/loading.spec.ts
- packages/feature_flags/flags.json
This should now include problems from the parent device, along with any ancestor devices which have inheritance enabled. Please see the issue for the precise spec; if you find anything wonky, please let me know!
Connects https://github.com/iFixit/ifixit/issues/50604
> Extended Related Problems: Switch feature flag to true

- .github/workflows/deploy-strapi.yml
We don't want two of these running at the same time. Let's make sure
only one can run at a time.
Connects: https://github.com/iFixit/react-commerce/issues/2175
qa_req 0
> Strapi Deploy: Add concurrency

- frontend/templates/product/sections/CompatibilityNotesSection/index.tsx
Slack https://ifixit.slack.com/archives/C0252FETV2S/p1704319373049219
Check the production preview `/products/wfcb-electrolux-refrigerator-water-filter`
> Use array length for compatibility notes emptiness check

- frontend/templates/product/sections/ProductOverviewSection/ProductOptions.tsx
closes #2174 
Using an iOS device, visit the Vercel preview and verify that the bug described by #2174 is fixed
> Fix ios safari select overflow bug

- frontend/app/(defaultLayout)/@storeSelect/products/app-router/[handle]/page.tsx
- frontend/app/(defaultLayout)/products/app-router/[handle]/json-ld-scripts.tsx
- frontend/app/(defaultLayout)/products/app-router/[handle]/page.tsx
- frontend/app/_data/product.ts
- frontend/app/_helpers/app-helpers.ts
- frontend/app/_helpers/product-helpers.ts
Part of https://github.com/iFixit/ifixit/issues/51165
This PR uses React.cache to memoize product request, since we are fetching the product multiple times.
qa_req 0
> Memoize app router find product

- frontend/templates/product/sections/ProductReviewsSection/index.tsx
Closes https://github.com/iFixit/ifixit/issues/51268
> [Fix] Product review star and date alignment

- frontend/app/(defaultLayout)/Troubleshooting/[device]/components/Answers.tsx
- frontend/app/(defaultLayout)/Troubleshooting/[device]/components/NavBar.tsx
- frontend/app/(defaultLayout)/Troubleshooting/[device]/components/Problem.tsx
- frontend/app/(defaultLayout)/Troubleshooting/[device]/components/ProblemCard.tsx
- frontend/app/(defaultLayout)/Troubleshooting/[device]/components/troubleshootingProblems.tsx
Mattia made some final updates to the Problems List page. We'll need another style pass for design/UI parity.
https://react-commerce-prod-8wehk7717-ifixit.vercel.app/Troubleshooting/Dryer
**UI:**
**Breadcrumbs:**
**NavBar:**
**API:**
Connects https://github.com/iFixit/ifixit/issues/51698
> Problems List: Finalize UI

- frontend/app/(defaultLayout)/app-router/Store/[[...slug]]/data.ts
- frontend/app/(defaultLayout)/app-router/Store/[[...slug]]/page.tsx
- frontend/app/_data/product.ts
- frontend/helpers/metadata-helpers.ts
- frontend/templates/page/meta-tags.tsx
- frontend/templates/product-list/MetaTags.tsx
Part of https://github.com/iFixit/ifixit/issues/51872
This PR adds memoized data fetching to the app router store pages
qa_req 0
> Add memoized data fetching
