iFixit/react-commerce

- features/collection/components/FilterableProductSection.tsx
- lib/algolia/reducers/filtersCleared.ts
- lib/algolia/reducers/listFilterAllItemsCleared.ts
- lib/algolia/reducers/listFilterItemAdded.ts
- lib/algolia/reducers/listFilterItemCleared.ts
- lib/algolia/reducers/listFilterItemSet.ts
- lib/algolia/reducers/listFilterItemToggled.ts
- lib/algolia/reducers/queryChanged.ts
- lib/algolia/reducers/rangeFilterSet.ts
This PR closes #53, #54 and fixes #63 
2. Visit any collection that contains products
3. Verify that when you change the page of the product list, the top item is scrolled into view
4. Verify that when you change filters or search query, the top item is scrolled into view
> Improve collection scroll behavior

- features/collection/components/sections/FilterableProductsSection/FilterList/FilterRow.tsx
- features/collection/components/sections/FilterableProductsSection/FilterList/RangeFilter/RangeFilterList.tsx
- features/collection/components/sections/FilterableProductsSection/FilterList/index.tsx
- lib/api/strapi/generated/sdk.ts
This PR fixes #45 
2. Visit the parts collection page
3. Open price range filter and select `$10 - $25` option
4. Verify that the filter `$10 - $25` option text **does not** change to `Under $25`
> Fix filtered price range label bug

- lib/api/collection/index.ts
- lib/api/layout/index.ts
- lib/api/strapi/generated/sdk.ts
- lib/api/strapi/operations/getCollection.graphql
- lib/api/strapi/operations/layout.graphql
- pages/collections/[handle].tsx
- test/cypress/integration/collection/newsletter_subscribe.spec.ts
This PR closes #116 
I'm still keeping the name "collections" in many parts of the codebase mostly to avoid conflicts with other branches that are ready to be reviewed after this PR. When those branches will be merged too then I'll refactor all references to "collection"
2. Visit the parts collection page
3. Verify that product list page works with the new Strapi instance
> Use new collection type names

- frontend/features/productList/components/MetaTags.tsx
This PR closes #103  
- Adds open graph tags
2. Visit parts product list page and copy the url
3. Use Facebook sharing debug tool (https://developers.facebook.com/tools/debug) to verify that the generated preview link is correct. The description should come from product list `metaDescription`, or if not set it should come from product list `description`
4. [Optional] You can try to paste the link on Slack, or twitter and see if a card is created
> Add open graph tags

- frontend/features/productList/components/sections/FilterableProductsSection/Toolbar.tsx
- frontend/features/productList/components/sections/FilterableProductsSection/index.tsx
- frontend/features/productList/components/sections/HeroSection.tsx
This PR closes #70 
- Makes product list view selector responsive
2. Visit a parts product list and verify that the product list view selector is responsive (renders also on mobile sizes)
> Make product list view selector responsive

- .gitignore
As we pull this repo into our monorepo, I find that the top-level gitignore doesn't take effect within this submodule. This adds an ignore line to ignore some temp files Rush creates.
qa_req 0
This shouldn't be breaking anything serious.
> .gitignore: Ignore Rush tempfiles

- backend/package.json
This restores the package name for the backend package from before the refactor.
qa_req 0
> Configure more specific name for backend

- backend/package-lock.json
- frontend/lib/strapi-sdk/index.ts
closes #141 
cc @lithobraking @sterlinghirsh @andyg0808 
- Add better logging to graphql requests
There's not an easy way to promt Strapi to return errors in order to verify error logging. The way I did it while developing is by sending wrong queries on purpose.
If you want to reproduce an error yourself you need to clone the repo and replace this: https://github.com/iFixit/react-commerce/blob/094f877d2b90d464b970dda603e4692e8f6e7ec2/frontend/lib/strapi-sdk/index.ts#L16 with this:
```ts
variables: {
filters: {
foo: 'bar',
},
},
```
Start the dev server (`npm run dev`) then navigate a product list page and you'll see an error like this on your terminal:
> Add logs to graphql queries

- backend/docker-compose.yaml
Currently Strapi images are being deleted when new changes are pushed to a branch since they're not backed by a persistent volume. This PR fixes the issue.
- Add docker volume to Strapi `/public/uploads` folder
The only file affected by this change is the docker compose config, so not sure what to QA beside that Strapi govinor deploy should still be up and running.
> Add docker persistent volume for file upload

- frontend/components/product-list/sections/FeaturedProductListSection.tsx
- frontend/components/product-list/sections/FilterableProductsSection/index.tsx
- frontend/models/product-list/index.ts
- frontend/models/product-list/types.ts
fixes #233 
- Use `public=1` when searching with Algolia
3. Verify that products marked with `public=0` in Algolia are not visible in product list search results
> Show only public products

- frontend/components/product-list/sections/FilterableProductsSection/ProductGrid.tsx
- frontend/components/product-list/sections/FilterableProductsSection/ProductList.tsx
fixes #218   
3. Verify that out of stock alerts are not visible anymore
> Hide out of stock alerts from product cards

- frontend/components/product-list/ProductListBreadcrumb.tsx
fixes #201  
3. Verify that breadcrumb product list title is not visible for mobile screens
> Remove mobile breadcrumb page title

- README.md
- backend/src/api/product-list/content-types/product-list/schema.json
fixes #243 
This PR also adds instructions for how to work with Strapi and make changes to the content types.
1. Visit https://add-legacy-description-field.govinor.com/admin/
2. Use credentials found in the readme to login
3. Verify that product lists have the new legacy description
> Add legacy description field

- frontend/components/product-list/sections/FilterableProductsSection/ProductGrid.tsx
- frontend/components/product-list/sections/FilterableProductsSection/ProductList.tsx
- frontend/models/product-list/types.ts
fixes #212 
- Switch `title` with `group_title` in product list and grid views
2. Visit the parts product list
3. Verify that the changes close #212
> Replace `title` with `group_title`

- frontend/components/product-list/sections/FilterableProductsSection/ProductListFilters/index.tsx
- frontend/lib/strapi-sdk/generated/sdk.ts
fixes #191 
- Add `Main Category` and `Category` to facet blocklist
2. Visit the parts product list
3. Verify that neither `Main Category`, nor `Category` are displayed in the facets list
> Add main category and category to blocklist

- frontend/components/product-list/sections/FilterableProductsSection/ProductListFilters/FilterRow.tsx
This sorts hard drive capacities from largest to smallest in the filter
options dropdown list. Before, they were being sorted alphabetically.
Triplet programmed with @danielbeardsley and @sterlinghirsh 
Visit the preview link.
Click the capacity dropdown and confirm that capacity sizes are sorted from largest to smallest.
Closes https://github.com/iFixit/ifixit/issues/42631
> Filters: Sort capacity filter options

- frontend/components/product-list/MetaTags.tsx
closes #282 
1. visit vercel preview (replace _vercel.app_ with _cominor.com_)
2. navigate to `/Store/Parts`
3. confirm that the page title displays in the tab as "All Parts | iFixit"
> Update meta title to display product list name before brand name

- frontend/lib/algolia/client.ts
fixes https://github.com/iFixit/ifixit/issues/42374
- Add facet name override map
2. Navigate to `/Store/Parts` and verify that `Price Range` facet name is rendered with capital `R`
> Add facets name override

- backend/Dockerfile
The strapi docker image is kind of big-ish at 1.2GB. We can cut that almost _in half_ by cleaning out the yarn package cache.
Clearing the cache brings the image down to ~650MB, which isnt the smallest image, but is a relatively normal size.
qa_req 0
Closes: https://github.com/iFixit/react-commerce/issues/296
> Clear yarn cache during docker build

- frontend/components/product-list/sections/FilterableProductsSection/index.tsx
- frontend/next-env.d.ts
- packages/ui/hooks/index.ts
fixes #95 
- Preserve user preference on product list view type
2. Select product list `grid` type and verify that product list grid is shown
3. Reload the page a verify that the product list grid is still shown
cr_req  1
> Store product list view user preference in local storage

- backend/.env.example
This PR fixes a Govinor deployment issue introduced by #309 that breaks the seed of new govinor preview instances.
The bug is due to Govinor usage of `.env.example` to populate env variables, but since Govinor deploys are not required to use S3, we're commenting out env variables related to that so they're not used by Govinor.
This is just a quick fix as probably a better way to solve it would be to build env variable management into Govinor.
1. Open the Govinor Strapi preview deployment for this branch
2. Verify that product lists have been seeded
> Fix Govinor deployment seed

- frontend/helpers/strapi-helpers.ts
- frontend/lib/ifixit-api/devices.ts
- frontend/models/product-list/index.ts
- frontend/models/product-list/types.ts
Fill in images for some devices on Parts ProductList pages that were missing images.
The list of child-nodes we show on a given product list page (parent device) sometimes don't match up with the list of device children in our ifixit.com hierarchy. When we query ifixit.com for the parent device, we only get pictures for the immediate children. For those nodes in strapi which aren't immediate children of the parent-device in our device hierarchy, the ifixit.com device api thus won't give us pictures. For these nodes without pictures, query their information (in bulk) via the new `topic_images` API so we can get images for them.
Closes #304
> Images for imageless devices

- frontend/components/product-list/sections/FilterableProductsSection/FacetsAccordion.tsx
~~🚨 Blocked by #332 deploy_block~~
This PR removes the top border for the first facet accordion item, and the bottom one from the last facet accordion item.
2. Verify that the first and last borders are not shown
> Fix facet accordion items borders

- frontend/components/product-list/ProductListView.tsx
- frontend/components/product-list/sections/FilterableProductsSection/FacetsAccordion.tsx
- frontend/components/product-list/sections/FilterableProductsSection/FacetsDrawer.tsx
- frontend/components/product-list/sections/FilterableProductsSection/Toolbar.tsx
- frontend/components/product-list/sections/FilterableProductsSection/index.tsx
- frontend/components/product-list/sections/FilterableProductsSection/useFacets.tsx
- frontend/models/product-list/index.ts
- frontend/models/product-list/types.ts
Hide Facets that are already specified by the Device Parts page we are on.
Context: Assume we are on the iPhone 7 parts list page
The "Device Brand" facet and its "iPhone" option is useless and
confusing cause all products here are already compatible with iPhones.
Here we hide any facets that come from the wiki info of the current
device and its ancestors.
When you visit a refined page of parts or tools (like /Parts/Dell_Laptop) make sure that any facets that exist in the device's wiki info are excluded from the page, both on mobile and on desktop views.
Closes #299
> Search Facets: Hide irrelevant ones (algolia hooks version)

- frontend/components/product-list/sections/FilterableProductsSection/ProductList.tsx
- frontend/models/product-list/types.ts
Adds a green OEM Partnership flare tag to product list items if the field exists in Algolia. Also updates the flare text for some badges.
Find products in product_en in [Algolia](https://www.algolia.com/apps/XQEP3AD9ZT/) that have the oem_partnership field. Also test when it is null.
Visit the vercel preview and view those products. Make sure the tag is present, and meets the conditions specified in the issue. The flare should come before 'Lifetime Warranty'.
(You can type 'teenage' into the search bar, and results come up with this flare)
Also make sure that these flares have the right text:
- 'Lifetime warranty' is now 'Lifetime Warranty'
- 'PRO' is now 'iFixit Pro'
Closes #316
Closes #317
> Collections: Add OEM partnership flare

- frontend/components/product-list/sections/FilterableProductsSection/RefinementList.tsx
This reintroduces Capacity facet sorting. It was accidentally erased
when we switched over to using Algolia hooks.
This is an adaptation of the original implementation in #277.
Closes https://github.com/iFixit/ifixit/issues/42631
> Facets: Sort `Capacity` from high to low

- frontend/pages/Parts/[handle].tsx
- frontend/pages/Parts/index.tsx
- frontend/pages/Store/[handle].tsx
- frontend/pages/Tools/[handle].tsx
- frontend/pages/Tools/index.tsx
Cloudfront doesn't respect stale-while-revalidate, so at 10s, nearly all
of our page requests will be misses which are quite expensive.
Let's bump this because product data in algolia changes relatively
infrequently.
> Cache: Bump it up

- frontend/next.config.js
NextJS doesn't tree-shake server-side bundles by default:
https://github.com/vercel/next.js/issues/8956#issuecomment-557867732
We suspect that the large amount of code being loaded by our Lambdas is resulting in slow startup times.
This enables tree-shaking and other optimizations on the server-side code, in order to reduce bundle size. We're hoping this helps with startup times.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> Webpack: Enable optimization on server-side bundles

- frontend/package.json
- pnpm-lock.yaml
Several subdependencies have a peer dep on webpack. Next actually has webpack built *into* the package (in its `dist/` directory). It seems like serverless builds (at least on Amplify) are broken because one of these subdependencies (`@next/react-refresh-utils`) can't find webpack. It seems like the pull that added sentry caused `webpack` to not be hoisted to top level and thus not to be found by `@next/react-refresh-utils`.
This ensures all our dependencies use the same copy when they've got it as a peer dependency.
> Webpack: install our own copy

- frontend/components/product-list/ProductListView.tsx
- frontend/components/product-list/sections/FeaturedProductListSection.tsx
- frontend/helpers/product-list-helpers.ts
- frontend/models/product-list/index.ts
fixes #342 
- Use instantsearch `Index` component to separate different Algolia use cases
2. Visit the `/Parts` product list
3. Verify that the product list displays generic parts, while the featured list below displays only Nintendo parts
> Decouple main product list from featured product list state

- frontend/components/common/AppProviders.tsx
- frontend/components/common/InstantSearchProvider.tsx
- frontend/components/common/Layout/index.tsx
- frontend/components/product-list/ProductListView.tsx
- frontend/components/product-list/sections/FilterableProductsSection/Pagination.tsx
- frontend/pages/Parts/[handle].tsx
- frontend/pages/Parts/index.tsx
- frontend/pages/Store/[handle].tsx
- frontend/pages/Tools/[handle].tsx
- frontend/pages/Tools/index.tsx
- frontend/pages/_app.tsx
- packages/auth-sdk/csrf.ts
- pnpm-lock.yaml
closes #345 
- Move InstantSearch provider up in the component tree hierarchy to avoid unnecessary re-renders
- Force InstantSearch provider to unmount when it re-render, so that internals do not get stuck in a broken state
2. Browse trough product lists, use refinements, use the browser back button and verify that the product list page does not break
> Add temporary fix to avoid page crash

- frontend/components/common/Layout/Footer.tsx
- frontend/components/common/ProductCard.tsx
- frontend/components/ifixit-image/ifixit-image.tsx
- frontend/components/ifixit-image/index.ts
- frontend/components/product-list/sections/BannerSection/index.tsx
- frontend/components/product-list/sections/FeaturedProductListSection.tsx
- frontend/components/product-list/sections/FilterableProductsSection/ProductList.tsx
- frontend/components/product-list/sections/ProductListChildrenSection.tsx
- frontend/components/product-list/sections/ProductListSetSection.tsx
- frontend/components/product-list/sections/RelatedPostsSection/PostCard.tsx
- packages/ui/cart/drawer/CartLineItem.tsx
We want fine grained control over when and how we use next/image and its image resizing pipeline. Given that each of our images are rendered in many sizes, we want to be able to choose the sizes to use and when.
This is a minimal starting point. This gives us one place where we can tune when to use which sizes and when to use next's image pipeline. For the time being, all images are served directly from their sources instead of being re-compressed on the fly.
CC @sterlinghirsh @andyg0808
> Images: add IfixitImage component

- frontend/config/constants.ts
Instead of `product_en`.
We can't get accurate counts on facet values because of the way algolia faceting works with combining product variant records into product group records with the algolia's distinct feature. This results in extraneous facet options showing up.
This change should avoid having to use distinct and fix facet value counts.
Run through all parts of the preview, and make sure nothing appears broken compared to main's preview.
Closes #305
> Algolia: Use `product_group_en`

- frontend/components/product-list/MetaTags.tsx
closes #355 
1. Open [Vercel preview](https://react-commerce-git-noindex-single-item-product-lists-ifixit.cominor.com/Parts/Toshiba_Chromebook_2)
2. Verify that single item product lists have a "noindex" meta tag (e.g. [Toshiba Chromebook CB35-B3340 Parts](https://react-commerce-git-noindex-single-item-product-lists-ifixit.cominor.com/Parts/Toshiba_Chromebook_2)
3. Verify that if a product list has more than 1 product then it doesn't have a "noindex" meta tag
> Add noindex meta tag for single item product lists

- frontend/components/product-list/MetaTags.tsx
- frontend/components/product-list/sections/HeroSection.tsx
fixes #363 
1. Open [Vercel preview](https://react-commerce-git-fix-product-list-missing-description-ifixit.cominor.com/Parts)
2. Verify that product list description is displayed
3. Verify that for pages after the first one, product list description is not shown
cr_req 2
> Fix missing product list pagination

- backend/src/api/product-list/content-types/product-list/schema.json
- backend/src/plugins/seed/server/seed/data/product-lists.json
- frontend/components/product-list/MetaTags.tsx
- frontend/components/product-list/ProductListBreadcrumb.tsx
- frontend/components/product-list/ProductListView.tsx
- frontend/components/product-list/sections/FilterableProductsSection/FacetFilter.tsx
- frontend/components/product-list/sections/FilterableProductsSection/FacetsAccordion.tsx
- frontend/components/product-list/sections/FilterableProductsSection/FacetsDrawer.tsx
- frontend/components/product-list/sections/FilterableProductsSection/RefinementMenu.tsx
- frontend/components/product-list/sections/FilterableProductsSection/Toolbar.tsx
- frontend/components/product-list/sections/FilterableProductsSection/index.tsx
- frontend/components/product-list/sections/FilterableProductsSection/useFacets.tsx
- frontend/components/product-list/sections/HeroSection.tsx
- frontend/components/product-list/sections/ProductListChildrenSection.tsx
- frontend/helpers/product-list-helpers.ts
- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/models/product-list/index.ts
- frontend/models/product-list/types.ts
- frontend/pages/Parts/[deviceHandle]/[itemTypeHandle].tsx
- frontend/pages/Parts/[deviceHandle]/index.tsx
- frontend/pages/Parts/index.tsx
- frontend/test/cypress/integration/product-list/filters.spec.ts
closes #354 
fixes #370 
⚠️ After merging this, strapi.ifixit.com needs to be redeployed since the product list type enum has been updated.
The product lists should have `type` set to:
- All parts product list: `all-parts`
- Device parts product list: `parts`
- All tools product list: `all-tools`
- Tools category product list: `tools`
An unset `type` field is assumed as a device parts product list.
cc @sterlinghirsh 
1. Open [Vercel Preview](https://react-commerce-git-add-item-type-product-lists-ifixit.cominor.com/Parts)
2. Verify than when in device parts product lists you can use the "item type" facet to navigate to the corresponding device item type product list (e.g. iPhone batteries)
3. Verify that the bug described by #370 is fixed
> Add item type product lists

- frontend/components/product-list/sections/FilterableProductsSection/RangeInput.tsx
- frontend/components/product-list/sections/ProductListChildrenSection.tsx
- frontend/test/cypress/integration/product-list/collections_scroll.spec.ts
- frontend/test/cypress/integration/product-list/collections_view_button.spec.ts
- frontend/test/cypress/integration/product-list/parts_page_devices.spec.ts
- frontend/test/cypress/support/commands.ts
- frontend/test/cypress/support/index.d.ts
Adds a new test to the collection `/Parts` page. 
- ~The first test visits devices/models on `/Parts` page and asserts that the search filter and `filterable-products-section` section is visible (copy of `WDStorePagesSmokeTest -> testAllToplevelPartsPages` in iFixit/ifixt).~
- The second test clicks on a device (hard coded to `Mac Parts` for the moment), then navigates until the last device page and asserts that there is at least one product (`WDStorePagesSmokeTest -> testDrillDownUntilPartFound`).
Please re-run the `E2E tests / cypress-run` ci check and make sure it passes.
Connects: https://github.com/iFixit/ifixit/issues/43590 and https://github.com/iFixit/react-commerce/issues/387
> Tests: Collections parts page add tests

- frontend/components/product-list/ProductListDeviceNavigation.tsx
- frontend/components/product-list/ProductListView.tsx
Previously, Parts/Guides/Answers was visible on the `/Tools` page. This PR hides it from the `/Tools` page.
Make sure that Parts, Guides and Answer is not visible on `/Tools`.
Closes #376
> Tools Homepage: Hide Parts/Guides/Answers

- .prettierrc
- README.md
- frontend/components/product-list/sections/FilterableProductsSection/index.tsx
- frontend/package.json
- package.json
When a user searches but does't find any results, this changes the no-results page to clarify that they're only searching within their given page. There's now a link to the main iFixit search with their query pre-filled, too.
I also added a couple changes in the project setup to fix some issues I encountered while setting this up on windows.
Closes #401
> No Results Search: Add link to main search

- packages/auth-sdk/user.tsx
- packages/ui/header/UserMenu.tsx
Previously, we did not check if the `unique_username` was null and the page could break. This PR fixes this so that the null case for `unique_username` is handled.
Users created with https://www.cominor.com/dev/create_user don't have unique usernames by default. 
Visit this branch's [preview](https://react-commerce-git-unique-username-check-for-null-ifixit.cominor.com/Parts) while logged in as a user without a unique username and confirm log in/out and appearance is the same for a user with a unique username.
Closes #372 
CC: @sterlinghirsh @dhmacs
> Unique Username: Add a null check 

- frontend/components/product-list/sections/FilterableProductsSection/RefinementList.tsx
- frontend/components/product-list/sections/FilterableProductsSection/RefinementMenu.tsx
- frontend/components/product-list/sections/FilterableProductsSection/useFacets.tsx
- frontend/components/product-list/sections/FilterableProductsSection/useSortBy.ts
Algolia's Facet Display doesn't work for nested facets like facet_tags. This adds code to customize the sort order.
It also adds code to alphabetize the "Item Type" refinement list items (aka facet options).
Make sure the facet accordions are sorted as spec'd on desktop and mobile. Check it across parts pages, tools pages, and other pages (ie marketing).
Also make sure the item type facet options are alphabetized.
Closes #390
> Facets: Custom sort order

- frontend/components/product-list/ProductListView.tsx
- frontend/components/product-list/sections/FilterableProductsSection/index.tsx
- frontend/helpers/product-list-helpers.ts
Fixes a bug where only the search parameters passed to the most recently
rendered `<Configure>` get used.
Now we only ever render `<Configure>` once, and combine all the
necessary search parameters.
Search filter conditions are intersected using "AND":
https://www.algolia.com/doc/api-reference/api-parameters/filters/#boolean-operators
CC @erinemay 
Closes #391
> Search: Only render `<Configure>` once

- frontend/components/product-list/sections/FilterableProductsSection/SearchInput.tsx
- frontend/components/product-list/sections/FilterableProductsSection/Toolbar.tsx
Previously, we didn't have any clear indication that the 2 different search bars [the header search bar and the product search bar] would have different behaviors. This PR makes the distinction by including the title of the page in the product search bar.
- Go to the preview
- Scroll to the product search bar
- Make sure that for each page the placeholder text says something [like here](https://github.com/iFixit/react-commerce/issues/386#issuecomment-1176496362)
Closes #386 
CC: @erinemay @sterlinghirsh
> Product Search Box: Differentiate from header search box

- frontend/components/product-list/sections/FilterableProductsSection/FacetsDrawer.tsx
- frontend/components/product-list/sections/ProductListChildrenSection.tsx
closes #371 
closes #414 
1. Open [Vercel Preview](https://react-commerce-git-facets-drawer-scrolling-behaviour-ifixit.cominor.com/Parts)
2. Verify that the buttons on the bottom part of the page are not anymore hidden by the browser UI (#371). 
3. Verify that the scroll positioning issues described in #414 are not present anymore
> Facets drawer layout fixes

- frontend/components/product-list/sections/FilterableProductsSection/Pagination.tsx
Previously, the logic to generate the link for the previous button created the `pageUrl` for the `currentPage`. This PR changes that to `currentPage- 1`. 
- Visit the [preview](https://react-commerce-git-pagination-fix-link-on-hover-ifixit.vercel.app/Parts?p=3)
- Make sure that when we hover over the previous page button the link that shows up is correct, ie, the link shows p={previous page#} instead of p={current page#}. Here are screenshots of the change locally:
<details><summary>Screenshot BEFORE Change</summary>
</details>
<details><summary>Screenshot AFTER Change</summary>
</details>
Closes #428 
CC: @erinemay
> Previous Page: Fix pagination link

- frontend/test/cypress/integration/product-list/parts_page_search.spec.ts
Sometimes `parts_page_search` test fails because the ui is still updating 
when it's doing the assertions. Let's wait for the ui to update after
searching. This will help to deflake the test.
Please make sure `E2E tests / cypress-run (push)` ci check passes.
> Tests: Deflake parts_page_search test

- frontend/components/product-list/sections/FilterableProductsSection/ProductList.tsx
- frontend/test/cypress/integration/product-list/parts_results_view.spec.ts
Adds test for the Results view on /Parts page. From https://github.com/iFixit/react-commerce/issues/124:
> Results view
- Body
- Price
- View button
Please re-run the E2E tests / cypress-run ci check and make sure it passes.
Connects: https://github.com/iFixit/react-commerce/issues/124 and https://github.com/iFixit/ifixit/issues/43590
> Tests: Add tests for products on /Parts

- frontend/components/product-list/ProductListView.tsx
- frontend/components/product-list/sections/FilterableProductsSection/ProductGrid.tsx
Previously, when switched to grid view, an empty tile appeared if we scrolled all the way to the bottom. This PR gets rid of that tile.
- We had a `bg` color set to `gray.100` for the `<SimpleGrid`.
- While this was adding borders between each individual link box, if there was no link box displayed we could see an empty tile in the grid.
- I decided to get rid of that `bg` color and add borders to each individual `LinkBox`.
- This took care of both things:
- The empty tile
- The border around the linkboxes.
<details><summary>Screenshot BEFORE Change</summary>
</details>
<details><summary>Screenshot AFTER Change</summary>
</details>
Closes #410 
CC: @jordycosta
> Empty Tile: Get rid of it

- .github/workflows/main.yml
- frontend/cypress.json
1. Dropped recording for cypress videos because they weren't working properly (frozen at the beginning) and slowing down the ci. Seems like an [existing cypress issue for this](https://github.com/cypress-io/github-action/issues/483). We still have the screenshots on failures, so I believe this should be fine.
In `E2E tests / cypress-run` ci check, `Cypress run` step, make sure there are no video processing logs like the following:
```
(Video)
-Started processing:Compressing to 32 CRF
-Finished processing:/home/runner/work/react-commerce/react-commerce/frontend/te(36 seconds)
st/cypress/videos/product-list/collections_scroll.spec.ts.m
p4
Compression progress:  100%
```
> Update cypress workflow

- frontend/cypress.json
- frontend/test/cypress/integration/product-list/collections_scroll.spec.ts
- frontend/test/cypress/integration/product-list/collections_view_button.spec.ts
- frontend/test/cypress/integration/product-list/filters.spec.ts
- frontend/test/cypress/integration/product-list/newsletter_subscribe.spec.ts
- frontend/test/cypress/integration/product-list/parts_page_devices.spec.ts
- frontend/test/cypress/integration/product-list/parts_page_search.spec.ts
- frontend/test/cypress/integration/product-list/parts_results_view.spec.ts
- frontend/test/cypress/support/commands.ts
- frontend/test/cypress/support/index.d.ts
1. Added cypress retries to cypress config, [ref](https://docs.cypress.io/guides/guides/test-retries#Global-Configuration). Now failed tests will retry 2 times. 
Hopefully, this will prevent flaky tests or help to catch them
2. Moved common intercepts and wait statements from [here](https://github.com/iFixit/react-commerce/pull/359/commits/bd074d7b61213badc1e45473c4a7dd60259964d4#diff-e81662fc335a428ae62a3c659b1e32d31f596711ef35d4a019a9291e546798c6R4-R15) to a custom cypress command for reusability. 
Now, we can simply do `cy.loadCollectionPageByPath('/Parts')` or `cy.loadCollectionPageByPath('/Tools')`.
Please re-run the cypress tests ci check and make sure they don't fail.
> Tests: Cypress add auto retry and deflake tests

- README.md
- frontend/components/product-list/ProductListView.tsx
- frontend/components/product-list/sections/ProductListChildrenSection.tsx
closes #411 
To remove the layout shift we are now rendering all the model button elements and we are masking them adjusting the `maxHeight` of an additional external div.
#QA
1. Open the vercel preview
3. Verify that #411 is fixed (eventually throttling the connection to better inspect first load)
> Remove layout shifts

- README.md
- frontend/components/product-list/ProductListView.tsx
- frontend/components/product-list/sections/FilterableProductsSection/FacetsDrawer.tsx
closes #385
As agreed in the weekly meeting, we are going to mitigate the issue experienced by iOS users hiding the underlying body on small devices as soon as the drawer is shown. 
cc @sterlinghirsh 
1. Open [Vercel Preview](https://react-commerce-git-vertical-scrollbar-in-mobile-filter-ifixit.cominor.com/Parts) on a iOS mobile device
2. Verify that even in Safari - portrait mode - when the browser UI is not fully visible (i.e. the address bar is retracted, and the toolbar bar fully collapsed), the issue described in #385 is not present anymore
> Mitigate #385 for iPhone devices

- frontend/components/product-list/sections/FilterableProductsSection/RefinementMenu.tsx
I noticed that the item type facet urls were linking to the wrong place, typically the current window.location.href.
The item type urls were previously all the same as window.location.href,
indicating that something wasn't working right with InstantSearch's
`createURL()`. A quick solution is to just add the correct item type
slug ourselves.
Make sure the item type urls always link to the right place now.
Bug introduced in #431, thought I could have sworn they were linking to the right place in that pull.
CC @sterlinghirsh @erinemay
> Facets: Fix item type urls

- frontend/components/product-list/sections/FilterableProductsSection/ProductList.tsx
Previously, the flairs were missing when the product was out of stock or when it wasn't for sale. 
This PR makes it so that  those labels will always be visible if the product has a lifetime warranty and/or if it is a genuine part regardless of whether it's in stock or no.
Make sure the labels are present when expected.
Closes #471
> Fix the missing productlist flairs

- frontend/.env.development
- frontend/.env.production
- frontend/components/analytics/GoogleAnalytics.tsx
- frontend/components/analytics/index.ts
- frontend/components/product-list/ProductListView.tsx
- frontend/config/env.ts
- frontend/next.config.js
I copied the GA config from `UI/templates/google_analytics_create.phtml` in the main repo.
This leaves out a couple configuration options: `userid`, `loggedIn`, `customerType` cause Jeff Snyder doesn't use them and doesn't think they're necessary for launch.
QA
---
With the production config the GA JS should show up in the `<head>` on every page and mostly match the JS on the old product list pages.
Closes https://github.com/iFixit/react-commerce/issues/483
> Add Google Analytics to Collections pages

- frontend/config/env.ts
This is causing issues in production because we are unable to build
absolute urls with the ifixit origin. In production, we shouldn't have the CORS problem because we'll be on www.ifixit.com.
See https://github.com/iFixit/react-commerce/issues/489#issuecomment-1195598782
Smoke test that all basic features are working. We will probably see CORS errors in the previews as detailed in https://github.com/iFixit/ifixit/issues/43646
CC @danielbeardsley @dhmacs 
Connects #489
> Revert  #393: "iFixit Origin: use relative urls if on same origin"

- .gitignore
- README.md
- frontend/next.config.js
- package.json
#348 broke [Fast Refresh](https://nextjs.org/docs/basic-features/fast-refresh), so here I'm proposing to drop `withUniversalOptimization` to fix it. This [comment](https://github.com/vercel/next.js/issues/8956#issuecomment-557871585) from Next.js core member says:
```
Minification is disabled by default for serverless bundles as it significantly increases 
build times and doesn't give any significant benefits when deploying serverless bundles.
```
@andyg0808 do you have better insights about this? 
1. Fix fast refresh
2. Update readme to reflect new dependencies install requirements
1. Clone the process locally
3. Install dependencies
4. Run dev server
5. Try to change a component and verify that you can see changes applied in the browser almost instantly (less than 1 sec)
> Fix broken fast refresh

- frontend/helpers/product-list-helpers.ts
This change is for links we generate on the frontend, but I don't think we actually generate any marketing links anywhere. I made this change for correctness sake, but I don't think we can QA because we don't currently generate marketing links.
qa_req 0
> getProductListPath: Use /Shop for marketing links

- frontend/components/product-list/sections/FilterableProductsSection/index.tsx
Add a link to the parent category with the text `Return to parent category` on empty collection pages.
This replaces the "Try to navigate to subcategories..." text that was there previously.
Closes: #460
> Empty collection text: Add link to parent category

- frontend/components/product-list/sections/ProductListChildrenSection.tsx
Previously, the model buttons were getting weirdly cut off on the top. This PR  fixes it by adding some padding and fixing the space within the grid accordingly.
CR:
- The spacing was altered because when the padding was added, the buttons moved down and were getting cut off by the `Show More` toggle like shown here:
- In order to fix this^, the spacing was reduced when the padding was added.
QA:
- Visit the preview
- Make sure that the highlight isn't cut off
- At the top
- By the toggle
- And when when expanded, by the `Show Less` toggle.
Closes #477 
CC: @jordycosta
> Model highlight: Fix the highlight that was getting cut off

- frontend/.env.development
- frontend/.env.production
- frontend/config/constants.ts
- frontend/config/env.ts
- frontend/models/product-list/index.ts
- frontend/pages/Parts/[...deviceHandleItemType].tsx
- frontend/pages/Parts/index.tsx
- frontend/pages/Shop/[handle].tsx
- frontend/pages/Tools/[handle].tsx
- frontend/pages/Tools/index.tsx
This PR will let us use different Algolia index for different environments
- Refactor algolia index name from being a const to be an env variable
- Override production `NEXT_PUBLIC_ALGOLIA_PRODUCT_INDEX_NAME` env variable to  point to `product_group_en`
2. Visit parts product list
3. Open dev tools network tab
4. Trigger an Algolia search (e.g. by clicking on a filter)
5. Inspect the request and verify that it's using `dev_product_group_en` index
> Add env variable for Algolia index name

- frontend/pages/Parts/[...deviceHandleItemType].tsx
Fixes a bug where a visit to /Parts/Device/Item_Type would 404. The item type slug is optional, but any extra path components after that should 404.
This bug was unintentionally introduced in https://github.com/iFixit/react-commerce/commit/c32b62fe8859fa04f68b4f6e855b0938120544fd (and I missed it in CR!).
Admittedly it was bad idea on my part to store the itemTypeHandle in an unused variable, and it got "cleaned up" in that commit. Now, we'll include it in the `...` and only 404 if there is > 1 extra path component.
Visit /Parts/iPhone_11/Adhesives and make sure it doesn't 404.
Closes #516
> Routing: Don't 404 on item type visits

- frontend/components/product-list/ProductListDeviceNavigation.tsx
- frontend/components/product-list/ProductListView.tsx
These were unintentionally hidden in #466. This adds back breadcrumbs on /Tools/Category pages.
CC @erinemay 
Closes #502
> Breadcrumbs: Display on desktop tool category pages

- frontend/components/common/InstantSearchProvider.tsx
- frontend/components/product-list/sections/FilterableProductsSection/RefinementMenu.tsx
We were having problems where the HTML page returned from the Vercel SSR included facet links pointing at the Vercel subdomain where it's actually hosted, instead of at `www.ifixit.com`. This switches things around to use the host from `NEXT_PUBLIC_IFIXIT_ORIGIN` when rendering on the server, which means that we're in full control of where the code thinks its origin is.
I didn't handle the case where `NEXT_PUBLIC_IFIXIT_ORIGIN` has a path on it; it doesn't seem currently relevant, and it's kinda a change from the previous behavior (which breaks up the `location` and uses it to generate the new URL; the path is handled separately).
Check the page source on https://react-commerce-prod-git-instant-search-use-correc-eb6415-ifixit.vercel.app/Parts/Mac (use the `View Source` function in your …
> InstantSearch: Render facets with URL from environment on the server

- frontend/components/product-list/sections/FilterableProductsSection/FacetsAccordion.tsx
This PR hides `Worksin` on both `/Parts` and `/Tools` and `Tools Category` on `/Parts` when the search query results in an empty product list state.
- `Tool Category` should now always be hidden on `/Parts` and its children. And on empty state:
- `Tool Category` and `Worksin` should be hidden on `/Parts`
- `Worksin` should be hidden on `/Tools`
Closes #500 
CC: @erinemay @jeffsnyder
> Facets: Only show relevant ones on empty product list

- frontend/components/common/InstantSearchProvider.tsx
- frontend/components/product-list/sections/ProductListChildrenSection.tsx
Hides the device children links on item type pages (like /Parts/iPhone/Batteries) when there are no product results and there are no other refinements applied. This prevents crawlers from continuing to descend down the device tree, when we know they will keep hitting empty pages.
- Find a device that has children device links on `main`. You might have to go into [strapi admin](https://hide-children-on-no-hits-item-type.govinor.com/admin) for this branch and set the `parent` field for some devices in order to see them.
- Visit an item type page for this device that has no results.
- One way to do this: Visit the device parts page, like /Parts/iPhone. Type gibberish as the last component, like /Parts/iPhone/asdf.
- On main, the children links should still show on the empty item type page. …
> Hide device children on unfiltered item type pages with no hits

- frontend/components/product-list/MetaTags.tsx
- frontend/models/product-list/index.ts
- frontend/models/product-list/types.ts
We have pages like `/Parts/Mac_Laptop` with no corresponding Strapi
content. And pages like `/Parts/iBook_G3` whose Strapi content is
unpublished.
In both of those cases, we want to noindex the Collections page.
QA
---
- Check that collections that aren't in Strapi, or are unpublished noindexed.
- Check that I didn't accidentally noindex anything important
Closes #514
> Noindex collections pages without corresponding Strapi content

- frontend/legacyPartCollectionRoutes.js
- frontend/next.config.js
So we can redirect to something useful if a user finds an old Product
Page link somewhere.
The old values are from the `product_tags` table; the new values are
from the `tag_item_type` Akeneo attribute.
QA
---
Examples of URLs that should redirect:
- /Parts/MacBook_Pro/Adapters -> /Parts/MacBook_Pro/Power_Adapters
- /Parts/MacBook_Pro/Audio -> /Parts/MacBook_Pro
Fixes iFIxit/ifixit#44040
> Redirect old Product List tags to new Item Type values

- frontend/components/product-list/sections/FilterableProductsSection/FacetsDrawer.tsx
This PR hides the facet `Tool Category` on mobile on `/Parts`.
Closes #534 
CC: @rickisXP
> Hiding Tool Category on mobile.

- frontend/components/product-list/sections/FilterableProductsSection/RefinementSingleSelect.tsx
When the facet title was very long, it did a weird wrapping thing and displayed itself. This PR fixes that.
For context this is how they were before
This is how they look right now on main
This is how they look with the changes made in this PR
Closes #530 
CC: @jeffsnyder
> Fix multi line facet styling

- frontend/lib/ifixit-api/devices.ts
- frontend/models/product-list/index.ts
Before, we had a call to strapi and a conditional call to iFixit API afterwards. This makes it so the two requests are done at the same time so we can cut out the overhead of the faster request. This should make the two calls take less time overall as one is not conditional on the other and they are practically always both called anyway.
Pretty simple
Do product lists still load? Are they any faster? I've found a slight improvement when running locally (~60 ms speed up) but couldn't find that same performance gain in lighthouse for whatever reason.
Closes: #525
> Have findProductList() Make Async Calls in Parallel.

- frontend/components/product-list/MetaTags.tsx
- parseNoIndexExemptDeviceUrls.ts
This sets up logic to exempt certain device pages and item type pages from being no-indexed if the number of results in that collection is 1.
MacBook_Pro is included here as an example, more data will be filled in on the next commit.
Visit some of the urls in the CSV below. If they have at least 1 result, they should have a `<link rel="canonical" href={canonicalUrl} />` in the `<head>` of the html. For context, normal pages (that aren't exempted here) will have this canonical when there are 2 or more results.
[1-product-item-type-collections_exempt.xlsx](https://github.com/iFixit/react-commerce/files/9223728/1-product-item-type-collections_exempt.xlsx)
Closes #543
> SEO: Setup no-index exemption logic

- frontend/components/ifixit-image/ifixit-image.tsx
Add custom loaders for Guide and Cart images that load the smallest size larger than the required width for the image.
CR
---
I was torn on whether or not to deduplicate the logic between `guideImageLoader` and `cartImageLoader`. Ultimately I decided that doing so would add too much complexity for two 3-line functions.
~~I turned on optimizations for Strapi images using the default loader based on this comment: https://github.com/iFixit/react-commerce/issues/361#issuecomment-1178375740~~
QA
---
Guide and Cart images should now have a `srcset` to allow loading of larger sizes only when needed.
~~Strapi images now use the default Next.js image loader.~~ Strapi images are unchanged.
I'm not sure how to test Strapi images on local dev, but please do so.
Closes: #361
> Images: Add custom loaders for Guide and Cart images

- frontend/components/product-list/sections/FilterableProductsSection/useFacets.tsx
We think there are too many device options too be helpful as a facet. We still want device to be searchable, so we'll keep indexing it in Algolia.
CC @jeffsnyder @sterlinghirsh 
Closes #553 
Closes #536
> Facets: Drop `device` facet

- frontend/components/product-list/MetaTags.tsx
- frontend/components/product-list/sections/FilterableProductsSection/useDevicePartsItemType.tsx
Modifies the `useDevicePartsItemType()` hook to use the item type from the slug on the server.
Algolia's `useCurrentRefinements()` hook doesn't include the 'Item Type' filter on page load, even when we visit an item type page like /Parts/iPhone/Batteries. This is unexpected because we explicitly add the 'Item Type' to the current UIState in the InstantSearchProvider. This approach is a workaround for this unexpected behavior.
Uses the fix in https://github.com/iFixit/react-commerce/pull/527 everywhere else.
A smoke test of the app. Notably, when you visit item type pages directly, you shouldn't see a flash of unfiltered results before the page finishes loading and you shouldn't see the "Parts" version of the title flash.
CC @sterlinghirsh @dhmacs 
Closes #531
> Fix SSR for item type product lists

- backend/src/api/product-list/content-types/product-list/schema.json
- frontend/lib/strapi-sdk/generated/sdk.ts
https://github.com/iFixit/react-commerce/pull/545 failed because we started querying for this field before strapi got redeployed. Let's deploy Strapi first, then modify our queries in another pull.
Make sure `metaTitle` shows up in https://add-custom-meta-title-on-strapi-ONLY.govinor.com/admin
Redeploy Strapi
Connects #539
> Strapi: Add custom meta title field

- frontend/components/product-list/MetaTags.tsx
- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/operations/getProductList.graphql
- frontend/models/product-list/index.ts
- frontend/models/product-list/types.ts
Uses the `metaTitle` field in the `<title>` of the `<head>`, and nowhere else on the page. This field was added to Strapi in https://github.com/iFixit/react-commerce/pull/550.
Pages with a value in `metaTitle` should have the value in the `<title>` tag, otherwise it should default to the normal device title. You can edit the `metaTitle` in Strapi here: https://collections--add-meta-title-to-strapi.govinor.com/admin
Closes #539
> Use `metaTitle` from Strapi

- frontend/components/product-list/sections/FilterableProductsSection/FacetsAccordion.tsx
- frontend/components/product-list/sections/FilterableProductsSection/FacetsDrawer.tsx
Previously, we displayed the `1` bubble when we had a facet select for the [single select facet categories](https://github.com/iFixit/react-commerce/pull/476). We don't want that anymore because in case of single select that number will always be a 1. Instead we want something of this sort:
- We only want this for single select facet categories [ie everything except for `Capacity` and `Price Range`].
-  `Capacity` and `Price Range` should still display the count as before when the options under these categories are selected [where count = # of options selected]
- Visit the preview
- Make sure the blue bubble [refer screenshot] is visible when we select an option for single select categories on desktop and mobile
- Price Range and Capacity should still display the number
Closes #522 
CC: …
> Filter bubble: Fix for single select

- frontend/lib/ifixit-api/devices.ts
- packages/auth-sdk/user.tsx
We introduced logs in #457, and this makes sure that the places that use `iFixtAPIClient` now can handle the response's format. Before our failures were basically nulling out and thus making it so no information gotten from the api was being used in the pages. This makes sure that we expect the appropriate data formats so we don't default to nulls.
Uh I think this should work but make sure that nothing I'm doing is funky. You know, the usual.
Make sure the normal pages work and load the pictures for the children again. Also make sure that pages that aren't in strapi are loading correctly from the iFixit API and stuff. You can use `Asus_Phone` and `Phone` for this. 
You also need to test authenticating a user in react-commerce.
Closes: #577
> Fix Images and Part Collections API calls

- frontend/pages/Parts/[...deviceHandleItemType].tsx
- frontend/pages/Parts/index.tsx
- frontend/pages/Shop/[handle].tsx
- frontend/pages/Tools/[handle].tsx
- frontend/pages/Tools/index.tsx
We were setting the max age of the cache to 10 min when we were on Cloudfront because Cloudfront doesn't respect the SWR header.
Now that we're on Vercel, we can drop max age back to 10 seconds and set a 10 minute SWR.
https://vercel.com/docs/concepts/edge-network/caching#serverless-functions---lambdas
Not sure that we need it here?
Motivation: https://github.com/iFixit/react-commerce/pull/551#issuecomment-1203982043
#341
CC @danielbeardsley @dhmacs 
qa_req 0
> Revert #341: Cache for only 10 sec, not 10 min

- frontend/components/product-list/sections/FilterableProductsSection/ProductGrid.tsx
- frontend/components/product-list/sections/FilterableProductsSection/index.tsx
closes #434
closes #449
We introduced a pseudo element to cover the gray background that we exploit for colouring the grid guts.
This allows to eliminate the problems described in #434
2. Verify that all the issues described in #434 are not present anymore
> fix: polishing guts and overflow styles

- frontend/models/product-list/index.ts
This got super easy after #556 
We want to now 1.) handle iFixit only devices (ghost devices) redirect to the correct capitalization 2.) prioritize iFixit's capitalization over Strapi's. This will make it easier to link from iFixit to the store so they don't have to check strapi for the official url, etc.
While testing watch out for permanent redirecting (308s and the like). You may have to clear your browsers cache (or in the code change the `[...deviceHandleItemType].tsx` redirect calls permanent attribute to false)
You should test an device not in strapi (`/Phone` is what I use) and make sure that even if you mess around with the capitalization it reroutes back to the correct URL. Also make sure that iFixit data is prioritized over strapi's, so maybe change some local strapi data to be …
> Redirect Device Pages If Capitalization Isn't Right

- frontend/package.json
- frontend/sentry.client.config.ts
- pnpm-lock.yaml
We want to add sentry logging for the frontend performance, so this pr introduces changes to do so at the same rate as `ifixit/fixit`. 
The `pnpm-lock.yaml` changes seemed necessary for `ts` standards, but I'm not sure how to determine issues of changing tons of packages or if I should do this a better way to reduce the code change.
You'll want to change the value of `tracesSampleRate` in `frontend/sentry.client.config.ts` to `1` to make sure 100% of logging goes to sentry. Then run `pnpm dev` and check if `react-commerce-dev` on sentry is getting performance logs.
Closes: https://github.com/iFixit/ifixit/issues/44070
> Add Sentry Logging to Frontend Performance

- frontend/components/analytics/GoogleAnalytics.tsx
- Fixes a bug where page views weren't being tracked properly.
- Follows the Next.js [reference implementation](https://nextjs.org/docs/messages/next-script-for-ga#using-analyticsjs) of Google Analytics. Note that this puts the script in the `<body>`, and it was in the `<head>` before. This doesn't seem to make a difference functionally. I couldn't find a way to use the Next's `<Script>` component in the `<head>`.
- Sends a GA pageview when the Next router indicates that the route has changed.
- Install the Legacy Google Tag Manager extension on Chrome: https://chrome.google.com/webstore/detail/tag-assistant-legacy-by-g/kejbdjndbnbjgmefkgdddjlbokphdefk?hl=en
- Run react-commerce locally, and set `NEXT_PUBLIC_GA_URL=https://www.google-analytics.com/analytics.js` in `.env.development`.
- …
> Fix google analytics

- frontend/components/product-list/sections/FilterableProductsSection/useFacets.tsx
OMG, this was causing our server-side algolia query (and react dom
rendering) to happen twice. This was effectively doubling our response
times.
See this line in algolia's getServerState():
https://github.com/algolia/react-instantsearch/blob/affcbb58ee5c63345cc9424ad8ab566f3a01c9f9/packages/react-instantsearch-hooks-server/src/getServerState.tsx#L48-L49
Connect https://github.com/ifixit/ifixit/issues/43498
> Algolia: Drop unused hook (make much faster!)

- frontend/components/product-list/sections/HeroSection.tsx
Converts newlines to `<br />` tags before rendering product list descriptions from markdown to html.
Leading and trailing newlines are stripped.
- Visit the preview link, and choose a product list page.
- Find that product list in strapi admin: https://productlist-description-preserve-newlines.govinor.com/admin
- Edit the product list description to have newlines.
- The newlines in the UI should be one-to-one with the number of newlines in Strapi. (Leading and trailing newlines will be stripped).
CC @jeffsnyder
Closes #450
> Preserve product list description newlines

- frontend/models/product-list/index.ts
- frontend/pages/_app.tsx
- frontend/pages/_document.tsx
closes #586 
Move the viewport meta to `_app.tsx` as suggested by the remediation [here](https://nextjs.org/docs/messages/no-document-viewport-meta)
cc @masonmcelvain 
1. Visit the Vercel preview
2. Verify that there are no changes in functionalities
3. Verify that the viewport meta is still present
4. Verify that the console warning which appeared while compiling a page is not present anymore
> Remove viewport meta tag warning

- frontend/components/analytics/Matomo.tsx
- frontend/next.config.js
- frontend/package.json
- packages/matomo/index.tsx
- packages/matomo/package.json
- packages/matomo/tsconfig.json
- pnpm-lock.yaml
- Tracks navigation between pages in Matomo.
- Uses Next's `Script` component to run the Matomo script after the page is interactive. Consequently, the script is moved from the head to the body.
- Make sure the preview link you're using is added to matomo.ubreakit.com (see screenshot below)
- Click around through some links in the preview.
- Verify that the visits are recorded in the `Visits Log` in matomo's dashboard.
- Verify that navigation on `main` wasn't working, but it's working on this branch.
- Thanks! 🙏🏻 
Closes #595 
Closes #495
> Matomo: Track interpage navigation

- packages/ui/cart/drawer/CartDrawer.tsx
Previously, we would not have the "Back to Shopping" button and associated text elements visible but they would still be interactable. This has been fixed by making that section now collapse instead of not being rendered.
Are the aforementioned buttons and text not in the drawer anymore when they shouldn't be (having items in the cart)?
I've changed the `scalefade` section to a `collapse` section, which you can see how these animate differently [here](https://chakra-ui.com/docs/components/transitions/usage#scalefade-transition) and [here](https://chakra-ui.com/docs/components/transitions/usage#scalefade-transition) respectively. This is seen when your cart is clear and the "Back to Shopping" button is valid again. If this isn't acceptable design lmk, but I feel like it is ok.
Closes: #444
> Make Sure "Back to Shopping" Button isn't on Page When Not Visible

- frontend/components/common/Layout/Footer.tsx
- frontend/test/cypress/integration/product-list/newsletter_subscribe.spec.ts
- packages/ui/footer/index.tsx
Previously, when the user successfully subscribed, we would disable the text box and that would cause the cursor to change to the
disabled state making it look like there was an error. This PR fixes this by hiding the entry text box on subscription.
Before:
With this PR:
Closes #480 
CC: @sterlinghirsh @erinemay
> Subscribed: Hide the text box

- frontend/helpers/next-helpers.ts
- frontend/pages/Parts/[...deviceHandleItemType].tsx
- frontend/pages/Parts/index.tsx
- frontend/pages/Shop/[handle].tsx
- frontend/pages/Tools/[handle].tsx
- frontend/pages/Tools/index.tsx
- packages/helpers/index.tsx
- packages/helpers/nextjs.tsx
- packages/helpers/package.json
- packages/sentry/index.tsx
- packages/sentry/package.json
- packages/sentry/tsconfig.json
- pnpm-lock.yaml
Sometimes it's hard to tell which page a user was on when an error occurred, so adding it in a tag will be useful for debugging.
The resolved url is the url that the user requested (like /Parts/iPhone). This is different than `context.req.url`, which can be a link like /_next/data..., which is not the helpful for debugging.
Throw an error on any page while running local dev. It should get reported to react-commerce-dev in sentry, and have a `resolved_url` tag.
> Sentry: Add resolved url tag

- packages/ui/package.json
Our main monorepo requires these for all dependencies of our main package. Now that we're wanting to start using the `@ifixit/ui` package from that main package, we need them.
qa_req 0
> @ifixit/ui: Add `build` and `clean` scripts

- frontend/components/product-list/sections/FilterableProductsSection/ProductList.tsx
Since we always want to display the  flairs, regardless of whether an item is in stock or not [ie the `quantityAvailable` > 0 or not], lets get rid of the check and assign the boolean value simply based on whether the item is discounted or not. This is similar to #471 
- Visit the prod [preview](https://react-commerce-prod-git-fix-missing-discount-flair-ifixit.vercel.app/Parts/PC_Laptop/Batteries?p=4)
- Make sure the discount flair is visible as desired for the different items [The flair should now be visible for [https://www.ifixit.com/Store/PC-Laptop/Lenovo-ThinkPad-X1-Yoga-1st-Gen-and-X1-Carbon-4th-Gen-56Wh-Battery/IF245-154?o=2](https://www.ifixit.com/Store/PC-Laptop/Lenovo-ThinkPad-X1-Yoga-1st-Gen-and-X1-Carbon-4th-Gen-56Wh-Battery/IF245-154?o=2)]
Closes #613 
@jeffsnyder
> Discount Flair : Make it visible always

- frontend/components/product-list/sections/FilterableProductsSection/FacetsDrawer.tsx
In https://github.com/iFixit/react-commerce/commit/e905db9176b532d461d469711a0e3e0f64e49dbb, we made it so that the on mobile view, when we select a facet in the single select facet category, we close the drawer and get back to the product page. The issue with that is if the user needs to filter further, they have to repeat certain steps.
Instead, lets keep the behavior so that when the user selects a facet in the single select category, we bring the user back to the facet list instead of closing the drawer.
- On mobile/tablet view, make sure that when a single select facet is selected, it brings you back to the list of facets instead of exiting out.
**NOTE: https://github.com/iFixit/react-commerce/issues/579#issuecomment-1209078103 hasn't been implemented in this PR and if this scrolling …
> Mobile Filtering: Improve UX

- backend/build-docker-and-push
We ran into a problem where different versions of `git` had different length short refs (old version had 7 chars, new version had 8 chars).
Let's always use the long ref so we don't have that problem in the future.
We should be able to [redeploy](https://github.com/ifixit/server-templates/wiki/strapi) strapi
CC @danielbeardsley
Connects https://github.com/iFixit/server-templates/pull/3512
qa_req 0
> strapi: Use long git ref for deploy

- frontend/templates/product-list/sections/FilterableProductsSection/RefinementSingleSelect.tsx
When we used to swap single select refinements we would sometimes have the no-refinements selection blip on the screen for a half second (see the issue #526 for an example). This pr helps make it smoother while we try to figure out whats wrong with vercel and #617. It does this by adding in the new refinement before removing the old refinement.
This isn't a bad pattern for react right?
Make sure that pages have less of the blip of wrong results when switching single select refinements (note that even on master this blip disappears on switching if youve already switched between the two refinements on a page load. it must be caching the refinement results in the browser). Make sure that refinements are working as intended. 
Connects #526
> Have Single Select Refinement UI Change Look Somewhat Smoother 

- frontend/templates/product/index.tsx
Adds the default layout to the product page
2. Go to `/Products/test`
3. Verify that the default header and footer are presents
> Add default layout to product page

- frontend/jest.config.js
- frontend/templates/product-list/sections/FilterableProductsSection/ProductGrid.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/ProductList.tsx
This PR refactors product list to link to the new product page (if the product page flag is enabled)
1. Open [prod-like Vercel preview](https://react-commerce-prod-m8006kj4z-ifixit.vercel.app/Parts) (flag not enabled)
2. Go to `/Parts` and verify that products list links point to the current product pages
3. Visit [staging Vercel preview](https://react-commerce-g7rzb3hpz-ifixit.vercel.app/Parts) (flag is enabled)
4. Go to `/Parts` and verify that product list links point to the new product page stub
> Refactor product list links to point to new product page

- frontend/templates/product-list/sections/FilterableProductsSection/useSortBy.ts
We were previously using to the default sorting of algolia for facets, which would sort by `isRefined`, then `count:desc` and `name:asc`. This would rearrange our facets when you would select them, and wasn't consistent with our custom sorting for specific facets. This makes sure we no longer sort by `isRefined` by default.
Make sure that when clicking on facets that aren't `price_range`, `Capacity`, or `Item Type`, they no longer resort and still work as expected
Closes: #635
> Don't Resort Facets When One is Selected

- frontend/lib/shopify-storefront-sdk/index.ts
- frontend/lib/strapi-sdk/index.ts
Adds Sentry reporting for failed GraphQL queries in our Strapi and Shopify Storefront SDKs.
It's difficult to mock graphql errors in practice, this is better suited for a test case. Since we'll see these errors in Sentry, we can decide if we more more/less metadata as events start rolling in.
qa_req 0
Our Strapi and Storefront SDKs use GraphQL to talk to their respective APIs. If the queries failed with errors in the response, we were logging them but not reporting them to Sentry.
https://github.com/iFixit/react-commerce/pull/643#discussion_r952791331
> Report failing SDK queries to Sentry

- frontend/helpers/product-list-helpers.ts
- frontend/lib/ifixit-api/devices.ts
- frontend/templates/product-list/sections/FilterableProductsSection/useSortBy.ts
We have some sentry errors like [this](https://sentry.io/organizations/ifixit/issues/3504489498/events/053ed493b7db4427868e074dec9ddc18/?project=6469069) where the page was failing because we had multiple spaces in the `deviceTitle`/`wiki_title`. This change makes sure when we encode/decode `deviceTitle` we maintain a character per space.
Make sure that you can click on `Samsung Galaxy A8+ (2018)` from [here](http://localhost:3000/Parts/Samsung_Galaxy_A) and it now works instead of 404ing. Also make sure other pages aren't broken i guess.
Connects: #632
> Handle deviceTitles with Multiple Spaces In Them

- frontend/components/ui/IconBadge.tsx
- frontend/components/ui/index.ts
- frontend/lib/shopify-storefront-sdk/generated/sdk.ts
- frontend/lib/shopify-storefront-sdk/operations/findProduct.graphql
- frontend/models/product.ts
- frontend/package.json
- frontend/pages/_app.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/useSortBy.ts
- frontend/templates/product/index.tsx
- frontend/templates/product/sections/ReplacementGuidesSection/index.tsx
- pnpm-lock.yaml
closes #655 
~~deploy_block 🛑 Blocked by #650~~
Adds replacements guides section:
2. Go to [/Products/iphone-11-pro-screen](https://react-commerce-git-add-replacement-guides-ifixit.vercel.app/Products/iphone-11-pro-screen)
3. Verify that you can see the replacement guides
> Add replacement guides

- frontend/sentry.client.config.ts
Basically we are getting a bunch of errors `TypeError: NetworkError when attempting to fetch resource`, an error particular to Firefox, in Sentry. Looking into this, this error is very hard to reproduce and only happens occasionally. While unsure of the explanation, even when I did manage to reproduce the bug I didn't notice any functional differences. I suspect something like [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1280189) is happening. With this in mind, and also that other people have [recommended](https://forum.sentry.io/t/typeerror-failed-to-fetch-reported-over-and-overe/8447) just having sentry ignore these errors, I think we shouldn't log them anymore with our sentry bandwidth. 
Its hard to reproduce, and there isn't much to check. I've checked my self and seen that …
> Ignore Firefox TypeError Network Errors in Sentry

- frontend/helpers/next-helpers.ts
We've had some errors like [this](https://sentry.io/organizations/ifixit/issues/3504489498/events/d9719aa880c2447abada45d57cdcf3fe/?project=6469069) where there seems to be some sort of link that is not encoded correctly. To investigate this more lets try to get the request/response context with the error for sentry.
Check if bad devices (so like `/Parts/badItemHere`) reports to sentry with a `Extra Info` json.
Connects #632
> Log findProductList Failures With More Context

- frontend/templates/product/index.tsx
- frontend/templates/product/sections/ReviewsSection/index.tsx
- frontend/templates/product/sections/ServiceValuePropositionSection/index.tsx
close #667 
This PR adds the service value proposition section
The section is already using the new icons and is already responsive
2. Go to [/Products/iphone-11-screen](https://react-commerce-git-add-service-value-proposition-section-ifixit.vercel.app/Products/iphone-11-screen)
3. Verify that the section is present and responsive
> Add service value proposition section

- .github/workflows/format.yml
- frontend/sentry.client.config.ts
The "Fail in production" step [failed](https://github.com/iFixit/react-commerce/runs/8120146230?check_suite_focus=true) even when there was no diff for some reason.
Let's use a more idiomatic pattern to skip workflows for the main branch.
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-branches-and-tags
Same as #665
Connects #616
> GH Actions: Skip `format` workflow for `main`

- frontend/components/common/InstantSearchProvider.tsx
- frontend/lib/cache.ts
- frontend/templates/product-list/index.tsx
This pull pertains to Vercel and `react-commerce`, and doesn't directly handle any Cloudfront related caching. Hopefully they respect `cache-control` headers.
Allow the `_vercel_no_cache=1` to disable use of the [vercel cache ](https://vercel.com/docs/concepts/edge-network/caching#cacheable-responses)for that request. Also makes it so that response has `cache-control` [headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) that should indicate to the browser to no cache. Also clears the `react-commerce` cache. 
its pretty easy to check if vercel is ignoring its caches. You can go the `react-commerce-prod` [instance](https://vercel.com/ifixit/react-commerce-prod/8FoSXqTSmrgn43XKwDF8nb3xne3m/functions) of this branch's functions, verify that going to a page like …
> Add Ability to Ignore Cache (Maybe)

- frontend/templates/product-list/sections/FilterableProductsSection/FacetsDrawer.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/Toolbar.tsx
When the facet drawer is closed on mobile, the view now scrolls so that the toolbar is at the top of the viewport.
- Preview /Parts on mobile.
- Click on "Filters" button.
- After closing the dialog, the view should have the number of results at the top of the screen. See the issue for a screenshot of the desired behavior.
- When the page first renders, nothing should be different (ie, there is no scroll effect).
CC @sumukhipandey
Closes #618
> Mobile Productlist: Scroll on facet drawer close

- frontend/components/common/ProductPrice.tsx
- frontend/models/product.ts
- frontend/templates/product/sections/ProductSection/index.tsx
close #662 
This PR introduce a new ProductPrice component.
The product page heading will use the red color scheme in horizontal direction as per mockup:
The component can however be configured to cover all the layouts visible in the mockup:
So, it may already cover most - if not all - the use cases that are being discussed [here](https://github.com/iFixit/react-commerce/issues/533). 
2. Go to [here](https://react-commerce-git-enrich-price-component-ifixit.vercel.app/Products/macbook-air-13-late-2010-2017-replacement-battery) to see a discounted product
3. Go to [here](https://react-commerce-git-enrich-price-component-ifixit.vercel.app/Products/iphone-11-screen) to see a product without discount
> ProductPrice component

- packages/cart-sdk/hooks/use-cart.ts
- packages/sentry/index.tsx
- packages/ui/cart/drawer/CartDrawer.tsx
Yeti bot / browser / crawler for some reason pretends that our cart api
returns a 403. So, on every page load (When it's indexing) the failed
cart API request results in a report to sentry. Let's ignore failed
requests if we're on the client side and if the browser is Yeti.
See commit messages for more
Closes #685
CC @sterlinghirsh @jarstelfox
> Yeti Crawler: don't send failed requests to sentry

- packages/sentry/index.tsx
If someone visits `/Parts/made-up-device-name` and this API 404s, let's not bother reporting this to Sentry.
Previously we were curious if this would help us find bugs (linking to pages that don't exist). But mostly we just get botspam that's just munging our urls to see what happens.
I've looked at the last 20 or 30 and found many variants on the same thing (Random edits to urls, urls for devices that don't exist, messe up punction in the urls, ...). None of the errors made me think we were at fault, so let's stop being hassled.
qa_req 0 Because of low blast-radius
Closes #632
> Sentry: don't report 404s

- frontend/sentry.server.config.ts
If a user submits a malformed url (with non-utf8 chars encoded), an error is thrown and was being reported to sentry.
I was never able to repro with a browser (nor with curl) but I can generate the error by just calling `decodeUriComponent('%80')`. This change effectively ignores these errors. In the past, we've gotten bursts of them as bots or vulnerability scanners peppered us with bad urls. As far as I could tell there wasn't an opportunity to stop these errors at the source because they happened deep in the next.js framework before middleware execution.
Closes #670
> Sentry: ignore malformed url errors

- frontend/components/common/CompatibleDevice.tsx
- frontend/lib/shopify-storefront-sdk/generated/sdk.ts
- frontend/lib/shopify-storefront-sdk/operations/findProduct.graphql
- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/models/product.ts
- frontend/templates/product/index.tsx
- frontend/templates/product/sections/CompatibilitySection/index.tsx
- frontend/templates/product/sections/ProductSection/ProductGallery.tsx
- frontend/templates/product/sections/ProductSection/index.tsx
- frontend/templates/product/sections/ServiceValuePropositionSection/index.tsx
- packages/ui/theme/components/alert.ts
closes #706 
This PR adds the compatibility accordion panel - just below the product variant selector - and the compatibility section in the lower part of the page.
The accordion panel shows the first 3 compatible devices at most. If there are more than 3 compatible devices it also show an anchor link that points to the compatibility section on the bottom of the page
The compatibility section always list all the possible compatible devices in a grid layout. 
Accordion panel:
Section:
2. Navigate to a [product with compatibilities](https://react-commerce-git-add-compatibility-panel-and-section-ifixit.vercel.app/Products/iphone-11-screen)
3. Verify that everything is like in the mockup
4. Check also products with a different number of compatible devices
> Add compatibility accordion panel + compatibility section

- frontend/components/common/PageBreadcrumb.tsx
- frontend/lib/shopify-storefront-sdk/generated/sdk.ts
- frontend/lib/shopify-storefront-sdk/operations/findProduct.graphql
- frontend/models/product.ts
- frontend/templates/product-list/ProductListBreadcrumb.tsx
- frontend/templates/product/component/SecondaryNavigation.tsx
- frontend/templates/product/index.tsx
- frontend/templates/product/sections/ProductSection/index.tsx
- frontend/templates/product/sections/ReviewsSection/index.tsx
closes #716 
1. Connect with the `ifixit.breadcrumbs` metafield to display correct breadcrumbs
2. Improved UI and UX to address also edge cases (like very long titles)
2. Visit some products (e.g. https://react-commerce-git-use-metafield-data-for-product-c0dc21-ifixit.vercel.app/Products/apple-watch-38-mm-series-2-replacement-battery )
3. Verify the breadcrumbs looks good, both [desktop](https://www.figma.com/file/jRG4EyQXRDMGfyLqut08KP/iFixit---Working-files?node-id=6737%3A90839) and [mobile](https://www.figma.com/file/jRG4EyQXRDMGfyLqut08KP/iFixit---Working-files?node-id=6737%3A90798). Please note that if there are more than 3 segments, we'll just show 3 and collapse the others into the menu button
> Improve product page breadcrumbs

- frontend/sentry.client.config.ts
These ` Typeerror: Network Request Failed` seem hard to reproduce and not overly harmful. Lets ignore them from sentry logs so they don't take up room on Sentry.
I don't think this needs qa since we don't know how to reproduce the error specifically. qa_req 0;
Connects: iFixit/ifixit#42336
> Ignore Typeerror: Network Request Failed In Sentry

- frontend/templates/product-list/MetaTags.tsx
Only append " | iFixit" to the titles of pages that don't have a custom title set in Strapi.
To give Strapi admin users full control over the title, we will use the custom title exactly as it exists on Strapi.
All product list pages should have ` | iFixit` appended to the title, unless there is a custom `meta title` set in Strapi. If that's the case, the meta title in Strapi is used as is. There should never be a case where it is double appended (like www.ifixit.com/Parts is right now).
Closes #735
> Only append suffix to default titles

- README.md
After running into the situation where my strapi did not have the ifixit test store, these were the steps I followed to fix it. In doing so, I also ran into the situation where the desired addons page did not appear on my localhost:1337 for strapi. I then had to delete the `.cache` and `dist` under `backend` and restart the dev server to finally be able to get my development environment back up and running
qa_req 0
CC: @sterlinghirsh @masonmcelvain @dhmacs
> README: Add troubleshooting steps for missing test store in strapi

- frontend/lib/ifixit-api/devices.ts
- frontend/next-config/helpers/redirects.js
- frontend/next-config/redirects/legacy-filter-slugs.json
- frontend/next-config/redirects/part-collections.js
- frontend/next-config/redirects/tool-collections.js
- frontend/next.config.js
Basically #529 had comments floating around it in and there were some more complaints to address.
This PR
1. Handles incorrect item types where they have spaces instead of "_" so things like `Parts/iPhone_11/Adhesive%20Strips` will now correctly reroute to `/Adhesives`. This might seem like an unnecessary fix but we are already handling things like `iPhone%2011` correctly so at least this stays consistent.
2. Redirect both  `/SSD_Enclosures` and `/Upgrade_Kits` to  `/Hard_Drives`.
3. Reorganize the `tool-collections` redirect generation so its more analogous to the parts one.
It should be pretty easy to test 1.) and 2.) above. 
`/Parts/HTC_Vive/I%2FO%20Board` seems like a decent route to test with.
Connects: #529
> Some More Legacy Redirect Fixes

- frontend/components/common/AppProviders.tsx
- frontend/pages/_app.tsx
- frontend/templates/product/index.tsx
- frontend/templates/product/sections/ProductSection/ProductGallery.tsx
- frontend/templates/product/sections/ProductSection/index.tsx
- pnpm-lock.yaml
closes #726 
This PR adds the side zoom functionality on product page.
Just hover with the mouse over any image in the gallery and a zoom side panel will appear.
We reverted #196 since now it is possible to handle pinch-zooming on modals - while still avoiding background scroll - exploiting the `allowPinchZoom ` flag of the [Chakra Modal component](https://chakra-ui.com/docs/components/modal/props).
So on mobile it is now possible to zoom on the gallery image by simply pinch zooming on the page.
Consider this as a base implementation for mobile. If then we want to add a more complex behaviour for mobile (click to fullscreen) we can discuss and integrate in a separate PR
2. Verify that the zoom behaviour is working correctly on desktop
3. Verify that on mobile it is …
> Add zoom to product gallery

- packages/icons/package.json
- pnpm-lock.yaml
We never required the icons to be pulled in? Weird!
qa_req 0
> Icons: Depend on the icon lib we use

- frontend/templates/product/sections/CrossSellSection/index.tsx
- frontend/templates/product/sections/ProductSection/ProductRating.tsx
- frontend/templates/product/sections/ReviewsSection/index.tsx
- frontend/test/cypress/support/index.ts
- packages/ui/theme/styles.ts
closes #727 
2. Go to a [product page](https://react-commerce-git-link-reviews-count-to-reviews-section-ifixit.vercel.app/Products/pro-tech-toolkit)
3. Click on the reviews count (under product title) and verify that the page scrolls to the reviews section
> Link reviews count to reviews section

- frontend/templates/product/sections/ProductSection/index.tsx
closes #731 
2. Verify that the new inter-paragraph spacing (12px) is present
3. Verify that last paragraph has no margin-bottom too
> Vertical spacing among paragraphs in product description

- frontend/templates/product/sections/ProductSection/ProductGallery.tsx
closes #762 
The problem seems to be due to the fact that before js kicks in, thumbnails are rendered with a width equal to 100% of the column width. I've inserted some css to resize images to the same scale that will be enforced as soon as js kicks in.
2. No thumbnail induced shift should be visible
> Fix layout shift in gallery thumbnails

- frontend/helpers/next-helpers.ts
- frontend/middleware.ts
- frontend/templates/product-list/index.tsx
- frontend/templates/product/index.tsx
This is a simpler approach to noindexing dev domains. We couldn't use it before because it caused Cypress to fail the collection scroll test. Now that this passes tests we prefer to use it.
Make sure the previews are no-indexed. (see #734)
> Noindex dev domains via middleware

- frontend/pages/_app.tsx
- frontend/templates/product/hooks/useSelectedVariant.ts
- frontend/templates/product/index.tsx
closes #707 
2. Open a [product page](https://react-commerce-g76xpq4uq-ifixit.vercel.app/Products/repair-business-toolkit)
3. Select a different variant and verify that the url updates accordingly
4. Reload the page and verify that the variant is selected according to the `variant` param
> Sync product variant selection with url

- frontend/lib/shopify-storefront-sdk/generated/sdk.ts
- frontend/lib/shopify-storefront-sdk/operations/findProduct.graphql
- frontend/models/product.ts
- frontend/templates/product/sections/ProductSection/ProductOptions.tsx
- frontend/templates/product/sections/ProductSection/index.tsx
closes #701 
This PR disable product variants that have `disable_when_oos = true` and `variant.availability <= 0`.
Such disabled variants are filtered out from the active variant set.
Moreover, product options that are not associated to any active variant are filtered out too, since hinting to the existence of those variants is not useful anymore.
To summarize:
- Variants with availabilities are always active
- Variants with zero availability and `disable_when_oos = false` show the `Notify me` banner
- Variants with zero availability and `disable_when_oos = true` will not be shown on the website. 
**If a product option is associated only to disabled variants or no variants at all, it will be hidden**
1. Visit Vercel preview (you can also take [this …
> Handle disable_when_oos metafield

- frontend/templates/product/sections/ReplacementGuidesSection/index.tsx
We want our customers to be able to view the guides that products are involved in without navigating them completely away from the store. So this opens the guide in a new tab for them.
Does clicking on the links for `Replacement Guides` now open them up in a new tab?
Recommend using `/Products/iphone-11-pro-screen`
Connects: #732
Analogous to https://github.com/iFixit/ifixit/pull/44987
> Links to Guides on Product Pages now open in a new tab

- frontend/helpers/product-helpers.ts
- frontend/next.config.js
- frontend/templates/product-list/sections/FilterableProductsSection/ProductGrid.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/ProductList.tsx
- frontend/templates/product/sections/FeaturedProductsSection/index.tsx
Attempts to visit featured products will redirect to our ifixit featured product pages.
When we link to featured products in Next.js, we link directly to ifixit featured product pages.
Confirm that the above features do what we intend them to do. (we link to featured products on collection pages)
CC @sterlinghirsh
Closes #806
> Redirect featured product links

- frontend/templates/product/sections/ProductSection/ProductOptions.tsx
We would prefer not to show a component that looks like a dropdown/button when there is only one option associated with a variant.
Make sure products with only one option per variant axis just display text for that axis (as opposed to a dropdown or radio buttons).
Closes #793
> Show no selector for variants with one option

- frontend/sentry.client.config.ts
- frontend/sentry.server.config.ts
Sentry only shows the top-level properties of json objects, if their values are nested json objects, you get "[Object]". This is pretty useless, so let's pretty print the request body
qa_req 0 //  low blast radius if it's incorrect.
Closes #815
> Sentry: stringify request body in reported error context

- frontend/helpers/next-helpers.ts
- frontend/templates/product/index.tsx
closes #770 
1. Visit [react-commerce-prod preview](https://react-commerce-prod-git-enable-product-page-in-pr-a1546e-ifixit.vercel.app/products/macbook-pro-14-2021-a2442-and-16-2021-a2485-antenna-cable-bracket)
2. Verify that the product page is visible
3. Verify that the product page is not indexable (`x-robots-tag` header set to `noindex, nofollow`
4. Go to product lists (e.g. [`/Parts`](https://react-commerce-prod-git-enable-product-page-in-pr-a1546e-ifixit.vercel.app/Parts)) and verify that products links still point to the legacy us product page
> Enable product page in production

- frontend/lib/shopify-storefront-sdk/generated/sdk.ts
- frontend/lib/shopify-storefront-sdk/operations/findProduct.graphql
- frontend/models/product.ts
closes #784 
This PR adds handling of the `enabled` metafield (formally `enabled2`)
We assumed all active variant have the `enabled2` metafield set to true by default and that only disabled variants have falsey values in it.
1. Visit the Vercel preview
2. Try to disable explicitly some product variants via the `enabled2` metafield
3. Verify that the interface is working as expected locking or even hiding disabled product options if no active variants include them at all
> Handing enable (enabled2) metafield

- frontend/templates/product/sections/ProductSection/AddToCart/index.tsx
- frontend/templates/product/sections/ProductSection/index.tsx
- packages/cart-sdk/hooks/use-cart-line-item.ts
- packages/cart-sdk/index.tsx
closes #799 
Product page now uses inventory quantity from the cart if available.
1. Visit [Vercel preview](https://react-commerce-git-sync-product-page-quantity-with-cart-ifixit.vercel.app/products/repair-business-toolkit?variant=39333695422554)
2. Verify that whenever an item is added to the cart the product page quantity is updated
⚠️ The iFixit test store has not always up to date inventory quantities so, when you add a product to the cart the remaining quantity count could show a different count than the expected, because we're using the available quantity returned by the cart api. This shouldn't happen in production
> Sync product page quantity with cart

- packages/footer/components/Shared.tsx
- packages/footer/homepage-kpis/index.tsx
We have some more minor changes to be made to the footer for iFixit/ifixit.
First, we added a margin on top of the footer to separate it from the content on the page. We want the KPI banner to be flush with the footer, however. So let's add a negative margin to remove the gap.
Second, we had some pages with a different default text color. To make sure we have the same color text on every page, let's be explicit about the colors.
qa_req 0
> Footer: minor styling updates

- frontend/components/common/PageBreadcrumb.tsx
- frontend/templates/product/index.tsx
- frontend/templates/product/sections/ProductSection/Prop65Warning.tsx
- frontend/templates/product/sections/ProductSection/index.tsx
closes #834 
This PR fixes issue described by #834 and a tricky bug on small size devices happening due to prop 65 warning popover
1. Open [Vercel preview](https://react-commerce-git-fix-product-page-breadcrumb-ba-56c795-ifixit.vercel.app/products/samsung-galaxy-s21-ultra-usa-usb-c-charge-port-genuine)
2. Visit a [product page](https://react-commerce-git-fix-product-page-breadcrumb-ba-56c795-ifixit.vercel.app/products/samsung-galaxy-s21-ultra-usa-usb-c-charge-port-genuine)
3. Verify that the issue described by #834 is fixed
> Make user menu display over breadcrumb bar

- .github/workflows/format.yml
Updates the usage of `set-output` in our current workflows, since it's getting deprecated.
1. git grep for `set-output` in the code and make sure there isn't any left.
2. Make sure the `format` workflow works fine. Check the logs, and see if there are any issues.  
Connects: https://github.com/iFixit/ifixit/issues/45080
> GH Actions: Update usage of set-output

- frontend/lib/shopify-storefront-sdk/generated/sdk.ts
- frontend/lib/shopify-storefront-sdk/operations/findProduct.graphql
- frontend/models/product.ts
- frontend/templates/product/sections/ProductSection/ProductGallery.tsx
- frontend/templates/product/sections/ProductSection/ProductOptions.tsx
- frontend/templates/product/sections/ProductSection/index.tsx
closes #823 
1. Visit [Vercel preview](https://react-commerce-git-fix-product-page-gallery-alt-texts-ifixit.vercel.app/products/galaxy-a51-screen)
2. Verify that product gallery images have alt tags set to the product title, or product title + product variant title
> Improve product page gallery alt tags

- frontend/templates/product/sections/ProductSection/ProductOptions.tsx
closes #788 
Allow to click on any variant option value. 
In case the chosen options combination has no corresponding variant, tweak it to match the nearest variant.
In case there is no exact match for the currently selected options, we have to pick the nearest option set available.
In order to do so we have to compute a `distance-score`.
We take into account only variants that include the selection just performed by the user.
Among those variants we check how the other options changes wrt the previously selected values.
The first variant is generally considered the most important, the last is the least important.
So if we have to tweak the first variant value in order to find an existing variant we will add 3 to the distance score, 2 if we need to tweak the second variant and just 1 if …
> Product option switch improvements

- frontend/helpers/next-helpers.ts
We tried to noindex when user agent was not "Amazon CloudFront", but we accidentally inverted the condition. This re-inverts the condition.
qa_req 0
> Noindex when user agent does not match

- frontend/templates/product-list/sections/FilterableProductsSection/useFilteredRefinementList.tsx
It was decided that the blank facet accordion is not what we want to display, so this implements a change so the `price_range` facet should always have some item returned so the accordion is not empty. The data sorted by the facet is not useful, but this looks better and isn't too confusing IMO.
Pages like `/Parts/Panasonic_PT-DX610` should now not have an empty accordion. Any product list should only have the price range as a facet choice if there is not multiple facet ranges/options for the returned products.
Closes: #461
> Always have a facet box of some sort

- frontend/templates/product/sections/ProductSection/ProductOptions.tsx
closes #841 
2. Find a product that includes variants without associated images like [this](https://react-commerce-git-use-placeholder-for-product-op-965be3-ifixit.vercel.app/products/iphone-7-plus-screen?variant=39333810372698)
3. Verify that those variants are now showing image placeholder instead of generic product images
> Use placeholder image for product options without specific images

- frontend/lib/shopify-storefront-sdk/generated/sdk.ts
- frontend/lib/shopify-storefront-sdk/operations/findProduct.graphql
- frontend/templates/product/index.tsx
This is a redo of #847 since there were some extra changes in that commit.
QA
==
Check the a product without a "Pro Only" tag has header "X-Robots-Tag" = "noindex, nofollow", but one with a "Pro Only" tag has "noindex, follow".
Closes #825
> Noindex products with "Pro Only" tag

- frontend/templates/product/sections/ProductSection/ProductOptions.tsx
closes #844 
This PR styles unavailable product options as follows:
- unavailable select are set to `color: gray.400` 
- unavailable image-radio are set to `color: gray.400; opacity: 0.4` as per mockup
2. Verify that products with unavailable product option combinations behave as stated above (check for instance [this product](https://react-commerce-git-gray-out-unavailable-product-v-8491ad-ifixit.vercel.app/products/iphone-7-plus-screen))
> Gray out unavailable product options

- backend/src/plugins/addons/server/services/seed/media-repository.ts
fixes #867 
1. Open [Govinor instance attached to this branch](https://fix-strapi-seed-duplicate-image-id-violation.govinor.com/admin/plugins/addons)
2. Open the strapi addon interface and seed the data from `strapi.ifixit.com`
3. Open the network tab and verify that the request to the seed endpoint succeed
After this has been merged I'll be able to make main.govinor work again
> Dedup images imported by Strapi seed plugin

- frontend/templates/product-list/sections/FilterableProductsSection/RefinementSingleSelect.tsx
Basically a reopening of #617 now that the `instant-search` update is working on vercel.
When we used to swap single select refinements we would sometimes have the no-refinements selection blip on the screen for a half second (see the issue #526 for an example). This pr should solve that problem by updating the full Index UI State at once (including the refinements) and not clearing out the refinements and then setting them which was why we would have a slight blip of wrong results.
Is there a more efficient way to organize the data for the IndexUIState than what I have?
Make sure that pages don't have the blip of wrong results when switching single select refinements (note that even on master this blip disappears on switching if youve already switched between the two refinements on a …
> Have Single Select Refinement UI Change Look Smoother

- frontend/templates/product/sections/ProductSection/index.tsx
closes #870 
1. Open [Vercel preview](https://react-commerce-git-move-warranty-out-of-accordion-ifixit.vercel.app/products/samsung-galaxy-s20-plus-usa-back-glass-genuine)
2. Verify that changes requested by #870 are implemented
> Move warranty out of the accordion

- frontend/models/product.ts
- frontend/templates/product/sections/ReplacementGuidesSection/index.tsx
closes #862 
1. Open [Vercel preview](https://react-commerce-git-make-repair-guides-boxes-all-c-522826-ifixit.vercel.app/products/iphone-7-plus-screen)
2. Verify that the entire repair guide box is clickable
> Make repair guides boxes all clickable

- frontend/templates/product/index.tsx
closes #860 
1. Open [Vercel preview](https://react-commerce-git-reset-cross-sell-section-state-86e57f-ifixit.vercel.app/products/iphone-se-2020-replacement-battery)
2. Verify that issue described by #860 is fixed
> Reset cross sell section state on variant change

- backend/src/api/page/content-types/page/schema.json
- backend/src/components/page/stat-item.json
- backend/src/components/page/stats.json
- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/operations/findPage.graphql
- frontend/models/page.ts
- frontend/templates/page/index.tsx
- frontend/templates/page/sections/StatsSection.tsx
closes #872 
1. Open [Vercel preview](https://react-commerce-git-add-store-home-page-stats-section-ifixit.vercel.app/store)
2. Verify that store home page stats section is implemented as specified in #872 
This PR adds a new content type so after having merged this we need to migrate the Strapi live server
cc @sterlinghirsh
> Add store home page stats section

- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/operations/findPage.graphql
closes #272 
Part of #272 was already addressed in #857
1. Open [Vercel preview](https://react-commerce-git-improve-browse-section-categories-ifixit.vercel.app/store)
2. Verify that more than 10 categories are shown in the browse section (the limit has been set to 100)
3. Verify that the categories are sortable by changing the sort order in [Strapi](https://improve-browse-section-categories.govinor.com/admin/content-manager/collectionType/api::page.page/1?plugins[i18n][locale]=en)
> Increase browse categories fetched count

- frontend/models/product-list/index.ts
- frontend/models/product-list/types.ts
- frontend/templates/page/sections/BrowseSection.tsx
- frontend/templates/product-list/MetaTags.tsx
- frontend/templates/product-list/ProductListBreadcrumb.tsx
- frontend/templates/product-list/sections/FeaturedProductListSection.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/index.tsx
- frontend/templates/product-list/sections/ProductListSetSection.tsx
Followup from this discussion. https://github.com/iFixit/react-commerce/pull/857#discussion_r1003497990
The idea is to centralize how we link to resources, so that whenever the routing logic changes it doesn't need to be changed in several place, just in the path helper.
Verify that product list links across the app still work. Some examples:
CC @dhmacs
> Drop product list `path` field

- frontend/templates/product/hooks/useSelectedVariant.ts
closes #881 
1. Open [Vercel preview](https://react-commerce-git-respect-akeneo-order-for-defau-c7d311-ifixit.vercel.app/products/macbook-12-retina-early-2015-2017-audio-board-flex-cable)
2. Verify that Akineo order by is respected as described by #881
> Use first variant as default variant

- frontend/components/common/CompatibleDevice.tsx
- frontend/templates/product/sections/ProductSection/index.tsx
closes #891 
1. Visit [Vercel preview](https://react-commerce-git-fix-device-compatibility-image-181e12-ifixit.vercel.app/products/2-tb-ssd-hybrid-3-5-hard-drive)
2. Verify that the image aspect ratio in compatibility sections is now correct
> Device compatibility image aspect ratio

- frontend/templates/product/index.tsx
There's some state on product pages. When you click a next-link and go to a different product page, we shouldn't be preserving any of that state. Previously, we were and we ran into bugs like: https://github.com/iFixit/react-commerce/issues/860
This should avoid an entire class of bugs like that.
CC @sterlinghirsh @federicobadini
> Product Page: use high level key prop

- frontend/lib/shopify-storefront-sdk/generated/sdk.ts
- frontend/lib/shopify-storefront-sdk/operations/findProduct.graphql
- frontend/models/product.ts
- frontend/templates/product/sections/ProductSection/index.tsx
closes #889 
1. Open [Vercel preview](https://react-commerce-git-use-product-page-variant-description-ifixit.vercel.app/products/p5-pentalobe-screwdriver-retina-macbook-pro-and-air)
2. Verify that the variant description is being used
> Use variant description in product page

- frontend/templates/product/sections/ReplacementGuidesSection/index.tsx
So we can link users straight to the replacement guides section of the product page with #guides
Visit /products/iphone-11-display-assembly-adhesive#guides and make sure the page scrolls to the replacement guides section.
Closes #894
> Product Page: Add fragment for replacement guides

- frontend/templates/product/sections/ProductSection/Prop65Warning.tsx
- fix(prop65): make warning link external
- fix(ui): prevent overlapping elements
Click the prop 65 external link on the product page, and make sure it opens in a new tab.
After closing the popup, make sure the accessibility highlight ring doesn't overlap with any text.
Closes #893
> Prop 65 Warning polish

- frontend/templates/product/hooks/useIsProductForSale.ts
- frontend/templates/product/index.tsx
- frontend/templates/product/sections/ProductSection/index.tsx
closes #897 
This PR shows a "not for sale" alert on pro only products when viewed by non pro users. We're hiding also non relevant sections, such as product reviews and cross sell.
1. Open [Vercel preview](https://react-commerce-git-make-pro-only-not-for-sale-ifixit.vercel.app/products/20-lb-steel-shot-bag)
2. Visit a pro-only product (e.g. https://react-commerce-git-make-pro-only-not-for-sale-ifixit.vercel.app/products/20-lb-steel-shot-bag) as an anonymous / not-pro user
3. Verify that the add to cart section is replaced by an alert
4. Login on cominor as a pro user
5. Visit the same pro-only product page an verify that you can add the product to cart
deploy_block 🛑  on a question:
- This PR identifies pro only products by looking for a "Pro Only" product tag. Is this correct?
cc …
> Make pro only products not for sale for non pro users

- frontend/templates/product-list/sections/FeaturedProductListSection.tsx
- frontend/templates/product/sections/CrossSellSection/index.tsx
- frontend/templates/product/sections/FeaturedProductsSection/index.tsx
- packages/analytics/google/index.tsx
- packages/analytics/index.tsx
- packages/analytics/matomo/index.tsx
- packages/analytics/matomo/track-event.ts
- packages/analytics/matomo/usePaq.ts
- packages/cart-sdk/hooks/use-add-to-cart.ts
- packages/cart-sdk/hooks/use-checkout.ts
- packages/footer/components/Legal.tsx
- packages/footer/components/Navigation.tsx
- packages/footer/components/Partners.tsx
- packages/footer/components/Shared.tsx
- packages/footer/hooks/useTrackedOnClick.tsx
- packages/footer/package.json
- packages/newsletter-sdk/index.tsx
- packages/newsletter-sdk/package.json
- packages/ui/cart/drawer/CartDrawer.tsx
- packages/ui/cart/drawer/hooks/useCartDrawer.tsx
- packages/ui/package.json
- pnpm-lock.yaml
This tracks more events in Matomo/GA across Next.js, making it more similar to what we already do for iFixit/ifixit pages.
Our iFixit/ifixit event tracking implementation: https://github.com/iFixit/ifixit/blob/323d77c499fc79b1088e453da3a17442a3a4369c/carpenter-frontend/Shared/Analytics/CombinedGAMatomo.ts#L29
Search for usages of this function in iFixit/ifixit to find the analogs to the usages here.
Check for each of the types of events in the parent issue. The wording might not be exactly the same, but make sure we're at least getting the relevant information for each type of event.
You'll need the [google tag manager legacy extension](https://chrome.google.com/webstore/detail/tag-assistant-legacy-by-g/kejbdjndbnbjgmefkgdddjlbokphdefk?hl=en) to QA this.
Click "Record", refresh the page, …
> Analytics: Track more events

- frontend/templates/product/sections/ProductSection/AddToCart/index.tsx
- frontend/templates/product/sections/ServiceValuePropositionSection/index.tsx
Pictures in here are the examples from our figma mock up.
In this pull we address the spacing for the limited products. It should look like 
We also change the icons in the buy box to be solid colors again. Ignore the line dividing the two sections.
Make sure the buy box looks right and that the Value proposition at the bottom looks right too.
Note the text will be different in the mock ups than on the site and that is fine. Just make sure everything else visually hasn't broken.
Connects: #923
> Small Styling Changes for the Buy Box.

- frontend/templates/product/sections/CrossSellSection/index.tsx
- frontend/templates/product/sections/FeaturedProductsSection/index.tsx
- frontend/templates/product/sections/ReviewsSection/index.tsx
As mentioned in the issue, the following need to be capitalized.
Featured products -> Featured Products
Customer reviews -> Customer Reviews
Frequently bought together -> Frequently Bought Together
Closes #929 
CC: @erinemay
> Capitalize the section headers

- frontend/lib/shopify-storefront-sdk/index.ts
- frontend/pages/_app.tsx
closes #914 
This PR makes GraphQL call fail instead of silently return a successful result when there are GraphQL errors.
It also appropriately logs the error, as shown here:
I've set an invalid storefront token in Strapi:
1. Open [Vercel preview](https://react-commerce-git-improve-product-page-error-reporting-ifixit.vercel.app/products/iphone-7-replacement-battery)
2. Verify that product page now returns 500 error
If you want to get rid of the error you just need to log into the branch Strapi instance and insert the same storefront access token used by https://main.govinor.com/admin
> Improve error reporting for Shopify GraphQL SDK

- frontend/test/cypress/integration/product-list/collections_view_button.cy.ts
- frontend/test/cypress/integration/product-list/filters.cy.ts
- frontend/test/cypress/integration/product-list/newsletter_subscribe.cy.ts
- frontend/test/cypress/integration/product-list/parts_page_devices.cy.ts
- frontend/test/cypress/integration/product-list/parts_page_search.cy.ts
- frontend/test/cypress/integration/product-list/parts_results_view.cy.ts
- frontend/test/cypress/integration/product/add_to_cart.cy.ts
- frontend/test/cypress/integration/redirect.cy.ts
- frontend/test/cypress/support/commands.ts
- frontend/test/cypress/support/cypress.config.ts
- frontend/test/cypress/support/index.d.ts
I noticed the cart test was failing sometimes, and then rerunning it would cause it to pass.
Cypress's claim to fame is that it's less flaky than Selenium, so I used some best practices to hopefully make this test and others less flaky and faster.
The commits have documentation links in them.
qa_req 0 this only modifies tests
> Cypress: Make tests faster and less flaky

- packages/helpers/commerce-helpers.ts
- packages/ui/commerce/ProductPrice.tsx
- packages/ui/commerce/hooks/useUserPrice.tsx
This shows the lowest price available to a user on the product page.
If the discount is lower, that is shown and no pro badge is displayed.
~~If the user is a pro/employee and that price is lower, the pro price is shown. The pro badge also is shown, unless the user's discount tier is employee.~~
Each user has one and only one discount tier, determined in PHP. If their discount tier is 'pro_x', and the pro price is the lowest, the user will see the pro price and the pro badge. If their discount tier is 'employee', and the employee price is the lowest, they will see the employee price and the regular discount badge.
See the parent issues for the expected behavior.
Let's make sure to be pretty thoroughly here and test all the cases as an employee, regular user, and pro user:
- Discount is …
> Product page: Show lowest price

- frontend/components/common/CompatibleDevice.tsx
- frontend/templates/product/sections/ProductSection/index.tsx
There are pages where theres a million devices under a compatible product list. This pull truncates that list so its only 3, and makes the page cleaner.
Does the page `/products/HP-Pavilion-G4-G6-and-G7-Fan` compatibility accordion now truncate into a readable form?
Connects: #931
> Truncate Device List In Compatibility Accordion 

- frontend/templates/product/sections/ProductSection/AddToCart/index.tsx
Had some products that were impossible to buy because of this.
I don't think there's an issue.
> Add-to-cart: don't fail when there are no images

- backend/src/api/product-list/content-types/product-list/schema.json
- frontend/helpers/product-list-helpers.ts
We weren't able to save > 255 chars. Now we can.
QA
==
Try saving more than 255 chars in a filter and make sure it works.
ON DEPLOY
==
Update Strapi
Closes #970
> Convert strapi product list filter to long text

- frontend/lib/ifixit-api/international-buy-box.ts
- frontend/models/product.ts
- frontend/templates/product/hooks/useInternationalBuyBox.tsx
- frontend/templates/product/index.tsx
- frontend/templates/product/sections/CrossSellSection/index.tsx
- frontend/templates/product/sections/ProductSection/InternationalBuyBox.tsx
- frontend/templates/product/sections/ProductSection/index.tsx
- packages/ui/hooks/index.ts
This should function the same as it did on the previous product page.
* Makes an API request to ifixit.com from the browser for the given
product
* That responds with "user is geolocated in country X, here's info for a
banner for each of the variants"
* OR it responds with null
* We use a react component to render the "Buy from our X Store" banner
for the currently selected variant
* Shows a "or buy from the US Store" link that will dismiss the buy box
for 7 days
* The previous product page used a 7-day cookie, so I kept it the
same.
Note: The UI differs from the old product page bannerl slightly and we
can definitely tweak it, but I might do that in a follow-up pull unless
there are bugs.
Also, matomo events will be in a follow up pull.
QA:
* Set your preferred store via the store …
> International Stores: add buy box when appropriate

- frontend/lib/shopify-storefront-sdk/generated/sdk.ts
- frontend/lib/shopify-storefront-sdk/operations/findProduct.graphql
- frontend/lib/strapi-sdk/generated/sdk.ts
closes #956
There was a low limit on the maximum number of images to fetch per product (was set to 20).
I augmented it to the maximum possible for a single storefront api query.
2. Verify that all product variants do show their associated images
> Augment the number of fetched product images

- frontend/lib/shopify-storefront-sdk/generated/sdk.ts
- frontend/lib/shopify-storefront-sdk/operations/findProduct.graphql
- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/models/product.ts
- frontend/templates/product/sections/ProductSection/index.tsx
Closes #977
Hmm.. I wonder if there are any other product details sections that we forgot. Glancing at our shopify theme indicates that no, this was the only missing one.
> Metafields: render assembly_contents

- frontend/templates/product/sections/ProductSection/InternationalBuyBox.tsx
Keep the same event names / categories we had on the previous product page.
Closes #930
> International Buy Box: track clicks in matomo

- backend/src/api/product-list/content-types/product-list/schema.json
- frontend/lib/strapi-sdk/generated/sdk.ts
Strapi changes linked to #682 and #741 
This PR covers only the Strapi related changes and will be completed by #983 
The aim of the two PR combined is the following:
A new product list flag is now giving the possibility to show all product list children on large screen.
If enabled the list is not showing the `Show more` / `Show less` button on `> lg` screen sizes.
On smaller screen sized nothing should change.
Here is a preview of the `/Tools` page with the flag enabled:
The same page on mobile is showing the `Show more` / `Show less` button as before:
This PR introduces only the flag into Strapi 
2. Verify that Strapi includes the new flag in the `productList` model
> Add a flag to control the show all default value of product list children on large screen (backend changes)

- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/operations/getProductList.graphql
- frontend/models/product-list/index.ts
- frontend/models/product-list/types.ts
- frontend/templates/product-list/sections/ProductListChildrenSection.tsx
closes #682 
closes #741 
completes #974 
A new product list flag is now giving the possibility to show all product list children on large screen.
If enabled the list is not showing the `Show more` / `Show less` button on `> lg` screen sizes.
On smaller screen sized nothing should change.
Here is a preview of the `/Tools` page with the flag enabled:
The same page on mobile is showing the `Show more` / `Show less` button as before:
2. Verify that the implementation is coherent with the spec described above
> Add a flag to control the show all default value of product list children on large screen (frontend changes)

- frontend/templates/product-list/sections/FilterableProductsSection/FacetFilter.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/FacetsAccordion.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/FacetsDrawer.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/RefinementMultiSelect.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/RefinementSingleSelect.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/ShowMoreButton.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/useFacets.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/useFilteredRefinementList.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/useSortBy.ts
Renders all the item type facet links for SEO reasons, and visually hides the extra ones until the "show more" button is clicked.
Visit /Parts, and verify the item type facets aren't links and when you inspect theres only 10.
Visit /Parts/iPhone and verify that they are links and that all of them show up when inspected, but only 10 are visually shown.
Make sure the item type facets still work normally. Make sure that the show more/ show less button still works normally.
Thanks!
Closes #819
> Collections: Render all item type facet links

- packages/ui/misc/IfixitImage.tsx
Various images on our site are much lower res than we'd like. This is likely an issue with the product urls.
It turns out it was an issue with our `isGuideImage()` function, as the regex wasn't catching `.guide-image` urls due to looking for two `/` back to back. This removes the extra `/` from the regex, and also makes our `isCartImage()` more like `isGuideImage`.
Are the images on `/products/macbook-pro-13-retina-function-keys-late-2016-2017-battery` for Replacement Guides now higher res? This page in particular works because weve replaced the proper metafield on `ifixit-test` with production data (see replacement guides metafield https://ifixit-test.myshopify.com/admin/products/6556174286938). 
Also do the cart images still work after the slight changes? Production cartimage url …
> Fix isGuideImage() Regex

- frontend/cypress.config.ts
- frontend/lib/ifixit-api/international-buy-box.ts
- frontend/test/cypress/integration/product/add_to_cart.cy.ts
- frontend/test/cypress/support/commands.ts
- frontend/test/cypress/support/cypress.config.ts
- frontend/test/cypress/support/index.d.ts
closes #987 
- Drop unused Cypress config (and moved `experimentalSessionAndOrigin` to the actual config file)
- Add a commands for Cypress compatible loops
- Fixed issue described by #987 
- Cleaned up add to cart tests
I think it's not necessary, as this changes only affects CI
> Mock buybox api and improve tests

- frontend/components/common/ProductCard.tsx
- frontend/templates/product-list/sections/FeaturedProductListSection.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/ProductGrid.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/ProductList.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/useProductSearchHitPricing.ts
- frontend/test/jest/tests/ProductListItem.test.tsx
- frontend/test/jest/tests/__snapshots__/ProductListItem.test.tsx.snap
- packages/ui/commerce/ProductPrice.tsx
Reuses the `ProductPrice` component in our collections to consistently render product prices. Fixes a bug where trailing zeros weren't rendered in discounted prices.
Visit collection pages with and without discounts, and make sure prices are rendered correctly and the UI looks ok.
Also do this as a pro user.
Closes #886
> Product List Items: Fix decimal display

- frontend/helpers/path-helpers.ts
- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/models/product-list/index.ts
- frontend/models/product-list/types.ts
- frontend/templates/product-list/ProductListView.tsx
- frontend/templates/product-list/index.tsx
Apparently people want to be able to go back to `/Store` from the product-list pages. This makes sure that all `ancestor` lists for strapi productlists have "Home" as an ancestor by inserting them into all ancestor lists.
I wasn't able to fix out a switch statement to be as clean as i wanted (the `throw Error` line) but Im not sure if its supposed to as it can type-wise reach that case still.
Do all product-list breadcrumb navbars seem correctly? The only new functionality should be that `/Parts` and `/Tools` have breadcrumbs now and that `/Tools/<category>` should have the desktop view breadcrumbs now.
Closes: #884
> Product Lists: Add Home to all Breadcrumbs

- frontend/templates/product-list/sections/FilterableProductsSection/useProductSearchHitPricing.ts
Shows the normal product price to pro users if it is less than the pro price.
When a pro user is logged in on a collection page and their pro discount is less than (=final pro price is greater than) the price for regular users, they should see the price that regular users see. The flair color should be red in this case.
Check that the displayed price corresponds to the price they see on the product page and the price they get at checkout. 
CC @erinemay 
Closes #992
> Collections: Always show smallest price to pros

- frontend/components/common/InstantSearchProvider.tsx
Fixes a bug where query params on collection pages that weren't used by Algolia were stripped from the url.
This keeps all query params in the url, even if they aren't used in Algolia search.
This means we don't have to manually forward the `_vercel_no_cache` param anymore.
I also noticed that we can pass an option to `qs` to ignore the leading '?' in the query, instead of slicing it out ourselves.
https://github.com/ljharb/qs
- Make sure filtering on collections pages still works.
- Make sure when visiting a collections page from an external link, all query parameters are persisted in the url.
- Specifically, make sure `_vercel_no_cache=1` still works and doesn't get stripped.
You'll notice that www.ifixit.com/Parts?dogs=cats the `dogs=cats` gets stripped. On this branch, it shouldn't be …
> Collections: Don't strip query params

- packages/analytics/package.json
This is for compatibility with the `ifixit` monorepo. Rush expects each package we depend on to have these scripts.
See https://github.com/iFixit/react-commerce/pull/633 for the last time we did this.
Connects: 
https://github.com/iFixit/ifixit/pull/45326
https://github.com/ifixit/ifixit/issues/44933
qa_req 0
> Analytics: Add empty build/clean scripts

- frontend/helpers/product-list-helpers.ts
.replaceAll() isn't available on older browsers (Chrome 84 and below). Quite a fair number of users visit our site on older browsers (like web-TVs?) and report errors on this not being a thing.
Closes #1003
CC @sterlinghirsh
> String.replaceAll(): Use more available .replace()

- packages/cart-sdk/hooks/use-checkout.ts
See the issue for a description of the problem. In short, if you make a purchase, then try to make another one, it fails to create the checkout.
We have code that will try to use the shopify checkoutId from
LocalStorage. This code also seems to deal with the error state of that
checkoutId having already been completed or just plain invalid.
The code is written to the spec of the API docs and appears to do that
correctly. The API however, doesn't behave as the docs say.
Specifically, when these errors are encountered, the error messages come
back out of band:
Expected response:
{
data: {
checkoutLineItemsReplace: {
checkout: { ... },
userErrors: [{code: "ALREADY_COMPLETED"}]
}
}
Actual response:
{
data: {
checkoutLineItemsReplace: null
},
errors: [
{
"message":"Checkout is already …
> Making two purchases: allow it!

- frontend/components/common/CompatibleDevice.tsx
- frontend/templates/product/sections/ProductSection/index.tsx
We weren't rendering the compatibility link when we had devices with truncated models lists, leading to a confusing UI. Now if we have to truncate the model lists, we will always show the compatibility links so that people will be able to click and see all of the models.
Is there a better way to make this check?
Make sure that a device with more than 3 variants has the link, that a device with more than 4 models has the link, that a device with both has the link, and a device with neither doesn't have the link. 
Closes: #931
> Improve Compatibility Drawer in Product Page: Compatibility Link Is Used More Reasonably 

- frontend/lib/shopify-storefront-sdk/index.ts
This will report the query and variables in Sentry when we get a non-200 response from Shopify's api.
This is the same pattern we follow in frontend/lib/strapi-sdk/index.ts, for reference.
Since we can't make https://store.cominor.com/api/2022-10/graphql.json 500 easily, I think we should just merge this and as the sentry events roll in, we can check and see that they have all the data we want.
qa_req 0
Closes #1001
> Shopify Storefront SDK: use `sentryFetch()`

- frontend/layouts/default/DefaultLayout/Footer.tsx
- packages/footer/hooks/TrackingContext.ts
- packages/footer/hooks/useTrackedOnClick.tsx
- packages/footer/index.tsx
- packages/footer/package.json
- pnpm-lock.yaml
We don't want to use the same click tracking function in every location we use the footer. In particular, we don't want to use `@ifixit/analytics` from anywhere but this repo. This pull switches the footer component to fetch its click tracking function from a context, which enables us to swap it out per-use. It also adds that new context around the use of the `Footer` component in this repo, so we continue to use the same click tracking function within this repo.
Please confirm that the footer click tracking seems to still be working as described in https://github.com/iFixit/react-commerce/issues/855 (only the footer parts; the rest should not have been affected).
CC @jyee27 @jordycosta
> Footer: Move click tracking to context

- backend/src/components/store/shopify-settings.json
- frontend/lib/strapi-sdk/generated/sdk.ts
This is a first step to address #1017. 
Changes to the frontend will be done in a separate PR
1. Open [Govinor instance](https://add-delegate-access-token-field.govinor.com/admin/content-manager/collectionType/api::store.store/4)
2. Verify that delegate access token field is present
Production instance of Strapi needs to be redeployed
cc @danielbeardsley @sterlinghirsh
> Add delegate access token field in Strapi

- frontend/templates/product/hooks/useSelectedVariant.ts
This reverts commit 262cc4af7157a10a61247533e68cd6c66a977eb8.
Specifically, after ordering by orderby, choose the first in-stock variant to show as the default instead of always showing the default even if it's out of stock.
Closes #1000
CC @ifixitmaxb @jeffsnyder
> Revert "refactor(product page):  Use first variant as default variant"

- frontend/sentry.client.config.ts
We've tried to get to the bottom of these errors in sentry and can't.
They certainly tend to occur more on some devices that others, but we still can't figure out why. We also have no reports of actual issues from users, just error records in Sentry.
So, let's stop seeing this noise and move on with our lives.
Closes #765 
Closes #979 
qa_req 0
> Sentry: Ignore some specific errors

- frontend/components/common/AppProviders.tsx
- frontend/components/common/InstantSearchProvider.tsx
- frontend/helpers/next-helpers.ts
- frontend/helpers/path-helpers.ts
- frontend/models/posts.ts
- frontend/models/product-list/index.ts
- frontend/templates/page/index.tsx
- frontend/templates/page/sections/BrowseSection.tsx
- frontend/templates/product-list/index.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/index.tsx
- frontend/templates/product-list/sections/RelatedPostsSection/index.tsx
- frontend/templates/product/index.tsx
When we're proxying our Next app on cominor, use relative urls for external links and api requests. This will prevent CORS errors in dev, and keep developers on the same domain when clicking on links.
The only place we are still using a hard coded origin is in frontend/pages/_document.tsx, since I don't think we have access to the request context in that file.
If the app is being visited at *.vercel.app or ifixit.com, then the IFIXIT_ORIGIN value will be used as before, so there should be no change in behavior.
I'm not sure how to reproduce the original problem with localhost or the previews.
However, let's be sure we're still using `IFIXIT_ORIGIN` on *.vercel.app.
Closes #1022
> CORS: Use relative urls in dev

- frontend/helpers/next-helpers.ts
We tried to get around CORS errors in https://github.com/iFixit/react-commerce/pull/1025 by using the detected host for API requests when the app is proxied on cominor.
However, in https://github.com/iFixit/ifixit/pull/45577 it seems like the detected host isn't being used.
This logs the relevant headers so we can debug the problem.
qa_req 0
CC @danielbeardsley
> debug: log forwarded host headers

- README.md
- frontend/lib/shopify-storefront-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/templates/product-list/index.tsx
- package.json
- packages/bot/cli.ts
- packages/bot/commands/index.ts
- packages/bot/commands/shop/create.ts
- packages/bot/commands/shop/create/delegate-token.ts
- packages/bot/commands/shopify.ts
- packages/bot/package.json
- packages/bot/tsconfig.json
- packages/bot/utils/misc.ts
- packages/bot/utils/shopify.ts
- pnpm-lock.yaml
This is a second step to address #1017 
The generation of a delegate token is a little bit cumbersome since Shopify doesn't provide any UI to get a delegate token, we need to generate it via API.
To make this convenient, I'm introducing a bot package that will host every little automated script that we might need down the road.
1. Clone the project and follow the readme setup instructions
2. Run the following command:
```console
pnpm bot shopify create delegate-token
```
Follow the instructions and verify that you can successfully get a delegate token
🚨 **Please note that the delegate token should be considered a secret, and thus should not be shared, nor posted on Github.**
> Add automation bot

- frontend/templates/product/hooks/useSwiper.ts
- frontend/templates/product/sections/ProductSection/ProductGallery.tsx
- frontend/templates/product/sections/ProductSection/index.tsx
closes #861 
As proposed in [comment](https://github.com/ifixit/react-commerce/issues/861#issuecomment-1289278944) this PR helps the user in understanding that there are more thumbnails available.
1. Visit [Vercel preview](https://react-commerce-git-improvements-on-product-galler-0c72c4-ifixit.vercel.app/products/fix-the-world-t-shirt)
2. Verify that the currently active image is always positioned as the leftmost visible in the thumbnails carousel
3. Only exception is when the carousel cannot scroll anymore to the right
> Proposal active image always first

- packages/bot/cli.ts
Just a quick fix to make the bot compatible with linux environments.
@sterlinghirsh already QA this on his wls machine so I think we don't need QA
qa_req 0
> Replace shebang to add linux compatibility

- frontend/templates/product/sections/ProductSection/index.tsx
- frontend/test/cypress/integration/product/pro_user.cy.ts
- frontend/test/cypress/integration/product/product_page.cy.ts
- frontend/test/cypress/support/commands.ts
- frontend/test/cypress/support/index.d.ts
We recently added [pro user product page test](https://github.com/iFixit/react-commerce/pull/1049) which compares the product prices.
This pull adds additional assertions to check product title, sku and price. Added assertions 
in `pro_user` test since we already visit product page (instead of creating a new one). 
Also refactored `interceptLogin()` command to accept additional/optional params, 
instead of only passing the argument for `discount_tier`.
Make sure the Cypress tests are passing in CI. 
cc: @mlahargou 
Closes: https://github.com/iFixit/react-commerce/issues/1043
> Tests: Check for visible product title, price and sku

- frontend/test/cypress/integration/product/fix_kit.cy.ts
Added test for `Fix Kit`/`Part Only` product selection which tests the following:
- If `Fix kit` is selected, verifies that the `kit contents` section is displayed.
- If `Part only` is selected/clicked, verifies that the `Assembly contents` section is displayed.
- Verifies that the product images and skus change when switching between `Fix kit` / `Part Only`.
Note: didn't test for the product price change since they could potentially be the same price. Sometimes, the fix kit is cheaper than the part only, for example: [when the fix kit is on sale](https://react-commerce.vercel.app/products/iphone-6s-plus-replacement-battery).
Make sure the Cypress tests are passing in CI.
Closes #1045
> Tests: Add tests for Fix kit / Part Only selection

- frontend/templates/product-list/sections/FilterableProductsSection/CurrentRefinements.tsx
Closes #1034 
Previously, when removing facet filters using the pill's `x` button, the page number would not reset to zero. This pulls fixes that by setting the page to `NaN` when a facet filter is removed using the `x` button.
<details>
</details>
QA
--
1. Visit the preview for this pull
2. Add filters to narrow your search
3. Go to any page other than the first page
4. Remove the filter by using the `X` button next to the filter.
5. Observe that the page is now on the first page
6. Check that the same behavior is on Tools
> Reset page to zero when deselecting facets

- .github/workflows/jest.yml
- package.json
This has been extracted from #975 
There are a few issues that break tests with updated dependencies, such as a version of the pnpm action that does not support pnpm v7 and a wrong command to install dependencies.
qa_req 0
> Fix Jest CI

- frontend/components/common/InstantSearchProvider.tsx
- frontend/helpers/product-list-helpers.ts
Prevents 500s when the menu param is malformed.
Multiselect (aka refinement) facets use array indeces in the query params (like `[facet_tags.Price Range][0]=10-20`);
Single selects don't have that (e.g. `[worksin]=Device Name`).
However, if a user visits a malformed url that uses array indices on a menu facet, and we tell Algolia that the menu has an array of values, Algolia's code will throw.
The solution: detect array indices on these facets and ignore them before sending the state object to Algolia.
Visit /Parts?filter[facet_tags.Item Type][0]=Batteries, and make sure the item type filter is set correctly and that the page doesn't 500, and the url is quickly reverted to /Parts?filter[facet_tags.Item Type]=Batteries
Also make sure that any invalid filter params are ignored. You'll have …
> Hotfix: Handle malformed collection menu params

- frontend/templates/product/sections/ProductSection/ProductOptions.tsx
- frontend/test/cypress/integration/product/product_option.cy.ts
- packages/ui/cart/drawer/CartDrawer.tsx
Added a new test for a product with different variants.
It visits a product page, adds two product options/variants to the cart.
Then opens up the cart-drawer(on the right side), and checks that the cart
contains the price, and SKU for each of the added product variants. 
Make sure the Cypress tests are passing in CI.
Closes #1044
> Tests: Add test for a product with different variants

- frontend/templates/product/sections/ProductSection/index.tsx
closes #954 
1. Open [Vercel preview](https://react-commerce-git-increase-product-page-alert-pa-bc6d9e-ifixit.vercel.app/products/iphone-xr-screen)
2. Verify that #954 is fixed
> Increase product page alert paragraph spacing

- frontend/templates/product-list/sections/ProductListChildrenSection.tsx
- frontend/test/cypress/integration/product-list/parts_page_devices.cy.ts
extracted from #975 
closes #1064
This PR fixes a test that becomes flaky once we upgrade to React 18
qa_req 0
> Fix flaky Cypress test

- frontend/config/env.ts
- frontend/templates/product/components/PixelPing.tsx
- frontend/templates/product/index.tsx
Our old product page used a tracking pixel from our internal pixel-ping service. This only counts views in aggregate, no PII is kept or cookies set. this is the same service and stats used on other doc types.
We forgot to include this when re-creating the product page because there's no visible component.
Closes #1060
> View Stats Tracking: add view count pixel

- frontend/lib/shopify-storefront-sdk/generated/sdk.ts
- frontend/lib/shopify-storefront-sdk/operations/findProduct.graphql
- frontend/models/product.ts
- frontend/templates/product/MetaTags.tsx
Adds hreflangs to all other stores (including the US store) to the `<head>`, like we do on the shopify theme stores.
Make sure we get the hreflangs in the head for products that are enabled on other stores. Verify that the urls are correctly formatted by clicking on one of them.
Connects #976
> Add `hreflang`s to product page

- frontend/templates/product/index.tsx
Cache product pages for a minute and set "stale-while-revalidate" to 10 minutes. Product page data *doesn't* change much, so caching is fairly sensible. Let's start with 1/10 mins and see how we feel.
> Product pages: cache them

- frontend/templates/product/sections/ProductSection/ProductOptions.tsx
Product Thumbnails: use ResponsiveImage.
Previously, this ended up using <img> tags with urls of the 2000px
images even though the visible size was only 70px.
ResponsiveImage uses a srcset and results in the browser choosing the
correct size.
Co-author @danielcliu-ifixit 
Connect #1015
> Product images: use srcset for thumbnails

- frontend/models/product.ts
- frontend/templates/product/MetaTags.tsx
We're transitioning the product enabled_domains metafield to support multiple locales per store. Prefer the `locales` field if available, otherwise fallback to the `locale` field.
Make sure we still get the same hreflang link tags in the `<head>` as on main.
Connects https://github.com/iFixit/ifixit/issues/45707
> Product Page: Transition to multiple hreflang locales

- packages/footer/components/Navigation.tsx
- packages/footer/components/StoreMenu.tsx
- packages/footer/hooks/useTrackedOnClick.tsx
This pull updates the current tracking function we already use for the footer to match the spec from [the spreadsheet](https://docs.google.com/spreadsheets/d/16Xas1pHf_K7FmfOX3yX2mYgeYr2DIENr8cyQp19FZkA/edit?pli=1#gid=1839136207&fvid=1617862179).
We already had this tracking mechanism in place, so this just modifies what we actually send in the event action as well as adds tracking to the store change button.
Check that the event shows up in matomo or GA for events 125-143 from [the spreadsheet](https://docs.google.com/spreadsheets/d/16Xas1pHf_K7FmfOX3yX2mYgeYr2DIENr8cyQp19FZkA/edit?pli=1#gid=1839136207&fvid=1617862179).
Closes https://github.com/iFixit/ifixit/issues/44680 (and lines 125-143 from the spreadsheet)
> Matomo P3: Update Footer Tracking

- packages/newsletter-sdk/index.tsx
- packages/newsletter-sdk/package.json
- pnpm-lock.yaml
closes #949 
The only instance I could find where iFixit client was not used is the newsletter sdk
I don't think is necessary since newsletter is already covered by integration tests
qa_req 0
> Use iFixit client for every iFixit related request

- frontend/models/product.ts
- frontend/templates/product/index.tsx
- packages/icons/flags/Flag.tsx
Makes the links in the store selector product links for stores that the current product is enabled in. If the product is disable/doesn't exist, then we link to the homepage of the store as before.
I chose to augment the `stores` prop instead of introduce a new prop. Given that the `stores` prop could in theory be used for components besides the store selector, I'm open to adding a new prop like `storeSelectorUrlOverrides` (or any other implementation you can think of).
Pick a product page. Make sure the `product.enabled_domains` metafield has a value with store codes on ifixit test. Scroll to the footer, open the store selector, and verify that the links point directly to the product page of other stores (if the product is enabled on that store) or to the homepage of the store otherwise. …
> Add store selector product links

- frontend/templates/product/sections/ProductSection/index.tsx
closes #925 
1. Open [Vercel preview](https://react-commerce-git-fix-product-page-wiki-text-link-style-ifixit.vercel.app/products/iphone-6s-plus-replacement-battery)
2. Visit a [product](https://react-commerce-git-fix-product-page-wiki-text-link-style-ifixit.vercel.app/products/iphone-6s-plus-replacement-battery) that has links in its content kit
3. Verify that links are visible
> Fix wiki text links style

- frontend/templates/product-list/ProductListView.tsx
- frontend/templates/product-list/SecondaryNavigation.tsx
fixes #1080 
1. Open [Vercel preview](https://react-commerce-git-remove-extra-empty-navbar-ifixit.vercel.app/)
2. Verify that the issue described by #1080 is fixed
> Remove second empty navbar

- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/operations/getProductList.graphql
- frontend/models/product-list/index.ts
- frontend/models/product-list/types.ts
- frontend/templates/product-list/MetaTags.tsx
* Turn on the `forceNoindex` toggle for a product list in productlist-force-noindex.govinor.com/admin
* Verify that the productlist has the `<meta name="robots" content="noindex,nofollow" />` tag
Closes #705
> Productlist: Use strapi `forceNoindex` toggle

- frontend/layouts/default/DefaultLayout/Footer.tsx
- packages/footer/components/Shared.tsx
- packages/footer/hooks/useTrackedOnClick.tsx
This adds tracking for the "Help translate" link in the footer. 
Make sure that clicking on the `Help translate` link in the homepage footer _and_ the store footer tracks in matomo according to [the spreadsheet ](https://docs.google.com/spreadsheets/d/16Xas1pHf_K7FmfOX3yX2mYgeYr2DIENr8cyQp19FZkA/edit#gid=1839136207&fvid=415444935)line 123
Closes spreadsheet line 123.
Connects to https://github.com/iFixit/ifixit/issues/44540
> Matomo: track "Help translate"

- frontend/templates/product/MetaTags.tsx
Fixes a bug where only one locale per store was showing up in the hreflangs.
Make sure all the different locales are showing up for the FR and DE stores in the hreflang tags in teh `<head>`. (list is [here](https://github.com/iFixit/react-commerce/pull/1068#issuecomment-1332965850))
Connects #1068
> Make hreflang key unique

- frontend/models/product.ts
- frontend/templates/product/MetaTags.tsx
The `locale` field was deprecated in favor of `locales`. We supported both in a transition period, and now we only want to use the plural.
Connects https://github.com/iFixit/ifixit/pull/45709
> Drop deprecated metafield `locale` for hreflangs

- frontend/templates/product/sections/CrossSellSection/index.tsx
Makes the cross sell product cards links. Clicking the checkbox will select/deselect the cross sell product.
Note that `onKeyUp` was changed to `onKeyDown`. Without this change, clicking "Enter" with the checkbox focused caused the link to be followed (and the checkbox to be toggled). The expected behavior is to toggle the checkbox and not follow the link, and using `onKeyDown` achieves that.
Next link docs: https://nextjs.org/docs/api-reference/next/link#if-the-child-is-a-custom-component-that-wraps-an-a-tag
Easiest to view with whitespace hidden.
Make sure the cards are now links, and that you are still able to toggle the selections as before using the checkbox.
Closes #924
> Cross Sell: Cards should be links

- frontend/lib/shopify-storefront-sdk/generated/sdk.ts
- frontend/lib/shopify-storefront-sdk/operations/findProduct.graphql
- frontend/models/product.ts
- frontend/templates/product/index.tsx
Redirects requests for product pages that have a `redirect_url` metafield set, along with any search params that were on the url.
The issue spec'd just forwarding the utm params. We could match any params that start with `utm_` and only forward those, I wasn't sure what was best here.
Set the redirect url product metafield on shopify for a product. Visit it's product page on the react-commerce preview, and make sure that you're redirected to the proper url. Also make sure utm parameters are forwarded to the redirect url.
Closes #864
> Use `redirect_url` product metafield

- frontend/lib/shopify-storefront-sdk/generated/sdk.ts
- frontend/lib/shopify-storefront-sdk/operations/findProduct.graphql
- frontend/models/product.ts
- frontend/templates/product/index.tsx
Pushed this one out a little too early.
Reverts iFixit/react-commerce#1099
> Revert "Use `redirect_url` product metafield"

- frontend/templates/product-list/sections/FilterableProductsSection/useProductSearchHitPricing.ts
connects #105 
connects #1015
Curly braces import implies including the whole lib (see [here](https://www.blazemeter.com/blog/import-lodash-libraries))
> Avoid including the whole lodash

- packages/cart-sdk/hooks/use-checkout.ts
- packages/sentry/index.tsx
- packages/shopify-storefront-client/index.tsx
Handles an undocumented top level `errors` key that is sometimes returned by the Shopify API. When this is the case, the field of interest (e.g. `checkoutCreate`) can be null.
Example event reported by this new code: https://sentry.io/share/issue/15b33ce210ca49e0bd64328b4994e15d/
Make sure you can still make two purchases as described in https://github.com/iFixit/react-commerce/issues/1002  and fixed by https://github.com/iFixit/react-commerce/pull/1011
Closes #1014
> Handle top level shopify graphql api errors

- .husky/pre-commit
- .husky/pre-push
Auto formatting is not setup to work on just changed files and so takes way too long. Typechecking is already done in CI and currently takes 30 - 60s. This is quite annoying and hampers productivity and interrupts development. I find myself constantly using `--no-verify` anyway.
We can re-add them if we improve their performance.
Connect #1026
> Git hooks: drop format and type-check

- frontend/components/common/AppProviders.tsx
- frontend/templates/product/sections/CrossSellSection/index.tsx
- Hides the cross sell section when the main product is OOS.
- Stringifies mutation data that is sent to Sentry when errors happen.
Out of stock variants should have the cross sell section hidden.
Closes #1124
> Hide Cross Sell when current variant is sold out

- frontend/test/jest/__mocks__/products.ts
Similar to https://github.com/iFixit/react-commerce/pull/1123, this pull which added new mocked products was using the prior type definition of Product. 
qa_req 0 CI should pass now
**cc:** @davidrans
> Fix: Updated newly added mocked product types

- frontend/next.config.js
- packages/ui/misc/ResponsiveImage/iFixitUtils.ts
closes #1039 
2. Verify that images are now generated according to the default imageSizes + deviceSizes rounded up to the nearest available format offered by the ifixit api
> Revert image widths in guideImageSizeMap

- frontend/package.json
- frontend/templates/page/sections/BrowseSection.tsx
- packages/footer/package.json
- packages/ui/package.json
- pnpm-lock.yaml
This removes the following packages, in favor of FontAweseome:
- `@chakra-ui/icons`: last usage removed by 7e9d2c45f4d104157f7d06bd634f156d24ea5d7f
- `react-icons`: last usage removed in this pull
> Icons: remove unused packages

- frontend/components/product-list/ProductListCard.tsx
These were set to be responsive before, but they're actually used at 80x60 all the time.
Testing on http://localhost:3000/Parts/iPhone, I saw an 80% improvement in image bytes transferred. Most of the images on this page were child productlist images coming from the iFixit API. On the /Parts page, where images were mostly from Strapi, we didn't see much change, as expected.
Before
After
A few KB of HTML savings too.
Before:
After:
Closes #1131
> Add fixed size for child productlist images

- packages/ui/cart/drawer/CartLineItem.tsx
It used to be a responsive image, and due to the default `sizes` attr being 100vw, it was downloading a huge (sometimes 2000px) image that would display at 62x62px.
Before:
After:
Probably won't matter to most of us on gigabit connections, but for mobile users it's nice to be a little more efficient.
Connects #1136
> Fix minicart image size

- packages/ui/theme/foundations/breakpoints.ts
The docs say chakra breakpoints should all be the same units because the JS must sort these by their literal values.
Thankfully, this didn't break for us, but if any other breakpoint was not in PX (besides base), it completely borks `useBreakpoint()`
See this codepen:
https://codesandbox.io/s/sparkling-wildflower-o2ww7z?file=/src/index.tsx
qa_req 0 -- These are equivalent values and this just works around what is effectively a bug in chakra.
CC @jarstelfox
> breakpoints: use consistent units

- frontend/tests/jest/tests/ProductSection.test.tsx
Added the following tests for product specifications:
- Checks if the provided product specification renders.
- Checks if the specification button/accordion is hidden if we provide `null` to product specifications.
closes #1144
> Product Page: Add Product Specifications Tests

- frontend/tests/jest/tests/ProductSection.test.tsx
Added the following tests for product shipping restrictions:
- Checks if the shipping restriction renders and the restriction info is in the document.
- Checks if the shipping restriction does not render for a product with no shipping restrictions.
closes #1142
> Product Page: Add shipping restrictions test

- frontend/package.json
- pnpm-lock.yaml
qa_req 0
The frontend package is not using the Prettier version of the project root `package.json`. This can cause mismatching when formatting with VSCode and the cli, because they can pick up different versions.
> Upgrade frontend prettier version to v2.7.1

- frontend/templates/product/sections/ProductSection/index.tsx
- frontend/tests/jest/tests/ProductSection.test.tsx
- frontend/tests/jest/utils.tsx
Added the following tests for checking the warranty:
- Checks for the warranty text and its link for `limited`/`as-is` warranty products.
- Checks for the warranty text and its link for the `lifetime` warranty product. 
Also checks if the quality guarantee icon is visible (we display the quality guarantee icon for products with lifetime warranty).
Passing CI is enough. (qa_req 0)
closes #1145
> Product Page: Add Product Warranty Tests

- .github/workflows/nextjs_bundle_analysis.yml
We have working_directory: frontend/ as a default for all the steps but I think that doesn't apply for these tasks that take a "path" input. It hopefully *does* apply for all the steps with a "run" input.
This has meant that the cache of the .next directory is empty and the bundle from main isn't being uploaded.
> Bundle Analysis: add frontend/ for each step that takes a path

- frontend/tests/jest/tests/CompatibleDevice.test.tsx
- frontend/tests/jest/tests/__snapshots__/CompatibleDevice.test.tsx.snap
This is a basic test to ensure that the base component renders correctly as well as the component renders correctly when the number of variants exceeds the limit. In that case, the component should display the `And 3 other models...` text. In this case, I wanted to generalize it a bit more so I only included `other models...` in the query text.
QA:
--
Tests should pass.
Connects: https://github.com/iFixit/react-commerce/issues/1143
> CompatibleDevice: Add tests

- frontend/templates/product/sections/ProductSection/index.tsx
- frontend/tests/jest/tests/ProductSection.test.tsx
This is the final part in testing the compatibility section. This just loads the `ProductSection` for a product and ensures the compatibility section is shown and is hidden when expected. It also asserts that clicking the dropdown displays the inner accordion element.
QA:
-- 
CI passing should be good enough here.
Closes: #1143 
cc @batbattur @ardelato
> Add tests for product compatibility section

- frontend/tests/cypress/integration/product-list/parts_page_devices.cy.ts
- frontend/tests/jest/tests/ProductSection.test.tsx
We display a prop 65 warning on all battery products. This adds some basic tests for when the warning should/shouldn't show up.
Also, test the basic functionality of the "more details" popup that displays on click.
QA:
--
The tetss should run and pass.
Connects: #1165
> Prop 65 warning: Add tests

- frontend/components/common/CompatibleDevice.tsx
- frontend/models/product.ts
- frontend/templates/product/sections/ProductSection/CompatibleDevices.tsx
- frontend/tests/jest/tests/CompatibleDevice.test.tsx
- frontend/tests/jest/tests/__snapshots__/CompatibleDevice.test.tsx.snap
- Fixes a bug where the compatibility section was hidden if any device had a `null` variant.
- Memoizes variant calculations in the compatibility section.
- Prevents empty variant `<p>` tags from being rendered in the compatibility section.
- Properly uses the plural for the hidden variant indicator in the compatibility section.
@sterlinghirsh 
Closes #1182
> Don't reject null compatibility variants

- frontend/tests/playwright/utils.ts
We forgot to add this param when we switched this to a Playwright test. It's needed so we can set pro user discounts.
QA:
--
The test should pass.
`pnpm playwright test --project=chromium --headed pro_user` 
Closes: https://github.com/ifixit/react-commerce/issues/1181
cc @ardelato
> Playwright: Fix broken pro_user test

- frontend/tests/jest/tests/ProductReplacementGuide.test.tsx
Added the following tests for checking the replacement guides section:
1. Checks if the replacement guide section renders when the product has associated guides.
- Checks if the guide title and guide link are present.
2. Checks if the replacement guide section does not render when the product has no associated guides.
Passing CI is enough. (qa_req 0)
closes #1166
> Product Page: Test Replacement Guides Section

- frontend/tests/playwright/product-list/filters.spec.ts
- frontend/tests/playwright/product-list/parts_page_search.spec.ts
- frontend/tests/playwright/utils.ts
This came up in https://github.com/iFixit/react-commerce/pull/1180#discussion_r1055888310.
We have this piece of code duplicated across some of our current tests, let's just extract it to a utils file and reuse it.
While extracting it, I also simplified the matching logic a bit.
Connects: https://github.com/iFixit/react-commerce/issues/1111
> Playwright Tests: Extract Search Query Response to Utils

- frontend/templates/product/server.tsx
closes #1174 
The product template was modifying in place the stores variable.
Since that variable was potentially preserved, this polluted the cache and led to unexpected results.
2. Verify that the store selector links are now pointing to the correct destination
> Fix store selector links

- frontend/templates/product-list/sections/FilterableProductsSection/facets/useFacets.tsx
closes #533
closes #1190 
1. Visit Vercel Preview
2. Verify that the price-range filter is not showing anymore in /Parts collections but is still visible in /Tools collections
> Remove price facet from /Parts collections

- frontend/templates/product/MetaTags.tsx
closes #1198 
2. Analyze a random product page via [rich result tester](https://search.google.com/test/rich-results)
3. Verify that the leaf element is not referencing any url anymore as [in the documentation](https://developers.google.com/search/docs/appearance/structured-data/breadcrumb#json-ld)
4. If the url is not crawlable it is possible to copy the source code of the page in the tool
> Avoid referencing /# for the leaf element

- frontend/templates/product-list/sections/FilterableProductsSection/facets/accordion/FacetAccordionItem.tsx
closes #155 
2. Verify that newly shown facet are always scrolled into the viewport
> Manually scroll to newly shown facet details

- frontend/templates/product/sections/ReviewsSection/index.tsx
- frontend/tests/jest/__mocks__/products.ts
closes #1140 
Show review section only if `reviewsData.average >= 4 || reviewsData.count > 10`
2. Verify that the reviews section is hidden for products that do not satisfy the condition above
> Apply review hiding logic to ReviewsSection

- frontend/templates/product/sections/ReviewsSection/index.tsx
- frontend/tests/playwright/product/product_reviews.spec.ts
Added a test for a product with multiple reviews.
The test compares the number of reviews before hitting the `see more reviews` button and after. 
Also expects that all of the reviews are visible after clicking the button.
Passing CI is enough (qa_req 0).
closes: #1201 Note: currently, we don't have the `filter by` or `sort by` buttons implemented for the reviews
> Product Page: Add reviews test

- frontend/templates/product/MetaTags.tsx
closes #1140
This PR removes review data from the ld+json structured data unless `product.rating.value >= 4 || product.reviewsCount > 10`.
1. Visit Vercel preview ([here](https://react-commerce-prod-git-review-hiding-logic-remov-c801ba-ifixit.vercel.app/products/anti-clamp) is a sample product with hidden reviews)
2. Verify that the review section in the product ld+json is not present anymore if `product.rating.value < 4 && product.reviewsCount <= 10`
> Hide aggregate rating and reviewCount if needed

- .github/workflows/lint.yml
- frontend/.eslintrc.json
- frontend/package.json
- frontend/tests/cypress/integration/product/product_option.cy.ts
- frontend/tests/cypress/integration/product/product_page.cy.ts
- frontend/tests/jest/tests/CompatibleDevice.test.tsx
- frontend/tests/playwright/product/product_page.spec.ts
- pnpm-lock.yaml
1. Installed `eslint-plugin-jest` plugin and added `no-focused-tests` eslint rule to prevent `.only` in jest tests.
2. Fixed existing errors from the linter.
3. Added a new workflow to run the linter.
Note: Playwright tests already have `forbidOnly` (checks for `.only`) set correctly in the config so we don't have to worry about it.
1. Find a jest test and add `.only` like the following:
```diff
frontend/tests/jest/tests/CompatibleDevice.test.tsx
describe('CompatibleDevice', () => {
-   it('renders and matches the snapshot', () => {
+   it.only('renders and matches the snapshot', () => {
const product = getMockProduct();
```
2. Then run `cd frontend && pnpm lint`. 
4. Make sure the linter returns the following error: `Unexpected focused test  jest/no-focused-tests`
connects: …
> Actions: Add linter workflow

- .github/workflows/main.yml
- frontend/playwright.config.ts
- frontend/tests/playwright/product-list/filters.spec.ts
- frontend/tests/playwright/product-list/parts_page_devices.spec.ts
This will add a `mobile` and `tablet` device for the current playwright tests. This emulates the device's viewport size and user agent and does not actually emulate the hardware.
There were two tests that we had to skip for mobile testing because UI changes on mobile and therefore the selectors we are using do not work.
In addition, we are using a matrix to run each `device - browser` combo in parallel but as independent Playwright jobs.
Closes: https://github.com/ifixit/react-commerce/issues/1204
> Run Playwright tests on Mobile Devices

- frontend/templates/product/sections/ProductSection/ProductGallery.tsx
- frontend/tests/jest/tests/ProductSection.test.tsx
- frontend/tests/playwright/product/product_image.spec.ts
Added tests that:
-  checks a product with no image and asserts `No photos available for this product` image placeholder is visible.
-  checks a product with a single image and asserts that the image is visible.
-  checks a product with multiple images and asserts that clicking on the next image button shows the other image by checking that they have different sources. 
Passing CI is enough. 
qa_req 0
closes #1200
> Product Page: Add tests for images

- frontend/tests/playwright/product/cross_sell.spec.ts
- frontend/tests/playwright/product/product_image.spec.ts
Recently we enabled mobile testing and it's merged into the main branch.
We added a product image test (written for desktop viewport) in https://github.com/iFixit/react-commerce/pull/1218 but it didn't have the main branch merged in, so it started failing in the mobile and tablet ci.
Skips product image test on mobile and tablet.
Passing CI is fine.
qa_req 0
> Tests: Skip product_image test on mobile and tablet

- frontend/components/common/PageBreadcrumb.tsx
- frontend/tests/playwright/product/product_breadcrumb.spec.ts
Added tests that check breadcrumbs on mobile/tablet and desktop.
On mobile and tablet (viewport width sizes below 1000px), we display only the last child breadcrumb
regardless of the number of breadcrumb links. Everything else is collapsed in the breadcrumb menu.
The test for mobile asserts that the last child breadcrumb and the mobile breadcrumb menu are visible.
On the desktop, we display 2 ancestors and the last child breadcrumb (in total 3 breadcrumbs). 
Everything else is collapsed in the breadcrumb menu. The tests for the desktop assert that the 
last child and ancestor breadcrumbs are visible, and the menu is visible/hidden when appropriate.  
qa_req 0
closes: #1203
> Product Page: Add Tests for Breadcrumbs

- frontend/helpers/cache-control-helpers.ts
- frontend/helpers/next-helpers.ts
- frontend/lib/duration.ts
- frontend/lib/next-middleware.ts
- frontend/pages/Parts/[...deviceHandleItemType].tsx
- frontend/pages/Parts/index.tsx
- frontend/pages/Shop/[handle].tsx
- frontend/pages/Tools/[handle].tsx
- frontend/pages/Tools/index.tsx
- frontend/templates/product/server.tsx
closes #1187 
This PR increases stale time for product page as we aim to reduce cache misses.
Other changes:
- Added a small convenient duration library
- Standardized get server side props middleware conventions
Not sure how to QA this given that Vercel seems to override cache control on preview links. Got any idea @danielbeardsley @masonmcelvain @sterlinghirsh  ?
qa_req 0
> Increase CDN cache up to 1 day

- .github/workflows/datadog.yml
- frontend/tests/playwright/product/cross_sell.spec.ts
1. This is a copy of `datadog.yml` workflow from `iFixit/ifixit`. 
The only difference is that this runs on github hosted ubuntu-latest machine (free).
2. Deflakes a test that's flaky in https://github.com/iFixit/react-commerce/pull/1235/commits/74674f6e889da10c76e470d37d57cb793c45a45d
Note: I created a new API key on Datadog and added it to this repo's secrets
We can test this after merging it, same as in https://github.com/iFixit/ifixit/pull/44282.
After merging it, the data should be visible on https://app.datadoghq.com/dashboard/3xd-yax-e2h/github-actions. 
Cloned the existing graphs and added filtering for each repo. 
qa_req 0
connects #1234
> CI: Add datadog workflow to send job metrics

- frontend/tests/playwright/msw/handlers.ts
- frontend/tests/playwright/product/disabled_product.spec.ts
1. Added a new `msw` handler for disabled products.
2. Added a test for the disabled product page that checks the following:
- `Not for Sale`, description, and warranty texts are displayed.
- `Add to cart`, `Notify me`, shipping restriction and stock details texts are **not** displayed.
- Noindexed
Got the test specs from  https://github.com/iFixit/react-commerce/issues/1153.
Passing ci is enough.
qa_req 0
closes: #1163
> Product Page: Add test for disabled products

- frontend/playwright.config.ts
It doesn't look like there is a straightforward way to disable CORS for WebKit. As opposed to Chromium, there are no launch option argument flags that we can pass to WebKit to disable the security features. I also tried intercepting all requests and removing the `sec-fetch` headers as a way to fake a no-cors request but that didn't seem to work either.
Therefore, we will not be able to run the tests in WebKit without some convoluted setup to disable CORS. I don't think it's worth the effort to do that. We can revisit this if there is a need to run the tests in WebKit, but for now, let's drop the mention of the Safari project in the config.
qa_req 0, CI should pass
Closes: #1224
> Playwright: Remove mention of Safari project

- frontend/helpers/next-helpers.ts
- packages/helpers/generic-helpers.ts
- packages/stats/stats.ts
In the pull that added statsd timing, we accidentally removed logging in a refactor that simplified some code in a response to a comment.
This adds both withLogging and withTiming helpers that wrap promise-Returning functions and changes the next logging middleware to use the withTiming helper (which wraps withLogging).
See [comment in #1162](https://github.com/iFixit/react-commerce/pull/1162#discussion_r1061912170)
> Stats Timing: re-add logging

- backend/src/api/product-list/content-types/product-list/schema.json
- frontend/lib/shopify-storefront-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/generated/sdk.ts
connects #741 
connects #682 
This PR reintroduce the defaultShowAllChildrenOnLgSizes flag that was added in #974 without the `"required": true`.
~~In draft since there is some work ongoing for testing Strapi v4.4.7 as suggested [here](https://github.com/strapi/strapi/issues/13731#issuecomment-1304322026)~~
v 4.4.7 still cannot handle correctly defaults values when adding required fields to existing records
2. Verify that Strapi includes the new flag in the `productList` model
> Display 4 rows devices on selected pages

- frontend/sentry.client.config.ts
Fixes a bug where some hydration errors weren't matched because they were suffixed with 'See more info here: https://nextjs.org/docs/messages/react-hydration-error'
Followup to #1233
> Sentry: sample hydration errors with regex

- frontend/lib/swr-cache/index.ts
- frontend/lib/swr-cache/utils.ts
Related to https://github.com/iFixit/react-commerce/issues/1156
qa_req 0
This address concern expressed here https://github.com/iFixit/react-commerce/pull/1232#issuecomment-1377527739
> Uptime [looks okay](https://status.upstash.com/uptime/x20f3jcqg1vq?page=1) (one 16 minute incident in the last year). What kind of fault-tolerance have we implemented here for if Redis goes down?
> Handle Redis errors as cache misses in SWR cache library

- frontend/package.json
We made this script in #1216 but recently changed our playwright project names https://github.com/iFixit/react-commerce/pull/1223. As a result, the script fails because the project name `chromium` no longer exists in the playwright config. This updates the script to use the new project name `Desktop Chromium`.
> Playwright Debug Fix: Update package.json script

- frontend/templates/product-list/sections/FilterableProductsSection/facets/drawer/ListItem.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/facets/drawer/MenuFacetPanel.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/facets/drawer/Panel.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/facets/drawer/RefinementListFacetPanel.tsx
- frontend/templates/product/sections/ProductSection/ProductGallery.tsx
- frontend/templates/product/sections/ProductSection/index.tsx
- frontend/tests/playwright/product-list/filters.spec.ts
- frontend/tests/playwright/product-list/parts_page_devices.spec.ts
- frontend/tests/playwright/product/product_image.spec.ts
1. Fixed `product_image`, `parts_page_devices`, and `filters` tests to be run on both mobile/tablet and desktop.
2. Added a new test in the `filters` test for mobile.
Note: only `product_breadcrumb` and `filters` tests have `.skip` conditional for specific viewports. Both of them have tests for mobile/tablet and desktop.
Commit by commit is probably the easiest (also hiding whitespaces in the diff).
qa_req 0
> Playwright: Unskip mobile tests

- packages/footer/homepage-kpis/index.tsx
The `dl` element is required to have a `dt` element followed by `dd` elements (if `div` elements aren't being used).[^1] The Chakra docs seem to suggest that `StatLabel` is intended to be used for text of the sort we're rendering in `StatHelpText` right now.[^2] `StatLabel` renders as a `dt` while `StatNumber` and `StatHelpText` render as `dd`s; thus, using `StatLabel` would provide the required `dt` element. Because the docs require that the `dt` appear before the `dd`, this moves the `StatLabel` to before the `StatNumber` and uses the `flex-direction` `column-reverse` value to make them appear in the reverse order.
Please check out this branch in the `react-commerce` subdirectory of your `Code` directory, then check that a Lighthouse run on the homepage isn't complaining about the `dl` …
> Homepage KPIs: Use required elements

- frontend/package.json
- frontend/tests/jest/tests/__snapshots__/CompatibleDevice.test.tsx.snap
- frontend/tests/jest/tests/__snapshots__/ProductListItem.test.tsx.snap
- pnpm-lock.yaml
Previous version of chakra caused a syntax error in Safar v13. This is a browser that came out <4 years ago and should be still supported.
This is the exact issue:
https://github.com/chakra-ui/chakra-ui/issues/6828
It looks like the commit that fixes the issue is present in
> 2.4.5, but 2.4.8 just came out, so let's bump to that.
Closes Fixit/ifixit#45976
> Chakra: update to latest version (fix for Safari 13)

- packages/helpers/generic-helpers.ts
When that initialization was in the outermost function, the time() call was only happening once per callsite. This resulted in calling the *same* `done()` closure over and over, logging larger and larger time values.
Effectively, it *was* show time-since-boot each time a request finished.
Previously:
> withLogging(): Fix sad bug!

- frontend/pages/api/nextjs/cache/product.ts
- frontend/pages/api/nextjs/index.ts
Related to #1156 
The goal of this PR is to define a prefix path for APIs defined in Next.js. This sets the stage for caching revalidation endpoints.
Following current iFixit convention (e.g. `/api/2.0`) I'm proposing to use `/api/3.0` and forward this path and all subpaths to the Next.js app.
I understand that you might want to use this for new versions of the iFixit PHP api, so I'm open for ideas. An alternative that I have in mind is `/api/rest`.
Thoughts?
👁️ Once we agree on the prefix, a forwarding rule must be set to serve all /api/3.0 subpaths through the Next.js app.
qa_req 0
> Add Next.js api endpoint

- packages/shopify-storefront-client/index.tsx
This allows the caller to handle errors when they want to, or leave them unhandled and let them be reported.
Closes #1186
> Shopify storefront client: throw errors instead of always reporting

- packages/footer/components/Legal.tsx
We got 1000s of hydration errors around new-years when this value was different between server and client.
The year isn't particularly relevant here as copyrights last a long time. Technically, we don't even need a copyright message, but claims are more defensible if it was clear your content is copyrighted by you.
CC @sterlinghirsh @davidrans
> Footer Copyright: remove year

- frontend/components/common/InstantSearchProvider.tsx
- frontend/templates/product-list/ProductListView.tsx
- frontend/templates/product-list/sections/FeaturedProductListSection.tsx
closes #1191 
Exploiting multiple times the same index on a page requires that all instances of `<Index />` have a unique `indexId` prop specified.
Otherwise the Algolia internal state is not updated correctly.
2. Navigate to a product-list page via a url with some pre-filled filters
3. Try to remove the filters and check that they are correctly removed from the url
4. Verify that filters continue to work also for interaction without pre-filled filters in the url
> Add indexId to correctly handle the Algolia state

- frontend/components/common/InstantSearchProvider.tsx
Fixes a bug where the code assumes the `indexUiState` is never undefined.
Sentry event: https://sentry.io/share/issue/ae902268ed2d4c2ebc4318ada29daeb4/
Bug introduced in #1272, where we started using the `indexId` instead of `indexName` to key the Algolia state.
Confirm that you can't reproduce the Sentry error on a product list page. Not sure on the exact reproduction steps, but it seems to be related to adding/removing facets or clicking on product list children links.
> Algolia: Missing null check

- .github/workflows/main.yml
- frontend/playwright.config.ts
We occasionally fail to run the Playwright tests because it times out waiting for the app to finish building and for the server to start up.
By moving the build step to a prior step, in the GitHub action workflow, we can ensure that Playwright just needs to start and wait for the server to be ready.
In addition, this build step will help when we create the custom Next.js servers needed for the dynamic `msw` handlers.[^1]
- Moves the `pnpm build` step from the Playwright config into a separate GitHub action step
- Ensures the app will be built using the `.env.test` values
- Caches the `.next` directory to help speed up future CI runs.[^2]
I could not extract the `Frontend Server` to an external GitHub action step as requested in #1279 because it is quite messy to start the server as a …
> Playwright GitHub Actions: Move build step to separate step and cache it

- frontend/pages/_app.tsx
Fixes errors on older browsers that don't have Object.fromEntries(). These errors started happening when we upgraded Chakra in #1255.
See #1280 for background.
Visit a product list page on an older browser that doesn't have Object.fromEntries, and confirm there is no Sentry event reported and that you can view the price of the product.
> Polyfill `Object.fromEntries()`

- frontend/tests/playwright/fixtures/cart-drawer.ts
- frontend/tests/playwright/fixtures/product-page.ts
- frontend/tests/playwright/product/add_to_cart.spec.ts
This is a continuation of https://github.com/iFixit/react-commerce/pull/1258 and the last set of utility functions to close out #1217.
- Adds a utility function to make it easier to assert a product's inventory message
- Adds a utility function to get the current `visibility` state of the cart drawer.
qa_req 0
Closes: #1217
> Playwright: Last Batch of Utility Functions

- .github/workflows/main.yml
There is currently an issue with this action that requires further investigation. **Playwright** seems to be unable to communicate with the `backend` server (i.e. localhost:1337) which is causing the tests to be re-run multiple times and eventually fail with a total time of about 30 minutes.
For now, let's set a timeout of 15 minutes to prevent the action from running more than normal.
qa_req 0 CI should continue passing
Closes: #1293
> Hotfix: Add timeout to Playwright Github Action

- .github/workflows/main.yml
If we change some logic to the `getServerSideProps` function we need to bust the cache. We currently only rely on the packages installed to bust the cache which is not enough. 
This will implement the same cache-busting logic we use for Webpack in iFixit/ifixit.
https://github.com/iFixit/ifixit/blob/master/.github/workflows/E2E.yml#L35-L42
**cc:** @andyg0808
> GitHub Actions: Change Nextjs Caching Logic

- frontend/templates/product-list/sections/FilterableProductsSection/ProductGrid.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/ProductList.tsx
- frontend/templates/product/sections/FeaturedProductsSection/index.tsx
closes #1292 
2. Go to product list pages and product pages
3. Verify that lifetime warranty badges now read "lifetime guarantee" as requested in #1292
> Fix lifetime guarantee wording

- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/operations/getProductList.graphql
- frontend/models/product-list/server.ts
- frontend/models/product-list/types.ts
- frontend/templates/product-list/sections/ProductListChildrenSection.tsx
closes #741 
closes #682 
This PR reintroduce the frontend changes related to the defaultShowAllChildrenOnLgSizes flag that was added in #983
A new product list flag is now giving the possibility to show all product list children on large screen.
If enabled the list is not showing the `Show more` / `Show less` button on `> lg` screen sizes.
On smaller screen sized nothing should change.
Here is a preview of the `/Tools` page with the flag enabled:
The same page on mobile is showing the `Show more` / `Show less` button as before:
2. Verify that the implementation is coherent with the spec described above
> Display 4 rows devices on selected pages frontend

- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/operations/getProductList.graphql
- frontend/models/product-list/server.ts
- frontend/models/product-list/types.ts
- frontend/templates/product-list/sections/ProductListChildrenSection.tsx
Reverts iFixit/react-commerce#1158
See: https://ifixit.slack.com/archives/C0252FETV2S/p1674863795570009
Example log:
```
2023-01-28T00:09:49.116Z	20fecd52-a6c3-4ae6-83c8-2f18c1301edf	ERROR	GraphQL query failed with errors:
2023-01-28T00:09:49.116Z	20fecd52-a6c3-4ae6-83c8-2f18c1301edf	ERROR		[GRAPHQL_VALIDATION_FAILED] Cannot query field "defaultShowAllChildrenOnLgSizes" on type "ProductList".
strapi.getProductList: 56ms
findProductList: 58ms
server_side_props: 59ms
2023-01-28T00:09:49.261Z	20fecd52-a6c3-4ae6-83c8-2f18c1301edf	ERROR	Error: GraphQL query failed to execute: Bad Request
at requester (/var/task/frontend/.next/server/chunks/786.js:1586:11)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async Promise.all (index 0)
at async findProductList …
```
> Revert "Display 4 rows devices on selected pages frontend"

- frontend/pages/_app.tsx
closes #1311 
1. Visit Vercel preview using a device that has no native support for ResizeObserver
2. Verify that this PR correctly polyfill ResizeObserver.
> Add ResizeObserver polyfill

- frontend/config/env.ts
- packages/helpers/logger.ts
> Logs: add colorless option

- frontend/next.config.js
We still see a fair number of errors (hydration errors) who's source maps are unavailable because the stack frames are in dist/framework.
Adding this option enables uploading those too. Unclear how bigger this makes the uploads, but we'll find out!
Connect #1209 
qa_req 0 - vercel does a `next build` which covers this.
See the docs: https://docs.sentry.io/platforms/javascript/guides/nextjs/manual-setup/#widen-the-upload-scope
> sentry sourcemaps: upload framework sourcemaps too

- packages/analytics/index.tsx
- packages/ui/cart/drawer/Upsell.tsx
Basically we want matomo events for adding to cart to be slightly different if they were added in unique ways (the two current unorthodox ways we want to track are `Frequently Bought Together` and the cart drawer's cross sell button). This pull's main point is to add the specific event to track cart drawer cross sells, but it also changes our `trackAddToCart()` to have its parameters better match the expected values from the [spreadsheet](https://docs.google.com/spreadsheets/d/16Xas1pHf_K7FmfOX3yX2mYgeYr2DIENr8cyQp19FZkA/edit?pli=1#gid=1839136207&fvid=1843464925).  
Make sure that the matamo events fired by adding to the cart normally, adding to the cart view the frequently bought together section, and adding by the cart drawer cross sell section all create the correct Matomo events as …
> Have Cart Drawer Cross Sell Use Specific Matamo Event

- frontend/templates/product/sections/CrossSellSection/index.tsx
- packages/ui/commerce/ProductPrice.tsx
closes #1139 
This fixes also a bug in pro prices icon alignment
1. Open [Vercel preview](https://react-commerce-git-fix-cross-sell-ui-bug-ifixit.vercel.app/products/fixmat)
2. Verify that the bug described by #1139 is fixed
> Fix product page cross sell section ui bug

- frontend/templates/troubleshooting/hooks/useTroubleshootingProps.tsx
- frontend/templates/troubleshooting/index.tsx
- frontend/templates/troubleshooting/prerendered.tsx
- frontend/templates/troubleshooting/solution.tsx
This should be mostly matching the mockup at this point.
Not all the wikitext is formatted nicely yet; please ignore how ugly bulleted lists and links look for now.
Also, the mockup includes more parts that we're not supporting yet; I made a bunch of the extra things invisible on it to get a feel for what this should look like without upvotes or card footers. Please comment if something looks weird; it's kinda scrawny right now because of the lack of features.
You'll need to add
```
[comment]solutions[/comment]
```
markup to mark where the solutions begin on your test page. You can also add
```
[comment]conclusion[/comment]
```
to mark the place where the solutions end.
Example: https://www.cominor.com/Wiki/Dryer_Making_Loud_Noise
Append: `/Vulcan/Dryer_Making_Loud_Noise`
Closes …
> Vulcan: Make Solution card look like mockup

- frontend/templates/product/sections/ProductSection/GenuinePartBanner.tsx
closes #1304 
Added the new placeholder image.
Un-suppressed the Google badge.
As for the previous implementation, the logo-only badge was not implemented since there is still no plan to use it.
> Add placeholder OEM partnership image

- frontend/templates/product/sections/ProductSection/ProductGallery.tsx
connects #1101 
Product page images were not perfectly squared because the image height was computed as 100% + the 2px border.
This PR changes the way in which the gallery border is rendered to eliminate the problem.
2. Verify that the gallery image aspect ratio is now exactly 1:1
3. No interaction (changing slide, zoom, etc) with the carousel should be compromised
> Correct product image aspect ratio

- frontend/templates/product/sections/ProductSection/index.tsx
Updates the "Not for Sale" alert styling to match the out of stock alert as updated in #1317.
Make sure the "Not for Sale" alert matches the styling of the out of stock alert.
> Product Page: "Not for Sale" alert styling

- frontend/.gitignore
- frontend/next.config.js
- frontend/playwright.config.ts
- frontend/tests/playwright/test-fixtures.ts
If we are running all the Playwright tests locally then the tests will often timeout. There are two main reasons this occurs.
Currently, we have no set limit to the number of workers we will use locally. Therefore, we could potentially have 4-8 workers running in parallel, all depending on the number of cores on the host machine. In CI, we use all available workers we can and since the GitHub action machine only has two cores, we really only use 2 workers in CI. To reduce the load on local runs, I've changed the number of workers to a quarter of available cores.
The other reason for the timeout is each worker will create its own custom Nextjs server but each server will use the same dist directory (i.e. `.next`). Therefore, while one instance is building files, another instance may be …
> Playwright: Mitigate Timeouts

- frontend/next.config.js
- frontend/package.json
- packages/breadcrumbs/Breadcrumbs.tsx
- packages/breadcrumbs/FlexHiddenWrap.tsx
- packages/breadcrumbs/package.json
- packages/breadcrumbs/tsconfig.json
- pnpm-lock.yaml
This pull copies the breadcrumbs from the iFixit repo and modifies them to work here.
The iFixit/ifixit breadcrumbs potentially have a nicer small-screen behavior than the existing ones here.
Connects https://github.com/iFixit/ifixit/issues/46349
qa_req 0
> Breadcrumbs: Copy from iFixit/ifixit

- frontend/.env.production
- frontend/helpers/strapi-helpers.ts
- frontend/next.config.js
closes #1330 
closes #1270 
This branch is longer than 63 characters to test the url abbreviation works correctly
Changes on the Govinor side have already been deployed.
1. Open [Vercel preview](https://react-commerce-git-generate-govinor-url-handles-f-be9310-ifixit.vercel.app/Parts)
2. Verify that `/Parts` product list page renders with data from the [govinor Strapi instance](https://generate-govinor-url-handles-for-git-branches-with-max-50db9bd7.govinor.com/admin/auth/login)
> Compute Strapi govinor handle to support longer branch names

- frontend/lib/swr-cache/adapters/index.ts
We're seeing errors talking to redis on occasion; short several-second
bursts of errors, totalling ~600 per day.
It's a 3rd party service, interruptions happen, let's try reconnecting
more quickly. Delays look like this:
58ms
66ms
82ms
114ms
178ms
306ms
...
with a cap at 10 minutes (as before)
qa_req 0
Connect #1322
CC @dhmacs
> Redis: reconnect sooner

- frontend/lib/redis/index.ts
- frontend/lib/swr-cache/adapters/index.ts
- frontend/lib/swr-cache/index.ts
closes #1322 
Fix #1341 addressed issue #1322, however, I have spotted another optimization opportunity. The code may establish redundant connections to Redis, which currently shouldn't pose a problem since the cache is preserved in the `withCache` closure and there's only one endpoint. However, as we add more cache endpoints, multiple connections will be created.
1. Open [Vercel preview](https://react-commerce-git-reuse-redis-connection-ifixit.vercel.app/products/surface-pro-7-battery)
2. Verify that [product page](https://react-commerce-git-reuse-redis-connection-ifixit.vercel.app/products/surface-pro-7-battery) renders
> Reuse Redis connection

- frontend/templates/troubleshooting/prerendered.tsx
This adds styles for the `code` and `pre` tags.
They now look about like the existing wikis do; the colors are a bit different, because I'm now using a core-primitives color:
https://www.cominor.com/Wiki/troubleshooting-test
https://react-commerce-git-troubleshooting-add-code-styling-ifixit.vercel.app/Vulcan/troubleshooting-test
I'd appreciate review from @mmarcon91, because I'm changing the color a bit. The actual QA should be really straightforward (links are provided above).
Closes https://github.com/iFixit/ifixit/issues/46386
> Troubleshooting: Add styling for `code` and `pre`

- frontend/helpers/cache-control-helpers.ts
Problem: we have been using `s-maxage` and vercel listens to that, but strips it off so both downstream caches (Cloudfront and browsers) see the response as uncacheable.
Since we're telling vercel to cache our responses (via s-maxage), we might as well let browsers and cloudfront cache them too (via maxage).
The only reason this isn't the default recommended for vercel is because they auto-invalidate your caches on deploy and they can't do that for downstream caches. Given that our cache times are 1 minute, I'm OK with CF and browsers storing these responses for that amount of time.
Note: max-age is computed relative to the when the response was generated, not when it was received. So, if vercel sends a 40s-old page to CF and CF caches it, it'll only consider it fresh for another 20s, not …
> Browser Caching: enable it!

- backend/docker-compose.yaml
- backend/package.json
- backend/src/plugins/addons/admin/src/components/Initializer/index.tsx
- backend/src/plugins/addons/admin/src/index.tsx
- backend/src/plugins/addons/package.json
- backend/src/plugins/addons/yarn.lock
- backend/tsconfig.json
- backend/yarn.lock
closes #1349 
1. Login into the [strapi instance for this branch](https://upgrade-strapi-to-v4-6-0.govinor.com/admin)
2. Go to settings and check that the Strapi version is `v4.6.1`
3. Open [Vercel preview](https://react-commerce-git-upgrade-strapi-to-v4-6-0-ifixit.vercel.app/Parts)
4. Verify that product list page renders
> Upgrade Strapi to v4.6.1

- backend/src/api/product-list/content-types/product-list/schema.json
- frontend/lib/strapi-sdk/generated/sdk.ts
connects #1170 
This PR adds two strapi fields on product list records for the optional hero image and brand logo 
❗ ❗ ❗ After this PR is merged Strapi should be redeployed in production ❗ ❗ ❗
1. Login into [Strapi](https://implement-hero-with-background-backend-changes.govinor.com/admin/)
2. Check that the productList model includes the new optional heroImage and brandImage fields
3. Visit [Vercel preview](https://react-commerce-git-implement-hero-with-background-94d831-ifixit.vercel.app/Parts)
4. Verify that everything renders correctly
> Hero with background backend changes

- frontend/templates/product-list/hooks/useSearchQuery.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/CurrentRefinements.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/SearchInput.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/facets/drawer/index.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/index.tsx
closes #1084 
This PR switch the searchBox from being and uncontrolled component to be a controlled component.
The searchQuery state is stored in a context to allow resetting it from several places
2. Check that the behaviour discussed in #1084 is working as expected
> Reset search text after clearing all filters

- backend/src/api/product-list/content-types/product-list/schema.json
- frontend/lib/strapi-sdk/generated/sdk.ts
connects #1170 
This PR is an addition to #1352: an additional `brandLogoWidth` image has been added to simplify the sizing of logos with different aspect ratios
❗ ❗ ❗ After this PR is merged Strapi should be redeployed in production ❗ ❗ ❗
1. Login into [Strapi](https://implement-hero-with-background-backend-changes.govinor.com/admin/)
2. Check that the productList model includes the new optional brandLogoWidth field
3. Visit [Vercel preview](https://react-commerce-git-implement-hero-with-background-94d831-ifixit.vercel.app/Parts)
4. Verify that everything renders correctly
> Hero with background: add brandLogoWidth field

- frontend/templates/product-list/sections/FilterableProductsSection/index.tsx
- frontend/templates/product/sections/CrossSellSection/index.tsx
- frontend/templates/product/sections/ProductSection/AddToCart/NotifyMeForm.tsx
- frontend/templates/product/sections/ProductSection/AddToCart/index.tsx
- frontend/templates/product/sections/ProductSection/InternationalBuyBox.tsx
- frontend/templates/product/sections/ProductSection/index.tsx
- frontend/tests/playwright/fixtures/product-page.ts
- frontend/tests/playwright/product-list/newsletter_subscribe.spec.ts
- frontend/tests/playwright/product-list/parts_page_search.spec.ts
- frontend/tests/playwright/product/add_to_cart.spec.ts
- frontend/tests/playwright/product/cross_sell.spec.ts
- frontend/tests/playwright/product/disabled_product.spec.ts
- frontend/tests/playwright/product/fix_kit.spec.ts
- frontend/tests/playwright/product/product_option.spec.ts
- frontend/tests/playwright/product/product_page.spec.ts
- frontend/tests/playwright/product/product_reviews.spec.ts
In https://github.com/iFixit/react-commerce/pull/1317 there was a small grammatical change that caused the tests to fail. https://github.com/iFixit/react-commerce/commit/4031350862efa7ef883f2a133e2af4ebbae51aa4
The main two reasons why this occurred are:
1. We use `toHaveText` instead of `toContainText`[^1] for asserting the text in an element. 
- `toHaveText` will do an explicit match while `toContainText` will match if the string is included. Therefore, we should use the latter for validating that some text is within the element. For explicit assertions, we can still use `toContainText` but pass in a `RegExp` instead. 
2. We search for elements based on text content
- By searching for elements based on text, we might end up nabbing a different element than expected if our text is too …
> Playwright: Make tests a bit more resilient

- frontend/tests/playwright/msw/handlers.ts
- frontend/tests/playwright/msw/request-handler.ts
- frontend/tests/playwright/product-list/newsletter_subscribe.spec.ts
- frontend/tests/playwright/product/add_to_cart.spec.ts
- frontend/tests/playwright/product/disabled_product.spec.ts
In #1275 we created the ability to set dynamic handlers for `MSW`. However, the API for creating a handler is rather bloated and a lot of it can be extracted to reduce the boilerplate.
As such, we created a new static helper function to create these handlers.
Commit by commit would be the easiest way to understand the code as some obscure context is needed in some cases.
Overall, the end goal was to abstract creating these dynamic handlers just enough to reduce the boilerplate and still be simple to use. Most of this was accomplished by making use of Typescript's features. 
Besides checking CI still passing, I am not sure if it will be worth validating if the error handling works, as that might be exhaustive. 
I already confirmed that the `international buybox` handler still works using …
> Playwright: Abstract Handler Creation for MSW

- .github/workflows/format.yml
- .github/workflows/jest.yml
- .github/workflows/lint.yml
- .github/workflows/main.yml
- .github/workflows/nextjs_bundle_analysis.yml
- .github/workflows/tsc.yml
The default node version for the runners was changed to 18, which is not compatible with our current setup. Unfortunately, this change was only tracked as an issue and was not announced on GitHub's blog (https://github.blog/changelog/label/actions/), which is why we did not notice it. 
In order to fix this, we need to explicitly set the node version to 16 for all our workflows that use node/pnpm.
qa_req 0 CI should pass
References:
https://github.com/actions/runner-images/issues/7002
https://ifixit.slack.com/archives/C02SMF0AZPF/p1676677777249139
> Hot Fix: Make Runners Explicitly use Node Version 16

- packages/breadcrumbs/package.json
- pnpm-lock.yaml
This adds the lodash types as a dev dependency to `@ifixit/breadcrumbs`
qa_req 0
This is dev-only.
> @ifixit/breadcrumbs: Require types as dev dependency

- frontend/tests/playwright/product/cross_sell.spec.ts
- packages/ui/cart/drawer/CartDrawer.tsx
closes #1384 
This PR introduces a new `data-testid` that targets the line items container.
The upsell component was also moved outside the line-items `ul`.
2. Verify that there is no visual changes to the upsell banner inside the cart drawer
3. Verify that the cross sell tests are now running correctly
> Correct cross sell test

- packages/ui/misc/ResponsiveImage/iFixitUtils.ts
- packages/ui/misc/ResponsiveImage/index.tsx
- packages/ui/misc/ResponsiveImage/shopifyUtils.ts
closes #1365 
Fixed a couple of missing escape in RegExp.
RegExp have been moved outside of functions to avoid recreating them on each function iteration.
Added `^\/uploads\/` to the Strapi image RegExp to handle correctly the relative urls associated to images uploaded during development
1. Visit [Vercel preview](https://react-commerce-git-refactor-responsive-image-load-71418b-ifixit.vercel.app/Parts)
2. Images should load correctly as before - no visual change should be present.
> Refactor Responsive image loader RegExp

- frontend/templates/product/sections/ProductSection/index.tsx
- packages/ui/theme/foundations/breakpoints.ts
close #1397 
1. Visit [Vercel preview](https://react-commerce-git-fix-zoom-wrapper-regression-ifixit.vercel.app/products/iphone-7-plus-screen)
2. Verify that the zoom container is now sized correctly and is not overflowing anymore outside of the viewport
> Correct zoom container size

- backend/src/api/page/content-types/page/schema.json
- backend/src/components/page/split-with-image.json
- frontend/components/sections/SplitWithImageSection.tsx
- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/operations/findPage.graphql
- frontend/models/page/index.ts
- frontend/models/page/server.ts
- frontend/models/shared/sections/split-with-image-section.ts
- frontend/templates/page/index.tsx
closes #1383 
1. Visit preview [store home page](https://react-commerce-git-add-split-with-image-section-ifixit.vercel.app/store)
2. Verify that the split with image section is visible and implemented according to [mockup](https://www.figma.com/file/jRG4EyQXRDMGfyLqut08KP/iFixit---Working-files?node-id=6315%3A69164&t=eCepNFgQfxNde2XK-4)
3. Verify that the split with image section is responsive
---
❗ ❗ ❗ This PR requires a Strapi redeploy ❗ ❗ ❗ 
I didn't split backend and frontend changes into separate PRs because this stuff is still behind a feature flag
cc @sterlinghirsh @danielbeardsley
> Add split with image section

- frontend/templates/product-list/sections/ProductListChildrenSection.tsx
closes #1402 
1. Visit [Vercel preview](https://react-commerce-git-fix-regression-default-show-al-a7a976-ifixit.vercel.app/Parts)
2. Verify that enabling the `defaultShowAllChildrenOnLgSizes` flag in [Strapi](https://fix-regression-default-show-all-children-on-lg-size.govinor.com/admin/), all the associated product list page children are shown on `lg` screen.
3. On screen size `< lg` children should still show only after interaction
> Fix defaultShowAllChildrenOnLgSizes regression

- backend/docker-compose.yaml
- backend/package.json
- backend/src/plugins/addons/package.json
- backend/src/plugins/addons/yarn.lock
- backend/yarn.lock
closes #1364 
cc @sterlinghirsh @danielbeardsley @masonmcelvain 
1. Login into the [strapi instance for this branch](https://fix-draft-content-type-visibility.govinor.com/admin)
2. Go to settings and check that the Strapi version is `v4.6.2`
3. Verify that bug described by #1364 is fixed, meaning that draft product lists are not rendered among children of their parents
> Upgrade Strapi to v4.6.2

- frontend/templates/troubleshooting/hooks/useTroubleshootingProps.tsx
- frontend/templates/troubleshooting/index.tsx
- frontend/tests/playwright/troubleshooting/loading.spec.ts
This adds a `link` tag with the canonical URL for each Vulcan page.
There's a test that should be validating the main point here.
qa_req 0
Closes iFixit/ifixit#46644
> Vulcan: Add `canonical` tag

- backend/src/api/company/content-types/company/schema.json
- backend/src/api/company/controllers/company.ts
- backend/src/api/company/routes/company.ts
- backend/src/api/company/services/company.ts
- backend/src/api/page/content-types/page/schema.json
- backend/src/components/page/press-quote.json
- backend/src/components/page/press.json
- backend/src/components/page/split-with-image.json
- frontend/components/sections/SectionDescription.tsx
- frontend/components/sections/SectionHeading.tsx
- frontend/helpers/strapi-helpers.ts
- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/operations/CompanyFields.fragment.graphql
- frontend/lib/strapi-sdk/operations/findPage.graphql
- frontend/lib/strapi-sdk/operations/sections/PressQuotesSectionFields.fragment.graphql
- frontend/models/page/components/press-quote.ts
- frontend/models/page/index.ts
- frontend/models/page/sections/press-quotes-section.ts
- frontend/models/page/server.ts
- frontend/models/shared/components/call-to-action.ts
- frontend/models/shared/components/company.ts
- frontend/templates/page/index.tsx
- frontend/templates/page/sections/PressQuotesSection.tsx
closes #1396 
> 🔍 The additional 29kb added to the `/store` bundle are due to the use of swiper.js, the same library that we're using to handle the product page gallery.
1. Visit preview [store home page](https://react-commerce-git-add-page-template-press-section-ifixit.vercel.app/store)
2. Verify that the press quotes section is visible and implemented according to [mockup](https://www.figma.com/file/jRG4EyQXRDMGfyLqut08KP/iFixit---Working-files?node-id=6315%3A68822&t=BgbMfgqro1NEnYVQ-4)
3. Verify that the section is responsive
---
❗ ❗ ❗ This PR requires a Strapi redeploy ❗ ❗ ❗ 
I didn't split backend and frontend changes into separate PRs because this stuff is still behind a feature flag
> Add page template press section

- frontend/helpers/next-helpers.ts
- frontend/lib/cache.ts
We are using Alertra to monitor uptime and we add a _vercel_no_cache=1 query param to ensure we actually run app code. We don't want this to constantly clear the in-memory cache because we have alerta checking twice a minute.
The in-memory cache only stores a few global settings and it expires every hour.
See comment here: https://github.com/iFixit/ifixit/issues/46312#issuecomment-1442379352
qa_req 0
> Memory Cache: don't clear on vercel_no_cache

- backend/src/bootstrap/permissions/config.json
closes #1411 
❕ CI cannot pass because without the change this PR is introducing, the remote instance of Strapi returns a forbidden request error to seeding requests (i.e. `main.govinor` will not be able to provide seed data for other instances until this is merged)
cc @sterlinghirsh @danielbeardsley @masonmcelvain 
This PR enables permissions for public reading of `company` content type. To verify this, visit this url:
https://fix-company-strapi-public-permission.govinor.com/api/companies?populate[logo][fields]=%2A&pagination[page]=1&pagination[pageSize]=100
and verify that you receive a `200` response (you can check this from the browser dev tools network tab
> Fix company content type public permission

- .github/workflows/main.yml
All reruns were failing b/c we were not building the nextjs app (`pnpm build`) on reruns:
- First run (successful): https://github.com/iFixit/react-commerce/actions/runs/4257656032/jobs/7408032866
- Second run (failure): https://github.com/iFixit/react-commerce/actions/runs/4257656032/jobs/7408197758
That lead me to think that there was some state that gets transferred from the first job that causes the second to fail. After digging into the workflow, I noticed that we are caching the entire `frontend/.nex`t directory. The second run drops the entire `frontend/.next` directory in from the first run and does not run `pnpm build`.
I did a little research and noticed that most other workflows [only cache the .next/cache directory](https://nextjs.org/docs/advanced-features/ci-build-caching#git …
> Playwright: Only cache the nextjs cache dir

- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/operations/findPage.graphql
- frontend/lib/strapi-sdk/operations/sections/BrowseSectionFields.fragment.graphql
- frontend/lib/strapi-sdk/operations/sections/HeroSectionFields.fragment.graphql
- frontend/lib/strapi-sdk/operations/sections/PressQuotesSectionFields.fragment.graphql
- frontend/lib/strapi-sdk/operations/sections/SplitWithImageSectionFields.fragment.graphql
- frontend/lib/strapi-sdk/operations/sections/StatsSectionFields.fragment.graphql
- frontend/models/page/components/browse-category.ts
- frontend/models/page/sections/browse-section.ts
- frontend/models/page/sections/hero-section.ts
- frontend/models/page/server.ts
- frontend/models/shared/sections/ifixit-stats-section.ts
- frontend/models/shared/sections/split-with-image-section.ts
Extracted this while working on #1409 
This is just a small refactor, let's just check that the store home page still renders:
1. Visit preview [store home page](https://react-commerce-git-refactor-page-model-sections-ifixit.vercel.app/store)
2. Verify that the page renders (don't worry about the sections, it's just dummy data from Strapi)
> Improve code organization for page sections

- frontend/tests/playwright/product-list/parts_page_search.spec.ts
This test is flaky as we wait for the algolia query to finish but this event does not mean that the page has fully been updated. As a result, we sometimes fail since we have not updated the url after the query has finished.
This flakiness became more of an issue in https://github.com/iFixit/react-commerce/pull/1375. Locally the test passes for the branch. However, when we run the entire test-suite the flakiness of the test increases. This means when the machine is under higher loads the test begins to fail more often. 
To fix this, we will instead wait for the url to be updated with a query parameter after we enter the search text but before the assertion is made. This will give the page enough time to update the URL. 
qa_req 0 CI should continue to pass.
I confirmed this helped to …
> Playwright: Deflake Parts Page Search Test

- frontend/tests/playwright/product-list/filters.spec.ts
The Algolia `dev_product_group_en` index was updated recently. This may have caused a bug to surface as our assumption of the Algolia results structure was causing the `filters` test to fail. However, we cannot validate this as we cannot go back to a prior state of the Algolia index.
Overall, what we now know is the Algolia results include hits from different filter parameters. We need to search for the filter parameters that include the facet option we selected. This will indicate that the hits are associated with the filter facet option we selected. 
Additionally, there are some guards to ensure that if our current assumption about the Algolia results is no longer valid, we will throw an error to indicate that the test might need to be updated.
The structure of the Algolia Results are …
> Playwright: Update `filters` test to use new Algolia Results

- frontend/templates/product-list/ProductListView.tsx
- frontend/templates/product-list/sections/BannerSection/index.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/index.tsx
- frontend/templates/product-list/sections/HeroWithBackgroundSection.tsx
- frontend/templates/product-list/sections/ProductListChildrenSection.tsx
- frontend/templates/product-list/sections/RelatedPostsSection/index.tsx
- frontend/tests/jest/tests/__snapshots__/ProductListItem.test.tsx.snap
- packages/ui/misc/IconBadge.tsx
closes #1428
closes #1422
This PR is a follow-up of #1369 #1373 #1375 and #1376
It fixes a couple of details like the border-radius of product-list items or the margin on top of the filterableListItem which were not yet correct.
In addition to this, the `HeroWithBackground` component needed to be adapted to the new wrapper, since it was introduced in parallel with it.
qa_req 0
> Collection page style refinements

- packages/ui/header/NavigationDrawer.tsx
- packages/ui/header/NavigationMenu.tsx
closes #1424 
1. Visit [Vercel preview](https://react-commerce-git-change-navigation-mobile-deskt-b1a66f-ifixit.vercel.app/Parts)
2. Verify that for screen widths `>= 1028px` the desktop header is shown
> Switch from mobile to desktop header at lg size

- packages/breadcrumbs/Breadcrumbs.tsx
This is ported from our main monorepo.
Original issue: https://github.com/iFixit/ifixit/pull/46667
qa_req 0
We'll test this when we integrate the breadcrumbs from here in the monorepo.
> Breadcrumbs: Allow mobile to be dynamic

- backend/src/api/product-list/content-types/product-list/schema.json
- frontend/lib/strapi-sdk/generated/sdk.ts
connects #898 
This pr add a ~`displayTitle`~ `h1` field to the Strapi backend
❗ ❗ ❗ After this PR is merged Strapi should be redeployed in production ❗ ❗ ❗
1. Navigate to [Strapi](https://add-collection-display-title-backend.govinor.com/admin)
2. Verify that the ~`displayTitle`~ `h1` field is present in the `productList` model
3. Visit [Vercel preview](https://react-commerce-git-add-collection-display-title-backend-ifixit.vercel.app/Parts)
4. Verify that the product list page still renders correctly
> Add collection displayTitle backend

- frontend/templates/product/MetaTags.tsx
closes #1440 
connects [#1092](https://github.com/iFixit/react-commerce/pull/1092#issuecomment-1455270179)
The code that was in charge of separating generic and variant specific product images was still using the old logic that exploited the image `altText` attribute. 
After the execution of the [formatImage](https://github.com/iFixit/react-commerce/blob/b40d56b2bba9f2f4f8dde57df19bc759cbecbb29/frontend/models/product/server.ts#L186-L195) function though, this is not anymore true.
We have to rely on the `variantId` attribute on the image to assert if an image is generic or variant specific.
1. Visit [Vercel preview](https://react-commerce-git-fix-product-page-og-image-ifixit.vercel.app/products/ifixit-precision-4-mm-screwdriver-bit)
2. Assert that `og:image` tags are generated only for …
> Fix `og:image` meta in product page

- frontend/templates/product/sections/ProductSection/AddToCart/index.tsx
Adds an OEM Partnership shipping restriction message to the product page.
Visit a product page for a variant whose shipping restriction metafield includes `is_oem_partner_restricted`. The product page should include the notice specified in the parent issue.
Backend change: https://github.com/iFixit/ifixit/pull/46793
Closes #1418
> Product Page: Add OEM partner shipping restriction

- backend/src/components/store/footer.json
- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/operations/findStore.graphql
- frontend/models/store.ts
1. This copies over the autogenerated changes from https://github.com/iFixit/react-commerce/pull/1342.
2. We need to add menu3 to strapi before trying to access it in the frontend.
Qa_req 0 - Tests should cover any regressions.
Connects to https://github.com/iFixit/ifixit/issues/45964
> Add menu3 to strapi store

- packages/analytics/index.tsx
This allows the E-Commerce team to see what variant "Frequently Bought Together" items are associated with. Currently in Matomo, you can see the URL, but that doesn't include the variant.
See row 223 of [iFixit EVENTS Spreadsheet (updated 03-08-2023)
](https://docs.google.com/spreadsheets/d/16Xas1pHf_K7FmfOX3yX2mYgeYr2DIENr8cyQp19FZkA/edit?pli=1#gid=1839136207&fvid=1843464925) for spec details.
A little discussion in the comments of this PR around the spec: https://github.com/iFixit/react-commerce/pull/1452#discussion_r1130094635
Closes https://github.com/iFixit/react-commerce/issues/1414
> Include current itemcode in Frequently Bought Together event

- frontend/tests/playwright/product-list/parts_page_search.spec.ts
Added a test that checks if the URL is updated after clearing the search text.
It makes sure the URL is updated and has no query parameters such as `?q=...`.
closes https://github.com/iFixit/react-commerce/issues/1276
qa_req 0
> Tests: Add search for empty query test

- backend/src/bootstrap/permissions/config.json
closes #1461 
⚠️ 👁️ CI is broken because the seed process is broken. This PR fixes that.
1. Verify that the following link returns `200` response (you can use the network tab in the browser dev tools)
https://fix-strapi-product-permissions.govinor.com/api/products?populate[sections][populate]=%2A&pagination[page]=1&pagination[pageSize]=100
> Add product collection type permissions

- frontend/templates/troubleshooting/hooks/useTroubleshootingProps.tsx
- frontend/templates/troubleshooting/index.tsx
Please view-source on https://react-commerce-git-troubleshooting-add-hreflangs-ifixit.vercel.app/Vulcan/troubleshooting-test and check that we end up with a `<link rel="alternate" hreflang="en" href="some reasonable URL for Vulcan">` tag and one for `x-default` on the page.
Then also check that a translated wiki, such as https://react-commerce-git-troubleshooting-add-hreflangs-ifixit.vercel.app/Vulcan/KitchenAid_KSM150PSER_Troubleshooting, ends up with some non-English values.
Closes https://github.com/iFixit/ifixit/issues/46809
> Troubleshooting: Add hreflang links to page head

- frontend/components/common/CompatibleDevice.tsx
- frontend/models/product/schema.ts
- frontend/models/product/server.ts
- frontend/templates/product/hooks/useSelectedVariant.ts
- frontend/templates/product/sections/CrossSellSection/index.tsx
- frontend/templates/product/sections/ProductSection/ProductGallery.tsx
- frontend/tests/jest/__mocks__/products.ts
connects https://github.com/iFixit/react-commerce/pull/1092#issuecomment-1455270179
closes #1443 
Cross sell variants are now grouped at product level and referenced by id.
The duplicated structures were removed - according to how many active variants we have we pass down the data and the images associated to the active elements (`> 0` active variants) or the one associated with the first variant (`= 0` active variants)
1. Visit [Vercel preview](https://react-commerce-git-restructure-product-page-next-data-ifixit.vercel.app/products/iphone-6s-screen)
2. Check that there is no change in how product pages or cross sell section behave wrt production
3. Check also that products with disabled variants and products with no variants available for sale are still working as they do in production
> Restructure product page next data

- packages/footer/components/Newsletter.tsx
- packages/footer/components/Partners.tsx
References https://github.com/iFixit/react-commerce/pull/1465#discussion_r1135888653
This PR removes any references to the flex `gap` property from the footer.
All the usages were easily substituted with margins.
cc @aburke07 
2. Check that this change does not introduce any visible change to the footer wrt production
> Remove flex gap property from footer

- .github/actions/build-test-frontend/action.yml
- .github/actions/playwright-setup/action.yml
- .github/workflows/main.yml
- .github/workflows/stress_test.yml
Added stress-test ci for playwright and jest tests.
The new workflow has 3 jobs:
- The first job checks for the test changes and the logic for skipping the stress-test check.
- It looks for modified jest test files in `frontend/tests/playwright/` folder with `*.spec.ts` file extension and jest tests in `frontend/tests/jest/tests/` with `*.test.tsx`. If changes were found, it will trigger the corresponding jobs to run the stress-test.
- Also, if the last commit message has [skip stress-test] commit message, then it will not run stress tests (copy from `ifixit`).
- The second job runs `playwright` stress-test if there were test changes. It runs stress-test for `Desktop Chrome` and `Mobile Chrome` projects (we can add `Firefox` and `Tablet` but seems a bit too many). It uses `--repeat-each` …
> Github Actions: Add stress-test workflow

- frontend/templates/product-list/sections/HeroSection.tsx
- packages/ui/misc/Wrapper.tsx
closes #1482
This issue was due to the wrapper not expanding to fill all the available space.
It was by chance that it was noted only on `HeroWithImage`.
The length of the description field contained in the Hero components was often enough to push the container to fill all the available space.
2. Verify that the issue described in #1482 is not present anymore
> Force wrapper to fill all available space

- frontend/templates/troubleshooting/prerendered.tsx
Add styles for non-YouTube videos and add styles for videos on mobile to prevent horizontal overflow.
QA
---
Check both YouTube and non-YouTube video styling at desktop and mobile.
Closes: https://github.com/iFixit/ifixit/issues/46894
> Troubleshooting: Add html5 video styling

- frontend/components/admin/PageEditMenu.tsx
- frontend/components/admin/ProductEditMenu.tsx
- frontend/components/admin/index.ts
- frontend/helpers/product-helpers.ts
- frontend/helpers/product-list-helpers.ts
- frontend/models/product-list/server.ts
- frontend/models/product-list/types.ts
- frontend/templates/product-list/SecondaryNavigation.tsx
- frontend/templates/product/index.tsx
Closes https://github.com/iFixit/react-commerce/issues/416
- Makes the existing admin menu more generic.
- Adds the admin menu to the product list page with a Strapi link, if the collection exists in Strapi.
- Visit a collection page that exists in strapi, and confirm that the new admin menu has a link to the strapi collection page.
- For collection pages that don't exist in strapi, no admin menu should appear (because it would have no links in it).
- Make sure the edit menu matches the [mockup](https://www.figma.com/file/sfj6r7Bn6eREMvuqo0f7Du/iFixit---Components?node-id=118-12832), and is accessible on mobile and desktop.
- Make sure the sub navigation menu (with breadcrumbs and parts/tools/guides links) still matches `main`.
- Make sure the product page admin menu still works as on …
> Collections: Add admin links

- frontend/components/common/InstantSearchProvider.tsx
Closes [#1492](https://github.com/iFixit/react-commerce/issues/1492)
**QA**
If the page number is invalid (<0), the parameter is ignored.
> Add Parameter Check for Negative Page Number

- frontend/components/sections/ReplacementGuidesSection.tsx
- frontend/models/product/index.ts
- frontend/models/product/sections/index.ts
- frontend/models/sections/replacement-guides-section.ts
- frontend/templates/product/index.tsx
- frontend/tests/jest/__mocks__/products.ts
- frontend/tests/jest/tests/ProductReplacementGuide.test.tsx
closes #1505 
1. Open [product page preview](https://react-commerce-git-add-replacement-guides-to-sections-ifixit.vercel.app/products/iphone-6s-screen)
2. Verify that the replacement guides section is still rendered
> Refactor product page replacement guides section

- backend/src/api/product/content-types/product/schema.json
- backend/src/components/product/device-compatibility.json
- backend/src/components/product/product.json
- backend/src/components/section/lifetime-warranty.json
closes #1512 
qa_req 0
This adds to Strapi 2 default product pages section that were missing
> Adds device compatibility and lifetime warranty sections

- frontend/components/common/ProductGridItem.tsx
- frontend/components/sections/ReplacementGuidesSection.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/CurrentRefinements.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/ProductList.tsx
- frontend/templates/product/sections/CrossSellSection/CrossSellVariantCard.tsx
- frontend/templates/product/sections/ProductOverviewSection/index.tsx
- frontend/tests/jest/tests/__snapshots__/ProductListItem.test.tsx.snap
- packages/ui/commerce/ProductPrice.tsx
- packages/ui/misc/IconBadge.tsx
- packages/ui/theme/components/icon-badge.ts
- packages/ui/theme/components/product-price.ts
- packages/ui/theme/index.ts
closes #1493 
Apart from fixing #1493, I took the opportunity to work on icon badges and product prices responsiveness.
[Icon badges](https://www.figma.com/file/sfj6r7Bn6eREMvuqo0f7Du/iFixit---Components?node-id=105-5772&t=8OduiF3pdPkIZJqs-0) as well as [product prices](https://www.figma.com/file/sfj6r7Bn6eREMvuqo0f7Du/iFixit---Components?node-id=104-7133&t=jrRjObNfi3KpE3O3-0) have been designed in 3 sizes and often mockups instructed to change the size of these two components at some specific breakpoints.
Up until now, however, those components allowed only to configure a specific size for all the possible screen sizes.
This PR allows to pass to those components a `ResponsiveObject` that allows to vary their sizes at specific breakpoint values.
2. Verify that icon …
> Working on badge and product price responsiveness

- frontend/templates/product-list/sections/FilterableProductsSection/index.tsx
closes #1510 
Open a product list preview from mobile and verify that by appending `#products` the browser scrolls down to the list of products.
For example check with this link [/Tools?q=Marlin#products](https://react-commerce-git-add-products-anchor-to-product-list-ifixit.vercel.app/Tools?q=Marlin)
> Add products anchor

- .husky/pre-commit
- package.json
- pnpm-lock.yaml
Re-enables the pre-commit format hook. This uses a new tool called [lint-staged](https://github.com/okonet/lint-staged) to only format staged files, making the hook much faster than formatting all files in the repo.
Connects https://github.com/iFixit/react-commerce/issues/1026
Make an intentional formatting error, stage it, and try to make a commit. The commit should fail if the formatting error is the only change. If there are other changes, then your commit should be successful with all formatting errors fixed.
CC @danielbeardsley @sterlinghirsh
> Enable pre-commit format hoook

- .github/workflows/stress_test.yml
Stress-tests workflow wasn't running stress tests even though it found changed test files, discovered by @ardelato in https://github.com/iFixit/react-commerce/pull/1519. 
Since we didn't specify outputs for the job at the top level, it wasn't able to get the output from the previous job
so the stress-test didn't run.
Now, playwright-run and jest runs will be able to get the output from the check-diff job.
Use the following steps to test:
1. Checkout this branch. 
2. Then create a new branch: `git co -b "<testing-branch-name>"`
3. Modify some jest and playwright tests. Add, commit, and push the changes. Create a test pull request.
4. Then make sure `playwright-stress-test` and `jest-stress-test` get triggered. 
5. Confirm the modifed tests get stress-tested.
6. Then close the testing pull …
> Stress-test: specify outputs for check-diff job

- backend/src/bootstrap/permissions/config.json
closes #1529 
qa_req 0
Of course I forgot to set permissions to enable the seed of banners 🤦‍♂️ 
▶️ CI is expected to fail because it can't seed
> Add banners permissions

- frontend/components/sections/BannersSection.tsx
- frontend/components/sections/BannersSection/MultipleBanners.tsx
- frontend/components/sections/BannersSection/SingleBanner.tsx
- frontend/components/sections/BannersSection/index.tsx
- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/operations/BannersFields.graphql
- frontend/lib/strapi-sdk/operations/CallToActionFields.graphql
- frontend/lib/strapi-sdk/operations/findPage.graphql
- frontend/lib/strapi-sdk/operations/findProduct.graphql
- frontend/lib/strapi-sdk/operations/sections/BannersSectionFields.fragment.graphql
- frontend/models/components/banner.ts
- frontend/models/product/sections/index.ts
- frontend/models/sections/banners-section.ts
- frontend/templates/product/index.tsx
- frontend/templates/product/sections/ProductOverviewSection/index.tsx
closes #1532 
1. Visit a [product preview](https://react-commerce-git-add-product-banners-section-ui-ifixit.vercel.app/products/repair-business-toolkit)
2. Verify that the two types of banners are rendered according to #1532 (note that the single banner call to action button will not show an icon at this time)
3. Verify that banners sections are responsive
4. Verify you can change banners content from [Strapi](https://add-product-banners-section-ui.govinor.com/admin/content-manager/collectionType/api::banner.banner?page=1&pageSize=10&sort=title:ASC&plugins[i18n][locale]=en)
> Add product banners section UI

- frontend/tests/jest/README.md
- frontend/tests/playwright/README.md
This is a follow-up to https://github.com/ifixit/react-commerce/issues/1400 and https://github.com/iFixit/react-commerce/pull/1470#pullrequestreview-1342102872
This adds a new `README` to the `jest` directory and updates the `playwright` `README` to include information about working with mocks. This includes tips on how to easily update the mocks and how to create new ones.
Closes: #1400
> Update Test Docs to Include Working with Mocks

- packages/footer/package.json
- pnpm-lock.yaml
We are running into typechecker errors on the iFixit side when trying to update the react-commerce submodule because this package was not added to the footer package. This should fix it.
Qa_req 0 - The icons still render in the footer.
Connects to https://github.com/iFixit/ifixit/pull/47233
> Add fortawesome/solid-icons to footer package

- packages/ifixit-api-client/package.json
- packages/newsletter-sdk/package.json
- packages/tracking-hooks/package.json
- pnpm-lock.yaml
These packages use react, so we need to add the dependency. According to: https://stackoverflow.com/questions/30451556/what-is-the-correct-way-of-adding-a-dependency-to-react-in-your-package-json-for we should add it as a peer dependency and a dev dependency.
We are failing the build-assets on https://github.com/iFixit/ifixit/pull/47270, so this should fix that.
Qa_req 0
Connects to https://github.com/iFixit/ifixit/pull/47270
> Add react as dependency to new packages

- frontend/helpers/next-helpers.ts
_vercel_no_cache is being deprecated in June 2023. Since there isn't a direct replacement provided by Vercel at the moment, let's use the familiar disableCacheGets instead.
qa_req 0
Closes #1502
> Drop `_vercel_no_cache`, use `disableCacheGets`

- frontend/components/sections/SplitWithImageSection.tsx
- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/operations/sections/SplitWithImageSectionFields.fragment.graphql
- frontend/models/sections/split-with-image-section.ts
- frontend/templates/product/index.tsx
closes #1553 
~~blocked by #1554~~
1. Open [featured product preview](https://react-commerce-git-add-split-with-image-label-ifixit.vercel.app/products/repair-business-toolkit)
2. Verify that the split with image label is present (see #1553) as specified in Strapi
3. Verify that you can change the label from [Strapi](https://add-split-with-image-label.govinor.com/admin/content-manager/collectionType/api::product.product/1)
> Add split with image label

- backend/src/api/page/content-types/page/schema.json
- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/operations/findPage.graphql
- frontend/models/page/index.ts
- frontend/models/page/server.ts
- frontend/templates/page/index.tsx
close #1558
cc @sterlinghirsh @danielbeardsley @masonmcelvain 
1. Open [store home page preview](https://react-commerce-git-add-banners-section-to-page-template-ifixit.vercel.app/store)
2. Verify that the banners section is visible (see #1558 for reference)
3. Verify that the banners section is responsive
4. Verify that you can edit the banners from [Strapi](https://add-banners-section-to-page-template.govinor.com/admin/content-manager/collectionType/api::page.page/1?plugins[i18n][locale]=en)
> Add banners section to page template

- frontend/next.config.js
- packages/ui/misc/ResponsiveImage/index.tsx
We want folks who upload images to strapi to not have to care about making their images web-ready. They should be able to upload high quality, high-res images and we can then lean on next/image to downsample and re-compress them.
Yes, vercel likely clears the image cache more than we'd like, but we have cloudfront sitting in front of them, so I'm not too worried.
I've left this check in here so there's an explicit callout (strapi images should be processed by next) rather than just an absence.
Closes #1560
> ResponsiveImage: let next.js handle strapi images

- frontend/tests/playwright/fixtures/index.ts
- frontend/tests/playwright/fixtures/trace-override.ts
- frontend/tests/playwright/test-fixtures.ts
This pull request adds a new formatting fixture for trace file output paths in Playwright tests. It modifies the `testInfo.outputDir` property to create a nested directory structure that makes it easier to locate trace files for specific tests.
The new directory structure for trace files will look like this:
```bash
[subtest-directory]/test-file-name/test-name/device-name/
```
For example:
```bash
product/add_to_cart/back-to-shopping-button-works/desktop-chrome/
```
This nested directory structure will allow us to easily find the trace files for a given test as the original trace files were underneath a single directory where the directory name was a flattened version of the new directory structure.
|Before|After|
|:---:|:---:|
| …
> Reorganize the Directory Structure of the Trace files

- frontend/components/common/AppProviders.tsx
- frontend/layouts/default/index.tsx
- frontend/templates/product-list/server.tsx
- packages/app/index.tsx
Closes #1399
Renders productlist pages with typos in their Strapi instantsearch filter instead of 500ing. The misconfiguration in Strapi is reported to Sentry.
- Add an invalid filter to a productlist on this branch's [strapi instance](https://handle-productlist-filter-typos.govinor.com/admin).
- For example, on add the following filter to this [productlist](https://handle-productlist-filter-typos.govinor.com/admin/content-manager/collectionType/api::product-list.product-list/461?plugins[i18n][locale]=en).
```
(identifiers: 'IF145-472' OR 
identifiers: 'IF145-348' OR 
identifiers: 'IF145-335' OR 
(identifiers: 'IF145-077' OR 
identifiers: 'IF145-523' OR 
identifiers: 'IF145-307' OR 
identifiers: 'IF145-364' OR 
identifiers: 'IF317-092' OR 
identifiers: 'IF145-106' OR 
identifiers: …
```
> Instantsearch: Handle typos in Strapi productlist filters

- frontend/templates/product-list/server.tsx
Drops a sentry report about invalid strapi filters. We already have a UI component to alert Strapi admin users that the filter field is invalid, so reporting to Sentry is just extra noise.
qa_req 0
> Sentry: Drop invalid strapi filter reporting

- frontend/lib/ifixit-api/devices.ts
- frontend/models/product/components/product-option.ts
- frontend/models/product/index.ts
- frontend/models/product/server.ts
- frontend/pages/api/nextjs/cache/product.ts
- frontend/templates/product/server.tsx
The variant selection on our product pages isn't always in a sensible order, and Shopify doesn't help you much in terms of making product data easy to return in the order you want it to. This uses the api introduced in https://github.com/iFixit/ifixit/pull/47291 to get back the products variants sorted correctly and use that data to have the variant dropdown options display in a sensible order.
Do product page variants work correctly and have a sensible order? you can check the preset order by looking at `ifixit_cart.attribute_options` `sort_order` column.
> Product Page: Use Sorted Variants

- frontend/tests/playwright/fixtures/trace-override.ts
We added this trace fixture in https://github.com/iFixit/react-commerce/pull/1563, but while addressing https://github.com/iFixit/react-commerce/issues/1569 I noticed an issue with the trace output path. There are some test cases that have similar names, but are under different test suites. This causes the trace outputs to be overwritten.
To fix this, we can take full advantage of the `titlePath` property to create the trace output path. The `titlePath` property is a convenient array of strings that represents the relative path to the test case from root test directory. This includes the file name, the test suite tree, and the test case name.
In addition, we can refactor the `formatTestNameForDirectory` function for more general usage. As such it will now be called `formatName`. …
> Playwright: Add Test Suites to Trace Output Path

- frontend/templates/product/sections/ProductReviewsSection/index.tsx
The new react product pages didn't have the `Edit` option for reviews. This PR adds the edit button for admins.
- If you go to this [link](https://react-commerce-git-product-pages-add-admin-reviews-edit-ifixit.vercel.app/products/mako-driver-kit-64-precision-bits), for example, should now have an edit option if logged in as Admin.
- The redirect from the Edit button should be similar to how it is [here](https://www.ifixit.com/Store/Tools/Pro-Tech-Toolkit/IF145-307#)
Closes #1500
> Product pages: Add Reviews Edit Button for Admin

- .github/workflows/deploy-strapi.yml
- backend/.gitignore
Add a github action to build the strapi docker image and push it to aws ecr.
This is dependent on the IAM setup that's in a separate pull request. It has already been run, so this now succeeds (see the workflow runs on this pull!)
> Github Actions: build strapi image and push to ECR

- frontend/components/common/CompatibleDevice.tsx
- frontend/templates/product/sections/CompatibilitySection/index.tsx
- frontend/templates/product/sections/ProductOverviewSection/CompatibleDevices.tsx
- frontend/tests/jest/tests/CompatibleDevice.test.tsx
- frontend/tests/jest/tests/__snapshots__/CompatibleDevice.test.tsx.snap
Collapses the product page compatibility component when there are more than 10 model number lines.
The diff is easier to view with whitespace ignored.
It also seems like the Jest test that was changed was broken before. The product being tested only has 3 variants on the compatible device, so the previous test implementation should have produced `other model...`, however the test was asserting for `other models...`.
- Find a product with a compatible device that has >10 model numbers.
- Make sure the implementation matches the disclosure [mockup](https://www.figma.com/file/BolmFORO6ZfHXePOSyEGSS/iFixit---Page-sections?node-id=159-5560) (disregard the search bar for this PR).
- Make sure _both_ compatibility components otherwise match their `main` counterparts.
Closes …
> Product Page: Add compatibility disclosure

- .github/workflows/nextjs_bundle_analysis.yml
The `nextjs-bundle-analysis package` has been updated, which caused a change in the comment text that the search logic was previously relying on. The relevant change can be found in the following commit: hashicorp/nextjs-bundle-analysis@067cb5d
Due to this update, a new `Nextjs Bundle Analysis` comment is created on every new run instead of updating the existing comment in the PR.
This updates the comment finding logic to use a different substring and to ensure it is from the `github-actions[bot]` user. 
To avoid this issue in the future I added a specific version to use for `npx -p nextjs-bundle-analysis`. 
Closes: #1578
> GitHub Actions: Fix Duplicate Nextjs Bundle Analysis Comments

- frontend/lib/ifixit-api/devices.ts
- frontend/lib/ifixit-api/productData.ts
- frontend/models/product/components/product-option.ts
- frontend/models/product/index.ts
- frontend/models/product/server.ts
- frontend/pages/api/nextjs/cache/product.ts
- frontend/templates/product/server.tsx
A redux of https://github.com/iFixit/react-commerce/pull/1572
Same as last time but this time empty option fields fall back to shopify option values. This should solve the issues we were seeing on pages like [repair business toolkit](https://ifixit.slack.com/archives/C0252FETV2S/p1681408439081469)
Same as last time but make sure it works on the repair business toolkit as well.
> Product Page: Use Sorted Variants (with no bugs!)

- backend/strapi-deploy
Yes, the use of two repos and a hard-coded path here isn't a great idea. But since we'll be merging these two repos soon, I'm not too worried about it.
Connect iFixit/ifixit#42822
> Strapi: add deploy script

- frontend/models/product/reviews.ts
- frontend/templates/product/sections/ProductReviewsSection/index.tsx
@c00perdanny pointed out in https://github.com/iFixit/react-commerce/issues/1500#issuecomment-1507555803 that the url that the Edit button points to is incorrect. 
In https://github.com/iFixit/ifixit/pull/47399, we add the sku field to the API. This allows us to access the sku for the product that corresponds to a review.
This PR uses this new field to build the correct url. 
Closes #1500 
CC: @danielbeardsley
> Reviews Edit : Use sku for url

- backend/strapi-deploy
Just like our main app deploy
Yes, this is borrowing a tool from our main repo, but these will soon be one repo, so I'm not concerned long term.
> Strapi deploy: announce it to slack

- frontend/templates/product/sections/ProductOverviewSection/index.tsx
closes #1598 
Swapped as requested.
The first two accordion item in the list were expanded by default (`Description` and `Kit contents`)
Since `Assembly contents` has more relevance than `Kit contents` I supposed that `Assembly contents` should now be the one expanded by default.
1. Visit Vercel Preview
2. Verify that the accordions are now ordered as requested
> Swap kit contents and assembly contents position

- frontend/lib/swr-cache/index.ts
endpoint is "/api/nextjs/cache/product" and doesn't get parsed by datadog without changing our log parsing filters.
Use statName like the rest of our timing and event logs in this function.
qa_req 0  (CI + typescript is enough)
> Cache timing logs: use statName

- frontend/config/env.ts
- frontend/lib/swr-cache/index.ts
In prod, VERCEL_URL looks like: react-commerce-prod-48uflsij4-ifixit.vercel.app
While this does correct to the correct service, it's reported to the
in the logs (and thus to datadog) as a different service who's name
keeps changing. This makes filtering logs for just react-commerce logs
really hard.
Let's allow overriding this in an env var.
qa_req 0 (CI + typescript is enough)
> Cache invalidation: make request to stable host

- frontend/models/global-settings.ts
- frontend/models/page/server.ts
- frontend/models/product/server.ts
- frontend/models/store.ts
Let's get `timeAsync()` around every call so we can graph them in datadog. Previously, we were only timing `getProductList`, now we time them all.
Connect #1607
> Strapi: time all calls to strapi

- backend/build-docker-and-push
We're moving to using the standard best-practice of strapi:latest for deploys over only strapi:{commit hash}. We now tag images with both.
This makes auto-deploy easier and booting new machines easier.
Connect https://github.com/iFixit/ifixit/issues/47518
> Strapi: tag with strapi:latest as well

- backend/config/admin.ts
- backend/docker-compose.yaml
- backend/package.json
- backend/src/plugins/addons/admin/src/utils/axiosInstance.ts
- backend/src/plugins/addons/package.json
- backend/src/plugins/addons/yarn.lock
- backend/yarn.lock
closes #1606 
qa_req 0
This PR upgrades Strapi to enable the new data transfer feature which we aim to use to improve the dev/staging db seeding process. It also patches a [security vulnerability](https://github.com/strapi/strapi/releases/tag/v4.8.0).
❗ ❗  This updates requires a `TRANSFER_TOKEN_SALT` environment variable to be set (you can generate the token with `crypto.randomBytes(16).toString('base64')` in Node.js). 
We also need to set `STRAPI_ADMIN_BACKEND_URL` to an empty string (in Govinor instances having it not being set resulted in an admin client error)
deploy_block 🛑  until we've confirmed that the 2 env vars are set in production
cc @masonmcelvain @sterlinghirsh @danielbeardsley
> Upgrade strapi v4.9.2

- frontend/helpers/next-helpers.ts
- frontend/lib/swr-cache/index.ts
- frontend/templates/product/server.tsx
Connects https://github.com/iFixit/react-commerce/issues/1612
CC @danielbeardsley @dhmacs 
- Visit the vercel preview, and open up the vercel logs page in a new tab.
- Visit a product page with a `disableCacheGets` query param. Confirm that you see `cache.findProduct.force_miss` in the logs.
- Without `disableCacheGets`, the behavior of product swr caching should match `main`.
> Make `disableCacheGets` force a swr cache miss

- frontend/lib/ifixit-api/devices.ts
- frontend/lib/ifixit-api/international-buy-box.ts
- frontend/lib/ifixit-api/productData.ts
- frontend/models/product/reviews.ts
- frontend/templates/product/sections/ProductOverviewSection/AddToCart/NotifyMeForm.tsx
- frontend/templates/troubleshooting/server.tsx
- packages/auth-sdk/user.tsx
- packages/cart-sdk/hooks/use-add-to-cart.ts
- packages/cart-sdk/hooks/use-cart.ts
- packages/cart-sdk/hooks/use-checkout.ts
- packages/cart-sdk/hooks/use-remove-line-item.ts
- packages/cart-sdk/hooks/use-update-line-item-quantity.ts
- packages/ifixit-api-client/index.tsx
- packages/newsletter-sdk/index.tsx
Adds a mandatory stat name param to the iFixit API client's methods. This will help us measure timings of the same kinds of requests in DataDog, even if they are to different endpoints.
Connects https://github.com/iFixit/react-commerce/issues/1612
Verify that iFixit api requests follow the format `ifixit-api.get.stat-name` instead of `iFixit API GET:endpoint/name` in the Vercel logs.
> Add stat name to iFixit API client

- backend/docker-compose.yaml
closes #1628 
qa_req 0
deploy_block 🛑 on confirming that changing the docker compose file doesn't affect the Strapi production instance (i.e. we're not using the Docker compose file to deploy production, correct?)
cc @masonmcelvain @danielbeardsley @sterlinghirsh
> Improve Docker compose file to persist media files across re-deployments

- frontend/.eslintignore
- frontend/.eslintrc.json
- frontend/components/community/navigation.tsx
- frontend/components/community/video.tsx
- frontend/components/sections/BannersSection/SingleBanner.tsx
- frontend/helpers/application-helpers.ts
- frontend/helpers/product-helpers.ts
- frontend/helpers/product-list-helpers.ts
- frontend/lib/redis/index.ts
- frontend/models/page/sections/browse-section.ts
- frontend/models/page/sections/hero-section.ts
- frontend/models/page/sections/press-quotes-section.ts
- frontend/models/sections/ifixit-stats-section.ts
- frontend/models/sections/social-gallery-section.ts
- frontend/pages/CommunityNext/index.tsx
- frontend/templates/product-list/ProductListView.tsx
- frontend/templates/product-list/hooks/useProductListTemplateProps.ts
- frontend/templates/product-list/index.tsx
- frontend/templates/product-list/server.tsx
- frontend/templates/product/sections/CompatibilityNotesSection/index.tsx
- frontend/templates/troubleshooting/index.tsx
- frontend/templates/troubleshooting/solution.tsx
Turns on the [`no-unused-vars`](https://eslint.org/docs/latest/rules/no-unused-vars) rule, and offers prefixing with an underscore as an escape hatch.
qa_req 0
> ESLint: Turn on `no-unused-vars`

- frontend/codegen.yml
- frontend/lib/strapi-sdk/generated/validation.ts
- frontend/lib/strapi-sdk/index.ts
- frontend/lib/swr-cache/index.ts
- frontend/models/product-list/types.ts
- frontend/package.json
- frontend/pages/api/nextjs/cache/product-list.ts
- frontend/templates/product-list/server.tsx
- frontend/templates/product/server.tsx
- pnpm-lock.yaml
- Adds a [dev dependency](https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-validation-schema) ([GitHub](https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/tree/main)) to generate zod schemas for all inputs in Strapi's graphql schema.
- Adds a swr-cache endpoint to cache the product list model, with a 1 hour TTL and a 1 day SWR.
Closes https://github.com/iFixit/react-commerce/issues/1612
- Smoke test the product list pages to make sure they match main and don't produce any new errors in the logs or Sentry.
- While visiting the product list pages, open the Vercel logs and confirm that we get cache misses, stales, and hits when appropriate based on the timings listed above.
> Product list swr cache

- frontend/layouts/default/index.tsx
- packages/helpers/generic-helpers.ts
As part of next.js process, they evaluate our entire component tree from the page on down. JSX compiles into synchrnous functions that perform logic, then return something like:
React.createElement('div', attrs, children)
This process effectively involves a single run-through of our entire component tree. React then takes this resultant structure and translates it directly into html. We have a lot of control over the component code and shape. We don't have much control over (nor chance to optimize) the translation to html.
So, let's log the time take for our part on every page.
> Timing: Log time spent in synchronous component code

- frontend/helpers/strapi-helpers.ts
- frontend/models/product-list/server.ts
connects #1611
This PR removes the capping of hero images due to Strapi formats.
We remove the capping only on this section to verify that NextJS images scaling performs well and do not produce delays when downscaling large images.
If this proves effective for the hero we can think to rely more on Next image, removing the Strapi formats capping also on other Strapi provided images.
2. Verify that hero images are not capped anymore to 1000px width
3. Verify that hero images are scaled down by Next image to an acceptable size even when the originals are quite large
> Rely on Next image instead of Strapi formats for some Strapi provided images

- backend/src/components/page/category.json
- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/generated/validation.ts
- frontend/lib/strapi-sdk/operations/sections/BrowseSectionFields.fragment.graphql
- frontend/lib/strapi-sdk/operations/sections/CategoryFields.fragment.graphql
- frontend/models/page/components/browse-category.ts
- frontend/templates/page/sections/BrowseSection.tsx
closes #1633 
1. Visit [Strapi Govinor instance](https://add-browse-section-category-custom-description.govinor.com/admin/content-manager/collectionType/api::page.page/1?plugins[i18n][locale]=en)
2. Visit Content Manager > Page and view the `/Store` page
3. Verify that browse section categories have a description field
4. Write a short description for the first two categories
5. Visit the [store home page preview](https://react-commerce-git-add-browse-section-category-cu-8a0a8f-ifixit.vercel.app/Store)
6. Verify that the description field is being used
> Add browse section category custom description

- backend/src/api/product-list/content-types/product-list/schema.json
- backend/src/components/product-list/item-type-override.json
The issue is probably better to read for full context, but this pull is implementing the code to allow item type product list pages to have custom title, metatitle, description, metadescription, and tagline attributes. It allows people to set custom item type data in strapi which then gets rendered on the page. This only implements the backend changes needed.
Do product list pages still work?
Connects: https://github.com/iFixit/react-commerce/issues/589
Just the backend code from https://github.com/iFixit/react-commerce/pull/1630
> Add itemTypeOverrides to backend schema.

- .npmrc
- frontend/.npmrc
Using process.env in  #1636 seems to have broken preview deployments, see https://github.com/iFixit/react-commerce/pull/1647 for an example.
qa_req 0 If it passes CI
CC @ianrohde @danielbeardsley
> Use fontawesome env var in npmrc

- packages/cart-sdk/hooks/use-cart.ts
- packages/cart-sdk/types.ts
- packages/ui/cart/drawer/CartDrawer.tsx
- packages/ui/cart/drawer/CrossSell.tsx
We aren't upselling, technically. We are cross selling. So lets have the names be accurate.
The remaining references to "upsells" are because we don't want the code to break as we change the ifixit api response to be "crossSellProducts". Basically just so we can smoothly swap things out. 
Does the upsell section in the cart still work fine? 
Connects https://github.com/iFixit/ifixit/issues/46262
> Rename Upsell to Cross Sell

- frontend/templates/troubleshooting/index.tsx
This hides any section with the heading `Related Pages`.
We generally only have links to other troubleshooting pages in such a section, and because those links will be included as "Related Problems" cards, we don't want to include that section on the page.
https://react-commerce-git-troubleshooting-hide-related-p-fd2fc5-ifixit.vercel.app/Vulcan/Dryer_Making_Loud_Noise should be a good example page that has a "Related Pages" section which this pull should hide.
> Troubleshooting--hide-related-pages-section

- frontend/package.json
- pnpm-lock.yaml
This version removes `Liberation Mono` from the mono font stacks: https://github.com/iFixit/core-primitives/pull/40
TL;DR it improves the vertical alignment of mono fonts on Linux.
qa_req 0 - tested in https://github.com/iFixit/core-primitives/pull/40 and represents less than 1% of users.
> Bump @core-ds/primitives to `2.5.2`

- packages/ui/theme/foundations/sizes.ts
- packages/ui/theme/index.ts
Fixes a live bug as a result of https://github.com/iFixit/react-commerce/pull/1669
Revert the addition of the `primitiveBreakpoint` values from the mono theme:
- these are used differently than the mono repo so we may be able to bypass
- we'll know more as we get closer to sharing chakra themes
Main issue observed at: https://www.ifixit.com/products/nintendo-switch-joy-con-joystick
Previous correct version: https://web.archive.org/web/20230314234255/https://www.ifixit.com/products/nintendo-switch-joy-con-joystick
cc @erinemay 
Closes: https://github.com/iFixit/react-commerce/issues/1676
> Quick Fix: Revert change to theme sizes

- frontend/tests/playwright/product-list/parts-page-search.spec.ts
- frontend/tests/playwright/test-fixtures.ts
Fixes https://github.com/ifixit/react-commerce/issues/1639. 
1. Worked together with @ardelato on debugging and fixing the bug for the `findProductQueryMock` mutation. 
This deflaked most of the tests making them pass on the first try again.
2. Fixed the `parts-page-search` test by using a different way to properly clear the input field. 
1. Make sure CI is passing. 
2. Re-run the `E2E` workflow and make sure the jobs pass and don't reach the `15m` mark.
closes #1639
> Tests: Deflake flaky tests

- frontend/templates/troubleshooting/index.tsx
Address QA comment with heading font styles not fully matching design. I found more than one, so I correct them all.
https://github.com/iFixit/ifixit/discussions/46185#discussioncomment-5851368
https://www.figma.com/file/jRG4EyQXRDMGfyLqut08KP/iFixit---Working-files?type=design&node-id=12684-293207&t=BS6ygGmXZmUgAJ1D-4
1. [update page Heading styles to match design](https://github.com/iFixit/react-commerce/commit/4260c828fe08ccda469d4c2f5ed4dd5e1cbabe14)
http://localhost:3000/Vulcan/Samsung_TV_Turns_On_By_Itself
<details>
<summary>Post fix video</summary>
https://github.com/iFixit/react-commerce/assets/1634505/b4c79ffc-e55d-41b3-b152-1714efef0181
</details>
Closes: https://github.com/iFixit/ifixit/issues/47916
> Vulcan: Update styles for "First Steps" heading

- frontend/lib/redis/index.ts
closes #1671 
This PR adds a timeout for when a Redis command takes too long to respond.
From #1671
> If we don't have access to redis (connection is missing or timeout or whatever), pretend a cache miss
@danielbeardsley I've read through the code and tested it locally with a non-existent Redis server and it looks like connection errors are handled correctly an interpreted as cache misses. The only cause that came to mind for the logs that we're seeing is that a Redis command takes too long to respond.
Let me know if you think there's more to it.
I'm not sure if we want to QA this. Either way to simulate a command timeout error locally I've followed these steps:
1. **Prerequisites**: Ensure you have Redis installed and running locally on your computer. Follow the instructions in [this …
> Add command timeout to Redis client

- frontend/templates/product/sections/CrossSellSection/index.tsx
- frontend/templates/product/sections/CrossSellSection/useOptimisticAddToCart.tsx
Closes https://github.com/iFixit/ifixit/issues/47918
And also fixes a cross sell optimistic-add-to-cart image bug.
- Make sure that the current item variant on [`/products/macbook-fan`](https://react-commerce-git-variant-fallback-image-ifixit.vercel.app/products/macbook-fan) has an image.
- Observe that when you add to cart via the cross sell section, the cart drawer image no longer flickers from an empty image to the correct image. Instead, the cart item immediately has the correct image.
> Cross Sell: Fallback to group image

- frontend/models/product-list/server.ts
- frontend/templates/product-list/ProductListView.tsx
We'll now be using the "attributeForDistinct" feature. This means that for some products there will be more than one algolia document that represents it. We'll be turning on this attributeForDistinct feature which will ensure we only get one result per product in the result set. However, the result counts in the facets will show the number of documents instead of the number of products until we set this option.
See: https://www.algolia.com/doc/api-reference/api-parameters/facetingAfterDistinct/
Connect https://github.com/iFixit/ifixit/issues/47734
> Algolia: count facet results after doing distinct

- frontend/tests/playwright/msw/request-handler.ts
There was an issue with the msw request handlers for `strapi` requests. https://github.com/iFixit/react-commerce/issues/1627
After digging into the issue, it seems to be an issue with `node-fetch` or `strapi` itself. The trigger for it was 3 requests being made directly to `strapi`: `strapi.getGlobalSettings`, `strapi.getStoreList`, and `strapi.findStore`. These requests were not matched by any of the msw request handlers, so they were passed through to the real `strapi` server.
Then a `strapi.getProductList` request was made, which was matched by the msw request handler, so it was intercepted and mocked. However, this request was immediately returned while the previous 3 requests were still pending. This caused the `FetchError: socket hang up` error to be thrown by `node-fetch` as the …
> Fix MSW Handler Race Condition

- frontend/components/ui/HeadingSelfLink.tsx
- frontend/templates/troubleshooting/index.tsx
- frontend/templates/troubleshooting/solution.tsx
Adds a component to mimic the heading link functionality found on the mono, but with the link icon placed on the right side to balance design better: https://www.ifixit.com/Wiki/Dryer_Not_Spinning
<details>
<summary>Result Video</summary>
https://github.com/iFixit/react-commerce/assets/1634505/b57a1772-0688-4337-908a-b4e769b74d14
</details>
1. [create shared HeadingSelfLink component](https://github.com/iFixit/react-commerce/commit/4f3192728494f1d1c227a190c90ace41722d2181)
2. [use HeadingSelfLink component](https://github.com/iFixit/react-commerce/commit/0f0f15997ce9509784882d5a7b80574b73d43cea)
- Icon placed at the right of the text intentionally to balance design
- The icon size at a static 16px was too large for the `Causes` heading, so I added some styles to adjust based on the font …
> Vulcan: Add Anchor link on headings

- frontend/templates/troubleshooting/Resource.tsx
- frontend/templates/troubleshooting/hooks/useTroubleshootingProps.tsx
- frontend/templates/troubleshooting/server.tsx
- frontend/templates/troubleshooting/solution.tsx
Add product card links for product links in a solution.
See `/Vulcan/troubleshooting_products_test` for an example wiki.
Note that neither these cards nor guide product cards support on sale formatting for prices.
<details>
<summary>Images</summary>
Desktop/tablet
--
Mobile
--
</details>
Closes: https://github.com/ifixit/ifixit/issues/47437
> Troubleshooting: Add cards for product links

- frontend/components/common/InstantSearchProvider.tsx
https://www.ifixit.com/Shop/Spring_Yard_Sale was 404ing when you clicked on an item type, because the InstantSearchProvider rewrote the url to https://www.ifixit.com/Shop/Spring_Yard_Sale/Batteries
closes #1696
> Hotfix: Prevent 404s on `/Shop/*`

- .github/actions/pnpm-setup/action.yml
- README.md
- package.json
- pnpm-lock.yaml
1. Ran `npm install -g pnpm@8` and `pnpm install:all` to update the pnpm version to `v8`.
2. Updated the readme and `pnpm-setup` action.
Note: the vercel deployments seem to be failing because it's using an old build cache: `Restored build cache`.
1. Do a smoke test on all pages: collections (parts, tools), side cart, product pages (regular product and FPP like [rbt](https://www.ifixit.com/products/repair-business-toolkit)), and all other existing pages.
2. Make sure all features are still working, such as adding products to the cart, and searching on collection pages.
3. Do a local setup with pnpm v8 using the following steps:
- git co update-pnpm
- `run pnpm -v` and confirm that it's using pnpm v7.
- then run `pnpm store path` which will return a directory. Then remove that folder usin …
> Update pnpm to version 8

- frontend/helpers/product-list-helpers.ts
Lets use the deviceTitle to replace `[DEVICE]` in all cases. If deviceTitle doesn't exist for that productlist, we will no longer skip the override we will instead replace `[DEVICE]` with `title` instead.
Pretty much just check that it does what the overview says it will.
Connects: https://github.com/iFixit/react-commerce/issues/589
> Use DeviceTitle As Device Replacement in Item Type Overrides 

- frontend/components/common/InstantSearchProvider.tsx
- frontend/templates/product-list/server.tsx
Followup to #1697 
Verify that the item type facet on product list pages works and is:
- a button on `/Parts` and `/Shop/*`
- a link on `/Parts/*/*`
> Product List Pages: `InstantsearchProvider` cleanup

- frontend/tests/playwright/fixtures/shopify-mocked-queries.ts
- frontend/tests/playwright/product/pro-user.spec.ts
- frontend/tests/playwright/product/product-variant.spec.ts
The following two tests were failing on master because the default SKU for RBT has changed:
- `product/pro-user.spec.ts:5:8 › Pro User Test › Pro Discount Applied to Product Price`
- `product/product-variant.spec.ts:58:8 › Product Variant Tests › Switch Variants and Add To Cart`
Instead of relying on Cominor, we are now mocking RBT so it's less likely to fail if RBT gets out of stock again or edited. 
Passing E2E and stress test checks in CI is enough.
closes #1699
> E2E Tests: Don't rely on Cominor

- .gitignore
- README.md
You can pull down all the appropriate env vars with `vercel env pull`, so let's update the instructions with two ways of getting an env file.
If you don't have a vercel account, I've left (and reformatted) the previous instructions.
Closes #1617
> README: update with instructions to use vercel cli

- frontend/tests/playwright/troubleshooting/loading.spec.ts
This ensures the canonical link points at the new page and not at the original WIKI the data is sourced from. This test already passes; I just wanted to add something to confirm that it works as-expected.
qa_req 0
This only changes a test.
Closes https://github.com/iFixit/ifixit/issues/48082
> Troubleshooting: Update test to require Vulcan canonical link

- frontend/components/common/ProductGridItem.tsx
- frontend/helpers/path-helpers.ts
- frontend/helpers/product-helpers.ts
- frontend/templates/product-list/sections/FilterableProductsSection/ProductList.tsx
- frontend/templates/product/hooks/useProductPageAdminLinks.tsx
- frontend/templates/product/index.tsx
- frontend/templates/product/sections/CrossSellSection/CrossSellVariantCard.tsx
- packages/ui/slider/index.tsx
closes #1719 
This fixes #1719 as well as a couple of minor React warnings. I've also done some refactoring on the path helpers
1. Open [this product page preview](https://react-commerce-git-fix-product-links-ifixit.vercel.app/products/tesa-61395-tape)
2. Scroll to the Frequently Bought Together section and click on the pro tech toolkit card
3. Verified that you are redirected to the legacy php product page
> Link to legacy featured product pages from cross sell section

- frontend/templates/product/sections/CrossSellSection/CrossSellVariantCard.tsx
Fixes a bug where cross sell links to the pro tech toolkit and manta driver kit would 404 when the app was served on www.ifixit.com.
Related to #1720
It seems like when we use `https://www.ifixit.com/Store/Tools/Pro-Tech-Toolkit/IF145-307` with `<NextLink>`, Next.js tries to serve the page (when on www.ifixit.com) and 404s. A smart link will use a plain link for for urls that start with `https`.
CC @deltuh-vee
> Use smart link for cross sell

- frontend/components/sections/BannersSection/SingleBanner.tsx
Keeps the banner text vertically aligned if the link is missing.
Closes #1703
- Visit `/products/repair-business-toolkit`
- On https://page-header-alignment.govinor.com/admin, get rid of the banner call to action for the repair business toolkit page.
- Verify that the height of the image remains unchanged, and that the text is vertically aligned.
- With the call to action, the UI should match `main`.
> Page: Add banner link fallback spacing

- backend/package.json
- backend/yarn.lock
Closes #1738
Smoke test https://bump-strapi-4-11-0.govinor.com/admin and Next.js pages that use Strapi.
Make sure that you can successfully run `pnpm install:all` locally.
> Upgrade strapi to `4.11.0`

- frontend/models/sections/featured-products-section.ts
closes #1733 
2. Verify that using a wrong filter value in the linked featured collection makes the whole featured collection section to hide, since the default product list is currently an empty array
> Apply default featured product list in case of retrieval errors

- frontend/templates/troubleshooting/index.tsx
Remove Windows+Chrome Parts/Guides/Answers section scrollbar.
https://react-commerce.vercel.app/Vulcan/Dyson_Brush_Not_Spinning
<details>
<summary>Screenshot</summary>
</details>
[fix windows container overflow bug](https://github.com/iFixit/react-commerce/commit/c00973655185da984ab4d8c3715f852eea83dfff)
This issue is only present on Windows using Chromium browser
https://react-commerce-prod-git-vulcan-fix-windows-chrome-b883a3-ifixit.vercel.app/Vulcan/Dyson_Brush_Not_Spinning
Closes: https://github.com/iFixit/ifixit/issues/48141
> Vulcan: Fix Windows+Chrome header bar bug

- frontend/templates/troubleshooting/index.tsx
Render one of the double dividing lines only when there is a `wikiData.introduction.length`.
1. [render Spacer only on wikiData.introduction.length](https://github.com/iFixit/react-commerce/commit/f25bb0af2cad4e35a97c613d9561ada17d0b24fb)
Closes: https://github.com/iFixit/react-commerce/issues/1751
> Vulcan: Remove double dividing line if no introduction

- frontend/templates/product-list/sections/FilterableProductsSection/index.tsx
- frontend/templates/product/hooks/useInternationalBuyBox.tsx
- packages/auth-sdk/user.tsx
- packages/ui/hooks/index.ts
Now corrupt values in localStorage won't be used if they don't pass the validator (which is required to return the same type as the data or null).
Closes #1656
> localStorage: require a schema validator

- frontend/templates/page/sections/BrowseSection.tsx
Closes #1741
Searching the store homepage should navigate you to results on the "Store" tab of site search
CC @davidrans
> Store homepage: Add param to search store facet

- packages/cart-sdk/hooks/use-cart.ts
- packages/cart-sdk/types.ts
- packages/ui/cart/drawer/CartDrawer.tsx
- packages/ui/cart/drawer/CrossSell.tsx
We want to have mulitple x-sell items show up in minicart. This makes it so that happens. 
It also does away with some unnecessary `upsell` diction that i forgot to clean up previously.
For now, just make sure the cross sell works the same as before
Connects: https://github.com/iFixit/ifixit/issues/48134
> Cross Sell: Display Multiple Items

- frontend/templates/product-list/sections/FilterableProductsSection/index.tsx
We want to show the facet filter sidebar if there is only 1 product that fits the filters so that users can still deselect the filters. This implements that change.
Is there a cleaner way to do this?
Do the facet filters work the same except now if only 1 product is in the filters it still shows the filters sections with the `clear all sections`. 
Closes: https://github.com/iFixit/react-commerce/issues/1728
> Still Show Facet Filter Sidebar If 1 Product Fits Filters

- frontend/components/analytics/GoogleAnalytics.tsx
Hotfix for a small issue on main causing build failures.
Due to a typo the id was placed on the `Script` tag with src instead on the one with inline content.
According to Nextjs documentation it is needed only for inline scripts.
See https://nextjs.org/docs/messages/inline-script-id
qa_req 0
> Id is required for inline script

- frontend/components/product-list/ProductListCard.tsx
closes #1747 
2. Verify that text is kept even on mobile for `variant === medium` cards
3. Verify that the image is aligned on top
> Keep product-list card description visible on mobile

- frontend/templates/troubleshooting/index.tsx
- frontend/templates/troubleshooting/prerendered.tsx
- frontend/templates/troubleshooting/solution.tsx
We added containers to our wiki tables to handle overflow in https://github.com/iFixit/ifixit/pull/48424. Now let's get the tables looking nice on Vulcan 💅 
1. [fix overflow: block elements for parent wrappers](https://github.com/iFixit/react-commerce/commit/5ad243dc73f7ccda0477c0e6e036e1189b78f8f2)
2. [remove unnecessary DOM elements](https://github.com/iFixit/react-commerce/commit/b5c0da956846718cf8dc7c57f06430b286ebf445)
3. [add mobile overflow styling from pr 48424](https://github.com/iFixit/react-commerce/commit/7f25abb9e3186126e64d86bd82237b6fe58765ec)
4. [fix imageBox layout & tweak table styling](https://github.com/iFixit/react-commerce/commit/d4c6dd63999c657521cb5bc51c2cdd43bbb6eabe)
5. [remove unnecessary fontWeight applications](https://github.com/iFixit/react-commerce/commit/97 …
> Vulcan: fix mobile table overflow

- frontend/components/common/InstantSearchProvider.tsx
- frontend/templates/product-list/sections/ProductListChildrenSection.tsx
- frontend/templates/product-list/server.tsx
closes #1764
RouterOptions' createURL and parseURL functions were not pure anymore due to the references to `productListType`. InstantSearch seems to live across page render and to preserve the first read `productListType` value even after navigation.
It was reverted to the old logic.
closes #1765 
Intermediate states are due to the fact that Algolia share the provider across renders and if we move via Next links Algolia reacts to the url changes only after the effective page change. 
These shifts might also have an impact on CLS since page content is moved around with a not so small delay from user interaction (connects #1643)
A possible solution to this was to force regenerating the Algolia provider on every url change (as suggested …
> Correct algolia integration url handling

- frontend/templates/product-list/ProductListDeviceNavigation.tsx
- frontend/templates/product-list/SecondaryNavigation.tsx
closes #1754 
Device breadcrumbs are now shown only for devicePart collections
The additional header bar is eventually shown also to display admin user actions.
2. Verify that there is not anymore an empty bar on marketing collections
3. Verify that in case of admin user the bar is displayed to show admin actions
> Fix marketing page extra blank header

- frontend/templates/troubleshooting/prerendered.tsx
This matches the wiki view styling and applies to all featured blockquotes in Vulcan.
We still need to allow block quotes in the wysiwyg editor, but using plaintext still lets us add a featured block quote to wikis, so this won't break anything.
1. Open a vulcan wiki and add a featured block quote to the wiki text.
- Ex: https://me.cominor.com/Wiki/Edit/Dryer_Stops_Mid_Cycle
- Add this text: `[quote|format=featured]This is a featured blockquote! -Alex[/quote]`
2. Viewing the Vulcan wiki should render the block quote with this styling:
- Ex: http://localhost:3000/Vulcan/Dryer_Stops_Mid_Cycle
Part 1 of 2 for https://github.com/iFixit/ifixit/issues/48526
> Vulcan: Add featured blockquote styling

- frontend/templates/troubleshooting/solution.tsx
We currently don't render solutions link cards, such as guides or products. This was because the conditional for rendering them was off.
1. Visit a Vulcan wiki with guides or products listed under one of the solutions
- Ex: http://localhost:3000/Vulcan/Nintendo_Switch_Blue_Screen_of_Death#display-damage
2. Make sure the link cards are rendered.
Connects to https://github.com/iFixit/ifixit/issues/48545
> Vulcan: render solutions cards

- frontend/tests/playwright/product-list/filters.spec.ts
Added tests for `/Shop` pages on desktop and mobile.
Mostly re-used the existing tests with slight modifications.
The test ensures that navigating to `/Shop/xyz` page loads, and clicking on a facet keeps
the URL pathname same and adds the filter as query params. 
For example, after clicking the `Phone` Device category filter on `Shop/Samsung_Repair_Kits`
page should redirect to `/Shop/Samsung_Repair_Kits?filter[facet_tags.Device Category]=Phone`
instead of `/Shop/Samsung_Repair_Kits/Phone`.
Easier to review by commit by commit.
qa_req 0 passing ci is enough
closes #1701
> Tests: Add `/Shop` page test

- frontend/templates/troubleshooting/Resource.tsx
- frontend/templates/troubleshooting/solution.tsx
Some link cards were missing images because the product variant didn't have an image set. The variant image is not guaranteed to exist, and we have always fell back to the first product image. We didn't do that here so we were missing images.
This also removes duplicate link cards from the same solution.
1. View a Vulcan wiki with a product link card that is missing an image.
Ex: http://localhost:3000/Vulcan/Nintendo%20Switch%20Blue%20Screen%20of%20Death#display-damage (the [`Nintendo Switch Screen OLED Assembly`](http://localhost:3000/products/nintendo-switch-oled-screen-assembly) product card)
2. The link card should now have an image.
3. Viewing a solution with duplicate links should no longer show duplicate link cards
Ex: http://localhost:3000/Vulcan/Nintendo%20Switch%20Blue%20Screen%2 …
> Vulcan: fix missing linkcard images

- frontend/templates/troubleshooting/prerendered.tsx
Vimeo videos were overflowing past the page bounds on mobile. Details and screenshots of issue in https://github.com/iFixit/react-commerce/issues/1787
- I removed the previous border/padding intentionally to match youtube embeds
- `aspect-ratio` support: https://caniuse.com/?search=aspect-ratio
`Vulcan/iPhone_Bluetooth_Not_Working`
<details>
https://github.com/iFixit/react-commerce/assets/1634505/7d667bbc-1167-4a27-ba32-0dae9bd82a97
</details>
Closes https://github.com/iFixit/react-commerce/issues/1787
> fix videoFrame layout

- frontend/components/analytics/PixelPing.tsx
- frontend/templates/product/components/PixelPing.tsx
- frontend/templates/product/index.tsx
- frontend/templates/troubleshooting/hooks/useTroubleshootingProps.tsx
- frontend/templates/troubleshooting/index.tsx
QA
---
* Load a vulcan page
* Check for a network request to `https://ping.ubreakit.com/?key=ifixit%wiki%2F<SOMEID>%2Fen"`
* Ensure pixel pings for product pages [still match](https://github.com/iFixit/react-commerce/pull/1061#issuecomment-1329540342) `https://ping.ubreakit.com/?key=ifixit%product%2F<SOMEID>%2Fen"`
Closes: https://github.com/iFixit/react-commerce/issues/1790
> PixelPing: Add to Vulcan pages

- frontend/sentry.client.config.ts
Since Sentry does not show any hydration error in the last 30 days let's try to remove the sentry sampling filter.
If no further error is registered then we can consider #1209 resolved
qa_req 0
> Remove hydration errors filter

- frontend/templates/troubleshooting/server.tsx
The `Location` header supports relative URLs; let's use those to allow the browser to handle the protocol/host matching for the redirect.
This code seems to have been causing weird redirect problems in prod; I'm not sure what's going wrong, but simplifying it seems to be a good first thing to try.
Connects https://github.com/iFixit/ifixit/issues/48621
> Troubleshooting: Redirect to relative URL

- frontend/templates/troubleshooting/prerendered.tsx
We're considering adding inline SVG icons to wikitext under some conditions; this adds the necessary CSS to support them.
This is tricky to test, because we need to render some SVGs in order to see if the CSS is working. There's a parallel PR which can be checked out to start generating these SVG icons: https://github.com/iFixit/ifixit/pull/48569
With that checked out (and possibly with some caches busted), loading a problem page with links which open in a new tab should show nice icons to the right of each link.
qa_req 0 https://github.com/iFixit/react-commerce/pull/1783#issuecomment-1622529267
> Prerendered: Support SVG icons from FontAwesome

- frontend/templates/troubleshooting/hooks/useTroubleshootingProps.tsx
- frontend/templates/troubleshooting/server.tsx
After https://github.com/iFixit/ifixit/pull/48619, there is now a param to the API which will return the guides in the same shape as the /guides/id API.
This saves us multiple server-side requests.
This pull updates the code to use the flag and drops multiple requests in the process.
QA
---
* Ensure embed guides are still shown at the bottom of a section
Connects: https://github.com/iFixit/ifixit/issues/48100
> Guides: Receive from new api feature

- frontend/templates/troubleshooting/server.tsx
We have now removed the param and cut over to always sending the full guide.
Let's remove the unneeded code.
qa_req 0
Connects: https://github.com/iFixit/ifixit/issues/48100
Connects: https://github.com/iFixit/ifixit/pull/48640
> Troubleshooting API: Drop unneeded param

- .github/workflows/stress_test.yml
- frontend/tests/playwright/product/disabled-product.spec.ts
- frontend/tests/playwright/product/pro-user.spec.ts
- frontend/tests/playwright/product/product-page-and-cart.spec.ts
- frontend/tests/playwright/product/product-variant.spec.ts
Unskipped some of the skipped tests because of the next 13 update.
Since there is no way to mock the server-side api calls on next 13, we are going to use some hard-coded products.
Most of these products are stocked by a cron job on `iFixit/ifixit` side in https://github.com/iFixit/ifixit/pull/48707, so it's a bit safe, but not a permanent solution, since a data change on Akeneo could cause some of the tests to fail.
For the moment, this lets us have at least some test coverage until we merge this repo to the monorepo.
All CI checks for the playwright tests should pass.
closes https://github.com/iFixit/ifixit/issues/48312
> Tests: Unskip mocked tests

- frontend/layouts/default/LayoutErrorBoundary.tsx
- frontend/layouts/default/index.tsx
- frontend/package.json
- pnpm-lock.yaml
Closes #1655
Adds a catch-all error boundary at the layout level that renders a minimal fallback UI. Client errors will still be reported to Sentry.
This will increase the bundle size on all pages due to the installation of `react-error-boundary`. Bundlephobia [approximates](https://bundlephobia.com/package/react-error-boundary@4.0.10) it is 1.1 kb gzipped, which lines up with the ~1kb difference we see in the bundle stats.
Hiding whitespace will make the diff easier to view. The fallback UI is inspired by the [cart drawer fallback ui](https://github.com/iFixit/react-commerce/blob/547fccd5bdbb097c579b08b0ba1ce5067186291e/packages/ui/cart/drawer/CartDrawer.tsx#L120-L143).
Make sure unhandled client side errors render a page that looks like the following. Make sure the errors show up in the …
> Add top level error boundary

- frontend/next.config.js
- frontend/package.json
- packages/cart-sdk/hooks/use-checkout.ts
- packages/cart-sdk/package.json
- packages/local-storage/index.tsx
- packages/local-storage/package.json
- packages/local-storage/tsconfig.json
- packages/ui/hooks/index.ts
- packages/ui/package.json
- pnpm-lock.yaml
This pull does 2 things.
1.) Move localstorage calls into try block.
2.) Replace "deleteIem" with removeItem()
Not quite how to qa this. I was able to make sure the removeItem() works now on chrome by just loading a product page while logged in. I think the errors in question have have to do with third party cookie blocking, which makes testing it on the test sites hard.
Closes: #1798
qa_req 0
> Catch localstorage Access Errors

- frontend/tests/playwright/troubleshooting/loading.spec.ts
This updates an existing test to ensure that it doesn't break when we change what the canonical URLs look like. It also adds a new test to ensure that the Troubleshooting pages redirect to the canonical URL when it doesn't match the page URL. This is important (mildly) because it's the mechanism by which our existing (non-public) Vulcan URLs will continue to end up at the right URLs after we start using the final URLs as the canonical URLs.
> Troubleshooting: Update tests for new canonical URLs

- startReactCommerce.sh
The react commerce repo setup is starting to get long. Lets make a script that can handle all of it for a more streamlined dev experience.
1. Add your algolia api key to the `algoliaApiKey` variable
2. Run `source startReactCommerce.sh`
1. Make sure the script successfully runs on both a newly cloned repo and an existing repo.
2. Try out making a new Verdaccio account and logging into an existing account.
> React-commerce: Add startup script

- README.md
We recently migrated to using [Verdaccio](https:/verdaccio.org) as our private npm registry, #1815. That said the steps for how to retrieve a `VERDACCIO_AUTH_TOKEN` was tribal knowledge.
This updates the `README.md` with instructions on how to either create a new account or log in to our Verdaccio registry.
- ⚠️ If you do create a new _test_ user, please take note of the `username` you used so we can delete it from the registry later.
**Reference:**
https://ifixit.slack.com/archives/C01K32B4FPX/p1689354809125539
> Update README with Verdaccio Authentication Steps

- README.md
- startReactCommerce.sh
Instead, let's make the user export or define the variable when running the script.
This adds a check to make sure the variable is defined before running the script and tells the user what to do if they fail the check.
1. Run the script (`source startReactCommerce.sh`) without an algoliaApiKey env variable and make sure we stop the script and tell the user they need to export the variable.
2. Export the variable or run the script with the variable defined:
- `export algoliaApiKey=YOUR_API_KEY` and `source startReactCommerce.sh`
or
- `algoliaApiKey=xyz123 source startReactCommerce.sh`
3. The script should run successfully. Check that localhost:3000/Parts loads correctly.
CC @addison-grant
> Startup Script: Remove hardcoding algoliaApiKey

- frontend/tests/playwright/product-list/parts-page-navigation.spec.ts
This test started failing on main because the headings on the `/Parts` pages aren't showing up in CI.
Created an issue to unskip it here: https://github.com/iFixit/react-commerce/issues/1844
qa_req 0
> Tests: Skip parts-page-navigation test

- frontend/templates/troubleshooting/index.tsx
This was flagged on a Lighthouse run for HTML semantics. We are rendering NavTabs without href attributes.
This change renders a `Box` component instead of a `Link` when the href URL doesn't exist.
<details>
<summary>After Screenshot</summary>
</details>
Closes https://github.com/iFixit/react-commerce/issues/1840
> Lighthouse: Render a Box instead of a Link when no `href` prop exists

- packages/sentry/index.tsx
Closes  https://github.com/iFixit/ifixit/issues/48949
qa_req 0
> Sentry: Stop reporting http status 499 from `fetch()`

- frontend/tests/playwright/troubleshooting/loading.spec.ts
We made a change in the iFixit/ifixit repo which replaced spaces in urls with '+' characters (https://github.com/iFixit/ifixit/pull/48898).
As a result, the playwright tests in the `react-commerce` repo have started to fail because we were matching with `%20` instead of `+`.
This updates the tests with the new url format and also dropped an unnecessary `await` in the `loading.spec.ts` test.
qa_req 0 CI should pass
**Reference:** https://ifixit.slack.com/archives/C97UC89AR/p1690403596540979
> Playwright: Update Vulcan Tests

- frontend/templates/troubleshooting/index.tsx
- frontend/tests/playwright/troubleshooting/loading.spec.ts
It's live! Start indexing.
QA
---
Ensure pages have `<meta name="robots" content="index, follow">`
Closes: https://github.com/iFixit/ifixit/issues/48973
> Troubleshooting: Index!

- frontend/next.config.js
We want the troubleshooting sitemap to be visible under the `/Troubleshooting` path. Because we send all traffic for the `/Troubleshooting` path to NextJS, we need to implement the redirect here.
See the issue for the path that should work.
Closes https://github.com/iFixit/ifixit/issues/48979
> Vulcan: Redirect sitemap for `/Troubleshooting`

- frontend/templates/troubleshooting/index.tsx
Fix the device image showing on first render on mobile on Troubleshooting pages.
Any server-side breakpoints can be incorrect on the first render, causing the image to flash in/out.
Directly adding the media breakpoint with sx fixes this.
Closes: https://github.com/iFixit/ifixit/issues/48975
> Vulcan: Fix device image flash on mobile

- frontend/templates/troubleshooting/components/TagManager.tsx
- frontend/templates/troubleshooting/index.tsx
- frontend/tests/playwright/troubleshooting/loading.spec.ts
The hreflangs component was working as expected. The correct links were rendered,
but when viewing the page no links were actually rendered. It ends up we
are running into an edge case in next/head: vercel/next.js#8384
This commit adds a workaround for this issue which was suggested from the
issue mentioned above.
The fix is to invert the usage such that <Head> is used in your component.
Multiple uses of <Head> will be merged together.
Closes: https://github.com/iFixit/ifixit/issues/48856
> Vulcan Hreflangs: Get rendering

- frontend/package.json
- pnpm-lock.yaml
[As recommended to try to fix this error](https://github.com/iFixit/react-commerce/pull/1846#issuecomment-1649423093) lets update next js to the lastest version. This just upgrades patches so everything should be backwards compatible, meaning no code changes should be necessary on our end.
Does everything still seem fine?
CC @federicobadini @danielbeardsley @sterlinghirsh 
Connects: https://github.com/iFixit/react-commerce/issues/1808
Closes: #1852
> Update Nextjs to 13.4.12

- frontend/templates/troubleshooting/prerendered.tsx
Our blockquote styles need some attention. They are really thin, and it's unclear they are a quote without indentation.
https://me.cominor.com/Troubleshooting/Whirlpool_Refrigerator/Whirlpool+Freezer+Not+Freezing+Ice+Cream/509239
Modified:
- clean up border/padding styles
- increase block padding for clarity
- consistent spacing with other UI page elements
<details>
<summary>Post-fix screenshot</summary>
</details>
Closes https://github.com/iFixit/ifixit/issues/48985
> Vulcan: Refactor blockquote styles

- backend/docker-compose.yaml
- backend/package.json
- backend/src/plugins/addons/package.json
- backend/src/plugins/addons/yarn.lock
- backend/yarn.lock
Closes https://github.com/iFixit/react-commerce/issues/1867
Make sure strapi still works and is on the correct version, and smoke test product pages and product list pages.
Try running `pnpm install:all` locally and confirm you don't get a diff.
> chore(deps): bump strapi to `v4.12.1`

- frontend/helpers/cache-control-helpers.ts
- frontend/helpers/next-helpers.ts
- frontend/templates/product-list/server.tsx
- frontend/templates/product/server.tsx
I will want to expand on when the cache is disabled to aid with https://github.com/iFixit/ifixit/issues/48965. However, I noticed the caching behavior was controlled in multiple places. This pull moves the caching to a single middleware.
QA
---
See: https://github.com/iFixit/react-commerce/pull/1882#issuecomment-1664680136
> Refactor: DisableCacheGets move to cache control middleware

- frontend/helpers/cache-control-helpers.ts
- frontend/templates/product-list/server.tsx
- frontend/templates/product/server.tsx
- frontend/templates/troubleshooting/server.tsx
This related back to https://github.com/iFixit/ifixit/issues/48965#issue-1823307688
We will want to send editors to this url to bypass vercel's caching
and view the content with the edits immediately.
QA
---
Same as https://github.com/iFixit/react-commerce/pull/1882#issuecomment-1664680136 But ensure `?revisionid=HEAD` also bypasses the cache only on troubleshooting pages
Connects: https://github.com/iFixit/ifixit/issues/48965
> Revisionid param: Set to no cache if value is HEAD

- frontend/templates/troubleshooting/server.tsx
- packages/ifixit-api-client/index.tsx
This commit adds a header which we will use to bypass varnish
As an added measure I added a nice bit of logging.
QA
---
* Make an edit to a vulcan page
* Visit the page without `?revisionid=HEAD`
* Ensure the latest changes show up
Connects: https://github.com/iFixit/ifixit/issues/48965
> Troubleshooting: Bypass varnish always

- frontend/tests/playwright/product-list/parts-page-navigation.spec.ts
Previously in CI, and react-commerce vercel deployments, some of the titles and headings on the product list pages were not showing up. 
https://github.com/iFixit/react-commerce/pull/1848 fixed the issue, so we're unskipping the test.
1. Make sure the `parts-page-navigation` CI is passing in CI.
2. Make sure the headings on product list pages are showing up in the vercel deployments, see the examples from [here](https://github.com/iFixit/react-commerce/issues/1844#issuecomment-1646255972). 
closes #1844
> Tests: Unskip parts-page-navigation.spec.ts

- frontend/helpers/cache-control-helpers.ts
- frontend/pages/_error.tsx
Closes https://github.com/iFixit/ifixit/issues/49029
This instructs browsers to not cache 404s and 500s. I think it will also tell cloudfront not to cache 404s for static assets. SSR pages shouldn't be cached by cloudfront anymore https://github.com/iFixit/ifixit/pull/49130).
Make sure errors still get reported to Sentry. You can test this by running the project locally and throwing an error somewhere in the application code.
We could also check any product, product list, or troubleshooting route that 404s on the previews and make sure the correct `Cache-Control` header is set on the response. (I think this will work based on the [docs](https://nextjs.org/docs/pages/building-your-application/routing/custom-error#more-advanced-error-page-customizing), but perhaps we will have to run the …
> Prevent errors from being cached

- frontend/next.config.js
We've had some errors show up on sentry like [this](https://github.com/iFixit/react-commerce/issues/1808) since we updated `next.js`. Based on a github issue comment on the next js repo, turning `swcMinify` to `false` may stop these errors. You can read more about `swc` [here](https://swc.rs/) and [here](https://nextjs.org/docs/architecture/nextjs-compiler) but basically next js started using it to compile and it could be causing this error. Because `next.js` just changed the default from `false` to `true` and now this is changing it back, im not too worried about potential problems with this change, outside of slower build times and the like. Nevertheless, we should keep an eye on sentry when this deploys. 
Make sure the vercel preview seems fine. 
Connects: …
> Set swcMinify To False

- frontend/helpers/strapi-helpers.ts
- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/operations/findProductList.graphql
- frontend/models/components/image.ts
- frontend/models/product-list/component/product-list-child.ts
- frontend/models/product-list/server.ts
- frontend/models/product-list/types.ts
- frontend/templates/product-list/MetaTags.tsx
- frontend/tests/playwright/fixtures/strapi-mocked-queries.ts
closes #1892 
On top of addressing #1892 this PR standardize a couple of images that were not being handled by the image model schema
1. Open a [product list preview](https://react-commerce-git-remove-unused-product-list-ima-c93abc-ifixit.vercel.app/Parts)
2. Verify that child device images are still being rendered
> Remove unused product list image attribute

- frontend/helpers/next-helpers.ts
- frontend/templates/product-list/server.tsx
- frontend/templates/product/server.tsx
- frontend/templates/troubleshooting/server.tsx
We think the recent proxying change that sends *all* client headers through to the origin may have resulted in the user-agent no longer being `Amazon Cloudfront`. Thus we are now no-indexing all of prod :-(
> Robots Header: Stop no-indexing in prod

- frontend/templates/troubleshooting/index.tsx
Change the text on the button linking to Answers from "Ask a question" to "Browse our forum".
Context: https://github.com/iFixit/ifixit/issues/49125#issuecomment-1668521038
Closes: https://github.com/iFixit/ifixit/issues/49181
> Vulcan: Change "Ask a question" button text to "Browse our forum"

- frontend/config/constants.ts
- frontend/helpers/next-helpers.ts
Recently we foudn that we were no-indexing *everything* from next.js accidentally. We quickly removed that entirely:
(https://github.com/iFixit/react-commerce/pull/1901)
Now we re-add the fixed functionality.
Specifically, we want to no-index all responses that come from requests that *are not* being proxied through cloudfront. In other words, we only want www.ifixit.com/* responses to be indexed.
In the case of Troubleshooting pages, this directive conflicts with the html metatag but we've found evidence that google will listen tot he more restricive directive (noindex in this case).
> No Index: re-add for all non-cloudfront requests

- frontend/codegen/config.ts
- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/generated/validation.ts
In #1869 we upgraded Strapi and apparently some slight api changes have been introduced that trigger the sdk code generation. 
This quick PR is to push these changes into the repo. I've also taken the chance to declare zod schema for unhandled scalars so the next dev cli will not keep showing warnings about unhandled scalars. I'm using `z.unknown()` to preserve the current behaviour.
qa_req 0
> Add generated types

- frontend/lib/links.tsx
- frontend/tests/jest/__mocks__/useProductTemplateProps.tsx
We are now using a valkyrie page with a new url. This updates the two places in react-commerce code where we link to the jobs page.
Qa_req 0 - The `links.CAREERS` link is currently unused in react-commerce. The other change is with tests.
Closes https://github.com/iFixit/ifixit/issues/49218 (Part 2 of 2)
> React-commerce: Update jobs page link

- frontend/helpers/next-helpers.ts
- frontend/next.config.js
- frontend/templates/product-list/server.tsx
- frontend/templates/product/server.tsx
- frontend/templates/troubleshooting/server.tsx
@jarstelfox and I discovered this while testing something else and came up with this solution.
The short of it is, since vercel caches responses based on url only (seemingly), we can't have it changing the response based on a header. Currently, we have code here to add a "X-Robots-Tag: noindex" header if there are Cloudfront headers on a request. This works some of the time but we end up caching (and serving) responses generated for the same url, but different sets of headers.
Effectively, the requests from CF and the the requests directly to https://react-commerce-prod.vercel.app share an http cache in vercels CDN. Because of this, we need to not change our vercel responses based on headers as they aren't part of the cache key.
The most straightforward way to disallow indexing on all …
> noindex all responses

- frontend/templates/product/sections/ProductReviewsSection/index.tsx
- packages/helpers/product-helpers.ts
We weren't using the whole sku just the itemcode in the link. This meant that the links weren't working as intended. We now use the full sku in the links to link directly to the desired review.
Do reviews `edit` links for admins now directly link to the review?
Closes: #1500
> Get Edit Review Links To Link Directly To Review

- frontend/lib/ifixit-api/productData.ts
- frontend/models/product/index.ts
- frontend/templates/product/sections/CompatibilityNotesSection/index.tsx
- frontend/templates/product/sections/ProductOverviewSection/CompatibilityNotes.tsx
Closes https://github.com/iFixit/ifixit/issues/49081
Fixes the product page to show the count of compatible devices instead of the count of the characters.
Also adds support for receiving a list of devices from the api, instead of a string of devices delimited by newlines. I'd like to make an API change to use this data format so we don't have to do parsing on the frontend.
Visit https://www.cominor.com/products/ice-bucket-assembly-da97-14504c
(cominor api url https://www.cominor.com/api/2.0/store/product/ice-bucket-assembly-da97-14504c)
The text should say 297 more devices, not 5773.
> Product page: Fix compatibility notes count

- frontend/components/sections/FAQsSection.tsx
- frontend/helpers/ui-helpers.ts
- frontend/templates/product-list/sections/HeroSection.tsx
Slack conversation: https://ifixit.slack.com/archives/C01GMQXJC95/p1692141525169339
This change correctly renders markdown from Strapi FAQ answers on featured product pages.
snarkdown is about 1kb and we import it on the product page in this change, so the +1kb bundle size diff on product pages makes sense.
Add some markdown syntax to a strapi faq on https://product-page-faq-markdown.govinor.com/admin/content-manager/collectionType/api::faq.faq
Link the faq to a featured product on https://product-page-faq-markdown.govinor.com/admin/content-manager/collectionType/api::product.product
When you visit the featured product page on this preview, you should notice that the markdown text is rendered correctly when the appropriate faq is expanded.
> FAQ fix: Render markdown

- frontend/templates/product/index.tsx
- frontend/templates/product/sections/ProductOverviewSection/index.tsx
We were always showing compatibility notes, even when empty.
This shows as an empty compatibility notes section on any product where compatibility notes isn't set, like most of them.
https://www.ifixit.com/products/iphone-x-replacement-battery
Connects https://github.com/iFixit/ifixit/issues/49081
> Only show compatibility notes when length > 0

- frontend/lib/ifixit-api/productData.ts
- frontend/models/product/index.ts
- frontend/templates/product/sections/CompatibilityNotesSection/index.tsx
- frontend/templates/product/sections/ProductOverviewSection/CompatibilityNotes.tsx
- frontend/templates/product/sections/ProductOverviewSection/index.tsx
Connects https://github.com/iFixit/ifixit/issues/49081
Now that the iFixit product api only returns an array of compatibility note device strings, we can narrow our types.
Make sure the compatibility notes section works the same as on `main`.
Here is a product that has compatibility notes: https://www.cominor.com/products/ice-bucket-assembly-da97-14504c
There are many products without them
> Product page: Compatibility notes api update

- frontend/templates/product-list/sections/HeroSection.tsx
Closes https://github.com/iFixit/ifixit/issues/48955
This change includes:
- Shows the Hero tagline and description on pages 2+ when a backgroundImage is also shown
- If there isn't a backgroundImage, Hero tagline and description won't be shown on pages 2+
- Using non-breaking spaces between the ` - Page <num>`
> HeroSection: Show tagline and description on page 2+ with image

- .github/workflows/main.yml
- frontend/playwright.config.ts
Drops `Firefox` from the playwright projects list.
Playwright tests running on `Firefox` take the longest time and usually cause
timeout which leads to failing CI. `Firefox` has been historically slower than `Chrome`
and only `~3.4%` of our users use Firefox, see https://github.com/iFixit/react-commerce/issues/1871#issuecomment-1684389877. 
- `Desktop Firefox` should no longer be part of `E2E` CI checks. 
- Passing is enough. 
connects #1871
> Tests: Drop Firefox from playwright projects

- frontend/templates/product-list/server.tsx
Closes #1911
Fixes a bug where any kind of strapi product list could be viewed on /Tools/*
Slack conversation: https://ifixit.slack.com/archives/C02KMFEHX62/p1691797628050609
Marketing pages should no longer be viewable on tools urls. For example, `/Shop/Sale` should still exist, but `/Tools/Sale` should now permanently redirect to `/Shop/Sale`. All existing marketing product lists can be viewed in Strapi:
Additionally, `/Tools/[handle]` should no longer render a page for any valid strapi handle (unless the handle belongs to a tools category or marketing Strapi product list). For example, `/Tools/camera`, `Tools/Parts`, and `/Tools/Tools` should now all 404.
> Productlist Fix: Only show tools on `/Tools/*`

- packages/cart-sdk/hooks/use-cart.ts
- packages/cart-sdk/types.ts
Closes https://github.com/iFixit/ifixit/issues/45708
The retail discount is a new field that factors in the retail (aka compare at) price when it is set, otherwise it is the same as the `discount` field.
Test all combinations of discounts and make sure that the Next.js product page, the Next.js cart drawer, and checkout all align with each other (except for employee discounts, which only appear in checkout).
You can edit a product in akeneo.cominor.com to change it's price and retail (aka "compare at") price, as well as price tier overrides. Default pro percent off discounts are defined in `ifixit_cart.customer_discounts`, and apply to products when "Reseller Discount" is enabled in Akeneo.
> Minicart: Use retail discount from api

- frontend/layouts/default/server.ts
- frontend/lib/cache.ts
- frontend/models/global-settings.ts
- frontend/models/store.ts
- frontend/templates/page/server.tsx
- frontend/templates/product-list/server.tsx
- frontend/templates/product/server.tsx
- frontend/templates/troubleshooting/server.tsx
Closes https://github.com/iFixit/ifixit/issues/49358
Forces an LRU cache miss on Strapi layout data (global settings, stores) when the ?disableCacheGets query param is present.
Make sure the original problem is solved:
> When I made an edit to a footer link in Strapi, the edit didn't immediately show immediately when I used ?disableCacheGets. I refreshed a few times and checked various pages. Some time later the change had applied.
https://force-miss-strapi-layout-cache.govinor.com/admin
> `?disableCacheGets` on strapi layout data

- frontend/templates/troubleshooting/index.tsx
I'd not realized that the ToC wasn't shipped yet, so we didn't want to hide the `Causes` list on desktop yet.
Please confirm that the Causes list is visible on both Desktop and mobile
Closes https://github.com/iFixit/ifixit/issues/49627
> Vulcan: Show `Causes` list on desktop and mobile

- frontend/templates/product/sections/ProductOverviewSection/GenuinePartBanner.tsx
As per title, this PR enables the Google genuine part banner logo, that was still commented out in code.
qa_req 0
> Enable Google genuine part banner logo

- backend/src/api/faq/content-types/faq/schema.json
- backend/src/api/product-list/content-types/product-list/schema.json
- backend/src/api/reusable-section/content-types/reusable-section/schema.json
- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/generated/validation.ts
Part of #1940 
qa_req 0
This PR expands the Strapi FAQ collection type with the fields that are necessary to accomplish an MVP for #772.
Allowing complex filtering capabilities to determine whether an FAQ should be visible or not in a product list is tricky and can result in a complex interface for the editors. 
We've explored many solutions and during last week iOP meeting we agreed on getting started with a simple version that only allows to apply an item type filter (e.g. an FAQ that only applies to "Batteries"). This will help us ship an initial implementation and iterate afterward on filtering capabilities as needed.
> Add placement fields to Strapi FAQ

- frontend/templates/troubleshooting/index.tsx
Update the Causes introduction icon from `InfoCircle` to `List`
[Figma link](https://www.figma.com/file/QVLUEpDVoyiMM4MXEGq1L9/iFixit---Problems?type=design&node-id=201-65621&mode=design&t=qzcftwURjqxSnmrO-0)
<details>
<summary>Post-update</summary>
</details>
Test on `Troubleshooting/Nintendo_Switch/Will+Not+Turn+On/481634`
Closes https://github.com/iFixit/ifixit/issues/49674
> Vulcan: Update Causes introduction icon

- frontend/app/(defaultLayout)/Troubleshooting/[device]/components/Header.tsx
- frontend/app/(defaultLayout)/Troubleshooting/[device]/components/ServerHeader.tsx
- frontend/app/(defaultLayout)/Troubleshooting/[device]/page.tsx
- frontend/app/(defaultLayout)/components/GoogleAnalytics.tsx
- frontend/app/(defaultLayout)/components/IFixitPageFrame.tsx
- frontend/app/(defaultLayout)/components/Matomo.tsx
- frontend/app/(defaultLayout)/layout.tsx
- frontend/app/(defaultLayout)/not-found.tsx
This PR moves from the previous hello-world-app-router one (https://github.com/iFixit/react-commerce/pull/1950) and:
- removes the 'use client' directive inside `(defaultLayout)/layout.tsx` since that was meant to be a server component
- explicitly mark the page.tsx as an async server component, since there we will need to perform data fetching
- refactor a bit the file structure
qa_req 0
> Improve hello world app router

- frontend/config/env.ts
- frontend/helpers/vercel-helpers.ts
- frontend/sentry.client.config.ts
- frontend/sentry.edge.config.ts
- frontend/sentry.server.config.ts
Closes #1942
Adds a boolean tag (`current_production`) to all Sentry events indicating whether the deployment is the current production deployment.
Throw an error somewhere in local dev. Make sure the new tag (`current_production`) shows up in Sentry. It should be `false` for local dev.
> Sentry: Tag production deployment status

- frontend/components/sections/FAQsSection.tsx
- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/operations/FAQFields.fragment.graphql
- frontend/lib/strapi-sdk/operations/components/FAQFields.fragment.graphql
- frontend/lib/strapi-sdk/operations/findProductList.graphql
- frontend/lib/strapi-sdk/operations/findReusableSections.graphql
- frontend/models/components/faq.ts
- frontend/models/product-list/sections/index.ts
- frontend/models/product-list/sections/reusable-sections.ts
- frontend/models/product-list/server.ts
- frontend/models/reusable-section/index.ts
- frontend/models/reusable-section/server.ts
- frontend/models/sections/faqs-section.ts
- frontend/templates/product-list/ProductListView.tsx
- frontend/templates/product-list/hooks/useAvailableItemTypes.ts
closes #1940
This PR introduces the first iteration of bulk assignment for FAQs. The key features are:
- An FAQ can be linked to multiple product lists.
- The FAQ will be visible on every linked product list as well as their descendants, assuming an FAQs section is present. A reusable FAQs section [is already configured in this brannch](https://implement-reusable-faqs.govinor.com/admin/content-manager/collectionType/api::reusable-section.reusable-section/3).
- FAQs can belong to a category.
- On each product list, only one FAQ per category is displayed. Descendant FAQs take precedence over ancestor FAQs.
- All FAQs without a category are displayed.
- FAQs can be filtered by item type (e.g., "Batteries").
- If set, the FAQ will be displayed only if the product list contains items of that …
> Add bulk FAQs assignment

- frontend/pages/_app.tsx
- packages/sentry/index.tsx
We are having a ton of unhandledrejections filling up our sentry logs and the info they have for debugging isn't helpful enough to debug what is going wrong. This should add some more errors to our logs, but will at least we should have better/more specific error data.
Check if unhandled rejections are being sentry logged now. You can trigger an unhandled rejection easily by inserting the following code into the file `_app.js` in `myApp()`
```tsx
new Promise((resolve, reject) => {
reject(new Error("This is a custom error"));
});      
``` 
Connects: #1913
> Log More Info About Unhandled Rejections

- .vscode/settings.json
We've got some useful [default settings in the mono](https://github.com/iFixit/ifixit/blob/master/.vscode/settings.default.json). Let's port over the ones that make sense to commerce.
Settings that rely on an extension (e.g. [cSpell](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)) are ignored when the extension isn't installed or disabled.
> VSCode: Port applicable settings

- frontend/components/sections/ServiceValuePropositionSection.tsx
- frontend/templates/product/index.tsx
- frontend/templates/product/sections/ProductOverviewSection/index.tsx
closes #1969 
I left the `1PM` note as suggested by @sterlinghirsh [comment](https://github.com/iFixit/react-commerce/issues/1969#issuecomment-1716625196)
1. Open [Vercel Preview](https://react-commerce-3q1bj2i2g-ifixit.vercel.app/products/asus-c302ca-laptop-battery) for a product shipped by Encompass
2. Verify that "Same day shipping if ordered by 1PM Pacific" value proposition is present
> Drop dropshipping check for value proposition

- frontend/templates/troubleshooting/index.tsx
Fix whitespace between the bottom of the Introduction section and the "First Steps" heading.
<details>
</details>
`Troubleshooting/Google_Phone/Google+Pixel+Overheating/479437`
Closes https://github.com/iFixit/ifixit/issues/49892
> Vulcan: Fix First Steps Spacing

- frontend/templates/troubleshooting/index.tsx
wikiData.introduction is undefined
wikiData.introduction[0] is also undefined
We just want to ensure it's an empty section to move on
https://ifixit.slack.com/archives/C90126AN4/p1695319975585399
> Fix: Ensure we correctly handle no intro

- frontend/tests/playwright/product/product-page-and-cart.spec.ts
The fake test products are not working when trying to checkout.  
- https://www.cominor.com/products/playwright-out-of-stock-product
- https://www.cominor.com/products/playwright-low-stock-product
Checking out actual products is working. It looks like the test products exist properly on Shopify
but something might be going wrong on iFixit/ifixit side.
qa_req 0
cc: @jarstelfox
> Tests: skip product-page-and-cart.spec.ts

- frontend/sentry.client.config.ts
- frontend/sentry.server.config.ts
There were two reasons we didn’t see the error.
1. The first is that react-commerce errors went to [#errors-store](https://ifixit.slack.com/archives/C03SL3EF40H), but we fixed this by archiving that channel and we now send all react-commerce errors to [#errors](https://ifixit.slack.com/archives/C5BJE8ALF)
2. The second is that we are reporting the environment for 500 errors as ‘development’. Our error reporting only pays attention to ‘production’ environment errors. I’m not sure how Sentry automatically categorizes some errors as development or production, but I do know that we are not specifying the environment in the sentry config ([docs](https://docs.sentry.io/platforms/python/guides/logging/configuration/environments/?original_referrer=https%3A%2F%2Fwww.google.com%2F)).
So, as a …
> Set environment for sentry errors

- frontend/components/common/InstantSearchProvider.tsx
See https://ifixit.sentry.io/issues/4511266043/?project=6469069
All the urls are invalid and look like pen testers.
Let's stop hearing about them by bypassing the parsing failure.
Using the origin as the url means the user is show a valid search page still. i.e. we 200 instead of 500.
qa_req 0
Closes #2005
> Next/Sentry: Ignore bad urls from pen testers

- backend/config/plugins.ts
- backend/config/server.ts
- backend/package.json
- backend/yarn.lock
- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/generated/validation.ts
- pnpm-lock.yaml
I decided to go with https://github.com/ComfortablyCoding/strapi-plugin-publisher as it is slightly more robust: More devs, longer lived, more releases, newer releases, more downloads etc
QA
---
* I had to run the following to kick over strapi locally
* `cd backend/ &&  rm -rf .cache/ node_modules/ dist/`
* Then `cd ../ && pnpm install:all`
* After running `pnpm dev` strapi should allow scheduling
* Note: The scheduling UI does not appear until after the first save of an item
Before:
Click save once, then you should see: 
* Note: [You can not see if something is scheduled in the list view](https://github.com/ComfortablyCoding/strapi-plugin-publisher/issues/95)
Closes: https://github.com/iFixit/ifixit/issues/50009
> Strapi: Allow scheduling content to be published / unpublished

- backend/src/api/product-list/content-types/product-list/schema.json
- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/generated/validation.ts
We wanted to be able to highlight some products on product list pages by surfacing or boosting them to the top of the results. This pull allows us to do that by using algolia's optionalFIlters.
These are the required strapi backend changes to facilitate that.
To product list pages still work?
Connects: #2014 
Closes: https://github.com/iFixit/ifixit/issues/50010
> ProductList: Add Optional Filters To Backend

- .github/actions/pnpm-setup/action.yml
The Next.js Bundle Analysis action began failing. @batbattur  discovered that the default pnpm version was bumped to 8.9.0 while the prior version was 8.8.0. 
To address this let's pin the pnpm version to 8.8.0 instead of a just a major semver range of v8.
qa_req 0 CI should pass
**Reference:** https://ifixit.slack.com/archives/C01DBJK0H7U/p1696882385520809
> CI Fix: Pin Pnpm Version to 8.8.0

- frontend/templates/product/sections/ProductOverviewSection/AddToCart/NotifyMeForm.tsx
- packages/ifixit-api-client/index.tsx
See: https://ifixit.slack.com/archives/C90126AN4/p1697489648458609
We had hid the response status away from devs in favor of a decent
default implementation.
Sometimes we may want to vary from the default implementation of throwing if not a 200
and instead, handle error codes ourselves.
QA
---
Check the notifyWhenSkuInStock input with `something@something` without a `.com`
Closes: https://github.com/iFixit/ifixit/issues/50266
> notifyWhenSkuInStock: Add a nicer error handler

- frontend/components/common/PrerenderedHTML.tsx
It looks like we missed porting over the PHP app styles to Vulcan for blockquotes 1:1. Let's get the blockquotes polished up.
<details>
<summary>After Screenshots</summary>
</details>
Blockquote: `/Troubleshooting/Whirlpool_Refrigerator/Leaking+Water/509236`
Featured Blockquote: `Troubleshooting/Stove/Oven+Not+Turning+On/509246`
Closes https://github.com/iFixit/ifixit/issues/50276
> Vulcan: Blockquote Style Pass

- frontend/templates/troubleshooting/index.tsx
Mattia updated the design for the Related Problems Heading. Let's update the spacing we have to match.
[figma.com/file/QVLUEpDVoyiMM4MXEGq1L9/iFixit---Problems?node-id=296%3A42472&mode=dev](https://www.figma.com/file/QVLUEpDVoyiMM4MXEGq1L9/iFixit---Problems?node-id=296%3A42472&mode=dev)
`/Troubleshooting/Nintendo_Switch/Will+Not+Turn+On/481634`
<details>
</details>
Closes https://github.com/iFixit/ifixit/issues/50262
> Vulcan: Update Related Problems Heading Spacing

- frontend/components/common/PrerenderedHTML.tsx
- frontend/templates/troubleshooting/index.tsx
We have viewport overflow on mobile, narrowed down to the `pre` element.
- issue was in the parent display
- add top margin to separate from surrounding content
`/Troubleshooting/Whirlpool_Refrigerator/Making+Humming+Noise/509241#Section_Faulty_Compressor_Components`
<details>
<summary>Before/After Screenshots</summary>
</details>
Closes https://github.com/iFixit/ifixit/issues/50246
> Vulcan: Fix mobile content overflowing the viewport

- frontend/layouts/default/index.tsx
- packages/analytics/piwik/index.tsx
- packages/auth-sdk/user.tsx
- packages/helpers/shopify-helpers.ts
This pr introduces code to track the preferred store of a user in their piwik session. It first tries to use the users preferred langid from their ifixit account. If there isn't a user for the current session,  it just defaults to the current store's langid (which should always be EN now).
Make sure the `preferredStore` is correctly logged in piwik. Make sure that it uses the ifixit user's langid if they are logged in, and "EN" if not.
Closes: #2017
> PPRO: Add Custom Dimension Tracking for PreferredStore

- packages/auth-sdk/user.tsx
Fix issue that we had with lang id where you would get
> PPRO: Let Langid be optional.

- frontend/components/common/PrerenderedHTML.tsx
- frontend/templates/troubleshooting/index.tsx
We had a regression in spacing for our `prerendered` containers recently. We're effectively doubling the spacing between the headings and the content.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
Closes: https://github.com/iFixit/ifixit/issues/50307
> Vulcan: Refactor `prerenderd` margins

- frontend/templates/troubleshooting/hooks/useTroubleshootingProps.tsx
- frontend/templates/troubleshooting/index.tsx
1. We now have the count of associated problems from the api, so lets add the count and a link to the troubleshooting section of the parent device wiki.
2. This matches the styles in the [figma mockup](https://www.figma.com/file/QVLUEpDVoyiMM4MXEGq1L9/iFixit---Problems?type=design&node-id=296-42468&mode=design&t=U0qVoPpyOePi4fOw-0).
- Make sure the new component matches [the mockup](https://www.figma.com/file/QVLUEpDVoyiMM4MXEGq1L9/iFixit---Problems?type=design&node-id=296-42468&mode=design&t=U0qVoPpyOePi4fOw-0). 
- Try it out troubleshooting pages with [zero](http://localhost:3000/Troubleshooting/iPhone_11/Will+Not+Turn+On/478192), one, and [multiple related problems](http://localhost:3000/Troubleshooting/Refrigerator/Compressor+Not+Running/505022).
Closes …
> Add related problems count to troubleshooting page

- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/templates/troubleshooting/index.tsx
This PR fix a markup nesting issue.
I think it was the reason why Sentry showed an high number of non crash-free sessions recently.
2. No visible change should be present.
3. As soon as released we should see crash-free sessions going back to normal
> Fix troubleshooting page markup error

- frontend/templates/troubleshooting/index.tsx
There appears to be a Chakra bug or conflict when trying to use `display` and `noOfLines` on a Text component. Resolve this.
Also, below our `desktop-xxl` breakpoint, our `RelatedProblems` layout isn't rendering in a column.
Matches design spec https://www.figma.com/file/QVLUEpDVoyiMM4MXEGq1L9/iFixit---Problems?node-id=296%3A44439&mode=dev
<details>
https://github.com/iFixit/react-commerce/assets/1634505/82f91e1b-ab11-4134-929d-6e0755100256
</details>
`Troubleshooting/iPhone_11/Will+Not+Turn+On/478192`
Closes https://github.com/iFixit/ifixit/issues/50335
> Vulcan: Fix RelatedProblems layout

- frontend/components/common/PrerenderedHTML.tsx
This fixes a regression introduced by #1946 where the rich text component has been replaced with one that does not support refs:
This adds refs support to the `PrerenderedHTML` component
Verify that rich text is still correctly rendered (check product list page hero description, or look at wiki text in troubleshooting pages)
> Fix prerendered html component ref

- frontend/.env.development
- frontend/app/(defaultLayout)/components/IFixitPageFrame.tsx
- frontend/components/analytics/GoogleAnalytics.tsx
- packages/analytics/google/index.tsx
- packages/analytics/package.json
- pnpm-lock.yaml
Adds the preferred store and preferred language (always english in react-commerce).
1. Apply this diff _before running `pnpm install:all`_
<details><summary>Diff</summary>
<p>
```diff
NEXT_PUBLIC_GA_KEY=UA-30506-1
-NEXT_PUBLIC_GA_DEBUG=
-NEXT_PUBLIC_GA_URL=
-NEXT_PUBLIC_GTAG_ID=
+NEXT_PUBLIC_GA_DEBUG=true
+NEXT_PUBLIC_GA_URL=https://www.google-analytics.com/analytics_debug.js
+NEXT_PUBLIC_GTAG_ID=G-5ZXNWJ73GK
NEXT_PUBLIC_ALGOLIA_PRODUCT_INDEX_NAME=dev_product_group_en
NEXT_PUBLIC_DEFAULT_STORE_CODE=test
```
</p>
</details> 
2. Make sure the custom dimensions show up in [GA4 debugger](https://analytics.google.com/analytics/web/#/a30506p383872824/admin/debugview/overview) when an event is fired.
3. The language dimension should now match the language of your logged in user on Cominor. …
> GA4: set custom dimensions

- frontend/app/layout.tsx
- frontend/package.json
- frontend/pages/_app.tsx
- pnpm-lock.yaml
We've tested Vercel Analytics but eventually we disabled it from the dashboard because of pricing and the fact that we were not really using it. This PR gets rid of the dependency on our project
qa_req 0
> Remove Vercel Analytics

- frontend/templates/product-list/sections/HeroSection.tsx
closes #2050 
1. Open a vercel [product page preview](https://react-commerce-git-fix-product-list-title-regression-ifixit.vercel.app/Parts/DJI_Phantom_4_Pro_Remote_Controller_with_Built-In_Screen)
2. Verify that the issue described by #2050 is no longer present
> Fix product list title regression

- packages/auth-sdk/user.tsx
We got thousands of sentry events overnight notifying us that the value "null" failed the user schema validation. Let's bail early with no validation in that case.
Slack: https://ifixit.slack.com/archives/C04C05FA3EH/p1698329545488009
Sentry: https://ifixit.sentry.io/share/issue/d7d55c09325f4e55880ffdeea3c7e202/
Followup to: https://github.com/iFixit/react-commerce/pull/2038
qa_req 0 when this deploys, we can validate that it's working be observing whether the sentry events start trending down
> User SDK: Don't validate null user data

- frontend/templates/product/sections/ProductOverviewSection/CrossSell/index.tsx
closes #1910 
Let's fix how we record "frequently bought together" add to cart event. Switching to using the add bundle function of the cart sdk should do the trick.
@addison-grant This PR should fix Piwik tracking. I saw that the GA4 cart tracking has been added recently, is it working as intended? If not I can look into it in another pull.
Not sure how to QA this, @masonmcelvain do we have a way to test Piwik event tracking in staging environments?
Since we're not tracking events correctly for this anyway, I think it's also fine to merge this and see if newer events in production are correct.
> Use bundle add to cart for cross sell items

- frontend/templates/product-list/sections/FilterableProductsSection/Pagination.tsx
If pagination page is the first page dont add search params. We don't need p=1 as a url parameter when its the same page as the url by itself. Lets just always use the canonical url.
You can read the issue and find it pretty straightforward, but basically for pagination on collection list pages we don't need search params for the first page. 
Closes: https://github.com/iFixit/ifixit/issues/50321
> Pagination: Don't Use Search Params On First Page

- frontend/templates/product-list/sections/FilterableProductsSection/facets/useCreateItemTypeURL.tsx
When someone is on a collection list page that isn't page 1, we append a `p=<pageNumber>` to the filter links. This is unnecessary and potentially detrimental. So lets stop adding that param.
Make sure collection list filters don't add `p` anymore to their links, even if one a current page where p=<1. 
Make sure this works for mobile and desktop.
You can read more on the issue for more specificity.
Closes: https://github.com/iFixit/ifixit/issues/50411
> Filters: Don't Add "P" URL Param To Links

- frontend/components/common/PrerenderedHTML.tsx
We have clipping on our ordered lists on mobile: https://www.ifixit.com/Troubleshooting/iPhone/Will+Not+Connect+to+WiFi/481127
<details>
<summary>Screenshot</summary>
</details> 
[Slack thread](https://ifixit.slack.com/archives/CDFNZ4N4A/p1697855660963489)
Primary issue observed at `/Troubleshooting/iPhone/Will+Not+Connect+to+WiFi/481127`
We'll need to keep Desktop in mind as well for regressions, but since this is more targeted than the previous application, I don't expect any.
Closes https://github.com/iFixit/ifixit/issues/50343
> Vulcan: Fix numbered list clipping

- packages/icons/misc/FaIcon.tsx
FaIcon had its types changed and a cast added as part of the TS 5 upgrade. (fe1ebadfb0109db9e65205da3b07e413a8a042c7). This removes some of the changes, in an attempt to support the full range of possible types which the `color` prop supports (e.g., ResponsiveArray types).
qa_req 0
This only affects types, so no QA should be needed.
> Simplify FaIcon types

- packages/ifixit-api-client/package.json
This gives us a way to easily get access to the `@ifixit/sentry` version that's being used, rather than needing to override a dependency of a dependency to configure that version.
qa_req 0
As long as this builds, it shouldn't affect functionality, as we're already using `@ifixit/sentry` in `frontend`.
CC @jarstelfox
Connects https://github.com/iFixit/ifixit/issues/50513
> ifixit-api-client: Use peer version of `@ifixit/sentry`

- frontend/components/common/InstantSearchProvider.tsx
- frontend/helpers/product-list-helpers.ts
I chose not to include it in the query params filter on URL generation
This pull still supports the old URL style as well.
QA
---
The works-in filter should be correct for:
* http://localhost:3000/Parts/PlayStation_4:CUH-11XXA 
* http://localhost:3000/Parts/PlayStation_4?filter%5Bworksin%5D=PlayStation%204%20CUH-11XXA
* http://localhost:3000/Parts/PlayStation_4?filter%5Bfacet_tags.Capacity%5D%5B0%5D=1%20TB 
* http://localhost:3000/Parts/PlayStation_4:CUH-11XXA?filter%5Bfacet_tags.Capacity%5D%5B0%5D=1%20TB
* http://localhost:3000/Parts/PlayStation_4
* http://localhost:3000/Parts/iPod_Mini?filter%5Bworksin%5D=iPod%20Mini%20A1051%202nd%20gen%204%20GB
For clarity both `Parts/PlayStation_4:CUH-11XXA` and `PlayStation_4?filter...` should work. We will prefer the `:` version of the works in …
> Worksin: Support passing it via the url

- frontend/helpers/metadata-helpers.ts
- frontend/helpers/path-helpers.ts
- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/operations/findPage.graphql
- frontend/models/page/index.ts
- frontend/models/page/server.ts
- frontend/models/product-list/server.ts
- frontend/templates/page/index.tsx
- frontend/templates/page/meta-tags.tsx
- frontend/templates/product-list/MetaTags.tsx
- frontend/templates/product-list/hooks/useItemTypeProductList.ts
- packages/helpers/generic-helpers.ts
closes https://github.com/iFixit/ifixit/issues/50536
1. Open [Strapi Govinor preview](https://add-page-template-metatags.govinor.com/admin/content-manager/collectionType/api::page.page/2?plugins[i18n][locale]=en)
2. Change store home page meta title and description
3. Verify that the [store home page preview](https://react-commerce-git-add-page-template-metatags-ifixit.vercel.app/Store) has page title and meta tags (title, description and `og`) that reflect what's been set in Strapi
> Add page template meta tags

- frontend/templates/troubleshooting/Problem.tsx
- frontend/templates/troubleshooting/index.tsx
Update Vulcan sidebar image aspect ratio to match our images. Previously set at 1:1, but images are 4:3.
Mattia may have updates to the design at a later time ([Figma discussion](https://www.figma.com/file/QVLUEpDVoyiMM4MXEGq1L9?node-id=201:65526&mode=dev#600241124)), but this resolves the issue for now.
Verify Image ratio has been updated and looks good on mobile/desktop.
`/Troubleshooting/Mac_Laptop/MacBook+Will+Not+Turn+On/483799`
> Vulcan: Sidebar: Update Image Aspect Ratio

- frontend/layouts/default/index.tsx
- frontend/templates/page/meta-tags.tsx
This PR improves rendering of meta tags by introducing React keys to deduplicate duplicate meta tags
qa_req 0
> Add React keys to meta tags

- backend/src/api/product/content-types/product/schema.json
- backend/src/api/screwdriver-bit-type/content-types/screwdriver-bit-type/schema.json
- backend/src/api/screwdriver-bit-type/controllers/screwdriver-bit-type.ts
- backend/src/api/screwdriver-bit-type/routes/screwdriver-bit-type.ts
- backend/src/api/screwdriver-bit-type/services/screwdriver-bit-type.ts
- backend/src/api/screwdriver-bit/content-types/screwdriver-bit/schema.json
- backend/src/api/screwdriver-bit/controllers/screwdriver-bit.ts
- backend/src/api/screwdriver-bit/routes/screwdriver-bit.ts
- backend/src/api/screwdriver-bit/services/screwdriver-bit.ts
- backend/src/bootstrap/permissions/config.json
- backend/src/components/product/bit-table.json
- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/generated/validation.ts
Part of https://github.com/iFixit/ifixit/issues/49327
Figma: https://www.figma.com/file/BolmFORO6ZfHXePOSyEGSS/iFixit---Page-sections?type=design&node-id=1766-10708&mode=design&t=z7yor1h57OAQfLpy-0
This PR introduces the backend changes needed to support the bit table section.
A `ScrewdriverBitType` and a `ScrewdriverBit` model are introduced to allow to define bits without having to input data twice.
Slugs are added to both models to allow selection from the referencing strapi entities.
A `BitTable` section then includes the list of bits, and decorate it with a title and a description to compose the page section
2. Verify that Strapi was restarted correctly with the new models 
3. Verify that the frontend is unchanged and working correctly
> Bit table section backend

- frontend/lib/strapi-sdk/generated/sdk.ts
This is the diff from running `pnpm dev`, and allowing codegen to regenerate the types. Followup to https://github.com/iFixit/react-commerce/pull/2076
qa_req 0 as long as the build succeeds
> Strapi SDK: Regenerate types

- frontend/components/sections/BitTableSection.tsx
The bit table section code included an additional extra margin that was not necessary.
Here the section spacing were reconciled to the mockup values:
qa_req 0
> Correct bit table section spacing

- frontend/lib/shopify-storefront-sdk/generated/sdk.ts
- frontend/lib/shopify-storefront-sdk/operations/findProduct.graphql
- frontend/models/product/index.ts
- frontend/templates/product/MetaTags.tsx
- frontend/tests/jest/__mocks__/products/battery.ts
- frontend/tests/jest/__mocks__/products/generic.ts
- frontend/tests/jest/__mocks__/products/part.ts
- frontend/tests/jest/__mocks__/products/tool.ts
closes #1780 
We're adding support to manual noindex a product page using the conventional [`seo.hidden`](https://shopify.dev/docs/apps/marketing/seo#step-2-hide-a-resource-from-search-engines-and-sitemaps) Shopify product metafield.
1. Visit a [product preview page](https://react-commerce-git-add-product-page-noindex-support-ifixit.vercel.app/products/google-pixel-7-pro-screen-genuine) for a product that is indexed
2. Verify that it has no robots meta tags with `noindex,nofollow` content
3. From the [Shopify admin product page](https://admin.shopify.com/store/ifixit-test/products/6856228044890), set `seo.hidden` to 1 to noindex the product and save
4. Verify that `<meta name="robots" content="noindex,nofollow" />` is present in the `head`
Add an integer metafield definition with `seo` …
> Add manual noindex to product page

- frontend/components/common/InstantSearchProvider.tsx
I am not sure we want URls like this long-term, but we know we have at least two examples where we have variants that could work easily with this one-line fix.
Caused by https://github.com/iFixit/react-commerce/pull/2059#discussion_r1385419955
qa_req 0
> Variants: Support variants with colons

- frontend/templates/troubleshooting/index.tsx
We don't have enough space to render the Figma layout on small mobile devices:
Switch the layout to a column when viewport is less than 375px:
`Troubleshooting/Whirlpool_Washing_Machine/Whirlpool+Washer+Not+Spinning/506149#Section_Additional_Information`
Closes https://github.com/iFixit/ifixit/issues/50591
> Vulcan: Answers CTA: Copy is too long on mobile

- frontend/components/sections/ServiceValuePropositionSection.tsx
- frontend/components/ui/Tooltip.tsx
- frontend/templates/product/sections/ProductOverviewSection/AddToCart/ShippingRestrictions.tsx
- frontend/templates/product/sections/ProductOverviewSection/ValuePropositionList.tsx
- frontend/templates/product/sections/ProductOverviewSection/index.tsx
closes https://github.com/iFixit/ifixit/issues/50505
This adds a line item for the return policy in the value proposition list. I took this opportunity to create a component that abstracts the tooltip (that we're using also for shipping restrictions) and re-organize a bit the involved code (the value proposition list component has been moved from the value proposition section to the product overview section where it belongs)
1. Open a [product page preview](https://react-commerce-git-add-return-policy-value-prop-item-ifixit.vercel.app/products/google-pixel-7-pro-screen-genuine)
2. Verify that the return policy badge is implemented as specified in https://github.com/iFixit/ifixit/issues/50505
cc @ifixitmaxb
> Add return policy value proposition list item

- frontend/templates/product-list/hooks/useProductListBreadcrumbs.ts
Closes https://github.com/iFixit/ifixit/issues/50611
Uses the product list title in the breadcrumbs, as opposed to the product list h1.
The h1 value was not intended to be used in breadcrumbs when it was introduced (https://github.com/iFixit/react-commerce/pull/1426).
- Visit a product list page on the react-commerce preview
- Make sure that the product list `title` is used in the breadcrumbs on all types of product lists, as opposed to the `h1` (as determined in strapi https://breadcrumbs-use-product-list-title.govinor.com/admin)
> Product List: Use `title` in breadcrumbs, not `h1`

- frontend/package.json
- packages/sentry/package.json
- pnpm-lock.yaml
See https://blog.sentry.io/next-js-sdk-security-advisory-cve-2023-46729/?mkt_tok=Nzc2LU1KTi01MDEAAAGPVLLVhs60jC-kjJ8LHYdo5u9F4_TdX29hOHP4R2SqGUuakbjAfahIPpGeYDQUKx6xiHckcvAinb8cGY5ugqspgRxQymUMxVt9kAivi48i9w
qa_req 0
> Sentry: Update to 7.80.0

- frontend/lib/swr-cache/index.ts
- frontend/tests/jest/tests/sentry.test.tsx
- frontend/tests/jest/tests/shopify-storefront-sdk.test.tsx
- frontend/tests/jest/tests/withCache.test.tsx
I was pretty sure we should get data in Sentry, but just in case I started some tests.
qa_req 0
Closes: https://github.com/iFixit/ifixit/issues/50607
> Shopify outage: Ensure we get sentry pings

- frontend/templates/product/sections/ProductOverviewSection/index.tsx
Patches regression from https://github.com/iFixit/react-commerce/commit/786f8841480ce2c424a1de344deeb712c06129a6#diff-4ba9a3ed2b1b0f257b259b4f1882666fed795caf6983cdc11995b6253d79a824L456-L458
Make sure `th` text is left aligned in Specifications accordion:
https://react-commerce-prod-git-revert-productoverviewsec-b28102-ifixit.vercel.app/products/google-pixel-7-pro-screen-genuine
`products/google-pixel-7-pro-screen-genuine`
> Revert ProductOverviewSection th style removal

- packages/feature_flags/README.md
- packages/feature_flags/flag_schema.ts
- packages/feature_flags/flags.json
- packages/feature_flags/index.ts
- packages/feature_flags/package.json
- packages/feature_flags/tsconfig.json
- pnpm-lock.yaml
This is an attempt at an ultra-simple feature flag package which could be used across the monorepo and this NextJS repo.
See the readme for rationale and design notes.
The goal is to add a minimal package which we can use to consistently have feature flags available.
qa_req 0
This code is unused.
Connects https://github.com/iFixit/ifixit/issues/50604
> Add feature flag package

- .npmpackagejsonlintrc.json
- frontend/package.json
- frontend/templates/troubleshooting/index.tsx
- frontend/tests/playwright/troubleshooting/loading.spec.ts
- packages/feature_flags/index.ts
- packages/react-feature-flags/README.md
- packages/react-feature-flags/index.ts
- packages/react-feature-flags/package.json
- packages/react-feature-flags/tsconfig.json
- pnpm-lock.yaml
This adds a second component for the related-problems change and 
ensures we're not accidentally exposing our new component to the world. It should be pretty hard to mess up, because it checks that the test attribute doesn't exist without the feature flag and does exist with the feature flag.
qa_req 0
There's a test for this!
> Troubleshooting: Split related-problems render on feature flag

- frontend/layouts/default/index.tsx
- frontend/lib/shopify-storefront-sdk/generated/sdk.ts
- packages/auth-sdk/user.tsx
- packages/ui/cart/drawer/CartDrawerTrigger.tsx
- packages/ui/header/UserMenu.tsx
- packages/ui/misc/BlueDot.tsx
- packages/ui/misc/index.ts
closes https://github.com/iFixit/ifixit/issues/50434
This PR adds an unread notifications count to the user menu avatar and refactors the user menu to match the mockup
1. Open [Vercel preview](https://react-commerce-git-add-unread-notifications-count-ifixit.vercel.app/Parts)
2. As a logged in user, make sure that if you have unread notifications, they show up as a blue dot in the avatar, and the unread notifications count is displayed in the user menu panel
3. Verify that the user menu matches the [mockup](https://www.figma.com/file/sfj6r7Bn6eREMvuqo0f7Du/iFixit---Components?type=design&node-id=3544-10387&mode=dev)
> Add unread notifications count

- frontend/templates/troubleshooting/Resource.tsx
- frontend/templates/troubleshooting/hooks/useTroubleshootingProps.tsx
- frontend/templates/troubleshooting/solution.tsx
Implements the [figma design](https://www.figma.com/file/QVLUEpDVoyiMM4MXEGq1L9/iFixit---Problems?type=design&node-id=588-33&mode=design&t=zRnaaF8j4VA0y902-0) for part collections linked in vulcan pages.
Qa_req 0 - This component will not render currently.
Connect to https://github.com/iFixit/ifixit/issues/50601
> Vulcan: Add parts collection Link Card

- frontend/seo/product-list/hreflangs.ts
- frontend/templates/product-list/MetaTags.tsx
Followup to https://github.com/iFixit/react-commerce/pull/2111
Connects https://github.com/iFixit/ifixit/issues/50649
Expands the product list hreflangs to include all locales that exist for our product pages, as spec'd by Max the SEO wizard.
Example hreflang doc: https://docs.google.com/document/d/1dHpIrEXm1B3McREdyd3ASAnuUSEM-ozJ2731U8mz_qs/edit
Hreflang builder sheet: https://docs.google.com/spreadsheets/d/1bFai7oXL1HJtgFm69taKA_VjKN8WtXyrJfMyB6UQ7xY/edit#gid=1228401214
Hreflang builder tutorial: https://ifixit.slack.com/archives/C04MB3SSGQ1/p1700514191128449
> Expand product list hreflangs

- frontend/components/common/PrerenderedHTML.tsx
- frontend/components/sections/BannersSection/SingleBanner.tsx
- frontend/components/sections/LifetimeWarrantySection.tsx
- packages/ui/cart/drawer/CartDrawerTrigger.tsx
- packages/ui/header/NavigationMenu.tsx
- packages/ui/theme/styles.ts
These popped up while doing some testing. Let's take care of the low-level UI bugs, so our friends stuck on older Safari versions can at least use the site.
Fixes the following issues:
<details>
<summary>Header styling</summary>
</details>
<details>
<summary>Limit image width to their container</summary>
</details>
<details>
<summary>Replace inset="0" usage</summary>
</details>
> Fix Safari 13.1 Bugs

- frontend/templates/product-list/hooks/useItemTypeProductList.ts
Original report in Slack: https://ifixit.slack.com/archives/C02KMFEHX62/p1700521827373909
Wrong H1:
https://www.ifixit.com/Parts/Samsung_Galaxy_S21/Batteries
Correct H1:
https://www.ifixit.com/Parts/Google_Pixel_4a/Batteries
I noticed that the Samsung Strapi product list had an H1 set, while the Google Pixel Strapi page did not. When there are no item type overrides, the code picks a default title but not a default H1. This change picks a default H1.
> Product List: Add default H1 override

- frontend/helpers/path-helpers.ts
- frontend/seo/product-list/hreflangs.ts
- frontend/templates/page/sections/BrowseSection.tsx
- frontend/templates/product-list/MetaTags.tsx
- frontend/templates/product-list/hooks/useProductListBreadcrumbs.ts
- frontend/templates/product-list/sections/FeaturedProductListsSection.tsx
- frontend/templates/product-list/sections/FilterableProductsSection/index.tsx
- frontend/templates/product-list/sections/ProductListChildrenSection.tsx
Noticed in my CR here https://github.com/iFixit/react-commerce/pull/2112#discussion_r1399848133
Make sure the product list links throughout the Next.js app still work normally.
In particular, make sure that item type canonical urls in the `<head>` are still correct, and check the new variant syntax too (`DeviceTitle:Variant`)
> Refactor product list path helper

- frontend/templates/troubleshooting/solution.tsx
1. This code is being SSR'ed without the feature flag. That mutates the solutions array and sets the parts collection to an empty array.
2. Then when the client passes the feature flag, it sets the partsCollection array to the empty array of solutions.partsCollection that we just mutated.
3. Setting this to a const instead of mutating the original array fixes the issue.
Qa_req 0 - this is still behind the feature flag.
Connects https://github.com/iFixit/ifixit/issues/50601
> Parts Collection Feature Flag: Don't mutate the server response

- frontend/seo/product-list/hreflangs.ts
Satisfies https://github.com/iFixit/ifixit/issues/50809 for the headless store
Make sure that `/Shop/Black_Friday` has only the hreflangs in the parent issue, and make sure other pages don't.
> Product List: Add black friday hreflangs

- packages/sentry/index.tsx
While deving I kept seeing the following in my console
```
instrument.js:123 ./sentry.client.config.ts
Attempted import error: 'SentryErrorIntegration' is not exported from '@ifixit/sentry' (imported as 'SentryErrorIntegration').
```
So this fixes that.
The above import error shouldn't show up anymore.
@jarstelfox Is this ok? Or am i missing something?
qa_req 0
> Sentry/index Exports All of SentryErrorIntegration

- frontend/seo/product-list/hreflangs.ts
From Max:
> the US page was https://www.ifixit.com/Tools/PC  but it should have been https://www.ifixit.com/Parts/PC_Laptop
Connects https://github.com/iFixit/ifixit/issues/50649
> Product List: Fix hreflang for pc laptop

- startReactCommerce.sh
This pull request introduces a few enhancements and bug fixes to the react-commerce project's startup script.
- Implemented a loop for Verdaccio account login and creation, allowing multiple attempts and user-friendly error handling. This resolves issues where users were the script would just continue upon entering incorrect credentials.
- Set up and exported the VERDACCIO_AUTH_TOKEN correctly to prevent the previous issue of failing to replace the environment variable in the .npmrc file.
- Streamlined the handling of the ALGOLIA_API_KEY, ensuring it's properly imported from the environment variable algoliaApiKey and updated in the frontend/.env.local file.
Check the following in the startup script: create an account, submit incorrect and correct credentials, and make sure you dont see …
> Enhancements to startup script

- frontend/templates/troubleshooting/Resource.tsx
Fixes image styling, centers the text on the card to match the Figma, and adds margin to keep buy button from touching the text.
Qa_req 0 - still behind a feature flag.
Connects https://github.com/iFixit/ifixit/issues/50601
> Troubleshooting: Part collections card: styling fixes

- frontend/app/(defaultLayout)/Troubleshooting/[device]/page.tsx
- frontend/lib/ifixit-api/devices.ts
- frontend/templates/troubleshooting/server.tsx
Before we werent encoding, which was resulting in bad requests that returned the doc endpoint and broke things in react-commerce. Now we encode so we at least hit the expected endpoint and don't redirect.
You can see the error on `/Troubleshooting/Television/TV+Has+Sound+But+No+Picture/493422` vs `/Troubleshooting/Television/TV+Has+Sound+But+No+Picture/..%2f..%2fpackage.json`. It should no longer 500
Closes: #50760
> Ifixit TroubleShooting API: Encode Parameters

- frontend/templates/troubleshooting/solution.tsx
- packages/feature_flags/flags.json
Releases the new feature!
Part collection link cards can now be added to troubleshooting pages just like linked guides or products. Simply add a link to a part collection, just as https://www.ifixit.com/Parts/iPad/Ports. This should be transformed into the storelink wiki text token, which you can also directly make instead: `[storelink|/Parts/iPad/Ports|iPad Ports]`.
On troubleshooting view, these links are extracted into the new link card component.
1. Add a part collection link to [a troubleshooting wiki](https://www.cominor.com/Wiki/Edit/iPad_Slow_Charge). This only applies to links starting with `/Parts`.
- Links should be transformed into a token: `https://www.ifixit.com/Parts/iPad/Ports` -> `[storelink|/Parts/iPad/Ports|iPad Ports]`
- Link tokens should be transformed into a …
> Troubleshooting: Part collections card: Remove feature flag

- frontend/models/components/image.ts
- frontend/models/product/index.ts
- frontend/templates/product/MetaTags.tsx
- frontend/templates/product/sections/ProductOverviewSection/ProductGallery.tsx
- frontend/tests/jest/__mocks__/products/battery.ts
- frontend/tests/jest/__mocks__/products/generic.ts
- frontend/tests/jest/__mocks__/products/part.ts
- frontend/tests/jest/__mocks__/products/tool.ts
Products may now have fallback images (only one right now, but using an
array made integration easier). These are only to be used when a variant
has no other image to represent it. They are identified by (altText ===
'*fallback')
Here we extract them into a new property and make use of them wherever
we are using product.images.
We can't inject copies of these fallback images into product.images
otherwise the gallery would show one copy of the fallback for each
variant that uses it.
fallback images won't always be present and we've dealt with that here.
Our schema validation on the cache should protect us against this
change.
Note: We are filtering out fallback images from the normal
product.images because in that array, variantId === null implies it's
valid for all variants and that's not …
> Product images: use fallback images

- frontend/templates/troubleshooting/index.tsx
When we have the `extended-related-problems` flag enabled, we have extra
problems potentially included in the `Related Problems` list
(confusingly, these come from the `relatedProblems` key and are added to
the existing `linkedProblems` list). This ensures that we update the
`hasRelatedPages` boolean to accurately reflect the state of the
`Related Problems` section.
Check that adding `#enable-extended-related-problems` to a troubleshooting page URL results in the extended related-problems section showing up.
> Troubleshooting: Show Related Problems appropriately

- frontend/templates/troubleshooting/index.tsx
We've got an issue where the Conclusion component is rendering empty, but it has a top padding applied, which throws off the UI spacing.
<details>
</details>
`/Troubleshooting/Nintendo_Switch/Will+Not+Turn+On/481634`
`/Troubleshooting/Nest_Cam/Overheating/532364`
<details>
<summary>Post-fix</summary>
</details>
Closes https://github.com/iFixit/ifixit/issues/50875
> Vulcan: Conclusion padding when div is empty

- frontend/templates/troubleshooting/hooks/useTroubleshootingProps.tsx
- frontend/templates/troubleshooting/index.tsx
Part 2/2
Change the "View all"/"View problem" link on device cards to use the `deviceTroubleshootingUrl` from the API.
Don't deploy until https://github.com/iFixit/ifixit/pull/50890 is merged.
Connects: https://github.com/iFixit/ifixit/pull/50890
Closes: https://github.com/iFixit/ifixit/issues/50886
> Troubleshooting: Use deviceTroubleshootingUrl for "View all" link

- packages/cart-sdk/hooks/use-checkout.ts
Basically the shopify graphql was giving us back a domain to the shopify that wasn't right. We want to use the domain the user is on, not the official shopify domain.
This fixes that.
> Fix Checkout

- frontend/components/common/PrerenderedHTML.tsx
- frontend/templates/troubleshooting/index.tsx
The device card order displays below the related problems on mobile, but it's currently switching at the wrong breakpoint.
<details>
<summary>Pre-fix Video</summary>
https://github.com/iFixit/react-commerce/assets/1634505/d4a61ff9-3b29-4b97-afdf-1fe8b3a13a06
</details>
Confirm breakpoints have been corrected after adjusting the breakpoint for `#main` content.
<details>
<summary>Post-fix Video</summary>
https://github.com/iFixit/react-commerce/assets/1634505/ab08671d-2d90-4972-93c1-e7a39fcac957
</details>
https://github.com/iFixit/react-commerce/pull/2141/commits/83c18db24cc673e26c0761fbbf3200c76e0912c5 corrects a bug found while testing
Closes https://github.com/iFixit/ifixit/issues/50953
> Vulcan: Sidebar order breakpoint incorrect

- frontend/lib/shopify-storefront-sdk/generated/sdk.ts
- frontend/lib/shopify-storefront-sdk/operations/findProduct.graphql
- frontend/models/product/index.ts
- frontend/models/product/server.ts
- frontend/pages/api/nextjs/cache/product.ts
- frontend/templates/product/server.tsx
- frontend/tests/jest/__mocks__/products/battery.ts
- frontend/tests/jest/__mocks__/products/generic.ts
- frontend/tests/jest/__mocks__/products/part.ts
- frontend/tests/jest/__mocks__/products/tool.ts
- frontend/tests/playwright/fixtures/shopify-mocked-queries.ts
Closes https://github.com/iFixit/ifixit/issues/50841
Our PHP [backend](https://github.com/iFixit/ifixit/blob/master/iFixit/Shopify/ShopifyUrlHandleRedirectJob.php) adds product redirects to Shopify whenever a product handle is changed.
Shopify redirects should be followed, unless the given handle corresponds to an enabled product that exists.
For example, `/products/t5-torx-screwdriver-1` should redirect to `/products/t5-torx-screwdriver`.
For a specific path or target, you can use
https://admin.shopify.com/store/ifixit-us/redirects.json?path=/products/macbook-pro-13-a2159-2019-trackpad
Existing product redirects are viewable at https://admin.shopify.com/store/ifixit-test/redirects.json
> Product: Follow Shopify redirects

- frontend/templates/product/server.tsx
Connects https://github.com/iFixit/ifixit/issues/45225
Creates a valid url when both the redirect url and the request url have search params. If the urls have overlapping params, the parameters from the redirect url are used.
- Give a product a redirect url in shopify admin that has a query param (the redirect url must point to a different product).
- For example, I gave [arctic silver thermal paste](https://admin.shopify.com/store/ifixit-test/products/6579687948378) a redirect to https://www.ifixit.com/products/ifixit-thermal-paste?variant=40263220166759
- Then try to visit `/products/arctic-silver-thermal-paste` on the react-commerce deployment with some existing query params.
- Maybe `?a=b` or `?a=b&b=c` or `?variant=39333662982234` which is the other [detailing brush …
> Create valid redirect urls when params exist

- .github/workflows/deploy-strapi.yml
There is a warning about the 'mask-password' option for the "amazon-ecr-login" action. If ran in debug mode, the password will be outputted. By default this option is not enabled as the expectation is to run the service after the deployment but as a secondary job. As such the password cannot be masked as it is needed to run the service.
https://github.com/aws-actions/amazon-ecr-login#run-an-image-as-a-service
However, this is not the workflow we have set up, therefore we need to enable the option to mask the password.
Reference: https://github.com/iFixit/vigilo/pull/19
> GitHub Actions: Enable masking option for ECR Login

- frontend/templates/troubleshooting/Resource.tsx
Makes the link card images on troubleshooting pages 4:3 ratio to match [the figma](https://www.figma.com/file/QVLUEpDVoyiMM4MXEGq1L9/iFixit---Problems?type=design&node-id=588-33&mode=design&t=oZ88nbX5qcuK3xcO-0).
This also keeps product link card images in 1:1 ratio because those images will always be 1:1.
- Check that [part collection link cards](http://localhost:3000/Troubleshooting/iPhone/Won't+Turn+On/405189?revisionid=HEAD) and [guide link cards](/Troubleshooting/Refrigerator/Compressor+Not+Running/505022) now have a 4:3 aspect ratio and matches [the figma](https://www.figma.com/file/QVLUEpDVoyiMM4MXEGq1L9/iFixit---Problems?type=design&node-id=588-33&mode=design&t=oZ88nbX5qcuK3xcO-0).
- Check that [product link cards](http://localhost:3000/Troubleshooting/Refrigerator/Compressor+Not+R …
> Troubleshooting: 4:3 link card images

- .vscode/settings.json
I noticed an odd automatic update to our `source.fixAll.eslint` setting, dig a little digging, and found that the values have changed from boolean: https://code.visualstudio.com/updates/v1_83#_code-actions-on-save-and-auto-save 
This updates our setting, so autosave still functions as it currently does.
Confirm formatting on VSCode still functions as expected with the new `always` value.
qa_req 0
> VSCode: Update eslint Setting Value

- frontend/templates/troubleshooting/components/Causes.tsx
- frontend/templates/troubleshooting/index.tsx
Found a bug where we were displaying the Conclusion TOCHeading without content on https://www.ifixit.com/Troubleshooting/Garbage_Disposal/Hums/491105. 
<details>
</details>
Noted in original pull: https://github.com/iFixit/react-commerce/pull/2143#issuecomment-1853047747
Confirm were are not displaying an empty TOC Heading for `Conclusion` on various `/Troubleshooting` pages
`/Troubleshooting/Refrigerator/Ice+Maker+Not+Making+Ice/481782`
`/Troubleshooting/Garbage_Disposal/Hums/491105`
`/Troubleshooting/Google_Phone/Google+Pixel+Overheating/479437`
...
> Vulcan: Conditionally render Conclusion TOCHeading

- .github/workflows/deploy-strapi.yml
Updates `aws-actions/amazon-ecr-login` from v1 to v2.
This will set the `mask-password` option to true by default
so it prevents logging the password in the debug mode, [ref](https://github.com/aws-actions/amazon-ecr-login#new-v2-release).
qa_req 0
connects https://github.com/iFixit/ifixit/issues/51077
> Actions: Update `aws-actions/amazon-ecr-login` from v1 to v2

- frontend/templates/troubleshooting/Problem.tsx
Image corners are overflowing past the parent bounds when `borderRadius` is applied. Just needs `overflow: hidden` applied.
`/Troubleshooting/Google_Phone/Google+Pixel+Overheating/479437#Section_See_Also`
Confirm image corners are now hidden.
<details>
<summary>Post-fix</summary>
</details>
Closes https://github.com/iFixit/ifixit/issues/50699
> Vulcan: Fix related problem image corners

- frontend/templates/product-list/sections/FilterableProductsSection/ProductList.tsx
- frontend/templates/product/sections/ProductOverviewSection/ProductRating.tsx
- frontend/templates/product/sections/ProductReviewsSection/index.tsx
- frontend/tests/jest/tests/__snapshots__/ProductListItem.test.tsx.snap
QA
---
* Ensure you screen reader now reads the rating
Connects: https://github.com/iFixit/ifixit/issues/51161
> Stars: Make reviews accessible

- frontend/templates/product-list/server.tsx
See: https://github.com/vercel/next.js/issues/49646
We have slashes in some variants.
You can see the bug by visiting:
* https://www.ifixit.com/Parts/iPhone_XR:A1984_US%2FCanada
* Click Any item type and the page loads fine
* Refresh and the page 404s
This works around the issue by manually handling the url parsing for this page. We only needed the path segments.
> Product Pages: Support encoded slashes

- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/operations/findProductList.graphql
- frontend/models/product-list/server.ts
- frontend/models/product-list/types.ts
- frontend/templates/product-list/server.tsx
Closes https://github.com/iFixit/react-commerce/issues/2067
Setting a `redirectTo` on a product list in Strapi (https://product-list-redirects.govinor.com/admin) should cause a redirect. Item types will be passed along in the redirect if applicable, but the device variant will not. Any query parameters in the request should also be added to the redirect url.
> Obey Strapi product list redirects

- frontend/layouts/default/index.tsx
- packages/analytics/piwik/index.tsx
- packages/auth-sdk/user.tsx
We want to track what users are doing what based on user privilege or role (admin, moderator, user, etc). This change will send piwik a userPrivilege dimension if a user is logged in. If the user is not logged in, it will not update or set the dimension.
Do users have their userPrivilege logged correctly in piwik? If you log out does that userPrivilege change (it shouldn't, we want to track the last privilege you had). 
CC @addison-grant 
Connects: [#51217](https://github.com/iFixit/ifixit/issues/51217)
> Piwik: Add User Privilege Custom Dimension Tracking

- backend/src/api/product/content-types/product/schema.json
- backend/src/components/section/tools.json
- backend/types/generated/components.d.ts
- backend/types/generated/contentTypes.d.ts
- frontend/lib/strapi-sdk/generated/sdk.ts
Connects https://github.com/iFixit/ifixit/issues/49326
This PR introduces the necessary backend changes to port the old PTT tools section to react-commerce.
Here is the mockup for the new section: https://www.figma.com/file/BolmFORO6ZfHXePOSyEGSS/iFixit---Page-sections?node-id=1839%3A1795&mode=dev
Currently the only scenario in which this section is going to be used is inside the pro tech toolkit product page.
Strapi is currently providing only the section positioning. The section content is static.
This is due to the fact that right now each image requires custom margins and scaling to fit the SVG proportions.
In the future, if we want to make the content of this section dynamic and provide data from Strapi, we will have to consider creating SVGs sized exactly as the tool images. 
1. …
> Tools section backend

- frontend/components/sections/ToolsSection/index.tsx
Moving from @ianrohde [suggestion](https://github.com/iFixit/react-commerce/pull/2173#issuecomment-1870642128), here is a slightly modified version of the tools section that features:
- vertically centered tools - to compensate for tool height differences
- scroll snapping behaviour
1. Visit Vercel [Preview](https://react-commerce-git-tools-section-frontend-ifixit.vercel.app/products/repair-business-toolkit)
2. Verify that the tools section is still fully functional and that the new scroll snapping behaviour is working correctly
> Tools section frontend improvements

- frontend/lib/ifixit-api/productData.ts
- frontend/lib/shopify-storefront-sdk/generated/sdk.ts
- frontend/lib/shopify-storefront-sdk/operations/findProduct.graphql
- frontend/models/product/index.ts
- frontend/models/product/server.ts
- frontend/templates/product/server.tsx
- frontend/tests/jest/__mocks__/products/battery.ts
- frontend/tests/jest/__mocks__/products/generic.ts
- frontend/tests/jest/__mocks__/products/part.ts
- frontend/tests/jest/__mocks__/products/tool.ts
Connects https://github.com/iFixit/ifixit/issues/45225
The product redirect sku metafield is no longer used. Instead, we issue the same kind of redirect if the iFixit API returns a `redirectSkuUrl` for a product. You might need to use `?disableCacheGets`.
The api is https://www.cominor.com/api/2.0/store/product/some-product-handle
Blocked by https://github.com/iFixit/ifixit/pull/51270
> Use redirect sku from iFixit product API

- frontend/templates/product-list/sections/FilterableProductsSection/facets/accordion/index.tsx
Closes https://github.com/iFixit/ifixit/issues/51222
1. Visit [Vercel preview](https://react-commerce-git-expand-tool-category-facet-acc-749d34-ifixit.vercel.app/Tools/)
2. Verify that the tool category facet accordion is open by default
> Expand tool category by default

- frontend/templates/product/server.tsx
iFixit redirect sku urls are absolute (e.g. https://www.ifixit.com/api/2.0/store/product/arctic-silver-thermal-paste).
Shopify redirect urls are relative (e.g. https://admin.shopify.com/store/ifixit-us/redirects.json?path=/products/apple-watch-series-7-speaker).
This change provides a base url that is used in the case where the redirect url is relative.
https://www.ifixit.com/products/apple-watch-series-7-speaker should no longer 400 on the production preview for this branch.
The `/products/arctic-silver-thermal-paste` redirect should still work.
> Handle relative Shopify product redirect urls

- backend/src/api/product-list/content-types/product-list/schema.json
- backend/types/generated/contentTypes.d.ts
- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/generated/validation.ts
Connects https://github.com/iFixit/ifixit/issues/51356
I decided to make `redirectToType` an enum instead of a boolean because I found it more readable as an admin user. If folks disagree I welcome their feedback.
One thing I noticed is that existing product list records do not have a default value populated. It seems like a Strapi bug (or "missing feature") https://github.com/strapi/strapi/issues/18636.
qa_req 0
> Strapi: Add redirect type to product list

- backend/strapi-deploy-actions
The `BUILD_REPO` variable is not set in the Strapi deploy job, 
so the commit link was broken. This commit hardcodes the link
to the react-commerce repo.
qa_req 0
Connects: https://github.com/iFixit/react-commerce/issues/2175
> Strapi Deploy: Fix deploy message

- frontend/lib/strapi-sdk/generated/sdk.ts
- frontend/lib/strapi-sdk/operations/findProductList.graphql
- frontend/models/product-list/component/product-list-redirect-to-type.server.ts
- frontend/models/product-list/component/product-list-redirect-to-type.ts
- frontend/models/product-list/index.ts
- frontend/models/product-list/server.ts
- frontend/models/product-list/types.ts
- frontend/templates/product-list/server.tsx
Closes https://github.com/iFixit/ifixit/issues/51356
- Add a `redirectTo` to a product list in Strapi (https://use-product-list-redirect-to-type.govinor.com/admin)
- Set the `redirectToType`. If unset, the behavior should default to a permanent redirect.
- `redirectToType` should control whether the redirect is permanent (308) or temporary (307)
> Product list: Use redirect to type

- frontend/layouts/default/index.tsx
- packages/analytics/piwik/index.tsx
- packages/auth-sdk/user.tsx
We were running into issues where piwik was getting translated privilege names in its data. This isn't desired. Lets make sure that doesn't happen with these changes.
Is this only sending the correct user privileges (not translated) to piwik now? 
Connects: https://github.com/iFixit/ifixit/issues/51313
> Piwik: Use greatest_privilege in User API Response

- frontend/helpers/path-helpers.ts
- frontend/templates/product/hooks/useProductPageAdminLinks.tsx
- frontend/templates/product/index.tsx
Closes https://github.com/iFixit/ifixit/issues/51121
Visit the Vercel preview logged in with your iFixit account. Visit a product page, and confirm that the admin edit link for netsuite takes you to NetSuite in a new tab.
> Product: Add NetSuite admin link

- packages/footer/components/Shared.tsx
Quick fix. I'm seeing this warning on dev:
`Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>.`
<details>
</details>
We're passing in children, which looks to have another Text component or paragraph element, so let's convert the parent to a Box instead.
Confirm footer is still functioning as expected.
> Footer: Fix HTML Semantics Warning

- frontend/lib/shopify-storefront-sdk/generated/sdk.ts
- packages/sentry/index.tsx
The [errors spike](https://ifixit.sentry.io/alerts/rules/details/180935/?end=2024-01-09T18%3A25%3A00&start=2024-01-09T16%3A40%3A29) that appeared today seems to be related to the way in which the sentry fetch config parses the input body.
This PR handles the process more defensively, not giving for granted that the body is JSON encoded.
qa_req 0
> Defensively parse fetch request body

- backend/src/plugins/addons/server/services/seed/custom/content-fetcher.ts
This PR switches two checks that were performed during Strapi seeding.
In detail we should check for 404 before checking the generic `response.ok`, otherwise new models introduced locally will make the seeding process fail.
qa_req 0
> Seeding - check 404 before failing

- frontend/app/(defaultLayout)/products/app-router/[handle]/page.tsx
- frontend/app/_helpers/app-helpers.ts
- frontend/lib/ifixit-api/productData.ts
- frontend/models/product/index.ts
- frontend/models/product/server.ts
- frontend/pages/api/nextjs/cache/product.ts
- frontend/templates/product/server.tsx
This PR contains a minor refactor of the product redirect logic and adds product fetching to the app router page.
Redirects should be followed (both from Shopify or iFixit), unless the given handle corresponds to an enabled product that exists.
For example, [`/products/ipad-air-4-battery`](https://react-commerce-git-refactor-product-redirect-ifixit.vercel.app/products/ipad-air-4-battery) should redirect to `/products/ipad-air-4-5-battery`.
> Refactor product redirect

- packages/cart-sdk/types.ts
Connects https://github.com/iFixit/ifixit/issues/51463
These fields are going away, so let's drop them from the type.
qa_req 0
> Drop deprecated cart api coupon fields

- frontend/templates/troubleshooting/Resource.tsx
This text matches the current [figma](https://www.figma.com/file/QVLUEpDVoyiMM4MXEGq1L9/iFixit---Problems?type=design&node-id=588-33&mode=design).
Make sure a linked guide card on troubleshooting solutions looks good across all screen sizes and matches the [figma](https://www.figma.com/file/QVLUEpDVoyiMM4MXEGq1L9/iFixit---Problems?type=design&node-id=588-33&mode=design).
Example page: http://localhost:3000/Troubleshooting/iPhone/Battery+Draining+Fast/480045#Section_Logic_Board
Closes https://github.com/iFixit/ifixit/issues/51458
> Add CTA button on guide cards

- frontend/app/(defaultLayout)/products/app-router/[handle]/json-ld-scripts.tsx
- frontend/app/(defaultLayout)/products/app-router/[handle]/page.tsx
- frontend/app/_helpers/product-helpers.ts
- frontend/app/global-error.tsx
Part of https://github.com/iFixit/ifixit/issues/51165
Under the app router metadata for a page has to be declared using the [`generateMetadata`](https://nextjs.org/docs/app/building-your-application/optimizing/metadata) function, which exports a typed object. This PR converts the `frontend/templates/product/MetaTags.tsx` component into this new format.
Compare an [`app router` product page preview](https://react-commerce-git-add-app-router-product-page-metadata-ifixit.vercel.app/products/app-router/iphone-11-screen) with its matching [`pages` product page preview](https://react-commerce-git-add-app-router-product-page-metadata-ifixit.vercel.app/products/iphone-11-screen) to verify that:
- They have the same meta title
- They have the same meta description
- They have the same open graph …
> Add metadata to app router product page

- packages/cart-sdk/hooks/use-add-to-cart.ts
- packages/cart-sdk/hooks/use-remove-line-item.ts
- packages/cart-sdk/hooks/use-update-line-item-quantity.ts
- packages/cart-sdk/package.json
- packages/ui/cart/drawer/CartDrawer.tsx
- packages/ui/cart/drawer/hooks/useCartDrawer.tsx
- pnpm-lock.yaml
We sometimes can have things error out when trying to update the cart. We would roll back the cart but not change anything, and not tell our user that anything wrong happened. Now we give some visual feedback that there was an error updating the cart in the cart drawer.
When we have an error updating the cart (adding a bad product, product is out of inventory, removing an item and it fails) we now display an error message in the cart drawer. The error message is closable, and also disappears after an alloted time.
Also, the checkout errors also still display as expected.
CC @dhmacs 
Closes: https://github.com/iFixit/ifixit/issues/51213
> Show Errors in Cart Drawer

- frontend/components/common/PrerenderedHTML.tsx
I saw an error div rendered on a Vulcan page that I hadn’t seen before: [ifixit.com/Troubleshooting/Nintendo_Switch/Will+Not+Turn+On/481634](https://www.ifixit.com/Troubleshooting/Nintendo_Switch/Will+Not+Turn+On/481634)
It's breaking the page layout because the pre elements don't wrap.
<details>
<summary>Pre-fix Details</summary>
</details>
This issue was only present on the live site, but Shawn has since fixed the content issue ([Slack ref](https://ifixit.slack.com/archives/C01GVQAAGDU/p1705450363393529?thread_ts=1705449298.795689&cid=C01GVQAAGDU)). I have a video of the proposed fix being toggled, which should suffice:
<details>
<summary>Post-fix Details</summary>
https://github.com/iFixit/react-commerce/assets/1634505/0ea5235a-a272-4fdb-a525-b57bb79af44c
</details>
Closes …
> Vulcan: Wrap pre elements

- frontend/templates/product/sections/ProductOverviewSection/AddToCart/ShippingRestrictions.tsx
- frontend/templates/product/sections/ProductOverviewSection/ValuePropositionList.tsx
Closes https://github.com/iFixit/ifixit/issues/51384
Makes the shipping restriction and returns notice visible to screen readers. Also adds aria label text to each.
This is similar to what we do for the prop 65 warning.
Chakra's docs recommend that the popover trigger be focusable, hence the use of IconButton. https://chakra-ui.com/docs/components/popover/usage#basic-usage
Visit the Vercel preview and make sure that the shipping restrictions and returns info buttons are not skipped by screen readers.
> Product: Make tooltips visible to screen readers

- frontend/templates/troubleshooting/components/Causes.tsx
- frontend/templates/troubleshooting/components/NavBar.tsx
We added "Troubleshooting" as a heading in the TOC and section list, but now it looks like "Troubleshooting" only applies up to the Causes and not beyond.
https://react-commerce-prod-git-vulcan-problem-rename-are-945c10-ifixit.vercel.app/Troubleshooting/Garbage_Disposal/Hums/491105
Spec:
Closes https://github.com/iFixit/ifixit/issues/51467
> Vulcan: Problem: Rename area link to "Troubleshooting"

- frontend/templates/troubleshooting/index.tsx
We display a 'Causes' header in the TOC, but don't actually show one in the troubleshooting page content. This adds one in the same style as the other headers.
We don't want to be able to permalink to this, so it should just be an h2 without special link properties.
If there are no causes to display, we don't render the header.
Closes https://github.com/iFixit/ifixit/issues/51468
> Troubleshooting: Add causes header

- frontend/tests/jest/tests/ProductSection.test.tsx
- frontend/tests/jest/tests/__snapshots__/ProductListItem.test.tsx.snap
- frontend/tests/playwright/fixtures/product-page.ts
- packages/ui/commerce/ProductPrice.tsx
Closes https://github.com/iFixit/ifixit/issues/51386
Visit the vercel preview and make sure product page and product list page prices are more clear for screen readers.
> A11y: Add visually hidden price qualifiers

- frontend/app/(defaultLayout)/Troubleshooting/[device]/components/AnswerCard.tsx
- frontend/app/(defaultLayout)/Troubleshooting/[device]/components/Answers.tsx
- frontend/app/(defaultLayout)/Troubleshooting/[device]/components/NavBar.tsx
- frontend/app/(defaultLayout)/Troubleshooting/[device]/components/ProblemCard.tsx
- frontend/app/(defaultLayout)/Troubleshooting/[device]/components/troubleshootingProblems.tsx
We found a few UI issues when reviewing the Problems List page yesterday during a Vulcan meeting. This is a second pass at the styles to shore it up.
[Figma link](https://www.figma.com/file/QVLUEpDVoyiMM4MXEGq1L9/iFixit---Problems?type=design&node-id=1-122&mode=design&t=ayzLTnsYXY4NW2PN-0)
https://react-commerce-prod-git-problems-list-finalize-ui-styles-ifixit.vercel.app/Troubleshooting/Google_Phone
**Fixed:**
- On mobile: Device images in question cards are variable size. [(ref link)](https://ifixit.slack.com/archives/CDFNZ4N4A/p1706051332728989)
- On mobile: Missing margin on the bottom of the question count. [(ref link)](https://ifixit.slack.com/archives/CDFNZ4N4A/p1706051332728989)
- Double-check desktop/mobile spacing variances
- Refactor the AnswerCard layout to vertically center …
> Problems List: Finalize UI styles

- frontend/components/common/PrerenderedHTML.tsx
Closes https://github.com/iFixit/ifixit/issues/51907
Fixes a bug where additional `sx` applied to `<PrerenderedHtml>` would prevent any default `sx` styles from being applied.
CC @ianrohde
> [Fix] Prerendered HTML style override

- frontend/app/(defaultLayout)/app-router/Store/[[...slug]]/page.tsx
- frontend/components/sections/BannersSection/index.tsx
- frontend/components/sections/FeaturedProductsSection.tsx
- frontend/components/sections/IFixitStatsSection.tsx
- frontend/components/sections/LifetimeWarrantySection.tsx
- frontend/components/sections/QuoteGallerySection.tsx
- frontend/components/sections/SocialGallerySection.tsx
- frontend/components/sections/SplitWithImageSection.tsx
- frontend/lib/shopify-storefront-sdk/generated/sdk.ts
- frontend/templates/page/sections/BrowseSection.tsx
- frontend/templates/page/sections/HeroSection.tsx
- frontend/templates/page/sections/PressQuotesSection.tsx
Part of https://github.com/iFixit/ifixit/issues/51872
Verify that the [`app router` store home page preview](https://react-commerce-git-add-app-router-store-page-sections-ifixit.vercel.app/app-router/Store) matches the [`pages` store home page preview](https://react-commerce-git-add-app-router-store-page-sections-ifixit.vercel.app/Store)
> Add app router store pages sections

- frontend/app/(defaultLayout)/Troubleshooting/[device]/components/Answers.tsx
- frontend/app/(defaultLayout)/Troubleshooting/[device]/components/troubleshootingProblems.tsx
- frontend/app/(defaultLayout)/Troubleshooting/[device]/hooks/useTroubleshootingProblemsProps.ts
Add ancestor Problems to Problems List page when available. See [issue](https://github.com/iFixit/ifixit/issues/51062) description for further details.
> Mock-up text is not final. Figure out final copy with Max.
Text will be updated separately in https://github.com/iFixit/ifixit/issues/51815
`/Troubleshooting/dryer` (no ancestors)
`/Troubleshooting/AEG_T865901H_dryer` (has ancestors)
Closes https://github.com/iFixit/ifixit/issues/51062
> Vulcan: Problem List: Ancestor problem lists

- frontend/sentry.client.config.ts
- frontend/sentry.edge.config.ts
- frontend/sentry.server.config.ts
This won't work the same way once this code is in a private repo.
Let's disable this while we move this code instead of trying to re-solve this problem beforehand.
qa_req 0
> Sentry: temp disable production check

- frontend/app/(defaultLayout)/Troubleshooting/[device]/components/NavBar.tsx
- frontend/components/common/NavTabs.tsx
- frontend/templates/product-list/ProductListDeviceNavigation.tsx
- frontend/templates/product-list/SecondaryNavigation.tsx
- frontend/templates/troubleshooting/components/NavBar.tsx
Extracts and reuses a styled nav tab component on /Parts, /Troubleshooting/device, and /Troubleshooting pages. Reuses the components from the Troubleshooting nav tabs on parts and problem list view pages. Now the styles are consistent across the tabs.
- The navtabs on [/Parts](http://localhost:3000/Parts/Mac) should now match the tabs on [/Troubleshooting pages](http://localhost:3000/Troubleshooting/iPhone/Won't+Turn+On/405189) and [problem list pages](http://localhost:3000/Troubleshooting/iPhone).
- All three should now match the updated [figma](https://www.figma.com/file/sfj6r7Bn6eREMvuqo0f7Du/iFixit---Components?type=design&node-id=125-13254&mode=design&t=pGlQ2ObPeeoZ0bti-0).
- When there is no /Parts or /Guides for a device, we disable the link.
- Please check this across all browser …
> Match Device Navigation Tab styling
